                         .IOSF_FIP_IS_ENCAPSULATED(IOSF_FIP_IS_ENCAPSULATED),   
                         .IOSF_UHFI_TTIF_PORT_EN(IOSF_UHFI_TTIF_PORT_EN),
                         .IOSF_DATA_WIDTH(IOSF_DATA_WIDTH), 
                         .IOSF_DATA_TARGET_WIDTH(IOSF_DATA_TARGET_WIDTH),
                         .IOSF_DATA_MASTER_WIDTH(IOSF_DATA_MASTER_WIDTH),
                         .IOSF_MAX_DATA_LEN(IOSF_MAX_DATA_LEN),
                         .IOSF_DATA_PARITY_WIDTH(IOSF_DATA_PARITY_WIDTH),
                         .FABRIC_PSFPORT_MAX_NUMCHAN(FABRIC_PSFPORT_MAX_NUMCHAN),
                         .FABRIC_PSFPORT_NUMCHAN(FABRIC_PSFPORT_NUMCHAN),
                         .FABRIC_PSFPORT_NUMCHANL2(FABRIC_PSFPORT_NUMCHANL2),
                         .AGENT_PSFPORT_NUMCHANL2(AGENT_PSFPORT_NUMCHANL2),
                         .AGENT_PSFPORT_MAX_NUMCHAN(AGENT_PSFPORT_MAX_NUMCHAN),
                         .AGENT_PSFPORT_NUMCHAN(AGENT_PSFPORT_NUMCHAN), 
                         .FABRIC_PSFPORT_NUM_EXTERNAL_PIPE_STAGES(FABRIC_PSFPORT_NUM_EXTERNAL_PIPE_STAGES),
                         .IOSF_PRI_TC_EN(IOSF_PRI_TC_EN), 
                         .IOSF_PRI_CHNL_EN(IOSF_PRI_CHNL_EN), 
                         .ONE_FIFO_USE(ONE_FIFO_USE),
                         .EXPANSION_MODE(EXPANSION_MODE),
                         .IOSF_SRC_ID_WIDTH(IOSF_SRC_ID_WIDTH),
                         .IOSF_CHID_WIDTH(IOSF_CHID_WIDTH),
                         .ORDERED_COMPL_EN(ORDERED_COMPL_EN),
                         .PASSTHRU_BUS_NUM(PASSTHRU_BUS_NUM),
                         .IM_DS_DMA_BUFFER_TAG_80_TO_FF(IM_DS_DMA_BUFFER_TAG_80_TO_FF),
                         .DESC_NUM_OF_QWORDS(DESC_NUM_OF_QWORDS),
                         .SHARED_CREDITS_EN      ( SHARED_CREDITS_EN      ),
                         .INT_SHARED_CREDITS_EN  ( INT_SHARED_CREDITS_EN  ),
                         .SHARED_CMD_CREDITS_DIS ( SHARED_CMD_CREDITS_DIS ),
                         .SHARED_DATA_CREDITS_DIS( SHARED_DATA_CREDITS_DIS)                               
                        
