/*------------------------------------------------------------------------------
  INTEL CONFIDENTIAL
  Copyright 2022 Intel Corporation All Rights Reserved.
  -----------------------------------------------------------------------------*/

module parhlpmsec
// EDIT_PORT BEGIN
 ( 
input [3:0] i_id,
input [6:0] fary_ffuse_hd2prf_trim,
input [31:0] SSN_START_0_bus_data_in,
input SSN_START_0_bus_clock_in,
output [31:0] SSN_END_0_bus_data_out,
input JT_IN_mbist_ijtag_reset_b,
input JT_IN_ijtag_tck,
input JT_IN_mbist_ijtag_select,
input JT_IN_mbist_ijtag_capture,
input JT_IN_mbist_ijtag_shift,
input JT_IN_mbist_ijtag_update,
input JT_IN_mbist_ijtag_si,
input JT_IN_scan_ijtag_reset_b,
input JT_IN_scan_ijtag_select,
input JT_IN_scan_ijtag_capture,
input JT_IN_scan_ijtag_shift,
input JT_IN_scan_ijtag_update,
input JT_IN_scan_ijtag_si,
output JT_OUT_mbist_ijtag_so,
output JT_OUT_scan_ijtag_so,
input adfx_tap_grpA_enable,
input adfx_tap_grpB_enable,
input adfx_tap_grpC_enable,
input adfx_tap_grpD_enable,
input adfx_tap_grpE_enable,
input adfx_tap_grpG_enable,
input adfx_tap_grpH_enable,
input adfx_tap_grpF_enable,
input adfx_tap_grpZ_enable,
input fdfx_powergood,
output DIAG_AGGR_mbist_diag_done,
output aary_post_busy_out,
output aary_post_complete_out,
output aary_post_pass_out,
input pd_vinf_bisr_si,
input pd_vinf_bisr_reset,
input pd_vinf_bisr_clk,
input pd_vinf_bisr_shift_en,
output pd_vinf_bisr_so,
//input mem_rst_n,
//input powergood_rst_n,
//input rst_n,
input i_msec_disable,
input i_force_clk_en,
input [8:0] fvisa_unit_id,
output [0:0] o_rpl_bkwd,
output [130:0] o_rpl_frwd,
input [0:0] i_rpl_bkwd,
input [130:0] i_rpl_frwd,
output aary_post_complete_rf,
output aary_post_pass_rf,
output [287:0] ascan_sdo,
output avisa_dbg_lane,
output [31:0] avisa_dbg_lane_0,
output avisa_frame,
output avisa_rddata,
output avisa_serdata,
output avisa_serstb,
output avisa_all_dis,
output [3:0] avisa_clk,
output o_msec_mac_rx_e,
output [207:0] o_msec_mac_tx,
output o_msec_mac_tx_v,
output [231:0] o_msec_switch_rx,
output o_msec_switch_rx_v,
output o_msec_switch_tx_e,
output o_msec_zeroize_done,
input [208:0] i_msec_mac_rx,
input i_msec_mac_rx_v,
input i_msec_mac_tx_e,
input i_msec_switch_rx_e,
input [217:0] i_msec_switch_tx,
input i_msec_switch_tx_v,
input clk,
input parhlpports_fabric_DFT_ARRAY_FREEZE_msec_0_15,
input hlp_post_clkungate,
input hlp_post_mux_ctrl,
input parhlpports_fabric_mbist_mode_out_msec,
input fary_post_force_fail,
input hlp_start_post_0,
input [5:0] fary_post_algo_select );
// EDIT_PORT END


// EDIT_NET BEGIN
logic reset_scan_mux_dft_afd_reset_msec_0_o ; 
logic msec_apr_0_ascan_preclk_div4_clk ; 
logic msec_0_div4_clk_pdop_parhlpmsec_clkout ; 
logic msec_0_clk_pdop_parhlpmsec_clkout ; 
logic msec_0_clk_pdop_parhlpmsec_clkfree ;
logic mem_rst_n;
logic powergood_rst_n;
logic rst_n;
// EDIT_NET END

// EDIT_INSTANCE BEGIN

  /* Added by UltiBuild Nets Start */
  wire bisr_so_pd_vinf;
  /* Added by UltiBuild Nets End */

  /* Added by UltiBuild Nets Start */
  wire msec_apr_so, sib_msec_apr_to_select, 
       msec_clk_pdop_parhlpmsec_fdop_scanclk, 
       msec_clk_pdop_parhlpmsec_fdop_clken, 
       msec_div4_clk_pdop_parhlpmsec_fdop_scanclk, clkfree, 
       msec_div4_clk_pdop_parhlpmsec_fdop_clken, 
       mbist_clk_pdop_parhlpmsec__clkout_fdop_scanclk, clkout, clkfree_ts1, 
       mbist_clk_pdop_parhlpmsec__clkout_fdop_clken, fscan_byprst_b, 
       fscan_clkungate, fscan_clkungate_syn_rtl, fscan_latchclosed_b, 
       fscan_latchopen, fscan_mode, fscan_mode_atspeed, fscan_ram_init_en, 
       fscan_ram_init_val, fscan_ret_ctrl, fscan_rstbypen, ijtag_tck, 
       fscan_ram_bypsel, i_fscan_core_shiften_rtl_intercept_o, 
       msec_div4_clk_pdop_parhlpmsec_fdop_divreset, msec_div4_clk_fdop_inv_o1;
  logic [1:0] fscan_clkgenctrl, fscan_clkgenctrlen;
  /* Added by UltiBuild Nets End */
pdop mbist_clk_pdop_parhlpmsec (
    .clken(mbist_clk_pdop_parhlpmsec__clkout_fdop_clken), 
    .clkenfree(1'b1), 
    .clkfree(clkfree_ts1), 
    .clkin(ijtag_tck), 
    .clkout(clkout), 
    .scanclk(mbist_clk_pdop_parhlpmsec__clkout_fdop_scanclk), 
    .soft_high_out()
) ; 
pdop msec_clk_pdop_parhlpmsec (
    .clkin(clk), 
    .clkout(msec_0_clk_pdop_parhlpmsec_clkout), 
    .clkfree(msec_0_clk_pdop_parhlpmsec_clkfree), 
    .clken(msec_clk_pdop_parhlpmsec_fdop_clken), 
    .clkenfree(1'b1), 
    .scanclk(msec_clk_pdop_parhlpmsec_fdop_scanclk), 
    .soft_high_out()
) ; 
pdop msec_div4_clk_pdop_parhlpmsec (
    .clkin(msec_apr_0_ascan_preclk_div4_clk), 
    .clkout(msec_0_div4_clk_pdop_parhlpmsec_clkout), 
    .clken(msec_div4_clk_pdop_parhlpmsec_fdop_clken), 
    .clkenfree(1'b1), 
    .clkfree(clkfree), 
    .scanclk(msec_div4_clk_pdop_parhlpmsec_fdop_scanclk), 
    .soft_high_out()
) ; 
hlp_msec_apr msec_apr (
    .fary_ffuse_hd2prf_trim(fary_ffuse_hd2prf_trim), 
    .i_id(i_id), 
    .mem_rst_n(mem_rst_n), 
    .powergood_rst_n(powergood_rst_n), 
    .DFT_AFD_RESET_B(reset_scan_mux_dft_afd_reset_msec_0_o), 
    .rst_n(rst_n), 
    .i_msec_disable(i_msec_disable), 
    .i_force_clk_en(i_force_clk_en), 
    .fvisa_unit_id(fvisa_unit_id), 
    .o_rpl_bkwd(o_rpl_bkwd), 
    .o_rpl_frwd(o_rpl_frwd), 
    .i_rpl_bkwd(i_rpl_bkwd), 
    .i_rpl_frwd(i_rpl_frwd), 
    .aary_post_complete_rf(aary_post_complete_rf), 
    .aary_post_pass_rf(aary_post_pass_rf), 
    .ascan_sdo(ascan_sdo), 
    .avisa_customer_dis(avisa_dbg_lane), 
    .avisa_dbg_lane(avisa_dbg_lane_0), 
    .avisa_frame(avisa_frame), 
    .avisa_rddata(avisa_rddata), 
    .avisa_serdata(avisa_serdata), 
    .avisa_serstb(avisa_serstb), 
    .avisa_all_dis(avisa_all_dis), 
    .avisa_clk(avisa_clk), 
    .o_msec_mac_rx_e(o_msec_mac_rx_e), 
    .o_msec_mac_tx(o_msec_mac_tx), 
    .o_msec_mac_tx_v(o_msec_mac_tx_v), 
    .o_msec_switch_rx(o_msec_switch_rx), 
    .o_msec_switch_rx_v(o_msec_switch_rx_v), 
    .o_msec_switch_tx_e(o_msec_switch_tx_e), 
    .o_msec_zeroize_done(o_msec_zeroize_done), 
    .i_msec_mac_rx(i_msec_mac_rx), 
    .i_msec_mac_rx_v(i_msec_mac_rx_v), 
    .i_msec_mac_tx_e(i_msec_mac_tx_e), 
    .i_msec_switch_rx_e(i_msec_switch_rx_e), 
    .i_msec_switch_tx(i_msec_switch_tx), 
    .i_msec_switch_tx_v(i_msec_switch_tx_v), 
    .ascan_preclk_div4_clk(msec_apr_0_ascan_preclk_div4_clk), 
    .fscan_postclk_div4_clk(msec_0_div4_clk_pdop_parhlpmsec_clkout), 
    .clk(msec_0_clk_pdop_parhlpmsec_clkout), 
    .ports_clk_free(msec_0_clk_pdop_parhlpmsec_clkfree), 
    .DFT_ARRAY_FREEZE(parhlpports_fabric_DFT_ARRAY_FREEZE_msec_0_15), 
    .hlp_post_clkungate(hlp_post_clkungate), 
    .hlp_post_mux_ctrl(hlp_post_mux_ctrl), 
    .mbist_mode(1'b1), 
    .aary_post_busy(aary_post_busy_out), 
    .aary_post_pass(aary_post_pass_out), 
    .aary_post_complete(aary_post_complete_out), 
    .fary_post_force_fail(fary_post_force_fail), 
    .fary_trigger_post(hlp_start_post_0), 
    .fary_post_algo_select(fary_post_algo_select), 
    .fet_ack_b(), 
    .fet_en_b(1'b0), 
    .fary_trigger_post_rf(1'b0), 
    .fary_post_pass_rf(1'b0), 
    .fdfx_jta_force_latch_mem_fuses(1'b0), 
    .clk_rscclk(clkout), 
    .mbist_diag_done(DIAG_AGGR_mbist_diag_done), 
    .DFTMASK(fscan_ram_bypsel), 
    .DFTSHIFTEN(i_fscan_core_shiften_rtl_intercept_o), 
    .fary_ffuse_rf_sleep(2'b0), 
    .fary_output_reset(1'b0), 
    .fscan_byprst_b(fscan_byprst_b), 
    .fscan_clkgenctrl({msec_div4_clk_fdop_inv_o1, fscan_clkgenctrl[0]}), 
    .fscan_clkgenctrlen(fscan_clkgenctrlen), 
    .fscan_clkungate(fscan_clkungate), 
    .fscan_clkungate_syn(fscan_clkungate_syn_rtl), 
    .fscan_latchclosed_b(fscan_latchclosed_b), 
    .fscan_latchopen(fscan_latchopen), 
    .fscan_mode(fscan_mode), 
    .fscan_mode_atspeed(fscan_mode_atspeed), 
    .fscan_ram_bypsel_rf(1'b0), 
    .fscan_ram_init_en(fscan_ram_init_en), 
    .fscan_ram_init_val(fscan_ram_init_val), 
    .fscan_ram_rdis_b(1'b0), 
    .fscan_ram_wdis_b(1'b0), 
    .fscan_ret_ctrl(fscan_ret_ctrl), 
    .fscan_rstbypen(fscan_rstbypen), 
    .fscan_sdi(288'b0), 
    .fscan_shiften(1'b0), 
    .fsta_dfxact_afd(1'b0), 
    .fvisa_all_dis(1'b0), 
    .fvisa_clk(4'b0), 
    .fvisa_customer_dis(1'b0), 
    .fvisa_dbg_lane(32'b0), 
    .fvisa_frame(1'b0), 
    .fvisa_rddata(1'b0), 
    .fvisa_resetb(1'b0), 
    .fvisa_serdata(1'b0), 
    .fvisa_serstb(1'b0), 
    .i_msec_zeroize(1'b0), 
    .isol_en_b(1'b0), 
    .pwr_mgmt_in_rf(5'b0), 
    .isol_ack_b(), 
    .fary_ijtag_tck(JT_IN_ijtag_tck), 
    .fary_ijtag_rst_b(JT_IN_mbist_ijtag_reset_b), 
    .fary_ijtag_capture(JT_IN_mbist_ijtag_capture), 
    .fary_ijtag_shift(JT_IN_mbist_ijtag_shift), 
    .fary_ijtag_update(JT_IN_mbist_ijtag_update), 
    .fary_ijtag_select(sib_msec_apr_to_select), 
    .fary_ijtag_si(JT_IN_mbist_ijtag_si), 
    .aary_ijtag_so(msec_apr_so), 
    .bisr_so_pd_vinf(bisr_so_pd_vinf), 
    .bisr_si_pd_vinf(pd_vinf_bisr_si), 
    .bisr_shift_en_pd_vinf(pd_vinf_bisr_shift_en), 
    .bisr_clk_pd_vinf(pd_vinf_bisr_clk), 
    .bisr_reset_pd_vinf(pd_vinf_bisr_reset), 
    .core_rst_b(1'b0)
) ; 
ctech_lib_inv msec_div4_clk_fdop_inv (
    .a(msec_div4_clk_pdop_parhlpmsec_fdop_divreset), 
    .o1(msec_div4_clk_fdop_inv_o1)
) ; 
bisr_pipeline_reg parhlpmsec_bisr_pipe (
    .CLK(pd_vinf_bisr_clk), 
    .RSTB(pd_vinf_bisr_reset), 
    .SI(bisr_so_pd_vinf), 
    .SO(pd_vinf_bisr_so), 
    .SE(pd_vinf_bisr_shift_en), 
    .D(1'b0), 
    .MSO(1'b0), 
    .MSEL(1'b0), 
    .Q()
) ; 
ctech_lib_mux_2to1 reset_scan_mux_dft_afd_reset_msec (
    .d2(powergood_rst_n), 
    .o(reset_scan_mux_dft_afd_reset_msec_0_o), 
    .d1(fscan_byprst_b), 
    .s(fscan_rstbypen)
) ; 
// EDIT_INSTANCE END

  /* Added by UltiBuild Instances Start */
  parhlpmsec_ub parhlpmsec_ub(.sib_scan_so(JT_OUT_scan_ijtag_so), 
                              .sib_msec_apr_so(JT_OUT_mbist_ijtag_so), 
                              .JT_IN_mbist_ijtag_si(JT_IN_mbist_ijtag_si), 
                              .msec_apr_so(msec_apr_so), 
                              .JT_IN_mbist_ijtag_select(JT_IN_mbist_ijtag_select), 
                              .JT_IN_scan_ijtag_si(JT_IN_scan_ijtag_si), 
                              .JT_IN_scan_ijtag_select(JT_IN_scan_ijtag_select), 
                              .sib_msec_apr_to_select(sib_msec_apr_to_select), 
                              .JT_IN_scan_ijtag_update(JT_IN_scan_ijtag_update), 
                              .JT_IN_scan_ijtag_reset_b(JT_IN_scan_ijtag_reset_b), 
                              .JT_IN_scan_ijtag_capture(JT_IN_scan_ijtag_capture), 
                              .JT_IN_mbist_ijtag_shift(JT_IN_mbist_ijtag_shift), 
                              .JT_IN_mbist_ijtag_update(JT_IN_mbist_ijtag_update), 
                              .JT_IN_scan_ijtag_shift(JT_IN_scan_ijtag_shift), 
                              .JT_IN_mbist_ijtag_reset_b(JT_IN_mbist_ijtag_reset_b), 
                              .JT_IN_ijtag_tck(JT_IN_ijtag_tck), 
                              .JT_IN_mbist_ijtag_capture(JT_IN_mbist_ijtag_capture), 
                              .bus_data_out(SSN_END_0_bus_data_out), 
                              .SSN_START_0_bus_data_in(SSN_START_0_bus_data_in), 
                              .SSN_START_0_bus_clock_in(SSN_START_0_bus_clock_in), 
                              .msec_clk_pdop_parhlpmsec_fdop_scanclk(msec_clk_pdop_parhlpmsec_fdop_scanclk), 
                              .clkout(msec_0_clk_pdop_parhlpmsec_clkout), 
                              .clkfree(msec_0_clk_pdop_parhlpmsec_clkfree), 
                              .msec_clk_pdop_parhlpmsec_fdop_clken(msec_clk_pdop_parhlpmsec_fdop_clken), 
                              .msec_div4_clk_pdop_parhlpmsec_fdop_scanclk(msec_div4_clk_pdop_parhlpmsec_fdop_scanclk), 
                              .clkout_ts1(msec_0_div4_clk_pdop_parhlpmsec_clkout), 
                              .clkfree_ts1(clkfree), 
                              .msec_div4_clk_pdop_parhlpmsec_fdop_clken(msec_div4_clk_pdop_parhlpmsec_fdop_clken), 
                              .mbist_clk_pdop_parhlpmsec__clkout_fdop_scanclk(mbist_clk_pdop_parhlpmsec__clkout_fdop_scanclk), 
                              .clkout_ts2(clkout), .clkfree_ts2(clkfree_ts1), 
                              .mbist_clk_pdop_parhlpmsec__clkout_fdop_clken(mbist_clk_pdop_parhlpmsec__clkout_fdop_clken), 
                              .fscan_byprst_b(fscan_byprst_b), 
                              .fscan_clkgenctrl(fscan_clkgenctrl), 
                              .fscan_clkgenctrlen(fscan_clkgenctrlen), 
                              .fscan_clkungate(fscan_clkungate), 
                              .fscan_clkungate_syn_rtl(fscan_clkungate_syn_rtl), 
                              .fscan_latchclosed_b(fscan_latchclosed_b), 
                              .fscan_latchopen(fscan_latchopen), .fscan_mode(fscan_mode), 
                              .fscan_mode_atspeed(fscan_mode_atspeed), 
                              .fscan_ram_init_en(fscan_ram_init_en), 
                              .fscan_ram_init_val(fscan_ram_init_val), 
                              .fscan_ret_ctrl(fscan_ret_ctrl), 
                              .fscan_rstbypen(fscan_rstbypen), .ijtag_tck(ijtag_tck), 
                              .fscan_ram_bypsel(fscan_ram_bypsel), 
                              .i_fscan_core_shiften_rtl_intercept_o(i_fscan_core_shiften_rtl_intercept_o), 
                              .msec_div4_clk_pdop_parhlpmsec_fdop_divreset(msec_div4_clk_pdop_parhlpmsec_fdop_divreset), 
                              .fdfx_powergood(fdfx_powergood), 
                              .adfx_tap_grpF_enable(adfx_tap_grpF_enable)
  );
  /* Added by UltiBuild Instances End */
endmodule
