config soc_rtl_config;
design cnic_lib_10m.cnic_wrapper;
//design cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap;
//instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_0 liblist mac100_lib;
//instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_0 liblist mac100_lib;
//instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_1 liblist mac100_lib;
//instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_1 liblist mac100_lib;
//instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_2 liblist mac100_lib;
//instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_2 liblist mac100_lib;
//instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_3 liblist mac100_lib;
//instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_3 liblist mac100_lib;
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap_0.mac100_0 liblist mac100_lib; 
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap_0.mac100_1 liblist mac100_lib;
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap_0.mac100_2 liblist mac100_lib;
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap_0.mac100_3 liblist mac100_lib;
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap_1.mac100_4 liblist mac100_lib;
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap_1.mac100_5 liblist mac100_lib;
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap_1.mac100_6 liblist mac100_lib;
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap_1.mac100_7 liblist mac100_lib;
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_0.port4_apr_0.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_1.port4_apr_0.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_2.port4_apr_0.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_3.port4_apr_0.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_4.port4_apr_0.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_5.port4_apr_0.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_0.port4_apr_1.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_1.port4_apr_1.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_2.port4_apr_1.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_3.port4_apr_1.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_4.port4_apr_1.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_5.port4_apr_1.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_0.port4_apr_2.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_1.port4_apr_2.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_2.port4_apr_2.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_3.port4_apr_2.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_4.port4_apr_2.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_5.port4_apr_2.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_0.port4_apr_3.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_1.port4_apr_3.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_2.port4_apr_3.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_3.port4_apr_3.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_4.port4_apr_3.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.hlp.parhlpports.parhlpport4_5.port4_apr_3.u_port4_apr_func_logic.u_mac4.u_mac.u_smac_top liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_0.U_INST.U_TXFF.U_DFFCFGTXCLK liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_1.U_INST.U_TXFF.U_DFFCFGTXCLK liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_2.U_INST.U_TXFF.U_DFFCFGTXCLK liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_3.U_INST.U_TXFF.U_DFFCFGTXCLK liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_4.U_INST.U_TXFF.U_DFFCFGTXCLK liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_5.U_INST.U_TXFF.U_DFFCFGTXCLK liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_6.U_INST.U_TXFF.U_DFFCFGTXCLK liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_7.U_INST.U_TXFF.U_DFFCFGTXCLK liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_0.U_INST.U_TXFF.U_DFFCFGTXCLK[1] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_0.U_INST.U_TXFF.U_DFFCFGTXCLK[0] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_1.U_INST.U_TXFF.U_DFFCFGTXCLK[1] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_1.U_INST.U_TXFF.U_DFFCFGTXCLK[0] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_1.U_INST.U_TXFF.U_DFFCFGTXCLK[1] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_1.U_INST.U_TXFF.U_DFFCFGTXCLK[0] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_5.U_INST.U_TXFF.U_DFFCFGTXCLK[1] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_5.U_INST.U_TXFF.U_DFFCFGTXCLK[0] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_2.U_INST.U_TXFF.U_DFFCFGTXCLK[1] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_2.U_INST.U_TXFF.U_DFFCFGTXCLK[0] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_6.U_INST.U_TXFF.U_DFFCFGTXCLK[1] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_6.U_INST.U_TXFF.U_DFFCFGTXCLK[0] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_3.U_INST.U_TXFF.U_DFFCFGTXCLK[1] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_3.U_INST.U_TXFF.U_DFFCFGTXCLK[0] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_7.U_INST.U_TXFF.U_DFFCFGTXCLK[1] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_7.U_INST.U_TXFF.U_DFFCFGTXCLK[0] liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_0.U_INST.U_M128_TOP.U_M128_TX_TOP.U_TSYNC liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_4.U_INST.U_M128_TOP.U_M128_TX_TOP.U_TSYNC liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_1.U_INST.U_M128_TOP.U_M128_TX_TOP.U_TSYNC liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_5.U_INST.U_M128_TOP.U_M128_TX_TOP.U_TSYNC liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_2.U_INST.U_M128_TOP.U_M128_TX_TOP.U_TSYNC liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_6.U_INST.U_M128_TOP.U_M128_TX_TOP.U_TSYNC liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad0.mac100_wrap0.mac100_3.U_INST.U_M128_TOP.U_M128_TX_TOP.U_TSYNC liblist snps_mac_100g_lib
instance cnic_wrapper.nac_ss.physs.physs0.parmquad1.mac100_wrap1.mac100_7.U_INST.U_M128_TOP.U_M128_TX_TOP.U_TSYNC liblist snps_mac_100g_lib
endconfig
