
`ifndef HLP_PHYSS_STUB
`ifndef NAC_STUB
`ifndef NMC_ONLY
//HLP
//hlpffu
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_3.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_4.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_5.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_6.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_7.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_8.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_9.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_10.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_11.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_12.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_13.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_14.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_15.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_16.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_17.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_18.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_19.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_20.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_21.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_22.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_23.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_24.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_25.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_26.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_27.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_28.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_29.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_30.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_31.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_3.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_4.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_5.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_6.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_7.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_8.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_9.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_10.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_11.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_12.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_13.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_14.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_15.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_16.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_17.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_18.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_19.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_20.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_21.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_22.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_23.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_24.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_25.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_26.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_27.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_28.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_29.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_30.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_31.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_3.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_4.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_5.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_6.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_7.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_8.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_9.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_10.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_11.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_12.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_13.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_14.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_15.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_16.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_17.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_18.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_19.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_20.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_21.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_22.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_23.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_24.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_25.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_26.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_27.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_28.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_29.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_30.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_31.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_3.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_4.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_5.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_6.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_7.FPGA_CLOCKS_RATIO = 64;

//hlp fwd
defparam nac_ss.hlp.parhlpfwd.fwd_apr.u_fwd_apr_tcam_mems.fwd_tcam_mems.fwd_wrap_tcam_ma_table_tcam_shell_1024x35_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpfwd.fwd_apr.u_fwd_apr_tcam_mems.fwd_tcam_mems.fwd_wrap_tcam_ma_table_tcam_shell_1024x35_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpfwd.fwd_apr.u_fwd_apr_tcam_mems.fwd_tcam_mems.fwd_wrap_tcam_ma_table_tcam_shell_1024x35_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpfwd.fwd_apr.u_fwd_apr_tcam_mems.fwd_tcam_mems.fwd_wrap_tcam_ma_table_tcam_shell_1024x35_3.FPGA_CLOCKS_RATIO = 64;

//hlp mod
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_ms_sci_table_tcam_shell_512x80_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_ms_sci_table_tcam_shell_512x80_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_3.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_4.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_5.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_6.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_7.FPGA_CLOCKS_RATIO = 64;

`endif
`endif
`endif
`ifndef HLP_PHYSS_ONLY
`ifndef NMC_ONLY
//hif itp
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems1.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_bar_decoder_tcam_mem_shell_1216x60.FPGA_CLOCKS_RATIO = 64;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems1.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_inner_bar_tcam_mem_shell_512x58.FPGA_CLOCKS_RATIO = 64;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems0.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_bar_decoder_tcam_mem_shell_1216x60.FPGA_CLOCKS_RATIO = 64;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems0.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_inner_bar_tcam_mem_shell_512x58.FPGA_CLOCKS_RATIO = 64;
//
////hif mpp0
//defparam nac_ss.nss.nss.hif_core.hif_cnic.hif_mpp0.parhif_mpp_itp_gic.mpp_itp_gic_apr.mpp_itp_gic_apr_mem.itp_mems.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_inner_bar_tcam_mem_shell_512x58.FPGA_CLOCKS_RATIO = 64;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.hif_mpp0.parhif_mpp_itp_gic.mpp_itp_gic_apr.mpp_itp_gic_apr_mem.itp_mems.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_bar_decoder_tcam_mem_shell_1216x60.FPGA_CLOCKS_RATIO = 64;
//
////hif mpp1
//defparam nac_ss.nss.nss.hif_core.hif_cnic.hif_mpp1.parhif_mpp_itp_gic.mpp_itp_gic_apr.mpp_itp_gic_apr_mem.itp_mems.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_bar_decoder_tcam_mem_shell_1216x60.FPGA_CLOCKS_RATIO = 64 ;
//
////hif_upp1
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_upp1.upp1_apr.upp1_apr_mem.upp_mems1.hif_pcie_pcie_upp_tcam_mems_inst.pcie_upp_wrap_tcam_hif_keepout_tcam_shell_128x72.FPGA_CLOCKS_RATIO = 64;
//
////hif_cnic_common
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_0.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_1.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_2.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_3.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_4.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_5.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_6.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_7.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_8.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_9.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_10.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_11.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_12.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_13.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_14.FPGA_CLOCKS_RATIO = 64 ;
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_15.FPGA_CLOCKS_RATIO = 64 ;
//
////hif_nocss
//defparam nac_ss.nss.nss.hif_nocss_top.hif_nocss_cnic_top.par_hif_nocss_mc.hif_nocss_mc_top.i_hif_nocss_mc_mems.hif_nocss_mc_tcam_mems_inst.hif_nocss_mc_wrap_tcam_hif_nocss_mc_func_chk_shell_6144x19.FPGA_CLOCKS_RATIO = 64;
////hi_upp0
//defparam nac_ss.nss.nss.hif_core.hif_cnic.parhif_upp0.upp0_apr.upp0_apr_mem.upp_mems0.hif_pcie_pcie_upp_tcam_mems_inst.pcie_upp_wrap_tcam_hif_keepout_tcam_shell_128x72.FPGA_CLOCKS_RATIO = 64;
`endif
`endif

`ifndef HLP_PHYSS_ONLY
`ifndef NAC_STUB
`ifndef NMC_ONLY
//CXP
//rdma
/*defparam nac_ss.nss.nss.rdma_top.peip_pmat_par.peip_pmat_apr.peip_pmat_mems_wrap_top.peip_pmat_mems_wrap.peip_pmat_tcam_mems_inst.pmat_wrap_tcam_pmat_ptcam_shell_3072x31_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.rdma_top.peip_pmat_par.peip_pmat_apr.peip_pmat_mems_wrap_top.peip_pmat_mems_wrap.peip_pmat_tcam_mems_inst.pmat_wrap_tcam_pmat_ptcam_shell_3072x31_1.FPGA_CLOCKS_RATIO = 64;

//fxp
defparam nac_ss.nss.nss.fxp_top.fxp.parfxplpm.fxp_lpm_apr.fxp_lpm_mems.fxp_lpm_tcam_mems_inst.fxp_lpm_wrap_tcam_fxp_lpm_root_tcam_shell_2048x33.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.cxp_top.parcxp_cps_hrx_mtx.cxp_trc_apr.cxp_trc_apr_mems.trc_mems.cxp_trc_tcam_mems_inst.trc_wrap_tcam_trc_tcam_shell_8192x40.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.cxp_top.parcxp_par_non_ana_wcm.cxp_wcm_apr.cxp_wcm_apr_mems.wcm_mems.cxp_wcm_tcam_mems_inst.wcm_wrap_tcam_wcm_tcam_shell_128x512.FPGA_CLOCKS_RATIO = 64;

//FXP
defparam nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_0.fpga_tcam.CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_3.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_4.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_5.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_6.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_7.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpsem.parfxpsemmngdp.fxp_sem_mngdp_apr.fxp_sem_mngdp_mems.fxp_sem_mngdp_tcam_mems_inst.fxp_sem_mngdp_wrap_tcam_fxp_sem_proftcam_shell_1024x43_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpsem.parfxpsemmngdp.fxp_sem_mngdp_apr.fxp_sem_mngdp_mems.fxp_sem_mngdp_tcam_mems_inst.fxp_sem_mngdp_wrap_tcam_fxp_sem_proftcam_shell_1024x43_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpsem.parfxpsemmngdp.fxp_sem_mngdp_apr.fxp_sem_mngdp_mems.fxp_sem_mngdp_tcam_mems_inst.fxp_sem_mngdp_wrap_tcam_fxp_sem_proftcam_shell_1024x43_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpsem.parfxpsemmngdp.fxp_sem_mngdp_apr.fxp_sem_mngdp_mems.fxp_sem_mngdp_tcam_mems_inst.fxp_sem_mngdp_wrap_tcam_fxp_sem_proftcam_shell_1024x43_3.FPGA_CLOCKS_RATIO = 64;

defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_3.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_4.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_5.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_6.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_7.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_0.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_1.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_2.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_3.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_4.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_5.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_6.FPGA_CLOCKS_RATIO = 64;
defparam nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_7.FPGA_CLOCKS_RATIO = 64;
*/

`endif
`endif
`endif
//fxp
initial
begin
`ifndef HLP_PHYSS_STUB
`ifndef NAC_STUB
`ifndef NMC_ONLY
//HLP
//hlp ffu
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_3.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_4.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_5.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_6.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_7.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_8.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_9.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_10.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_11.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_12.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_13.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_14.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_15.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_16.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_17.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_18.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_19.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_20.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_21.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_22.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_23.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_24.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_25.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_26.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_27.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_28.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_29.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_30.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_0.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_31.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_3.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_4.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_5.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_6.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_7.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_8.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_9.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_10.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_11.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_12.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_13.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_14.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_15.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_16.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_17.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_18.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_19.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_20.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_21.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_22.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_23.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_24.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_25.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_26.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_27.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_28.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_29.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_30.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_1.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_31.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_3.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_4.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_5.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_6.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_7.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_8.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_9.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_10.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_11.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_12.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_13.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_14.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_15.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_16.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_17.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_18.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_19.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_20.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_21.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_22.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_23.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_24.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_25.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_26.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_27.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_28.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_29.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_30.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfgrp_2.fgrp_apr.u_fgrp_apr_tcam_mems.fgrp_tcam_mems.fgrp_wrap_tcam_ffu_tcam_shell_512x40_31.fpga_fast_clk = clk_tcam_fast;
//hlp cmn
force nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_3.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_4.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_5.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_6.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpffu.parhlpfcmn.fcmn_apr.u_fcmn_apr_tcam_mems.fcmn_tcam_mems.fcmn_wrap_tcam_map_domain_shell_512x40_7.fpga_fast_clk = clk_tcam_fast;


//hlp fwd
force nac_ss.hlp.parhlpfwd.fwd_apr.u_fwd_apr_tcam_mems.fwd_tcam_mems.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpfwd.fwd_apr.u_fwd_apr_tcam_mems.fwd_tcam_mems.fwd_wrap_tcam_ma_table_tcam_shell_1024x35_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpfwd.fwd_apr.u_fwd_apr_tcam_mems.fwd_tcam_mems.fwd_wrap_tcam_ma_table_tcam_shell_1024x35_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpfwd.fwd_apr.u_fwd_apr_tcam_mems.fwd_tcam_mems.fwd_wrap_tcam_ma_table_tcam_shell_1024x35_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpfwd.fwd_apr.u_fwd_apr_tcam_mems.fwd_tcam_mems.fwd_wrap_tcam_ma_table_tcam_shell_1024x35_3.fpga_fast_clk = clk_tcam_fast;

//hlp mod
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_ms_sci_table_tcam_shell_512x80_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_ms_sci_table_tcam_shell_512x80_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_3.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_4.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_5.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_6.fpga_fast_clk = clk_tcam_fast;
force nac_ss.hlp.parhlpmod.mod_apr.u_mod_apr_tcam_mems.mod_tcam_mems.mod_wrap_tcam_mod_tx_stats_vlan_cnt_idx_map_tcam_shell_512x24_7.fpga_fast_clk = clk_tcam_fast;


//force nac_ss.nss.nss.rdma_top.peip_pmat_par.peip_pmat_apr.peip_pmat_mems_wrap_top.peip_pmat_mems_wrap.peip_pmat_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
//force nac_ss.nss.nss.rdma_top.peip_pmat_par.peip_pmat_apr.peip_pmat_mems_wrap_top.peip_pmat_mems_wrap.peip_pmat_tcam_mems_inst.pmat_wrap_tcam_pmat_ptcam_shell_3072x31_0.fpga_fast_clk = clk_tcam_fast;
//force nac_ss.nss.nss.rdma_top.peip_pmat_par.peip_pmat_apr.peip_pmat_mems_wrap_top.peip_pmat_mems_wrap.peip_pmat_tcam_mems_inst.pmat_wrap_tcam_pmat_ptcam_shell_3072x31_1.fpga_fast_clk = clk_tcam_fast;
//force nac_ss.nss.nss.fxp_top.fxp.parfxplpm.fxp_lpm_apr.fxp_lpm_mems.fxp_lpm_tcam_mems_inst.fxp_lpm_wrap_tcam_fxp_lpm_root_tcam_shell_2048x33.fpga_fast_clk  = clk_tcam_fast;
`endif
`endif
`endif

`ifndef HLP_PHYSS_ONLY
`ifndef NMC_ONLY
//hif itp
/*force nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems0.hif_pcie_pcie_itp_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems1.hif_pcie_pcie_itp_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems0.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_bar_decoder_tcam_mem_shell_1216x60.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems1.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_bar_decoder_tcam_mem_shell_1216x60.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems0.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_inner_bar_tcam_mem_shell_512x58.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_nli_itp.hif_nli_itp_apr.hif_nli_itp_apr_mem.nli_itp_mems1.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_inner_bar_tcam_mem_shell_512x58.fpga_fast_clk = clk_tcam_fast;

//hif mpp0
force nac_ss.nss.nss.hif_core.hif_cnic.hif_mpp0.parhif_mpp_itp_gic.mpp_itp_gic_apr.mpp_itp_gic_apr_mem.itp_mems.hif_pcie_pcie_itp_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_core.hif_cnic.hif_mpp0.parhif_mpp_itp_gic.mpp_itp_gic_apr.mpp_itp_gic_apr_mem.itp_mems.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_inner_bar_tcam_mem_shell_512x58.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_core.hif_cnic.hif_mpp0.parhif_mpp_itp_gic.mpp_itp_gic_apr.mpp_itp_gic_apr_mem.itp_mems.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_bar_decoder_tcam_mem_shell_1216x60.fpga_fast_clk = clk_tcam_fast;

//hif mpp1
force nac_ss.nss.nss.hif_core.hif_cnic.hif_mpp1.parhif_mpp_itp_gic.mpp_itp_gic_apr.mpp_itp_gic_apr_mem.itp_mems.hif_pcie_pcie_itp_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.hif_mpp1.parhif_mpp_itp_gic.mpp_itp_gic_apr.mpp_itp_gic_apr_mem.itp_mems.hif_pcie_pcie_itp_tcam_mems_inst.pcie_itp_wrap_tcam_hif_itp_bar_decoder_tcam_mem_shell_1216x60.fpga_fast_clk = clk_tcam_fast ;

//hif cnic common
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_0.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_1.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_2.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_3.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_4.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_5.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_6.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_7.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_8.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_9.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_10.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_11.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_12.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_13.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_14.fpga_fast_clk = clk_tcam_fast ;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_cnic_common.hif_cnic_common_apr.hif_cnic_common_apr_mem.csr_decoder_mems.hif_pcie_pcie_csr_decoder_tcam_mems_inst.pcie_csr_decoder_wrap_tcam_pcie_vec2evv_cam_shell_1024x26_15.fpga_fast_clk = clk_tcam_fast ;

//New one added
//r15
force nac_ss.nss.nss.hif_nocss_top.hif_nocss_cnic_top.par_hif_nocss_mc.hif_nocss_mc_top.i_hif_nocss_mc_mems.hif_nocss_mc_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_nocss_top.hif_nocss_cnic_top.par_hif_nocss_mc.hif_nocss_mc_top.i_hif_nocss_mc_mems.hif_nocss_mc_tcam_mems_inst.hif_nocss_mc_wrap_tcam_hif_nocss_mc_func_chk_shell_6144x19.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_upp1.upp1_apr.upp1_apr_mem.upp_mems1.hif_pcie_pcie_upp_tcam_mems_inst.pcie_upp_wrap_tcam_hif_keepout_tcam_shell_128x72.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.hif_core.hif_cnic.parhif_upp0.upp0_apr.upp0_apr_mem.upp_mems0.hif_pcie_pcie_upp_tcam_mems_inst.pcie_upp_wrap_tcam_hif_keepout_tcam_shell_128x72.fpga_fast_clk  = clk_tcam_fast;*/
`endif
`endif

`ifndef HLP_PHYSS_ONLY
`ifndef NAC_STUB
`ifndef NMC_ONLY
//CXP
/*force nac_ss.nss.nss.cxp_top.parcxp_cps_hrx_mtx.cxp_trc_apr.cxp_trc_apr_mems.trc_mems.cxp_trc_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.cxp_top.parcxp_par_non_ana_wcm.cxp_wcm_apr.cxp_wcm_apr_mems.wcm_mems.cxp_wcm_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.cxp_top.parcxp_cps_hrx_mtx.cxp_trc_apr.cxp_trc_apr_mems.trc_mems.cxp_trc_tcam_mems_inst.trc_wrap_tcam_trc_tcam_shell_8192x40.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.cxp_top.parcxp_par_non_ana_wcm.cxp_wcm_apr.cxp_wcm_apr_mems.wcm_mems.cxp_wcm_tcam_mems_inst.wcm_wrap_tcam_wcm_tcam_shell_128x512.fpga_fast_clk = clk_tcam_fast;

//FXP
//FXP HASH
force nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_3.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_4.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_5.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_6.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxphash.fxp_hash_apr.fxp_hash_mems.fxp_hash_tcam_mems_inst.fxp_hash_wrap_tcam_fxp_hash_profile_tcam_shell_512x25_7.fpga_fast_clk = clk_tcam_fast;

//FXPsem
force nac_ss.nss.nss.fxp_top.fxp.parfxpsem.parfxpsemmngdp.fxp_sem_mngdp_apr.fxp_sem_mngdp_mems.fxp_sem_mngdp_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpsem.parfxpsemmngdp.fxp_sem_mngdp_apr.fxp_sem_mngdp_mems.fxp_sem_mngdp_tcam_mems_inst.fxp_sem_mngdp_wrap_tcam_fxp_sem_proftcam_shell_1024x43_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpsem.parfxpsemmngdp.fxp_sem_mngdp_apr.fxp_sem_mngdp_mems.fxp_sem_mngdp_tcam_mems_inst.fxp_sem_mngdp_wrap_tcam_fxp_sem_proftcam_shell_1024x43_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpsem.parfxpsemmngdp.fxp_sem_mngdp_apr.fxp_sem_mngdp_mems.fxp_sem_mngdp_tcam_mems_inst.fxp_sem_mngdp_wrap_tcam_fxp_sem_proftcam_shell_1024x43_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpsem.parfxpsemmngdp.fxp_sem_mngdp_apr.fxp_sem_mngdp_mems.fxp_sem_mngdp_tcam_mems_inst.fxp_sem_mngdp_wrap_tcam_fxp_sem_proftcam_shell_1024x43_3.fpga_fast_clk = clk_tcam_fast;

//fxpwcm
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_3.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_4.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_5.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_6.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp0.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_7.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_0.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_1.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_2.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_3.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_4.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_5.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_6.fpga_fast_clk = clk_tcam_fast;
force nac_ss.nss.nss.fxp_top.fxp.parfxpwcm.parfxpwcmgrps.parfxpwcmgrp1.fxp_wcm_grp_apr0.fxp_wcm_grp_mems.fxp_wcm_grp_tcam_mems_inst.fxp_wcm_grp_wrap_tcam_fxp_wcm_grp_tcam_shell_1024x40_7.fpga_fast_clk = clk_tcam_fast;*/
`endif
`endif
`endif
end
