// i2c_master_inst_conduit_end_bfm_ip.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module i2c_master_inst_conduit_end_bfm_ip (
		output wire [0:0] sig_conduit_data_in, // conduit.conduit_data_in
		output wire [0:0] sig_conduit_clk_in,  //        .conduit_clk_in
		input  wire [0:0] sig_conduit_data_oe, //        .conduit_data_oe
		input  wire [0:0] sig_conduit_clk_oe   //        .conduit_clk_oe
	);

	i2c_master_inst_conduit_end_bfm_ip_altera_conduit_bfm_191_tdqh7na i2c_master_inst_conduit_end_bfm (
		.sig_conduit_data_in (sig_conduit_data_in), //  output,  width = 1, conduit.conduit_data_in
		.sig_conduit_clk_in  (sig_conduit_clk_in),  //  output,  width = 1,        .conduit_clk_in
		.sig_conduit_data_oe (sig_conduit_data_oe), //   input,  width = 1,        .conduit_data_oe
		.sig_conduit_clk_oe  (sig_conduit_clk_oe)   //   input,  width = 1,        .conduit_clk_oe
	);

endmodule
