// s10_iopll_125mhz_125mhz.v

// Generated using ACDS version 23.3 104

`timescale 1 ps / 1 ps
module s10_iopll_125mhz_125mhz (
		input  wire  refclk,   //  refclk.clk
		output wire  locked,   //  locked.export
		input  wire  rst,      //   reset.reset
		output wire  outclk_0  // outclk0.clk
	);

	s10_iopll_125mhz_125mhz_altera_iopll_1931_mbhbj2q iopll_0 (
		.refclk   (refclk),   //   input,  width = 1,  refclk.clk
		.locked   (locked),   //  output,  width = 1,  locked.export
		.rst      (rst),      //   input,  width = 1,   reset.reset
		.outclk_0 (outclk_0)  //  output,  width = 1, outclk0.clk
	);

endmodule
