//
//  INTEL CONFIDENTIAL
//
//  Copyright 2016 Intel Corporation All Rights Reserved.
//
//  The source code contained or described herein and all documents related
//  to the source code ("Material") are owned by Intel Corporation or its
//  suppliers or licensors. Title to the Material remains with Intel
//  Corporation or its suppliers and licensors. The Material contains trade
//  secrets and proprietary and confidential information of Intel or its
//  suppliers and licensors. The Material is protected by worldwide copyright
//  and trade secret laws and treaty provisions. No part of the Material may
//  be used, copied, reproduced, modified, published, uploaded, posted,
//  transmitted, distributed, or disclosed in any way without Intel's prior
//  express written permission.
//
//  No license under any patent, copyright, trade secret or other intellectual
//  property right is granted to or conferred upon you by disclosure or
//  delivery of the Materials, either expressly, by implication, inducement,
//  estoppel or otherwise. Any license under such intellectual property rights
//  must be express and approved by Intel in writing.
//

`ifndef _ARRAY_GENERIC_RWC_CAM_SV
`define _ARRAY_GENERIC_RWC_CAM_SV

///------------------------------------------------------------------------------------------------------------------------
/// Intel Proprietary        Intel Confidential        Intel Proprietary        Intel Confidential        Intel Proprietary
///------------------------------------------------------------------------------------------------------------------------
/// Copyright (c) 2013-2014 Intel Corporation.
/// The following information is a confidential and proprietary property of Intel Corporation.
/// The possession or use of the following information requires a written license from Intel Corporation.
///------------------------------------------------------------------------------------------------------------------------
/// RTL Primary Contacts         : Marcus Cheung <marcus.w.cheung@intel.com>
/// RTL Secondary Contacts       : Arvi Radhakrishnan <aravinda.k.radhakrishnan@intel.com>
///                              : Camly Lam <camly.lam@intel.com>
///------------------------------------------------------------------------------------------------------------------------
/// Generated by                 : nmbhanda
/// Generated on                 : Mon Aug  7 10:35:22 PDT 2017
/// Script Version               : 1p0_final
/// Last Modified by Author      : Marcus Cheung <marcus.w.cheung@intel.com>
/// Last Modified Date           :
/// Original Author              : Marcus Cheung <marcus.w.cheung@intel.com>
/// Created Date                 : 
///------------------------------------------------------------------------------------------------------------------------
/// General Information:
/// ------------------------------
/// Generic RD/WR CAM array module for SDG server designs in 10nm projects.
/// Behavioral modeling of a parameterized register file core with no DFX features.
/// RTL is written in SystemVerilog.
///------------------------------------------------------------------------------------------------------------------------
/// Detail Information:
/// ------------------------------
/// Addresses      : RD/WR addresses are encoded.
///                  Input addresses will be valid at the array in ADDRESS_LATENCY(#) phases after being driven.
///                  Default value for ADDRESS_LATENCY is 1, corresponding to a B-latch.
/// Enables        : RD/WR enables are used to condition the clock and wordlines.
///                : Input enables will be valid at the array in ENABLE_LATENCY(#) phases after being driven.
///                  Default value for ENABLE_LATENCY is 1, corresponding to a B-latch.
/// Write Data     : Write data will be valid at the array DATA_LATENCY(#) phases after being driven.
///                  Default value for DATA_LATENCY is 2, corresponding to a rising-edge flop. 
/// Read Data      : Read data will be valid at the output of a SDL 1 phase after being read.
/// Address Offset : 
///------------------------------------------------------------------------------------------------------------------------
/// Other Information:
/// ------------------------------
///  10nm SDG RFIP RTL Release Path:
///  /p/hdk/rtl/ip_releases/shdk74/array_macro_module
///
///------------------------------------------------------------------------------------------------------------------------
/// Lintra Information
/// ------------------------------
///
///------------------------------------------------------------------------------------------------------------------------

module array_generic_rwc_cam #(
//------------------------------------------------------------------------------------------------------------------------
// parameters
//------------------------------------------------------------------------------------------------------------------------
  parameter MODULE                 = "array_generic_rwc_cam",
  parameter BITS                   = 2,
  parameter ENTRIES                = 8,
  parameter DWIDTH                 = 2,
  parameter AWIDTH                 = 3,
  parameter RD_PORTS               = 1,
  parameter WR_PORTS               = 1,
  parameter CM_PORTS               = 1,
  parameter BPHASE_RD              = 0,
  parameter BPHASE_WR              = 0,
  parameter BPHASE_CM              = 0,
  parameter SEGMENTS               = 0,
  parameter BITS_PER_SEGMENT       = 0,
  parameter SDL_INITVAL            = {1'b0},
  parameter ADDRESS_OFFSET         = {AWIDTH{1'b0}},
  parameter NO_CAM_LATENCY         = 0,
  parameter NO_CAM_LSB             = 0,
  parameter IN_PIPE_STAGES         = 0,
  parameter OUT_PIPE_STAGES        = 0
)
(
//------------------------------------------------------------------------------------------------------------------------
// interfaces
//------------------------------------------------------------------------------------------------------------------------
  input  logic [RD_PORTS-1:0]               ckrd          ,
  input  logic [RD_PORTS-1:0]               rden          ,
  input  logic [RD_PORTS-1:0][AWIDTH-1:0]   rdaddr        ,
  output logic [RD_PORTS-1:0][DWIDTH-1:0]   rddata        ,
  input  logic [RD_PORTS-1:0]               sdl_init      ,
  input  logic [WR_PORTS-1:0]               ckwr          ,
  input  logic [WR_PORTS-1:0]               wren          ,
  input  logic [WR_PORTS-1:0][AWIDTH-1:0]   wraddr        ,
  input  logic [WR_PORTS-1:0][DWIDTH-1:0]   wrdata        ,
  input  logic [CM_PORTS-1:0]               ckcm          ,
  input  logic [CM_PORTS-1:0]               cmen          ,
  input  logic [CM_PORTS-1:0][DWIDTH-1:0]   cmdata        ,
  output logic [CM_PORTS-1:0][ENTRIES-1:0]  cmmatch       ,
  input  logic [RD_PORTS-1:0]               rdaddr_fd     ,
  input  logic [RD_PORTS-1:0]               rdaddr_rd     ,
  input  logic [WR_PORTS-1:0]               wraddr_fd     ,
  input  logic [WR_PORTS-1:0]               wraddr_rd     ,
  input  logic [WR_PORTS-1:0]               wrdata_fd     ,
  input  logic [WR_PORTS-1:0]               wrdata_rd     ,
  input  logic [CM_PORTS-1:0]               cmdata_fd     ,
  input  logic [CM_PORTS-1:0]               cmdata_rd     
);
//------------------------------------------------------------------------------------------------------------------------
// declarations
//------------------------------------------------------------------------------------------------------------------------
  logic [RD_PORTS-1:0]               ckrdaddrrcb      ;
  logic [WR_PORTS-1:0]               ckwraddrrcb      ;
  logic [WR_PORTS-1:0]               ckwrdatarcb      ;
  logic [WR_PORTS-1:0]               ckcmdatarcb      ;
  logic [RD_PORTS-1:0][AWIDTH-1:0]   rdaddr_lat       ;
  logic [RD_PORTS-1:0]               sdl_init_lat     ;
  logic [WR_PORTS-1:0][AWIDTH-1:0]   wraddr_lat       ;
  logic [WR_PORTS-1:0][DWIDTH-1:0]   wrdata_lat       ;
  logic [CM_PORTS-1:0][DWIDTH-1:0]   cmdata_lat       ;
  logic [RD_PORTS-1:0][DWIDTH-1:0]   sdltoout         ;

  logic [DWIDTH-1:0]   ARRAY            [ENTRIES-1:0];

logic       [IN_PIPE_STAGES:0][WR_PORTS-1:0] wren_pipe;
logic       [IN_PIPE_STAGES:0][WR_PORTS-1:0][AWIDTH-1:0] wraddr_pipe;
logic       [IN_PIPE_STAGES:0][WR_PORTS-1:0][DWIDTH-1:0] wrdata_pipe;
logic       [IN_PIPE_STAGES:0][RD_PORTS-1:0] rden_pipe;
logic       [IN_PIPE_STAGES:0][RD_PORTS-1:0][AWIDTH-1:0] rdaddr_pipe;
logic       [OUT_PIPE_STAGES:0][RD_PORTS-1:0][DWIDTH-1:0] rddata_pipe;
  
//------------------------------------------------------------------------------------------------------------------------

//------------------------------------------------------------------------------------------------------------------------
// modeling writes
//------------------------------------------------------------------------------------------------------------------------

  //Internal variables
  integer n,m;

  wire              common_ckwr;
  wire              common_ckrd;
  wire              common_ckcm;
  wire              common_sdl_init;


  assign  common_ckwr = ckwr[0];
  assign  common_ckrd = ckrd[0];
  assign  common_ckcm = ckcm[0];
  assign  common_sdl_init = sdl_init[0];

//add pipeline stages
assign wren_pipe[0] = wren;
assign wraddr_pipe[0] = wraddr;
assign wrdata_pipe[0] = wrdata;
assign rden_pipe[0] = rden;
assign rdaddr_pipe[0] = rdaddr;
assign rddata = rddata_pipe[OUT_PIPE_STAGES];

generate
  for (genvar port=0; port<WR_PORTS; port++) begin: wr_in_pipe
    if (IN_PIPE_STAGES > 0) begin: wr_ctrl_pipe
      for (genvar pipe=1; pipe<=IN_PIPE_STAGES; pipe++) begin
        always_ff @ (posedge common_ckwr ) begin
            wren_pipe[pipe][port] <= wren_pipe[pipe-1][port];
            wraddr_pipe[pipe][port] <= wraddr_pipe[pipe-1][port];
            wrdata_pipe[pipe][port] <= wrdata_pipe[pipe-1][port];
        end
      end
    end: wr_ctrl_pipe
  end: wr_in_pipe
  for (genvar port=0; port<RD_PORTS; port++) begin: rd_in_pipe
    if (IN_PIPE_STAGES > 0) begin: rd_ctrl_pipe
      for (genvar pipe=1; pipe<=IN_PIPE_STAGES; pipe++) begin
          always_ff @ (posedge common_ckrd ) begin
              rden_pipe[pipe][port] <= rden_pipe[pipe-1][port];
              rdaddr_pipe[pipe][port] <= rdaddr_pipe[pipe-1][port];
          end
      end
    end: rd_ctrl_pipe
  end: rd_in_pipe
  for (genvar port=0; port<RD_PORTS; port++) begin: out_pipe
    if (OUT_PIPE_STAGES > 0) begin
      for (genvar pipe=1; pipe<=OUT_PIPE_STAGES; pipe++) begin
          always_ff @ (posedge common_ckrd[port]) begin
            rddata_pipe[pipe][port] <= rddata_pipe[pipe-1][port];
          end
      end
    end
  end: out_pipe
endgenerate
  
  /*
    * Array Write Logic
    * Assuming common clock in all write ports
  */
  always@(posedge common_ckwr)
  begin
    if(common_sdl_init)
    begin
      for(n=0;n<WR_PORTS;n++)
      begin
        ARRAY[n]  <=  {DWIDTH{SDL_INITVAL[n]}};
      end
    end
    else
    begin
      for(n=0;n<WR_PORTS;n++)
      begin
        if(wren_pipe[IN_PIPE_STAGES][n])
        begin
          ARRAY[wraddr_pipe[IN_PIPE_STAGES][n] - ADDRESS_OFFSET] <=  wrdata_pipe[IN_PIPE_STAGES][n];
        end
      end
    end
  end

  /*
    * Array read logic
    * Assuming common clock for all read ports
  */
  always@(posedge common_ckrd)
  begin
    for(n=0;n<RD_PORTS;n++)
    begin
      if(sdl_init[n])
      begin
        rddata_pipe[0][n] <=  {DWIDTH{SDL_INITVAL[n]}};
      end
      else if(rden_pipe[IN_PIPE_STAGES][n])
      begin
        rddata_pipe[0][n] <=  ARRAY[rdaddr_pipe[IN_PIPE_STAGES][n] - ADDRESS_OFFSET];
      end
    end
  end

  generate
  for (genvar i=0; i<CM_PORTS; i++) begin : msff_cmdata_lat
    if (NO_CAM_LATENCY) begin : msff_cmdata_lat_no_cam_latency
      assign cmdata_lat[i] = cmdata[i];
    end
    else begin : msff_cmdata_lat_cam_latency
      always @(posedge common_ckcm ) if (cmen[i]) cmdata_lat[i] <= cmdata[i];
    end
  end
  endgenerate

  /*
    * Match logic
    * Assuming common match clock
  */
//  always@(posedge  common_ckcm)
always_comb
  begin
    for(int port_num =0;port_num <CM_PORTS;port_num++)
    begin
        for(int entry=0;entry<ENTRIES;entry++)
        begin
          cmmatch[port_num][entry] =  (ARRAY[entry][DWIDTH-1:NO_CAM_LSB]  ==  cmdata_lat[port_num][DWIDTH-1:NO_CAM_LSB]) ? 1'b1  : 1'b0;
        end
    end
  end

endmodule

`endif

///------------------------------------------------------------------------------------------------------------------------
/// Intel Proprietary        Intel Confidential        Intel Proprietary        Intel Confidential        Intel Proprietary
///------------------------------------------------------------------------------------------------------------------------
/// Copyright (c) 2013-2014 Intel Corporation.
/// The following information is a confidential and proprietary property of Intel Corporation.
/// The possession or use of the following information requires a written license from Intel Corporation.
///------------------------------------------------------------------------------------------------------------------------








