//
//  INTEL CONFIDENTIAL
//
//  Copyright 2016 Intel Corporation All Rights Reserved.
//
//  The source code contained or described herein and all documents related
//  to the source code ("Material") are owned by Intel Corporation or its
//  suppliers or licensors. Title to the Material remains with Intel
//  Corporation or its suppliers and licensors. The Material contains trade
//  secrets and proprietary and confidential information of Intel or its
//  suppliers and licensors. The Material is protected by worldwide copyright
//  and trade secret laws and treaty provisions. No part of the Material may
//  be used, copied, reproduced, modified, published, uploaded, posted,
//  transmitted, distributed, or disclosed in any way without Intel's prior
//  express written permission.
//
//  No license under any patent, copyright, trade secret or other intellectual
//  property right is granted to or conferred upon you by disclosure or
//  delivery of the Materials, either expressly, by implication, inducement,
//  estoppel or otherwise. Any license under such intellectual property rights
//  must be express and approved by Intel in writing.
//

`ifndef _ARRAY_GENERIC_RWX_STD_SV
`define _ARRAY_GENERIC_RWX_STD_SV

///------------------------------------------------------------------------------------------------------------------------
/// Intel Proprietary        Intel Confidential        Intel Proprietary        Intel Confidential        Intel Proprietary
///------------------------------------------------------------------------------------------------------------------------
/// Copyright (c) 2013-2014 Intel Corporation.
/// The following information is a confidential and proprietary property of Intel Corporation.
/// The possession or use of the following information requires a written license from Intel Corporation.
///------------------------------------------------------------------------------------------------------------------------
/// RTL Primary Contacts         : Marcus Cheung <marcus.w.cheung@intel.com>
/// RTL Secondary Contacts       : Arvi Radhakrishnan <aravinda.k.radhakrishnan@intel.com>
///                              : Camly Lam <camly.lam@intel.com>
///------------------------------------------------------------------------------------------------------------------------
/// Generated by                 : nmbhanda
/// Generated on                 : Mon Aug  7 10:35:22 PDT 2017
/// Script Version               : 1p0_final
/// Last Modified by Author      : Marcus Cheung <marcus.w.cheung@intel.com>
/// Last Modified Date           :
/// Original Author              : Marcus Cheung <marcus.w.cheung@intel.com>
/// Created Date                 : 
///------------------------------------------------------------------------------------------------------------------------
/// General Information:
/// ------------------------------
/// Generic RD/WR array module for SDG server designs in 10nm projects.
/// Behavioral modeling of a parameterized register file core with no DFX features.
/// RTL is written in SystemVerilog.
///------------------------------------------------------------------------------------------------------------------------
/// Detail Information:
/// ------------------------------
/// Addresses      : RD/WR addresses are encoded.
///                  Input addresses will be valid at the array in ADDRESS_LATENCY(#) phases after being driven.
///                  Default value for ADDRESS_LATENCY is 1, corresponding to a B-latch.
/// Enables        : RD/WR enables are used to condition the clock and wordlines.
///                : Input enables will be valid at the array in ENABLE_LATENCY(#) phases after being driven.
///                  Default value for ENABLE_LATENCY is 1, corresponding to a B-latch.
/// Write Data     : Write data will be valid at the array DATA_LATENCY(#) phases after being driven.
///                  Default value for DATA_LATENCY is 2, corresponding to a rising-edge flop. 
/// Read Data      : Read data will be valid at the output of a SDL 1 phase after being read.
/// Address Offset : 
///------------------------------------------------------------------------------------------------------------------------
/// Other Information:
/// ------------------------------
///  10nm SDG RFIP RTL Release Path:
///  /p/hdk/rtl/ip_releases/shdk74/array_macro_module
///
///------------------------------------------------------------------------------------------------------------------------
/// Lintra Information
/// ------------------------------
///
///------------------------------------------------------------------------------------------------------------------------

module array_generic_rwx_std #(
//------------------------------------------------------------------------------------------------------------------------
// parameters
//------------------------------------------------------------------------------------------------------------------------
  parameter MODULE                 = "array_generic_rwx_std",
  parameter BITS                   = 2,
  parameter ENTRIES                = 8,
  parameter DWIDTH                 = 2,
  parameter AWIDTH                 = 3,
  parameter RD_PORTS               = 1,
  parameter WR_PORTS               = 1,
  parameter CM_PORTS               = 0,
  parameter BPHASE_RD              = 0,
  parameter BPHASE_WR              = 0,
  parameter BPHASE_CM              = 0,
  parameter SEGMENTS               = 0,
  parameter BITS_PER_SEGMENT       = 0,
  parameter SDL_INITVAL            = {1'b0},
  parameter ADDRESS_OFFSET         = {AWIDTH{1'b0}},
  parameter NO_CAM_LATENCY         = 0,
  parameter NO_CAM_LSB             = 0
)
(
//------------------------------------------------------------------------------------------------------------------------
// interfaces
//------------------------------------------------------------------------------------------------------------------------
  input  logic [RD_PORTS-1:0]               ckrd          ,
  input  logic [RD_PORTS-1:0]               rden          ,
  input  logic [RD_PORTS-1:0][AWIDTH-1:0]   rdaddr        ,
  output logic [RD_PORTS-1:0][DWIDTH-1:0]   rddata        ,
  input  logic [RD_PORTS-1:0]               sdl_init      ,
  input  logic [WR_PORTS-1:0]               ckwr          ,
  input  logic [WR_PORTS-1:0]               wren          ,
  input  logic [WR_PORTS-1:0][AWIDTH-1:0]   wraddr        ,
  input  logic [WR_PORTS-1:0][DWIDTH-1:0]   wrdata        ,
  input  logic [RD_PORTS-1:0]               rdaddr_fd     ,
  input  logic [RD_PORTS-1:0]               rdaddr_rd     ,
  input  logic [WR_PORTS-1:0]               wraddr_fd     ,
  input  logic [WR_PORTS-1:0]               wraddr_rd     ,
  input  logic [WR_PORTS-1:0]               wrdata_fd     ,
  input  logic [WR_PORTS-1:0]               wrdata_rd     
);
	//local param modified to match e07 behavior
	localparam WR_SEGS       = 1;
	localparam RD_SEGS       = 1;
	localparam WR_SEGSZ      = DWIDTH;
	localparam WORDS         = ENTRIES;
	localparam WORDLOG2      = $clog2(WORDS);
	localparam RD_SEGSZ      = (WR_SEGS*WR_SEGSZ)/RD_SEGS;
    
        //currently supports 6 read and 5 write ports 
        logic [WR_SEGS-1:0] wenp0, wenp1, wenp2, wenp3, wenp4, wenp5;
	logic [RD_SEGS-1:0] renp0, renp1, renp2, renp3, renp4, renp5, renp6, renp7;
        logic [RD_SEGS-1:0][RD_SEGSZ-1:0] odoutp0,odoutp1,odoutp2,odoutp3,odoutp4,odoutp5,odoutp6,odoutp7; 
    	logic [WR_SEGS-1:0][WR_SEGSZ-1:0] idinp0,idinp1,idinp2,idinp3,idinp4,idinp5;
        logic [WORDLOG2-1:0] arp0, arp1, arp2, arp3, arp4, arp5, arp6, arp7;
   	logic [WORDLOG2-1:0] awp0, awp1, awp2, awp3, awp4, awp5;

 
	//fpga_mem_lib i/o assignments from e07 i/os

/////////////////////////////////
///////// ARRAY WRITE ENABLES ///
/////////////////////////////////

        //pack up wen
	if (WR_PORTS > 0) begin : gen_wenp0 assign wenp0 = wren[0]; end
   	if (WR_PORTS > 1) begin : gen_wenp1 assign wenp1 = wren[1]; end
   	if (WR_PORTS > 2) begin : gen_wenp2 assign wenp2 = wren[2]; end
   	if (WR_PORTS > 3) begin : gen_wenp3 assign wenp3 = wren[3]; end
   	if (WR_PORTS > 4) begin : gen_wenp4 assign wenp4 = wren[4]; end
   	if (WR_PORTS > 5) begin : gen_wenp5 assign wenp5 = wren[5]; end

/////////////////////////////////
///////// ARRAY WRITE ADDRESS ///
/////////////////////////////////

        //pack up awp
	if (WR_PORTS > 0) begin : gen_awp0 assign awp0 = wraddr[0]; end
   	if (WR_PORTS > 1) begin : gen_awp1 assign awp1 = wraddr[1]; end
   	if (WR_PORTS > 2) begin : gen_awp2 assign awp2 = wraddr[2]; end
   	if (WR_PORTS > 3) begin : gen_awp3 assign awp3 = wraddr[3]; end
   	if (WR_PORTS > 4) begin : gen_awp4 assign awp4 = wraddr[4]; end
   	if (WR_PORTS > 5) begin : gen_awp5 assign awp5 = wraddr[5]; end

/////////////////////////////////
///////// ARRAY WRITE DATA    ///
/////////////////////////////////

        //pack up idin
	if (WR_PORTS > 0) begin : gen_idinp0 assign idinp0 = wrdata[0]; end
   	if (WR_PORTS > 1) begin : gen_idinp1 assign idinp1 = wrdata[1]; end
   	if (WR_PORTS > 2) begin : gen_idinp2 assign idinp2 = wrdata[2]; end
   	if (WR_PORTS > 3) begin : gen_idinp3 assign idinp3 = wrdata[3]; end
   	if (WR_PORTS > 4) begin : gen_idinp4 assign idinp4 = wrdata[4]; end
   	if (WR_PORTS > 5) begin : gen_idinp5 assign idinp5 = wrdata[5]; end
   	if (WR_PORTS > 6) begin : not_used_wr_6 not_supported not_supported_wr_port_6(); end

/////////////////////////////////
///////// ARRAY READ ENABLES ////
/////////////////////////////////

        //pack up ren
	if (RD_PORTS > 0) begin : gen_renp0 assign renp0 = rden[0]; end
   	if (RD_PORTS > 1) begin : gen_renp1 assign renp1 = rden[1]; end
   	if (RD_PORTS > 2) begin : gen_renp2 assign renp2 = rden[2]; end
   	if (RD_PORTS > 3) begin : gen_renp3 assign renp3 = rden[3]; end
   	if (RD_PORTS > 4) begin : gen_renp4 assign renp4 = rden[4]; end
   	if (RD_PORTS > 5) begin : gen_renp5 assign renp5 = rden[5]; end
   	if (RD_PORTS > 6) begin : gen_renp6 assign renp6 = rden[6]; end
   	if (RD_PORTS > 7) begin : gen_renp7 assign renp7 = rden[7]; end
   	if (RD_PORTS > 8) begin : not_used_rd_8 not_supported not_supported_rd_port_8(); end

/////////////////////////////////
///////// ARRAY READ ADDRESS  ///
/////////////////////////////////

        //pack up arp
	if (RD_PORTS > 0) begin : gen_arp0 assign arp0 = rdaddr[0]; end
   	if (RD_PORTS > 1) begin : gen_arp1 assign arp1 = rdaddr[1]; end
   	if (RD_PORTS > 2) begin : gen_arp2 assign arp2 = rdaddr[2]; end
   	if (RD_PORTS > 3) begin : gen_arp3 assign arp3 = rdaddr[3]; end
   	if (RD_PORTS > 4) begin : gen_arp4 assign arp4 = rdaddr[4]; end
   	if (RD_PORTS > 5) begin : gen_arp5 assign arp5 = rdaddr[5]; end
   	if (RD_PORTS > 6) begin : gen_arp6 assign arp6 = rdaddr[6]; end
   	if (RD_PORTS > 7) begin : gen_arp7 assign arp7 = rdaddr[7]; end

/////////////////////////////////
///////// ARRAY READ DATA    ///
/////////////////////////////////

        //pack up odout
	if (RD_PORTS > 0) begin : gen_rddata0 assign rddata[0] = odoutp0; end
   	if (RD_PORTS > 1) begin : gen_rddata1 assign rddata[1] = odoutp1; end
   	if (RD_PORTS > 2) begin : gen_rddata2 assign rddata[2] = odoutp2; end
   	if (RD_PORTS > 3) begin : gen_rddata3 assign rddata[3] = odoutp3; end
   	if (RD_PORTS > 4) begin : gen_rddata4 assign rddata[4] = odoutp4; end
   	if (RD_PORTS > 5) begin : gen_rddata5 assign rddata[5] = odoutp5; end
   	if (RD_PORTS > 6) begin : gen_rddata6 assign rddata[6] = odoutp6; end
   	if (RD_PORTS > 7) begin : gen_rddata7 assign rddata[7] = odoutp7; end

///////////////////////////////////
/// ARRAY READ/WRITE OPERATIONS ///
///////////////////////////////////

   //`include "fpga_mem_lib.vs"
  fpga_mport_mem #(
    .RD_PORTS (RD_PORTS),
    .WR_PORTS (WR_PORTS),  
    .WR_SEGS  (WR_SEGS),  
    .WR_SEGSZ (WR_SEGSZ),  
    .RD_SEGS  (RD_SEGS),  
    .WORDS    (WORDS),
    .RW_MPORT_CONFLICT    (0)
   )
   fpga_mport_mem ( 
     .ckwr (ckwr[0]),//connecting only port 0 clock  
     .ckrd (ckrd[0]),//connecting only port 0 clock 
     .arp0 (arp0), 
     .renp0 (renp0), 
     .odoutp0 (odoutp0), 
     .arp1 (arp1), 
     .renp1 (renp1), 
     .odoutp1 (odoutp1), 
     .arp2 (arp2), 
     .renp2 (renp2), 
     .odoutp2 (odoutp2), 
     .arp3 (arp3), 
     .renp3 (renp3), 
     .odoutp3 (odoutp3), 
     .arp4 (arp4), 
     .renp4 (renp4), 
     .odoutp4 (odoutp4), 
     .arp5 (arp5), 
     .renp5 (renp5), 
     .odoutp5 (odoutp5), 
     .arp6 (arp6), 
     .renp6 (renp6), 
     .odoutp6 (odoutp6), 
     .arp7 (arp7), 
     .renp7 (renp7), 
     .odoutp7 (odoutp7), 
     .arp8 ( ),
     .renp8 ( ),
     .odoutp8 ( ),
     .arp9 ( ),
     .renp9 ( ),
     .odoutp9 ( ),
     .arp10 ( ),
     .renp10 ( ),
     .odoutp10 ( ),
     .arp11 ( ),
     .renp11 ( ),
     .odoutp11 ( ),
     .awp0 (awp0), 
     .idinp0 (idinp0), 
     .wenp0 (wenp0), 
     .awp1 (awp1), 
     .idinp1 (idinp1), 
     .wenp1 (wenp1), 
     .awp2 (awp2), 
     .idinp2 (idinp2), 
     .wenp2 (wenp2), 
     .awp3 (awp3), 
     .idinp3 (idinp3), 
     .wenp3 (wenp3), 
     .awp4 (awp4), 
     .idinp4 (idinp4), 
     .wenp4 (wenp4), 
     .awp5 (awp5), 
     .idinp5 (idinp5), 
     .wenp5 (wenp5),
     .awp6 ( ),
     .idinp6 ( ),
     .wenp6 ( ) ,
     .awp7 ( ),
     .idinp7 ( ),
     .wenp7 ( )
   );


endmodule

`endif

///------------------------------------------------------------------------------------------------------------------------
/// Intel Proprietary        Intel Confidential        Intel Proprietary        Intel Confidential        Intel Proprietary
///------------------------------------------------------------------------------------------------------------------------
/// Copyright (c) 2013-2014 Intel Corporation.
/// The following information is a confidential and proprietary property of Intel Corporation.
/// The possession or use of the following information requires a written license from Intel Corporation.
///------------------------------------------------------------------------------------------------------------------------








