// i2c_master_tb.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module i2c_master_tb (
	);

	wire  [31:0] i2c_master_inst_avalon_master_readdata;                  // i2c_master_inst_avalon_master_bfm:avs_readdata -> i2c_master_inst:readdata
	wire         i2c_master_inst_avalon_master_waitrequest;               // i2c_master_inst_avalon_master_bfm:avs_waitrequest -> i2c_master_inst:waitrequest
	wire  [31:0] i2c_master_inst_avalon_master_address;                   // i2c_master_inst:address -> i2c_master_inst_avalon_master_bfm:avs_address
	wire         i2c_master_inst_avalon_master_read;                      // i2c_master_inst:read -> i2c_master_inst_avalon_master_bfm:avs_read
	wire   [3:0] i2c_master_inst_avalon_master_byteenable;                // i2c_master_inst:byteenable -> i2c_master_inst_avalon_master_bfm:avs_byteenable
	wire         i2c_master_inst_avalon_master_readdatavalid;             // i2c_master_inst_avalon_master_bfm:avs_readdatavalid -> i2c_master_inst:readdatavalid
	wire         i2c_master_inst_avalon_master_write;                     // i2c_master_inst:write -> i2c_master_inst_avalon_master_bfm:avs_write
	wire  [31:0] i2c_master_inst_avalon_master_writedata;                 // i2c_master_inst:writedata -> i2c_master_inst_avalon_master_bfm:avs_writedata
	wire         i2c_master_inst_clock_bfm_clk_clk;                       // i2c_master_inst_clock_bfm:clk -> [i2c_master_inst:clk, i2c_master_inst_avalon_master_bfm:clk, i2c_master_inst_reset_bfm:clk]
	wire         i2c_master_inst_conduit_end_conduit_data_oe;             // i2c_master_inst:i2c_data_oe -> i2c_master_inst_conduit_end_bfm:sig_conduit_data_oe
	wire         i2c_master_inst_conduit_end_conduit_clk_oe;              // i2c_master_inst:i2c_clk_oe -> i2c_master_inst_conduit_end_bfm:sig_conduit_clk_oe
	wire   [0:0] i2c_master_inst_conduit_end_bfm_conduit_conduit_data_in; // i2c_master_inst_conduit_end_bfm:sig_conduit_data_in -> i2c_master_inst:i2c_data_in
	wire   [0:0] i2c_master_inst_conduit_end_bfm_conduit_conduit_clk_in;  // i2c_master_inst_conduit_end_bfm:sig_conduit_clk_in -> i2c_master_inst:i2c_clk_in
	wire         i2c_master_inst_reset_bfm_reset_reset;                   // i2c_master_inst_reset_bfm:reset -> [i2c_master_inst:rst_n, i2c_master_inst_avalon_master_bfm:reset]

	i2c_master i2c_master_inst (
		.clk           (i2c_master_inst_clock_bfm_clk_clk),                       //   input,   width = 1,         clock.clk
		.address       (i2c_master_inst_avalon_master_address),                   //  output,  width = 32, avalon_master.address
		.read          (i2c_master_inst_avalon_master_read),                      //  output,   width = 1,              .read
		.readdata      (i2c_master_inst_avalon_master_readdata),                  //   input,  width = 32,              .readdata
		.readdatavalid (i2c_master_inst_avalon_master_readdatavalid),             //   input,   width = 1,              .readdatavalid
		.waitrequest   (i2c_master_inst_avalon_master_waitrequest),               //   input,   width = 1,              .waitrequest
		.write         (i2c_master_inst_avalon_master_write),                     //  output,   width = 1,              .write
		.byteenable    (i2c_master_inst_avalon_master_byteenable),                //  output,   width = 4,              .byteenable
		.writedata     (i2c_master_inst_avalon_master_writedata),                 //  output,  width = 32,              .writedata
		.rst_n         (i2c_master_inst_reset_bfm_reset_reset),                   //   input,   width = 1,         reset.reset_n
		.i2c_data_in   (i2c_master_inst_conduit_end_bfm_conduit_conduit_data_in), //   input,   width = 1,   conduit_end.conduit_data_in
		.i2c_clk_in    (i2c_master_inst_conduit_end_bfm_conduit_conduit_clk_in),  //   input,   width = 1,              .conduit_clk_in
		.i2c_data_oe   (i2c_master_inst_conduit_end_conduit_data_oe),             //  output,   width = 1,              .conduit_data_oe
		.i2c_clk_oe    (i2c_master_inst_conduit_end_conduit_clk_oe)               //  output,   width = 1,              .conduit_clk_oe
	);

	i2c_master_inst_avalon_master_bfm_ip i2c_master_inst_avalon_master_bfm (
		.clk               (i2c_master_inst_clock_bfm_clk_clk),           //   input,   width = 1,       clk.clk
		.reset             (~i2c_master_inst_reset_bfm_reset_reset),      //   input,   width = 1, clk_reset.reset
		.avs_writedata     (i2c_master_inst_avalon_master_writedata),     //   input,  width = 32,        s0.writedata
		.avs_readdata      (i2c_master_inst_avalon_master_readdata),      //  output,  width = 32,          .readdata
		.avs_address       (i2c_master_inst_avalon_master_address),       //   input,  width = 32,          .address
		.avs_waitrequest   (i2c_master_inst_avalon_master_waitrequest),   //  output,   width = 1,          .waitrequest
		.avs_write         (i2c_master_inst_avalon_master_write),         //   input,   width = 1,          .write
		.avs_read          (i2c_master_inst_avalon_master_read),          //   input,   width = 1,          .read
		.avs_byteenable    (i2c_master_inst_avalon_master_byteenable),    //   input,   width = 4,          .byteenable
		.avs_readdatavalid (i2c_master_inst_avalon_master_readdatavalid)  //  output,   width = 1,          .readdatavalid
	);

	i2c_master_inst_clock_bfm_ip i2c_master_inst_clock_bfm (
		.clk (i2c_master_inst_clock_bfm_clk_clk)  //  output,  width = 1, clk.clk
	);

	i2c_master_inst_conduit_end_bfm_ip i2c_master_inst_conduit_end_bfm (
		.sig_conduit_data_in (i2c_master_inst_conduit_end_bfm_conduit_conduit_data_in), //  output,  width = 1, conduit.conduit_data_in
		.sig_conduit_clk_in  (i2c_master_inst_conduit_end_bfm_conduit_conduit_clk_in),  //  output,  width = 1,        .conduit_clk_in
		.sig_conduit_data_oe (i2c_master_inst_conduit_end_conduit_data_oe),             //   input,  width = 1,        .conduit_data_oe
		.sig_conduit_clk_oe  (i2c_master_inst_conduit_end_conduit_clk_oe)               //   input,  width = 1,        .conduit_clk_oe
	);

	i2c_master_inst_reset_bfm_ip i2c_master_inst_reset_bfm (
		.reset (i2c_master_inst_reset_bfm_reset_reset), //  output,  width = 1, reset.reset_n
		.clk   (i2c_master_inst_clock_bfm_clk_clk)      //   input,  width = 1,   clk.clk
	);

endmodule
