// i2c_ip_inst_reset_bfm_ip.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module i2c_ip_inst_reset_bfm_ip #(
		parameter ASSERT_HIGH_RESET    = 0,
		parameter INITIAL_RESET_CYCLES = 50
	) (
		output wire  reset, // reset.reset_n
		input  wire  clk    //   clk.clk
	);

	altera_avalon_reset_source #(
		.ASSERT_HIGH_RESET    (ASSERT_HIGH_RESET),
		.INITIAL_RESET_CYCLES (INITIAL_RESET_CYCLES)
	) i2c_ip_inst_reset_bfm (
		.reset (reset), //  output,  width = 1, reset.reset_n
		.clk   (clk)    //   input,  width = 1,   clk.clk
	);

endmodule
