// megafunction wizard: %ALTDDIO_IN%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTDDIO_IN 

// ============================================================
// File Name: my_ddio_in.v
// Megafunction Name(s):
//          ALTDDIO_IN
//
// Simulation Library Files(s):
//          altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 10.0 Build 262 08/18/2010 SP 1 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2010 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module IDDR #(
      parameter DDR_CLK_EDGE = "OPPOSITE_EDGE", // "OPPOSITE_EDGE", "SAME_EDGE"
                                                // or "SAME_EDGE_PIPELINED"
      parameter INIT_Q1 = 1'b0,                 // Initial value of Q1: 1'b0 or 1'b1
      parameter INIT_Q2 = 1'b0,                 // Initial value of Q2: 1'b0 or 1'b1
      parameter SRTYPE = "SYNC",                // Set/Reset type: "SYNC" or "ASYNC"
      parameter FPGA_FAMILY = "S5"              // S5: Stratix5 S10: Stratix10
) (
    Q1,                             // Q1),        // 1-bit output for positive edge of clock
    Q2,                             // Q2),        // 1-bit output for negative edge of clock
    C,                             // clk),        // 1-bit clock input
    CE,                             // 1'b1),      // 1-bit clock enable input
    D,                             // data_in), // 1-bit DDR data input
    R,                             // rst),     // 1-bit reset
    S                              // 1'b0)        // 1-bit set
);
    output Q1;
    output Q2;
    input  C;
    input  CE;
    inout  D;
    input  R;
    input  S;

    generate
    begin
      if(FPGA_FAMILY == "S10")
      begin : s10
        fourteennm_ddio_in demux (
            .clk(~C),
            .areset(1'b0),
            .sreset(1'b0),
            .ena(1'b1),
            .datain(D),
            .regouthi(Q1),
            .regoutlo(Q2));
          defparam demux.power_up = "low";
          defparam demux.async_mode = "none";
          defparam demux.sync_mode = "none";
          defparam demux.use_clkn = "false";
      end
      else
      begin : s5
       altddio_in ALTDDIO_IN_component (
          .aclr (R),
          .datain (D),
          .inclock (C),
          .dataout_h (Q1),
          .dataout_l (Q2),
          .aset (1'b0),
          .inclocken (1'b1),
          .sclr (1'b0),
          .sset (1'b0));
        defparam
                ALTDDIO_IN_component.intended_device_family = "Stratix IV",
                ALTDDIO_IN_component.invert_input_clocks = "OFF",
                ALTDDIO_IN_component.lpm_hint = "UNUSED",
                ALTDDIO_IN_component.lpm_type = "altddio_in",
                ALTDDIO_IN_component.power_up_high = "OFF",
                ALTDDIO_IN_component.width = 1;
      end
   end 
   endgenerate


endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix IV"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Stratix IV"
// Retrieval info: CONSTANT: INVERT_INPUT_CLOCKS STRING "OFF"
// Retrieval info: CONSTANT: LPM_HINT STRING "UNUSED"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altddio_in"
// Retrieval info: CONSTANT: POWER_UP_HIGH STRING "OFF"
// Retrieval info: CONSTANT: WIDTH NUMERIC "8"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT NODEFVAL "aclr"
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: USED_PORT: datain 0 0 8 0 INPUT NODEFVAL "datain[7..0]"
// Retrieval info: CONNECT: @datain 0 0 8 0 datain 0 0 8 0
// Retrieval info: USED_PORT: dataout_h 0 0 8 0 OUTPUT NODEFVAL "dataout_h[7..0]"
// Retrieval info: CONNECT: dataout_h 0 0 8 0 @dataout_h 0 0 8 0
// Retrieval info: USED_PORT: dataout_l 0 0 8 0 OUTPUT NODEFVAL "dataout_l[7..0]"
// Retrieval info: CONNECT: dataout_l 0 0 8 0 @dataout_l 0 0 8 0
// Retrieval info: USED_PORT: inclock 0 0 0 0 INPUT_CLK_EXT NODEFVAL "inclock"
// Retrieval info: CONNECT: @inclock 0 0 0 0 inclock 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_in.v TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_in.qip TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_in.bsf TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_in_inst.v TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_in_bb.v FALSE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_in.inc FALSE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_in.cmp FALSE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_in.ppf TRUE FALSE
// Retrieval info: LIB_FILE: altera_mf
