module IW_cms_add_drop_pld_add #(
	parameter MESH_AD_PTR_SIZE = 5,
	parameter AD_ADD_ADR_SIZE = 46, 
	parameter MESH_STOP_ID_SIZE = 6,
	parameter MESH_TGR_ID_SIZE = 4,
	parameter AD_ADD_HDR_SIZE = 61,
	parameter AK_ADD_HDR_SIZE = 28,
	parameter AKC_ADD_HDR_SIZE = 8,
	parameter BL_ADD_ADR_SIZE = 23,
	parameter BL_ADD_HDR_SIZE = 48,
	parameter ADD_P2P_VNA_CR = 6,
	parameter MESH_AK_PTR_SIZE = 5,
	parameter MESH_BL_PTR_SIZE = 5,
	parameter NUM_DEMUX_SIGNALS = (MESH_AD_PTR_SIZE + AD_ADD_ADR_SIZE + MESH_STOP_ID_SIZE + 
	                             MESH_TGR_ID_SIZE + AD_ADD_HDR_SIZE + MESH_STOP_ID_SIZE + 
				     MESH_TGR_ID_SIZE + AK_ADD_HDR_SIZE + MESH_STOP_ID_SIZE + 
				     MESH_TGR_ID_SIZE + AKC_ADD_HDR_SIZE + BL_ADD_ADR_SIZE + 
				     MESH_STOP_ID_SIZE + MESH_TGR_ID_SIZE + BL_ADD_HDR_SIZE + 
				     ADD_P2P_VNA_CR + 50),

	parameter NUM_MUX_SIGNALS = 2*(MESH_AD_PTR_SIZE + MESH_AK_PTR_SIZE + MESH_BL_PTR_SIZE) + 8


)(

    // Ports for Interface agt0_cms_pld_add
    output                            pld_add_ADEgrEntEnUnnnH,
    output   [MESH_AD_PTR_SIZE-1:0]   pld_add_ADEgrEntIDUnnnH,
    output                            pld_add_ADEgrWrDisUnnnH,
    output                            pld_add_AgtToFabricCredReset_b,
    output                            pld_add_AgtToFabricInst1CredReset_b,
    output   [AD_ADD_ADR_SIZE-1:0]    pld_add_ad_addr,
    output                            pld_add_ad_dest_coloc,
    output                            pld_add_ad_dest_diradd,
    output                            pld_add_ad_dest_dst_bounce,
    output   [MESH_STOP_ID_SIZE-1:0]  pld_add_ad_dest_dst_id,
    output                            pld_add_ad_dest_dst_type,
    output                            pld_add_ad_dest_for_me,
    output                            pld_add_ad_dest_poladd,
    output                            pld_add_ad_dest_remote_dir,
    output                            pld_add_ad_dest_remote_pol,
    output                            pld_add_ad_dest_src_inst,
    output                            pld_add_ad_dest_src_type,
    output                            pld_add_ad_dest_tgr_bounce,
    output   [MESH_TGR_ID_SIZE-1:0]   pld_add_ad_dest_tgr_id,
    output                            pld_add_ad_dest_valid,
    output   [AD_ADD_HDR_SIZE-1:0]    pld_add_ad_hdr,
    output                            pld_add_ak_dest_coloc,
    output                            pld_add_ak_dest_diradd,
    output                            pld_add_ak_dest_dst_bounce,
    output   [MESH_STOP_ID_SIZE-1:0]  pld_add_ak_dest_dst_id,
    output                            pld_add_ak_dest_dst_type,
    output                            pld_add_ak_dest_for_me,
    output                            pld_add_ak_dest_poladd,
    output                            pld_add_ak_dest_remote_dir,
    output                            pld_add_ak_dest_remote_pol,
    output                            pld_add_ak_dest_src_inst,
    output                            pld_add_ak_dest_src_type,
    output   [MESH_TGR_ID_SIZE-1:0]     pld_add_ak_dest_tgr_id,
    output                            pld_add_ak_dest_valid,
    output   [AK_ADD_HDR_SIZE-1:0]    pld_add_ak_hdr,
    output                            pld_add_akc_dest_coloc,
    output                            pld_add_akc_dest_diradd,
    output   [MESH_STOP_ID_SIZE-1:0]  pld_add_akc_dest_dst_id,
    output                            pld_add_akc_dest_dst_type,
    output                            pld_add_akc_dest_for_me,
    output                            pld_add_akc_dest_poladd,
    output                            pld_add_akc_dest_remote_dir,
    output                            pld_add_akc_dest_remote_pol,
    output                            pld_add_akc_dest_src_type,
    output   [MESH_TGR_ID_SIZE-1:0]   pld_add_akc_dest_tgr_id,
    output                            pld_add_akc_dest_valid,
    output   [AKC_ADD_HDR_SIZE-1:0]   pld_add_akc_hdr,
    output   [BL_ADD_ADR_SIZE-1:0]    pld_add_bl_addr,
    output                            pld_add_bl_dest_coloc,
    output                            pld_add_bl_dest_diradd,
    output   [MESH_STOP_ID_SIZE-1:0]  pld_add_bl_dest_dst_id,
    output                            pld_add_bl_dest_dst_type,
    output                            pld_add_bl_dest_for_me,
    output                            pld_add_bl_dest_half,
    output                            pld_add_bl_dest_poladd,
    output                            pld_add_bl_dest_remote_dir,
    output                            pld_add_bl_dest_remote_pol,
    output                            pld_add_bl_dest_src_inst,
    output                            pld_add_bl_dest_src_type,
    output                            pld_add_bl_dest_tgr_bounce,
    output   [MESH_TGR_ID_SIZE-1:0]   pld_add_bl_dest_tgr_id,
    output                            pld_add_bl_dest_valid,
    output   [BL_ADD_HDR_SIZE-1:0]    pld_add_bl_hdr,
    output                            pld_add_local_fatal,
    output                            pld_add_local_viral,
    output   [ADD_P2P_VNA_CR-1:0]     pld_add_p2p_vna_cr_add,
    input                             pld_add_ADCrdRtnInst1UnnnH,
    input                             pld_add_ADCrdRtnUnnnH,
    input                             pld_add_ADEgrCredRetUnnnH,
    input  [MESH_AD_PTR_SIZE-1:0]     pld_add_ADEgrRdPtrUnnnH,
    input  [MESH_AD_PTR_SIZE-1:0]     pld_add_ADEgrWrPtrUnnnH,
    input                             pld_add_AKCCrdRtnUnnnH,
    input                             pld_add_AKCrdRtnInst1UnnnH,
    input                             pld_add_AKCrdRtnUnnnH,
    input  [MESH_AK_PTR_SIZE-1:0]     pld_add_AKEgrRdPtrUnnnH,
    input  [MESH_AK_PTR_SIZE-1:0]     pld_add_AKEgrWrPtrUnnnH,
    input                             pld_add_BLCrdRtnInst1UnnnH,
    input                             pld_add_BLCrdRtnUnnnH,
    input  [MESH_BL_PTR_SIZE-1:0]     pld_add_BLEgrRdPtrUnnnH,
    input  [MESH_BL_PTR_SIZE-1:0]     pld_add_BLEgrWrPtrUnnnH,

    input  [NUM_DEMUX_SIGNALS-1:0]       demux_data,
    output [NUM_MUX_SIGNALS-1:0]         mux_data
);
assign {
        pld_add_ADEgrEntEnUnnnH,
        pld_add_ADEgrEntIDUnnnH,
        pld_add_ADEgrWrDisUnnnH,
        pld_add_AgtToFabricCredReset_b,
        pld_add_AgtToFabricInst1CredReset_b,
        pld_add_ad_addr,
        pld_add_ad_dest_coloc,
        pld_add_ad_dest_diradd,
        pld_add_ad_dest_dst_bounce,
        pld_add_ad_dest_dst_id,
        pld_add_ad_dest_dst_type,
        pld_add_ad_dest_for_me,
        pld_add_ad_dest_poladd,
        pld_add_ad_dest_remote_dir,
        pld_add_ad_dest_remote_pol,
        pld_add_ad_dest_src_inst,
        pld_add_ad_dest_src_type,
        pld_add_ad_dest_tgr_bounce,
        pld_add_ad_dest_tgr_id,
        pld_add_ad_dest_valid,
        pld_add_ad_hdr,
        pld_add_ak_dest_coloc,
        pld_add_ak_dest_diradd,
        pld_add_ak_dest_dst_bounce,
        pld_add_ak_dest_dst_id,
        pld_add_ak_dest_dst_type,
        pld_add_ak_dest_for_me,
        pld_add_ak_dest_poladd,
        pld_add_ak_dest_remote_dir,
        pld_add_ak_dest_remote_pol,
        pld_add_ak_dest_src_inst,
        pld_add_ak_dest_src_type,
        pld_add_ak_dest_tgr_id,
        pld_add_ak_dest_valid,
        pld_add_ak_hdr,
        pld_add_akc_dest_coloc,
        pld_add_akc_dest_diradd,
        pld_add_akc_dest_dst_id,
        pld_add_akc_dest_dst_type,
        pld_add_akc_dest_for_me,
        pld_add_akc_dest_poladd,
        pld_add_akc_dest_remote_dir,
        pld_add_akc_dest_remote_pol,
        pld_add_akc_dest_src_type,
        pld_add_akc_dest_tgr_id,
        pld_add_akc_dest_valid,
        pld_add_akc_hdr,
        pld_add_bl_addr,
        pld_add_bl_dest_coloc,
        pld_add_bl_dest_diradd,
        pld_add_bl_dest_dst_id,
        pld_add_bl_dest_dst_type,
        pld_add_bl_dest_for_me,
        pld_add_bl_dest_half,
        pld_add_bl_dest_poladd,
        pld_add_bl_dest_remote_dir,
        pld_add_bl_dest_remote_pol,
        pld_add_bl_dest_src_inst,
        pld_add_bl_dest_src_type,
        pld_add_bl_dest_tgr_bounce,
        pld_add_bl_dest_tgr_id,
        pld_add_bl_dest_valid,
        pld_add_bl_hdr,
        pld_add_local_fatal,
        pld_add_local_viral,
        pld_add_p2p_vna_cr_add
      } = demux_data;

assign mux_data = {
                     pld_add_ADCrdRtnInst1UnnnH,
                     pld_add_ADCrdRtnUnnnH,
                     pld_add_ADEgrCredRetUnnnH,
                     pld_add_ADEgrRdPtrUnnnH,
                     pld_add_ADEgrWrPtrUnnnH,
                     pld_add_AKCCrdRtnUnnnH,
                     pld_add_AKCrdRtnInst1UnnnH,
                     pld_add_AKCrdRtnUnnnH,
                     pld_add_AKEgrRdPtrUnnnH,
                     pld_add_AKEgrWrPtrUnnnH,
                     pld_add_BLCrdRtnInst1UnnnH,
                     pld_add_BLCrdRtnUnnnH,
                     pld_add_BLEgrRdPtrUnnnH,
                     pld_add_BLEgrWrPtrUnnnH
                  };

endmodule
