// megafunction wizard: %ALTDDIO_OUT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTDDIO_OUT 

// ============================================================
// File Name: my_ddio_out.v
// Megafunction Name(s):
//          ALTDDIO_OUT
//
// Simulation Library Files(s):
//          altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 10.0 Build 262 08/18/2010 SP 1 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2010 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module ODDR #(
parameter DDR_CLK_EDGE = "OPPOSITE_EDGE", // "OPPOSITE_EDGE" or "SAME_EDGE"
parameter INIT = 1'b0,                    // Initial value of Q: 1'b0 or 1'b1
parameter SRTYPE = "SYNC",                  // Set/Reset type: "SYNC" or "ASYNC"
parameter FPGA_FAMILY = "S5"                // S5: Stratix5 S10: Stratix10
) (
 Q,                             // data_out),   // 1-bit DDR output
 C,                             // clk),        // 1-bit clock input
 CE,                             // 1'b1),      // 1-bit clock enable input
 D1,                             // D1),        // 1-bit data input (positive edge)
 D2,                             // D2),        // 1-bit data input (negative edge)
 R,                             // rst),        // 1-bit reset
 S                              // 1-bit set
);

 inout  Q;
 input  C;
 input  CE;
 input  D1;
 input  D2;
 input  R;
 input  S;

    generate
    begin
      if(FPGA_FAMILY == "S10")
      begin : s10
          fourteennm_ddio_out mux 
        (
           .clk(C),
           .clkhi(1'b0),
           .clklo(1'b0),
           .muxsel(1'b0),
           .areset(1'b0),
           .sreset(1'b0),
           .ena(1'b1),
           .datainhi(D2),
           .datainlo(D1),
           .dataout(Q)
          );
          defparam mux.power_up = "low";
          defparam mux.async_mode = "none";
          defparam mux.sync_mode = "none";
          defparam mux.half_rate_mode = "false";
      end
      else
      begin : s5
          altddio_out     ALTDDIO_OUT_component 
          (
            .aclr (R),
            .datain_h (D1),
            .datain_l (D2),
            .outclock (C),
            .dataout (Q),
            .aset (1'b0),
            .oe (1'b1),
            .oe_out (),
            .outclocken (CE),
            .sclr (1'b0),
            .sset (S)
          );
          defparam
            ALTDDIO_OUT_component.extend_oe_disable = "OFF",
            ALTDDIO_OUT_component.intended_device_family = "Stratix IV",
            ALTDDIO_OUT_component.invert_output = "OFF",
            ALTDDIO_OUT_component.lpm_hint = "UNUSED",
            ALTDDIO_OUT_component.lpm_type = "altddio_out",
            ALTDDIO_OUT_component.oe_reg = "UNREGISTERED",
            ALTDDIO_OUT_component.power_up_high = "OFF",
            ALTDDIO_OUT_component.width = 1;
      end
    end 
    endgenerate

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix IV"
// Retrieval info: CONSTANT: EXTEND_OE_DISABLE STRING "OFF"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Stratix IV"
// Retrieval info: CONSTANT: INVERT_OUTPUT STRING "OFF"
// Retrieval info: CONSTANT: LPM_HINT STRING "UNUSED"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altddio_out"
// Retrieval info: CONSTANT: OE_REG STRING "UNREGISTERED"
// Retrieval info: CONSTANT: POWER_UP_HIGH STRING "OFF"
// Retrieval info: CONSTANT: WIDTH NUMERIC "8"
// Retrieval info: USED_PORT: aclr 0 0 0 0 INPUT NODEFVAL "aclr"
// Retrieval info: CONNECT: @aclr 0 0 0 0 aclr 0 0 0 0
// Retrieval info: USED_PORT: datain_h 0 0 8 0 INPUT NODEFVAL "datain_h[7..0]"
// Retrieval info: CONNECT: @datain_h 0 0 8 0 datain_h 0 0 8 0
// Retrieval info: USED_PORT: datain_l 0 0 8 0 INPUT NODEFVAL "datain_l[7..0]"
// Retrieval info: CONNECT: @datain_l 0 0 8 0 datain_l 0 0 8 0
// Retrieval info: USED_PORT: dataout 0 0 8 0 OUTPUT NODEFVAL "dataout[7..0]"
// Retrieval info: CONNECT: dataout 0 0 8 0 @dataout 0 0 8 0
// Retrieval info: USED_PORT: outclock 0 0 0 0 INPUT_CLK_EXT NODEFVAL "outclock"
// Retrieval info: CONNECT: @outclock 0 0 0 0 outclock 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_out.v TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_out.qip TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_out.bsf TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_out_inst.v TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_out_bb.v TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_out.inc TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_out.cmp TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL my_ddio_out.ppf TRUE FALSE
// Retrieval info: LIB_FILE: altera_mf
