//PHYSS0 STUB
//Generated from rtl/physs0.sv
//This is a stub module with all outputs tied to 0

module physs0
// EDIT_PORT BEGIN
 ( 
input [31:0] SSN_START_entry_from_nac_bus_data_in,
input SSN_START_entry_from_nac_bus_clock_in,
input [31:0] SSN_START_from_parmisc_physs1_bus_data_in,
output [31:0] SSN_END_entry_from_nac_bus_data_out,
output [31:0] SSN_END_exit_to_nac_bus_data_out,
output [31:0] SSN_END_towards_parmisc_physs1_bus_data_out,
inout [3:0] ioa_ck_pma3_ref_right_mquad0_physs0, //abutment signal on pam3
inout [3:0] ioa_ck_pma0_ref_left_mquad0_physs0, //abutment signal on pam0
inout [3:0] ioa_ck_pma0_ref_left_mquad1_physs0, //abutment signal on pam0
inout [3:0] ioa_ck_pma3_ref_right_mquad1_physs0, //abutment signal on pam3
output mbp_repeater_odi_parmisc_physs0_5_ubp_out,
output mbp_repeater_sfe_parmisc_physs0_2_ubp_out,
input [7:0] dfxagg_security_policy,
input dfxagg_policy_update,
input dfxagg_early_boot_debug_exit,
input [7:0] dfxagg_debug_capabilities_enabling,
input dfxagg_debug_capabilities_enabling_valid,
input fdfx_powergood,
input ETH_RXN0,
input ETH_RXP0,
input ETH_RXN1,
input ETH_RXP1,
input ETH_RXN2,
input ETH_RXP2,
input ETH_RXN3,
input ETH_RXP3,
output versa_xmp_0_xoa_pma0_tx_n_l0,
output versa_xmp_0_xoa_pma0_tx_p_l0,
output versa_xmp_0_xoa_pma1_tx_n_l0,
output versa_xmp_0_xoa_pma1_tx_p_l0,
output versa_xmp_0_xoa_pma2_tx_n_l0,
output versa_xmp_0_xoa_pma2_tx_p_l0,
output versa_xmp_0_xoa_pma3_tx_n_l0,
output versa_xmp_0_xoa_pma3_tx_p_l0,
input ETH_RXN4,
input ETH_RXP4,
input ETH_RXN5,
input ETH_RXP5,
input ETH_RXN6,
input ETH_RXP6,
input ETH_RXN7,
input ETH_RXP7,
output versa_xmp_1_xoa_pma0_tx_n_l0,
output versa_xmp_1_xoa_pma0_tx_p_l0,
output versa_xmp_1_xoa_pma1_tx_n_l0,
output versa_xmp_1_xoa_pma1_tx_p_l0,
output versa_xmp_1_xoa_pma2_tx_n_l0,
output versa_xmp_1_xoa_pma2_tx_p_l0,
output versa_xmp_1_xoa_pma3_tx_n_l0,
output versa_xmp_1_xoa_pma3_tx_p_l0,
inout wire ioa_pma_remote_diode_i_anode,
inout wire ioa_pma_remote_diode_i_anode_0,
inout wire ioa_pma_remote_diode_i_anode_1,
inout wire ioa_pma_remote_diode_i_anode_2,
inout wire ioa_pma_remote_diode_i_anode_3,
inout wire ioa_pma_remote_diode_i_anode_4,
inout wire ioa_pma_remote_diode_i_anode_5,
inout wire ioa_pma_remote_diode_i_anode_6,
inout wire ioa_pma_remote_diode_v_anode,
inout wire ioa_pma_remote_diode_v_anode_0,
inout wire ioa_pma_remote_diode_v_anode_1,
inout wire ioa_pma_remote_diode_v_anode_2,
inout wire ioa_pma_remote_diode_v_anode_3,
inout wire ioa_pma_remote_diode_v_anode_4,
inout wire ioa_pma_remote_diode_v_anode_5,
inout wire ioa_pma_remote_diode_v_anode_6,
inout wire ioa_pma_remote_diode_i_cathode,
inout wire ioa_pma_remote_diode_i_cathode_0,
inout wire ioa_pma_remote_diode_i_cathode_1,
inout wire ioa_pma_remote_diode_i_cathode_2,
inout wire ioa_pma_remote_diode_i_cathode_3,
inout wire ioa_pma_remote_diode_i_cathode_4,
inout wire ioa_pma_remote_diode_i_cathode_5,
inout wire ioa_pma_remote_diode_i_cathode_6,
inout wire ioa_pma_remote_diode_v_cathode,
inout wire ioa_pma_remote_diode_v_cathode_0,
inout wire ioa_pma_remote_diode_v_cathode_1,
inout wire ioa_pma_remote_diode_v_cathode_2,
inout wire ioa_pma_remote_diode_v_cathode_3,
inout wire ioa_pma_remote_diode_v_cathode_4,
inout wire ioa_pma_remote_diode_v_cathode_5,
inout wire ioa_pma_remote_diode_v_cathode_6,
input [3:0] quadpcs100_2_pcs_link_status,
input [3:0] quadpcs100_3_pcs_link_status,
input physs_reset_prep_req,
output physs_reset_prep_ack_double_sync_physs_scon_reset_prep_ack_sync,
input [5:0] physs_hd2prf_trim_fuse_in,
input [6:0] physs_hs2prf_trim_fuse_in,
input [7:0] physs_rfhs_trim_fuse_in,
input [15:0] physs_hdspsr_trim_fuse_in,
input physs_bbl_800G_0_disable,
input physs_bbl_400G_0_disable,
input physs_bbl_200G_0_disable,
input physs_bbl_100G_0_disable,
input physs_bbl_400G_1_disable,
input physs_bbl_200G_1_disable,
input physs_bbl_100G_1_disable,
input [3:0] physs_bbl_serdes_0_disable,
input [3:0] physs_bbl_serdes_1_disable,
input physs_bbl_spare_0,
input physs_bbl_spare_1,
input [3:0] ack_from_fabric_0,
input [3:0] req_from_fabric_0,
output [3:0] dfd_rtb_trig_ctf_adapter_0_trig_req_to_fabric,
output [3:0] dfd_rtb_trig_ctf_adapter_0_ack_to_fabric,
input [3:0] ack_from_fabric_1,
input [3:0] req_from_fabric_1,
output [3:0] dfd_rtb_trig_ctf_adapter_1_trig_req_to_fabric,
output [3:0] dfd_rtb_trig_ctf_adapter_1_ack_to_fabric,
input physs_bbl_100G_2_disable,
input physs_bbl_100G_3_disable,
input ethphyss_post_clkungate,
output logic physs_intf0_clk_adop_parmisc_physs0_clkout_0,
output logic soc_per_clk_adop_parmisc_physs0_clkout_0,
output logic physs_func_clk_adop_parmisc_physs0_clkout,
input wire physs_intf0_clk,
input wire physs_funcx2_clk,
input wire soc_per_clk,
input wire tsu_clk,
input wire o_ck_pma0_rx_postdiv_l0_adop_parpquad0_clkout,
input wire o_ck_pma1_rx_postdiv_l0_adop_parpquad0_clkout,
input wire o_ck_pma2_rx_postdiv_l0_adop_parpquad0_clkout,
input wire o_ck_pma3_rx_postdiv_l0_adop_parpquad0_clkout,
input wire o_ck_pma0_rx_postdiv_l0_adop_parpquad1_clkout,
input wire o_ck_pma1_rx_postdiv_l0_adop_parpquad1_clkout,
input wire o_ck_pma2_rx_postdiv_l0_adop_parpquad1_clkout,
input wire o_ck_pma3_rx_postdiv_l0_adop_parpquad1_clkout,
input fscan_txrxword_byp_clk,
output o_ck_pma0_cmnplla_postdiv_clk_mux_parmquad0_clkout,
input wire fscan_ref_clk,
output logic fscan_ref_clk_adop_parmisc_physs0_clkout_0,
input wire nss_cosq_clk0,
input wire nss_cosq_clk1,
input wire clk_1588_freq,
input wire i_ck_ucss_uart_sclk,
output logic uart_clk_adop_parmisc_physs0_clkout_0,
output fifo_top_mux_0_physs0_icq_port_0_link_stat,
output [3:0] fifo_top_mux_0_physs0_mse_port_0_link_speed,
output fifo_top_mux_0_physs0_mse_port_0_rx_dval,
output [1023:0] fifo_top_mux_0_physs0_mse_port_0_rx_data,
output fifo_top_mux_0_physs0_mse_port_0_rx_sop,
output fifo_top_mux_0_physs0_mse_port_0_rx_eop,
output [6:0] fifo_top_mux_0_physs0_mse_port_0_rx_mod,
output fifo_top_mux_0_physs0_mse_port_0_rx_err,
output fifo_top_mux_0_physs0_mse_port_0_rx_ecc_err,
output [39:0] fifo_top_mux_0_physs0_mse_port_0_rx_ts,
output fifo_top_mux_0_physs0_mse_port_0_tx_rdy,
output fifo_top_mux_0_physs0_mse_port_0_pfc_mode,
input mse_physs_port_0_rx_rdy,
input mse_physs_port_0_tx_wren,
input [1023:0] mse_physs_port_0_tx_data,
input mse_physs_port_0_tx_sop,
input mse_physs_port_0_tx_eop,
input [6:0] mse_physs_port_0_tx_mod,
input mse_physs_port_0_tx_err,
input mse_physs_port_0_tx_crc,
input mse_physs_port_0_ts_capture_vld,
input [6:0] mse_physs_port_0_ts_capture_idx,
output fifo_top_mux_0_physs0_icq_port_1_link_stat,
output [3:0] fifo_top_mux_0_physs0_mse_port_1_link_speed,
output fifo_top_mux_0_physs0_mse_port_1_rx_dval,
output [255:0] fifo_top_mux_0_physs0_mse_port_1_rx_data,
output fifo_top_mux_0_physs0_mse_port_1_rx_sop,
output fifo_top_mux_0_physs0_mse_port_1_rx_eop,
output [4:0] fifo_top_mux_0_physs0_mse_port_1_rx_mod,
output fifo_top_mux_0_physs0_mse_port_1_rx_err,
output fifo_top_mux_0_physs0_mse_port_1_rx_ecc_err,
output [39:0] fifo_top_mux_0_physs0_mse_port_1_rx_ts,
output fifo_top_mux_0_physs0_mse_port_1_tx_rdy,
output fifo_top_mux_0_physs0_mse_port_1_pfc_mode,
input mse_physs_port_1_rx_rdy,
input mse_physs_port_1_tx_wren,
input [255:0] mse_physs_port_1_tx_data,
input mse_physs_port_1_tx_sop,
input mse_physs_port_1_tx_eop,
input [4:0] mse_physs_port_1_tx_mod,
input mse_physs_port_1_tx_err,
input mse_physs_port_1_tx_crc,
input mse_physs_port_1_ts_capture_vld,
input [6:0] mse_physs_port_1_ts_capture_idx,
output fifo_top_mux_0_physs0_icq_port_2_link_stat,
output [3:0] fifo_top_mux_0_physs0_mse_port_2_link_speed,
output fifo_top_mux_0_physs0_mse_port_2_rx_dval,
output [511:0] fifo_top_mux_0_physs0_mse_port_2_rx_data,
output fifo_top_mux_0_physs0_mse_port_2_rx_sop,
output fifo_top_mux_0_physs0_mse_port_2_rx_eop,
output [5:0] fifo_top_mux_0_physs0_mse_port_2_rx_mod,
output fifo_top_mux_0_physs0_mse_port_2_rx_err,
output fifo_top_mux_0_physs0_mse_port_2_rx_ecc_err,
output [39:0] fifo_top_mux_0_physs0_mse_port_2_rx_ts,
output fifo_top_mux_0_physs0_mse_port_2_tx_rdy,
output fifo_top_mux_0_physs0_mse_port_2_pfc_mode,
input mse_physs_port_2_rx_rdy,
input mse_physs_port_2_tx_wren,
input [511:0] mse_physs_port_2_tx_data,
input mse_physs_port_2_tx_sop,
input mse_physs_port_2_tx_eop,
input [5:0] mse_physs_port_2_tx_mod,
input mse_physs_port_2_tx_err,
input mse_physs_port_2_tx_crc,
input mse_physs_port_2_ts_capture_vld,
input [6:0] mse_physs_port_2_ts_capture_idx,
output fifo_top_mux_0_physs0_icq_port_3_link_stat,
output [3:0] fifo_top_mux_0_physs0_mse_port_3_link_speed,
output fifo_top_mux_0_physs0_mse_port_3_rx_dval,
output [255:0] fifo_top_mux_0_physs0_mse_port_3_rx_data,
output fifo_top_mux_0_physs0_mse_port_3_rx_sop,
output fifo_top_mux_0_physs0_mse_port_3_rx_eop,
output [4:0] fifo_top_mux_0_physs0_mse_port_3_rx_mod,
output fifo_top_mux_0_physs0_mse_port_3_rx_err,
output fifo_top_mux_0_physs0_mse_port_3_rx_ecc_err,
output [39:0] fifo_top_mux_0_physs0_mse_port_3_rx_ts,
output fifo_top_mux_0_physs0_mse_port_3_tx_rdy,
output fifo_top_mux_0_physs0_mse_port_3_pfc_mode,
input mse_physs_port_3_rx_rdy,
input mse_physs_port_3_tx_wren,
input [255:0] mse_physs_port_3_tx_data,
input mse_physs_port_3_tx_sop,
input mse_physs_port_3_tx_eop,
input [4:0] mse_physs_port_3_tx_mod,
input mse_physs_port_3_tx_err,
input mse_physs_port_3_tx_crc,
input mse_physs_port_3_ts_capture_vld,
input [6:0] mse_physs_port_3_ts_capture_idx,
output fifo_top_mux_0_physs1_icq_port_4_link_stat,
output [3:0] fifo_top_mux_0_physs1_mse_port_4_link_speed,
output fifo_top_mux_0_physs1_mse_port_4_rx_dval,
output [1023:0] fifo_top_mux_0_physs1_mse_port_4_rx_data,
output fifo_top_mux_0_physs1_mse_port_4_rx_sop,
output fifo_top_mux_0_physs1_mse_port_4_rx_eop,
output [6:0] fifo_top_mux_0_physs1_mse_port_4_rx_mod,
output fifo_top_mux_0_physs1_mse_port_4_rx_err,
output fifo_top_mux_0_physs1_mse_port_4_rx_ecc_err,
output [39:0] fifo_top_mux_0_physs1_mse_port_4_rx_ts,
output fifo_top_mux_0_physs1_mse_port_4_tx_rdy,
output fifo_top_mux_0_physs1_mse_port_4_pfc_mode,
input mse_physs_port_4_rx_rdy,
input mse_physs_port_4_tx_wren,
input [1023:0] mse_physs_port_4_tx_data,
input mse_physs_port_4_tx_sop,
input mse_physs_port_4_tx_eop,
input [6:0] mse_physs_port_4_tx_mod,
input mse_physs_port_4_tx_err,
input mse_physs_port_4_tx_crc,
input mse_physs_port_4_ts_capture_vld,
input [6:0] mse_physs_port_4_ts_capture_idx,
output fifo_top_mux_0_physs1_icq_port_5_link_stat,
output [3:0] fifo_top_mux_0_physs1_mse_port_5_link_speed,
output fifo_top_mux_0_physs1_mse_port_5_rx_dval,
output [255:0] fifo_top_mux_0_physs1_mse_port_5_rx_data,
output fifo_top_mux_0_physs1_mse_port_5_rx_sop,
output fifo_top_mux_0_physs1_mse_port_5_rx_eop,
output [4:0] fifo_top_mux_0_physs1_mse_port_5_rx_mod,
output fifo_top_mux_0_physs1_mse_port_5_rx_err,
output fifo_top_mux_0_physs1_mse_port_5_rx_ecc_err,
output [39:0] fifo_top_mux_0_physs1_mse_port_5_rx_ts,
output fifo_top_mux_0_physs1_mse_port_5_tx_rdy,
output fifo_top_mux_0_physs1_mse_port_5_pfc_mode,
input mse_physs_port_5_rx_rdy,
input mse_physs_port_5_tx_wren,
input [255:0] mse_physs_port_5_tx_data,
input mse_physs_port_5_tx_sop,
input mse_physs_port_5_tx_eop,
input [4:0] mse_physs_port_5_tx_mod,
input mse_physs_port_5_tx_err,
input mse_physs_port_5_tx_crc,
input mse_physs_port_5_ts_capture_vld,
input [6:0] mse_physs_port_5_ts_capture_idx,
output fifo_top_mux_0_physs1_icq_port_6_link_stat,
output [3:0] fifo_top_mux_0_physs1_mse_port_6_link_speed,
output fifo_top_mux_0_physs1_mse_port_6_rx_dval,
output [511:0] fifo_top_mux_0_physs1_mse_port_6_rx_data,
output fifo_top_mux_0_physs1_mse_port_6_rx_sop,
output fifo_top_mux_0_physs1_mse_port_6_rx_eop,
output [5:0] fifo_top_mux_0_physs1_mse_port_6_rx_mod,
output fifo_top_mux_0_physs1_mse_port_6_rx_err,
output fifo_top_mux_0_physs1_mse_port_6_rx_ecc_err,
output [39:0] fifo_top_mux_0_physs1_mse_port_6_rx_ts,
output fifo_top_mux_0_physs1_mse_port_6_tx_rdy,
output fifo_top_mux_0_physs1_mse_port_6_pfc_mode,
input mse_physs_port_6_rx_rdy,
input mse_physs_port_6_tx_wren,
input [511:0] mse_physs_port_6_tx_data,
input mse_physs_port_6_tx_sop,
input mse_physs_port_6_tx_eop,
input [5:0] mse_physs_port_6_tx_mod,
input mse_physs_port_6_tx_err,
input mse_physs_port_6_tx_crc,
input mse_physs_port_6_ts_capture_vld,
input [6:0] mse_physs_port_6_ts_capture_idx,
output fifo_top_mux_0_physs1_icq_port_7_link_stat,
output [3:0] fifo_top_mux_0_physs1_mse_port_7_link_speed,
output fifo_top_mux_0_physs1_mse_port_7_rx_dval,
output [255:0] fifo_top_mux_0_physs1_mse_port_7_rx_data,
output fifo_top_mux_0_physs1_mse_port_7_rx_sop,
output fifo_top_mux_0_physs1_mse_port_7_rx_eop,
output [4:0] fifo_top_mux_0_physs1_mse_port_7_rx_mod,
output fifo_top_mux_0_physs1_mse_port_7_rx_err,
output fifo_top_mux_0_physs1_mse_port_7_rx_ecc_err,
output [39:0] fifo_top_mux_0_physs1_mse_port_7_rx_ts,
output fifo_top_mux_0_physs1_mse_port_7_tx_rdy,
output fifo_top_mux_0_physs1_mse_port_7_pfc_mode,
input mse_physs_port_7_rx_rdy,
input mse_physs_port_7_tx_wren,
input [255:0] mse_physs_port_7_tx_data,
input mse_physs_port_7_tx_sop,
input mse_physs_port_7_tx_eop,
input [4:0] mse_physs_port_7_tx_mod,
input mse_physs_port_7_tx_err,
input mse_physs_port_7_tx_crc,
input mse_physs_port_7_ts_capture_vld,
input [6:0] mse_physs_port_7_ts_capture_idx,
output physs_registers_wrapper_0_reset_ref_clk_override,
output physs_registers_wrapper_0_reset_pcs100_override_en,
output physs_registers_wrapper_0_clk_gate_en_100G_mac_pcs,
output physs_registers_wrapper_0_power_fsm_clk_gate_en,
output physs_registers_wrapper_0_power_fsm_reset_gate_en,
output physs_registers_wrapper_1_reset_ref_clk_override,
output physs_registers_wrapper_1_reset_pcs100_override_en,
output physs_registers_wrapper_1_clk_gate_en_100G_mac_pcs,
output physs_registers_wrapper_1_power_fsm_clk_gate_en,
output physs_registers_wrapper_1_power_fsm_reset_gate_en,
output physs_registers_wrapper_0_clk_gate_en_800G_mac_pcs,
input physs_registers_wrapper_2_reset_ref_clk_override_0,
input physs_registers_wrapper_2_reset_pcs100_override_en_0,
input physs_registers_wrapper_2_clk_gate_en_100G_mac_pcs_0,
input physs_registers_wrapper_2_power_fsm_clk_gate_en_0,
input physs_registers_wrapper_2_power_fsm_reset_gate_en_0,
input physs_registers_wrapper_3_reset_ref_clk_override_0,
input physs_registers_wrapper_3_reset_pcs100_override_en_0,
input physs_registers_wrapper_3_clk_gate_en_100G_mac_pcs_0,
input physs_registers_wrapper_3_power_fsm_clk_gate_en_0,
input physs_registers_wrapper_3_power_fsm_reset_gate_en_0,
input pd_vinf_0_bisr_si,
input pd_vinf_0_bisr_clk,
input pd_vinf_0_bisr_reset,
input pd_vinf_0_bisr_shift_en,
output parmisc_physs0_pd_vinf_0_2_bisr_so,
input pd_vinf_1_bisr_si,
input pd_vinf_1_bisr_clk,
input pd_vinf_1_bisr_reset,
input pd_vinf_1_bisr_shift_en,
output parmisc_physs0_pd_vinf_1_2_bisr_so,
input pd_vinf_2_bisr_si,
input pd_vinf_2_bisr_clk,
input pd_vinf_2_bisr_reset,
input pd_vinf_2_bisr_shift_en,
output parmisc_physs0_pd_vinf_2_2_bisr_so,
input pd_vinf_3_bisr_si,
input pd_vinf_3_bisr_clk,
input pd_vinf_3_bisr_reset,
input pd_vinf_3_bisr_shift_en,
output parmisc_physs0_pd_vinf_3_2_bisr_so,
input pd_vinf_4_bisr_si,
input pd_vinf_4_bisr_clk,
input pd_vinf_4_bisr_reset,
input pd_vinf_4_bisr_shift_en,
output parmisc_physs0_pd_vinf_4_2_bisr_so,
input pd_vinf_5_bisr_si,
output parmisc_physs0_pd_vinf_5_bisr_so,
input parmisc_physs1_pd_vinf_5_2_bisr_so,
output parmisc_physs0_pd_vinf_5_2_bisr_so,
input pd_vinf_5_bisr_reset,
input pd_vinf_5_bisr_shift_en,
input pd_vinf_5_bisr_clk,
input pd_vinf_6_bisr_si,
output parmisc_physs0_pd_vinf_6_bisr_so,
input parmisc_physs1_pd_vinf_6_2_bisr_so,
output parmisc_physs0_pd_vinf_6_2_bisr_so,
input pd_vinf_6_bisr_reset,
input pd_vinf_6_bisr_shift_en,
input pd_vinf_6_bisr_clk,
input physs0_func_rst_raw_n,
input ethphyss_post_clk_mux_ctrl,
output physs_synce_top_mux_0_clkout,
output physs_synce_top_mux_1_clkout,
output parmisc_physs0_DIAG_AGGR_parmisc0_mbist_diag_done,
input parpquad0_DIAG_AGGR_pquad_mbist_diag_done,
input parpquad1_DIAG_AGGR_pquad_mbist_diag_done,
output hlp_mac_rx_throttle_0_stop,
output hlp_mac_rx_throttle_1_stop,
output hlp_mac_rx_throttle_2_stop,
output hlp_mac_rx_throttle_3_stop,
input tx_stop_0_in,
input tx_stop_1_in,
input tx_stop_2_in,
input tx_stop_3_in,
output [7:0] physs_registers_wrapper_1_reset_sd_tx_clk_override_800G_0,
output [7:0] physs_registers_wrapper_1_reset_sd_rx_clk_override_800G_0,
output mac100_0_magic_ind_0,
output mac100_1_magic_ind_0,
output mac100_2_magic_ind_0,
output mac100_3_magic_ind_0,
output mac100_4_magic_ind_0,
output mac100_5_magic_ind_0,
output mac100_6_magic_ind_0,
output mac100_7_magic_ind_0,
input [7:0] icq_physs_net_xoff,
input [7:0] icq_physs_net_xoff_0,
input [7:0] icq_physs_net_xoff_1,
input [7:0] icq_physs_net_xoff_2,
input [7:0] icq_physs_net_xoff_3,
input [7:0] icq_physs_net_xoff_4,
input [7:0] icq_physs_net_xoff_5,
input [7:0] icq_physs_net_xoff_6,
output [7:0] mac100_0_pause_on_0,
output [7:0] mac100_1_pause_on_0,
output [7:0] mac100_2_pause_on_0,
output [7:0] mac100_3_pause_on_0,
output [7:0] mac100_4_pause_on_0,
output [7:0] mac100_5_pause_on_0,
output [7:0] mac100_6_pause_on_0,
output [7:0] mac100_7_pause_on_0,
output fifo_top_mux_0_physs_mse_800g_en_0,
input versa_xmp_2_o_ucss_uart_txd,
input versa_xmp_3_o_ucss_uart_txd,
output physs_uart_demux_out2,
output physs_uart_demux_out3,
output physs_uart_mux_out,
input i_ucss_uart_rxd,
output versa_xmp_0_o_rst_ucss_srds_pcs_rx_reset_pma0_l0_b_a_0,
output versa_xmp_0_o_rst_ucss_srds_pcs_rx_reset_pma1_l0_b_a_0,
output versa_xmp_0_o_rst_ucss_srds_pcs_rx_reset_pma2_l0_b_a_0,
output versa_xmp_0_o_rst_ucss_srds_pcs_rx_reset_pma3_l0_b_a_0,
output versa_xmp_1_o_rst_ucss_srds_pcs_rx_reset_pma0_l0_b_a_0,
output versa_xmp_1_o_rst_ucss_srds_pcs_rx_reset_pma1_l0_b_a_0,
output versa_xmp_1_o_rst_ucss_srds_pcs_rx_reset_pma2_l0_b_a_0,
output versa_xmp_1_o_rst_ucss_srds_pcs_rx_reset_pma3_l0_b_a_0,
input fary_post_force_fail,
input fary_0_trigger_post,
input [5:0] fary_post_algo_select,
output logic ethphyss_post_agg_mquad_0_post_pass_agg,
output logic ethphyss_post_agg_mquad_0_post_complete_agg,
input fary_1_trigger_post,
output logic ethphyss_post_agg_mquad_1_post_pass_agg,
output logic ethphyss_post_agg_mquad_1_post_complete_agg,
input fary_2_trigger_post,
output logic ethphyss_post_agg_mquad_2_post_pass_agg,
output logic ethphyss_post_agg_mquad_2_post_complete_agg,
input fary_3_trigger_post,
output logic ethphyss_post_agg_mquad_3_post_pass_agg,
output logic ethphyss_post_agg_mquad_3_post_complete_agg,
input wire xmp_mem_wrapper_2_aary_post_pass,
input wire xmp_mem_wrapper_2_aary_post_complete,
input wire xmp_mem_wrapper_3_aary_post_pass,
input wire xmp_mem_wrapper_3_aary_post_complete,
output logic ethphyss_post_agg_pquad_4_post_pass_agg,
output logic ethphyss_post_agg_pquad_4_post_complete_agg,
input wire pcs100_mem_wrapper_2_aary_post_pass,
input wire pcs100_mem_wrapper_2_aary_post_complete,
input wire pcs100_mem_wrapper_3_aary_post_pass,
input wire pcs100_mem_wrapper_3_aary_post_complete,
output logic ethphyss_post_agg_pquad_5_post_pass_agg,
output logic ethphyss_post_agg_pquad_5_post_complete_agg,
input fary_6_trigger_post,
output logic ethphyss_post_agg_par800g_6_post_pass_agg,
output logic ethphyss_post_agg_par800g_6_post_complete_agg,
input fary_7_trigger_post,
output logic ethphyss_post_agg_par400g0_7_post_pass_agg,
output logic ethphyss_post_agg_par400g0_7_post_complete_agg,
input fary_8_trigger_post,
output logic ethphyss_post_agg_par400g0_8_post_pass_agg,
output logic ethphyss_post_agg_par400g0_8_post_complete_agg,
input fary_9_trigger_post,
output logic ethphyss_post_agg_par400g1_9_post_pass_agg,
output logic ethphyss_post_agg_par400g1_9_post_complete_agg,
input fary_10_trigger_post,
output logic ethphyss_post_agg_par400g1_10_post_pass_agg,
output logic ethphyss_post_agg_par400g1_10_post_complete_agg,
input parmisc_physs1_dfx_ubp_ctrl_trig_in_to_parmisc_physs0_ubpc,
output parmisc_physs0_trig_clock_stop_to_parpquad0_pma0_txdat,
output parmisc_physs0_trig_clock_stop_to_parpquad0_pma1_txdat,
output parmisc_physs0_trig_clock_stop_to_parpquad0_pma2_txdat,
output parmisc_physs0_trig_clock_stop_to_parpquad0_pma3_txdat,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma0_rx,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma1_rx,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma2_rx,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma3_rx,
output parmisc_physs0_trig_clock_stop_to_parpquad0_pma0_rxdat,
output parmisc_physs0_trig_clock_stop_to_parpquad0_pma1_rxdat,
output parmisc_physs0_trig_clock_stop_to_parpquad0_pma2_rxdat,
output parmisc_physs0_trig_clock_stop_to_parpquad0_pma3_rxdat,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma0_cmnplla_postdiv,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma1_cmnplla_postdiv,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma2_cmnplla_postdiv,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma3_cmnplla_postdiv,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_slv_pcs1,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_ucss_mem_dram,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_ucss_mem_iram,
output parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_ucss_mem_tracemem,
output parmisc_physs0_trig_clock_stop_to_parpquad1_pma0_txdat,
output parmisc_physs0_trig_clock_stop_to_parpquad1_pma1_txdat,
output parmisc_physs0_trig_clock_stop_to_parpquad1_pma2_txdat,
output parmisc_physs0_trig_clock_stop_to_parpquad1_pma3_txdat,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma0_rx,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma1_rx,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma2_rx,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma3_rx,
output parmisc_physs0_trig_clock_stop_to_parpquad1_pma0_rxdat,
output parmisc_physs0_trig_clock_stop_to_parpquad1_pma1_rxdat,
output parmisc_physs0_trig_clock_stop_to_parpquad1_pma2_rxdat,
output parmisc_physs0_trig_clock_stop_to_parpquad1_pma3_rxdat,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma0_cmnplla_postdiv,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma1_cmnplla_postdiv,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma2_cmnplla_postdiv,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma3_cmnplla_postdiv,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_slv_pcs1,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_ucss_mem_dram,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_ucss_mem_iram,
output parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_ucss_mem_tracemem,
output [27:0] quadpcs100_0_pcs_desk_buf_rlevel_0,
output [31:0] quadpcs100_0_pcs_sd_bit_slip_0,
output [3:0] quadpcs100_0_pcs_link_status_tsu_0,
output [27:0] quadpcs100_1_pcs_desk_buf_rlevel_0,
output [31:0] quadpcs100_1_pcs_sd_bit_slip_0,
output [3:0] quadpcs100_1_pcs_link_status_tsu_0,
inout wire versa_xmp_0_xioa_ck_pma0_ref0_n,
inout wire versa_xmp_0_xioa_ck_pma0_ref0_p,
inout wire versa_xmp_0_xioa_ck_pma0_ref1_n,
inout wire versa_xmp_0_xioa_ck_pma0_ref1_p,
inout wire versa_xmp_0_xioa_ck_pma1_ref0_n,
inout wire versa_xmp_0_xioa_ck_pma1_ref0_p,
inout wire versa_xmp_0_xioa_ck_pma1_ref1_n,
inout wire versa_xmp_0_xioa_ck_pma1_ref1_p,
inout wire versa_xmp_0_xioa_ck_pma2_ref0_n,
inout wire versa_xmp_0_xioa_ck_pma2_ref0_p,
inout wire versa_xmp_0_xioa_ck_pma2_ref1_n,
inout wire versa_xmp_0_xioa_ck_pma2_ref1_p,
inout wire versa_xmp_0_xioa_ck_pma3_ref0_n,
inout wire versa_xmp_0_xioa_ck_pma3_ref0_p,
inout wire versa_xmp_0_xioa_ck_pma3_ref1_n,
inout wire versa_xmp_0_xioa_ck_pma3_ref1_p,
input rclk_diff_p,
input rclk_diff_n,
output versa_xmp_0_xoa_pma0_dcmon1,
output versa_xmp_0_xoa_pma0_dcmon2,
output versa_xmp_0_xoa_pma1_dcmon1,
output versa_xmp_0_xoa_pma1_dcmon2,
output versa_xmp_0_xoa_pma2_dcmon1,
output versa_xmp_0_xoa_pma2_dcmon2,
output versa_xmp_0_xoa_pma3_dcmon1,
output versa_xmp_0_xoa_pma3_dcmon2,
inout wire versa_xmp_1_xioa_ck_pma0_ref0_n,
inout wire versa_xmp_1_xioa_ck_pma0_ref0_p,
inout wire versa_xmp_1_xioa_ck_pma0_ref1_n,
inout wire versa_xmp_1_xioa_ck_pma0_ref1_p,
inout wire versa_xmp_1_xioa_ck_pma1_ref0_n,
inout wire versa_xmp_1_xioa_ck_pma1_ref0_p,
inout wire versa_xmp_1_xioa_ck_pma1_ref1_n,
inout wire versa_xmp_1_xioa_ck_pma1_ref1_p,
inout wire versa_xmp_1_xioa_ck_pma2_ref0_n,
inout wire versa_xmp_1_xioa_ck_pma2_ref0_p,
inout wire versa_xmp_1_xioa_ck_pma2_ref1_n,
inout wire versa_xmp_1_xioa_ck_pma2_ref1_p,
inout wire versa_xmp_1_xioa_ck_pma3_ref0_n,
inout wire versa_xmp_1_xioa_ck_pma3_ref0_p,
inout wire versa_xmp_1_xioa_ck_pma3_ref1_n,
inout wire versa_xmp_1_xioa_ck_pma3_ref1_p,
output versa_xmp_1_xoa_pma0_dcmon1,
output versa_xmp_1_xoa_pma0_dcmon2,
output versa_xmp_1_xoa_pma1_dcmon1,
output versa_xmp_1_xoa_pma1_dcmon2,
output versa_xmp_1_xoa_pma2_dcmon1,
output versa_xmp_1_xoa_pma2_dcmon2,
output versa_xmp_1_xoa_pma3_dcmon1,
output versa_xmp_1_xoa_pma3_dcmon2,
output logic interrupts_counter_level_fatal_int_0_out_signal_sync,
output logic interrupts_counter_level_imc_int_0_out_signal_sync,
output quad_interrupts_0_mac800_int,
output versa_xmp_0_o_ucss_irq_cpi_0_a,
output versa_xmp_1_o_ucss_irq_cpi_0_a,
output versa_xmp_0_o_ucss_irq_cpi_1_a,
output versa_xmp_1_o_ucss_irq_cpi_1_a,
output versa_xmp_0_o_ucss_irq_cpi_2_a,
output versa_xmp_1_o_ucss_irq_cpi_2_a,
output versa_xmp_0_o_ucss_irq_cpi_3_a,
output versa_xmp_1_o_ucss_irq_cpi_3_a,
output versa_xmp_0_o_ucss_irq_cpi_4_a,
output versa_xmp_1_o_ucss_irq_cpi_4_a,
output versa_xmp_0_o_ucss_irq_to_soc_l0_a,
output versa_xmp_0_o_ucss_irq_to_soc_l1_a,
output versa_xmp_0_o_ucss_irq_to_soc_l2_a,
output versa_xmp_0_o_ucss_irq_to_soc_l3_a,
output versa_xmp_1_o_ucss_irq_to_soc_l0_a,
output versa_xmp_1_o_ucss_irq_to_soc_l1_a,
output versa_xmp_1_o_ucss_irq_to_soc_l2_a,
output versa_xmp_1_o_ucss_irq_to_soc_l3_a,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_rx_clkena,
output logic [7:0] pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_rx_rxc,
output logic [63:0] pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_rx_rxd,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii0_txc_0,
input wire [63:0] hlp_xlgmii0_txd_0,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu0_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu0_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu0_xlgmii_tx_tsu,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_rx_clkena,
output logic [7:0] pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_rx_rxc,
output logic [63:0] pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_rx_rxd,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii1_txc_0,
input wire [63:0] hlp_xlgmii1_txd_0,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu1_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu1_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu1_xlgmii_tx_tsu,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_rx_clkena,
output logic [7:0] pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_rx_rxc,
output logic [63:0] pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_rx_rxd,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii2_txc_0,
input wire [63:0] hlp_xlgmii2_txd_0,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu2_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu2_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu2_xlgmii_tx_tsu,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_rx_clkena,
output logic [7:0] pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_rx_rxc,
output logic [63:0] pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_rx_rxd,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii3_txc_0,
input wire [63:0] hlp_xlgmii3_txd_0,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu3_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu3_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad0_tsu3_xlgmii_tx_tsu,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac0_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac0_cgmii_rx_clkena,
output logic [15:0] pcs_mac_pipeline_top_wrap_mquad0_mac0_cgmii_rx_rxc,
output logic [127:0] pcs_mac_pipeline_top_wrap_mquad0_mac0_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii0_txc_0,
input wire [127:0] hlp_cgmii0_txd_0,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac1_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac1_cgmii_rx_clkena,
output logic [15:0] pcs_mac_pipeline_top_wrap_mquad0_mac1_cgmii_rx_rxc,
output logic [127:0] pcs_mac_pipeline_top_wrap_mquad0_mac1_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii1_txc_0,
input wire [127:0] hlp_cgmii1_txd_0,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac2_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac2_cgmii_rx_clkena,
output logic [15:0] pcs_mac_pipeline_top_wrap_mquad0_mac2_cgmii_rx_rxc,
output logic [127:0] pcs_mac_pipeline_top_wrap_mquad0_mac2_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii2_txc_0,
input wire [127:0] hlp_cgmii2_txd_0,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac3_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad0_mac3_cgmii_rx_clkena,
output logic [15:0] pcs_mac_pipeline_top_wrap_mquad0_mac3_cgmii_rx_rxc,
output logic [127:0] pcs_mac_pipeline_top_wrap_mquad0_mac3_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii3_txc_0,
input wire [127:0] hlp_cgmii3_txd_0,
input wire [7:0] hlp_xlgmii0_rxc_nss_0,
input wire [63:0] hlp_xlgmii0_rxd_nss_0,
output logic [7:0] pcs_mac_pipeline_top_wrap_nss_pcs0_xlgmii_tx_txc,
output logic [63:0] pcs_mac_pipeline_top_wrap_nss_pcs0_xlgmii_tx_txd,
input wire [7:0] hlp_xlgmii1_rxc_nss_0,
input wire [63:0] hlp_xlgmii1_rxd_nss_0,
output logic [7:0] pcs_mac_pipeline_top_wrap_nss_pcs1_xlgmii_tx_txc,
output logic [63:0] pcs_mac_pipeline_top_wrap_nss_pcs1_xlgmii_tx_txd,
input wire [7:0] hlp_xlgmii2_rxc_nss_0,
input wire [63:0] hlp_xlgmii2_rxd_nss_0,
output logic [7:0] pcs_mac_pipeline_top_wrap_nss_pcs2_xlgmii_tx_txc,
output logic [63:0] pcs_mac_pipeline_top_wrap_nss_pcs2_xlgmii_tx_txd,
input wire [7:0] hlp_xlgmii3_rxc_nss_0,
input wire [63:0] hlp_xlgmii3_rxd_nss_0,
output logic [7:0] pcs_mac_pipeline_top_wrap_nss_pcs3_xlgmii_tx_txc,
output logic [63:0] pcs_mac_pipeline_top_wrap_nss_pcs3_xlgmii_tx_txd,
input wire [15:0] hlp_cgmii0_rxc_nss_0,
input wire [127:0] hlp_cgmii0_rxd_nss_0,
output logic [15:0] pcs_mac_pipeline_top_wrap_nss_pcs0_cgmii_tx_txc,
output logic [127:0] pcs_mac_pipeline_top_wrap_nss_pcs0_cgmii_tx_txd,
input wire [15:0] hlp_cgmii1_rxc_nss_0,
input wire [127:0] hlp_cgmii1_rxd_nss_0,
output logic [15:0] pcs_mac_pipeline_top_wrap_nss_pcs1_cgmii_tx_txc,
output logic [127:0] pcs_mac_pipeline_top_wrap_nss_pcs1_cgmii_tx_txd,
input wire [15:0] hlp_cgmii2_rxc_nss_0,
input wire [127:0] hlp_cgmii2_rxd_nss_0,
output logic [15:0] pcs_mac_pipeline_top_wrap_nss_pcs2_cgmii_tx_txc,
output logic [127:0] pcs_mac_pipeline_top_wrap_nss_pcs2_cgmii_tx_txd,
input wire [15:0] hlp_cgmii3_rxc_nss_0,
input wire [127:0] hlp_cgmii3_rxd_nss_0,
output logic [15:0] pcs_mac_pipeline_top_wrap_nss_pcs3_cgmii_tx_txc,
output logic [127:0] pcs_mac_pipeline_top_wrap_nss_pcs3_cgmii_tx_txd,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_rx_clkena,
output logic [7:0] pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_rx_rxc,
output logic [63:0] pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_rx_rxd,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii0_txc_1,
input wire [63:0] hlp_xlgmii0_txd_1,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu0_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu0_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu0_xlgmii_tx_tsu,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_rx_clkena,
output logic [7:0] pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_rx_rxc,
output logic [63:0] pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_rx_rxd,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii1_txc_1,
input wire [63:0] hlp_xlgmii1_txd_1,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu1_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu1_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu1_xlgmii_tx_tsu,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_rx_clkena,
output logic [7:0] pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_rx_rxc,
output logic [63:0] pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_rx_rxd,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii2_txc_1,
input wire [63:0] hlp_xlgmii2_txd_1,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu2_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu2_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu2_xlgmii_tx_tsu,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_rx_clkena,
output logic [7:0] pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_rx_rxc,
output logic [63:0] pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_rx_rxd,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii3_txc_1,
input wire [63:0] hlp_xlgmii3_txd_1,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu3_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu3_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_mquad1_tsu3_xlgmii_tx_tsu,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac0_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac0_cgmii_rx_clkena,
output logic [15:0] pcs_mac_pipeline_top_wrap_mquad1_mac0_cgmii_rx_rxc,
output logic [127:0] pcs_mac_pipeline_top_wrap_mquad1_mac0_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii0_txc_1,
input wire [127:0] hlp_cgmii0_txd_1,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac1_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac1_cgmii_rx_clkena,
output logic [15:0] pcs_mac_pipeline_top_wrap_mquad1_mac1_cgmii_rx_rxc,
output logic [127:0] pcs_mac_pipeline_top_wrap_mquad1_mac1_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii1_txc_1,
input wire [127:0] hlp_cgmii1_txd_1,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac2_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac2_cgmii_rx_clkena,
output logic [15:0] pcs_mac_pipeline_top_wrap_mquad1_mac2_cgmii_rx_rxc,
output logic [127:0] pcs_mac_pipeline_top_wrap_mquad1_mac2_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii2_txc_1,
input wire [127:0] hlp_cgmii2_txd_1,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac3_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_mquad1_mac3_cgmii_rx_clkena,
output logic [15:0] pcs_mac_pipeline_top_wrap_mquad1_mac3_cgmii_rx_rxc,
output logic [127:0] pcs_mac_pipeline_top_wrap_mquad1_mac3_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii3_txc_1,
input wire [127:0] hlp_cgmii3_txd_1,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac0_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac0_xlgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_rx_clkena,
input wire [7:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac0_xlgmii_rx_rxc,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_rx_rxc,
input wire [63:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac0_xlgmii_rx_rxd,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_rx_rxd,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac0_xlgmii_rxt0_next,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii0_txc_2,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs0_xlgmii_tx_txc,
input wire [63:0] hlp_xlgmii0_txd_2,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs0_xlgmii_tx_txd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu0_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu0_xlgmii_rx_sd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu0_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu0_xlgmii_rx_tsu,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu0_xlgmii_tx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu0_xlgmii_tx_tsu,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac1_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac1_xlgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_rx_clkena,
input wire [7:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac1_xlgmii_rx_rxc,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_rx_rxc,
input wire [63:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac1_xlgmii_rx_rxd,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_rx_rxd,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac1_xlgmii_rxt0_next,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii1_txc_2,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs1_xlgmii_tx_txc,
input wire [63:0] hlp_xlgmii1_txd_2,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs1_xlgmii_tx_txd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu1_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu1_xlgmii_rx_sd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu1_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu1_xlgmii_rx_tsu,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu1_xlgmii_tx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu1_xlgmii_tx_tsu,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac2_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac2_xlgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_rx_clkena,
input wire [7:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac2_xlgmii_rx_rxc,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_rx_rxc,
input wire [63:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac2_xlgmii_rx_rxd,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_rx_rxd,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac2_xlgmii_rxt0_next,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii2_txc_2,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs2_xlgmii_tx_txc,
input wire [63:0] hlp_xlgmii2_txd_2,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs2_xlgmii_tx_txd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu2_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu2_xlgmii_rx_sd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu2_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu2_xlgmii_rx_tsu,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu2_xlgmii_tx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu2_xlgmii_tx_tsu,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac3_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac3_xlgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_rx_clkena,
input wire [7:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac3_xlgmii_rx_rxc,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_rx_rxc,
input wire [63:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac3_xlgmii_rx_rxd,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_rx_rxd,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac3_xlgmii_rxt0_next,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii3_txc_2,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs3_xlgmii_tx_txc,
input wire [63:0] hlp_xlgmii3_txd_2,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs3_xlgmii_tx_txd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu3_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu3_xlgmii_rx_sd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu3_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu3_xlgmii_rx_tsu,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad0_0_tsu3_xlgmii_tx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad0_1_tsu3_xlgmii_tx_tsu,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac0_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac0_cgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac0_cgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac0_cgmii_rx_clkena,
input wire [15:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac0_cgmii_rx_rxc,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac0_cgmii_rx_rxc,
input wire [127:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac0_cgmii_rx_rxd,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac0_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii0_txc_2,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs0_cgmii_tx_txc,
input wire [127:0] hlp_cgmii0_txd_2,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs0_cgmii_tx_txd,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac1_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac1_cgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac1_cgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac1_cgmii_rx_clkena,
input wire [15:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac1_cgmii_rx_rxc,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac1_cgmii_rx_rxc,
input wire [127:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac1_cgmii_rx_rxd,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac1_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii1_txc_2,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs1_cgmii_tx_txc,
input wire [127:0] hlp_cgmii1_txd_2,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs1_cgmii_tx_txd,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac2_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac2_cgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac2_cgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac2_cgmii_rx_clkena,
input wire [15:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac2_cgmii_rx_rxc,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac2_cgmii_rx_rxc,
input wire [127:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac2_cgmii_rx_rxd,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac2_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii2_txc_2,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs2_cgmii_tx_txc,
input wire [127:0] hlp_cgmii2_txd_2,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs2_cgmii_tx_txd,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac3_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac3_cgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad0_0_mac3_cgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad0_1_mac3_cgmii_rx_clkena,
input wire [15:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac3_cgmii_rx_rxc,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac3_cgmii_rx_rxc,
input wire [127:0] pcs_mac_pipeline_top_wrap_pquad0_0_mac3_cgmii_rx_rxd,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad0_1_mac3_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii3_txc_2,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs3_cgmii_tx_txc,
input wire [127:0] hlp_cgmii3_txd_2,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad0_1_pcs3_cgmii_tx_txd,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac0_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac0_xlgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_rx_clkena,
input wire [7:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac0_xlgmii_rx_rxc,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_rx_rxc,
input wire [63:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac0_xlgmii_rx_rxd,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_rx_rxd,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac0_xlgmii_rxt0_next,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii0_txc_3,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs0_xlgmii_tx_txc,
input wire [63:0] hlp_xlgmii0_txd_3,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs0_xlgmii_tx_txd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu0_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu0_xlgmii_rx_sd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu0_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu0_xlgmii_rx_tsu,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu0_xlgmii_tx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu0_xlgmii_tx_tsu,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac1_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac1_xlgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_rx_clkena,
input wire [7:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac1_xlgmii_rx_rxc,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_rx_rxc,
input wire [63:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac1_xlgmii_rx_rxd,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_rx_rxd,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac1_xlgmii_rxt0_next,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii1_txc_3,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs1_xlgmii_tx_txc,
input wire [63:0] hlp_xlgmii1_txd_3,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs1_xlgmii_tx_txd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu1_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu1_xlgmii_rx_sd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu1_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu1_xlgmii_rx_tsu,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu1_xlgmii_tx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu1_xlgmii_tx_tsu,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac2_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac2_xlgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_rx_clkena,
input wire [7:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac2_xlgmii_rx_rxc,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_rx_rxc,
input wire [63:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac2_xlgmii_rx_rxd,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_rx_rxd,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac2_xlgmii_rxt0_next,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii2_txc_3,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs2_xlgmii_tx_txc,
input wire [63:0] hlp_xlgmii2_txd_3,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs2_xlgmii_tx_txd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu2_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu2_xlgmii_rx_sd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu2_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu2_xlgmii_rx_tsu,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu2_xlgmii_tx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu2_xlgmii_tx_tsu,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac3_xlgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac3_xlgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_rx_clkena,
input wire [7:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac3_xlgmii_rx_rxc,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_rx_rxc,
input wire [63:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac3_xlgmii_rx_rxd,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_rx_rxd,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac3_xlgmii_rxt0_next,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_rxt0_next,
input wire [7:0] hlp_xlgmii3_txc_3,
output logic [7:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs3_xlgmii_tx_txc,
input wire [63:0] hlp_xlgmii3_txd_3,
output logic [63:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs3_xlgmii_tx_txd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu3_xlgmii_rx_sd,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu3_xlgmii_rx_sd,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu3_xlgmii_rx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu3_xlgmii_rx_tsu,
input wire [1:0] pcs_mac_pipeline_top_wrap_pquad1_0_tsu3_xlgmii_tx_tsu,
output logic [1:0] pcs_mac_pipeline_top_wrap_pquad1_1_tsu3_xlgmii_tx_tsu,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac0_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac0_cgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac0_cgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac0_cgmii_rx_clkena,
input wire [15:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac0_cgmii_rx_rxc,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac0_cgmii_rx_rxc,
input wire [127:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac0_cgmii_rx_rxd,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac0_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii0_txc_3,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs0_cgmii_tx_txc,
input wire [127:0] hlp_cgmii0_txd_3,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs0_cgmii_tx_txd,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac1_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac1_cgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac1_cgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac1_cgmii_rx_clkena,
input wire [15:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac1_cgmii_rx_rxc,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac1_cgmii_rx_rxc,
input wire [127:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac1_cgmii_rx_rxd,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac1_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii1_txc_3,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs1_cgmii_tx_txc,
input wire [127:0] hlp_cgmii1_txd_3,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs1_cgmii_tx_txd,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac2_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac2_cgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac2_cgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac2_cgmii_rx_clkena,
input wire [15:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac2_cgmii_rx_rxc,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac2_cgmii_rx_rxc,
input wire [127:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac2_cgmii_rx_rxd,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac2_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii2_txc_3,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs2_cgmii_tx_txc,
input wire [127:0] hlp_cgmii2_txd_3,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs2_cgmii_tx_txd,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac3_cgmii_tx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac3_cgmii_tx_clkena,
input wire pcs_mac_pipeline_top_wrap_pquad1_0_mac3_cgmii_rx_clkena,
output logic pcs_mac_pipeline_top_wrap_pquad1_1_mac3_cgmii_rx_clkena,
input wire [15:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac3_cgmii_rx_rxc,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac3_cgmii_rx_rxc,
input wire [127:0] pcs_mac_pipeline_top_wrap_pquad1_0_mac3_cgmii_rx_rxd,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad1_1_mac3_cgmii_rx_rxd,
input wire [15:0] hlp_cgmii3_txc_3,
output logic [15:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs3_cgmii_tx_txc,
input wire [127:0] hlp_cgmii3_txd_3,
output logic [127:0] pcs_mac_pipeline_top_wrap_pquad1_1_pcs3_cgmii_tx_txd,
output [1:0] quad_interrupts_0_mac400_int,
output [1:0] quad_interrupts_1_mac400_int,
input [3:0] physs_0_AWID,
input [22:0] physs_0_AWADDR,
input [7:0] physs_0_AWLEN,
input [2:0] physs_0_AWSIZE,
input [1:0] physs_0_AWBURST,
input physs_0_AWLOCK,
input [3:0] physs_0_AWCACHE,
input [2:0] physs_0_AWPROT,
input physs_0_AWVALID,
input [31:0] physs_0_WDATA,
input [3:0] physs_0_WSTRB,
input physs_0_WLAST,
input physs_0_WVALID,
input physs_0_BREADY,
input [3:0] physs_0_ARID,
input [22:0] physs_0_ARADDR,
input [7:0] physs_0_ARLEN,
input [2:0] physs_0_ARSIZE,
input [1:0] physs_0_ARBURST,
input physs_0_ARLOCK,
input [3:0] physs_0_ARCACHE,
input [2:0] physs_0_ARPROT,
input physs_0_ARVALID,
output nic400_physs_0_awready_slave_physs,
output nic400_physs_0_wready_slave_physs,
input physs_0_RREADY,
output [3:0] nic400_physs_0_bid_slave_physs,
output [1:0] nic400_physs_0_bresp_slave_physs,
output nic400_physs_0_bvalid_slave_physs,
output nic400_physs_0_arready_slave_physs,
output [3:0] nic400_physs_0_rid_slave_physs,
output [31:0] nic400_physs_0_rdata_slave_physs,
output [1:0] nic400_physs_0_rresp_slave_physs,
output nic400_physs_0_rlast_slave_physs,
output nic400_physs_0_rvalid_slave_physs,
input mdio_in,
output mac100_0_mdc,
output mac100_0_mdio_out,
output mac100_0_mdio_oen_0,
output socviewpin_4to1digimux_0_outmux,
input [1:0] physs_timesync_sync_val,
output [3:0] quad_interrupts_0_mac100_int,
output [3:0] quad_interrupts_1_mac100_int,
output logic interrupts_counter_level_imc_ts_int_out_signal_sync,
output [3:0] quad_interrupts_0_ts_int_o,
output [3:0] quad_interrupts_1_ts_int_o,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_scan_in,
input parmisc_physs1_BSCAN_PIPE_OUT_scan_out,
output parmisc_physs0_BSCAN_PIPE_IN_FROM_parmisc_physs1_scan_final_out,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_force_disable,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_select_jtag_input,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_select_jtag_output,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_ac_init_clock0,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_ac_init_clock1,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_ac_signal,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_ac_mode_en,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_intel_update_clk,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_intel_clamp_en,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_intel_bscan_mode,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_select,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_bscan_clock,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_capture_en,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_shift_en,
output parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_update_en,
input PHYSS_BSCAN_BYPASS,
input PHYSS_BSCAN_BYPASS_0,
input PHYSS_BSCAN_BYPASS_1,
input PHYSS_BSCAN_BYPASS_2,
input PHYSS_BSCAN_BYPASS_3,
input PHYSS_BSCAN_BYPASS_4,
input PHYSS_BSCAN_BYPASS_5,
input PHYSS_BSCAN_BYPASS_6,
input PHYSS_BSCAN_BYPASS_7,
input PHYSS_BSCAN_BYPASS_8,
input BSCAN_PIPE_IN_1_bscan_clock,
input BSCAN_PIPE_IN_1_select,
input BSCAN_PIPE_IN_1_capture_en,
input BSCAN_PIPE_IN_1_shift_en,
input BSCAN_PIPE_IN_1_update_en,
input BSCAN_PIPE_IN_1_scan_in,
input BSCAN_PIPE_IN_1_ac_signal,
input BSCAN_PIPE_IN_1_ac_init_clock0,
input BSCAN_PIPE_IN_1_ac_init_clock1,
input BSCAN_PIPE_IN_1_ac_mode_en,
input BSCAN_PIPE_IN_1_force_disable,
input BSCAN_PIPE_IN_1_select_jtag_input,
input BSCAN_PIPE_IN_1_select_jtag_output,
input BSCAN_PIPE_IN_1_intel_update_clk,
input BSCAN_PIPE_IN_1_intel_clamp_en,
input BSCAN_PIPE_IN_1_intel_bscan_mode,
input BSCAN_PIPE_IN_1_intel_d6actestsig_b,
input parmisc_physs1_BSCAN_PIPE_OUT_2_bscan_to_intel_d6actestsig_b,
output parmisc_physs0_BSCAN_PIPE_OUT_2_bscan_to_intel_d6actestsig_b,
input trst_b,
input tck,
input tms,
input tdi,
output parmisc_physs0_NW_IN_tdo_en,
output parmisc_physs0_NW_IN_tdo,
input ijtag_reset_b,
input ijtag_shift,
input ijtag_capture,
input ijtag_update,
input ijtag_select,
input ijtag_si,
output parmisc_physs0_NW_IN_ijtag_so,
input shift_ir_dr,
input tms_park_value,
input nw_mode,
output parmisc_physs0_NW_IN_tap_sel_out,
input parmisc_physs1_NW_IN_tdo,
input parmisc_physs1_NW_IN_tdo_en,
output parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_reset,
output parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_ce,
output parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_se,
output parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_ue,
output parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_sel,
output parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_si,
input parmisc_physs1_NW_IN_ijtag_so,
input parmisc_physs1_NW_IN_tap_sel_out );

//Stub implementation - tie all outputs to 0

assign SSN_END_entry_from_nac_bus_data_out = 'b0;
assign SSN_END_exit_to_nac_bus_data_out = 'b0;
assign SSN_END_towards_parmisc_physs1_bus_data_out = 'b0;
assign mbp_repeater_odi_parmisc_physs0_5_ubp_out = 'b0;
assign mbp_repeater_sfe_parmisc_physs0_2_ubp_out = 'b0;
assign versa_xmp_0_xoa_pma0_tx_n_l0 = 'b0;
assign versa_xmp_0_xoa_pma0_tx_p_l0 = 'b0;
assign versa_xmp_0_xoa_pma1_tx_n_l0 = 'b0;
assign versa_xmp_0_xoa_pma1_tx_p_l0 = 'b0;
assign versa_xmp_0_xoa_pma2_tx_n_l0 = 'b0;
assign versa_xmp_0_xoa_pma2_tx_p_l0 = 'b0;
assign versa_xmp_0_xoa_pma3_tx_n_l0 = 'b0;
assign versa_xmp_0_xoa_pma3_tx_p_l0 = 'b0;
assign versa_xmp_1_xoa_pma0_tx_n_l0 = 'b0;
assign versa_xmp_1_xoa_pma0_tx_p_l0 = 'b0;
assign versa_xmp_1_xoa_pma1_tx_n_l0 = 'b0;
assign versa_xmp_1_xoa_pma1_tx_p_l0 = 'b0;
assign versa_xmp_1_xoa_pma2_tx_n_l0 = 'b0;
assign versa_xmp_1_xoa_pma2_tx_p_l0 = 'b0;
assign versa_xmp_1_xoa_pma3_tx_n_l0 = 'b0;
assign versa_xmp_1_xoa_pma3_tx_p_l0 = 'b0;
assign physs_reset_prep_ack_double_sync_physs_scon_reset_prep_ack_sync = 'b0;
assign dfd_rtb_trig_ctf_adapter_0_trig_req_to_fabric = 'b0;
assign dfd_rtb_trig_ctf_adapter_0_ack_to_fabric = 'b0;
assign dfd_rtb_trig_ctf_adapter_1_trig_req_to_fabric = 'b0;
assign dfd_rtb_trig_ctf_adapter_1_ack_to_fabric = 'b0;
assign physs_intf0_clk_adop_parmisc_physs0_clkout_0 = 'b0;
assign soc_per_clk_adop_parmisc_physs0_clkout_0 = 'b0;
assign physs_func_clk_adop_parmisc_physs0_clkout = 'b0;
assign o_ck_pma0_cmnplla_postdiv_clk_mux_parmquad0_clkout = 'b0;
assign fscan_ref_clk_adop_parmisc_physs0_clkout_0 = 'b0;
assign uart_clk_adop_parmisc_physs0_clkout_0 = 'b0;
assign fifo_top_mux_0_physs0_icq_port_0_link_stat = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_link_speed = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_rx_dval = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_rx_data = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_rx_sop = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_rx_eop = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_rx_mod = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_rx_err = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_rx_ecc_err = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_rx_ts = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_tx_rdy = 'b0;
assign fifo_top_mux_0_physs0_mse_port_0_pfc_mode = 'b0;
assign fifo_top_mux_0_physs0_icq_port_1_link_stat = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_link_speed = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_rx_dval = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_rx_data = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_rx_sop = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_rx_eop = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_rx_mod = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_rx_err = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_rx_ecc_err = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_rx_ts = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_tx_rdy = 'b0;
assign fifo_top_mux_0_physs0_mse_port_1_pfc_mode = 'b0;
assign fifo_top_mux_0_physs0_icq_port_2_link_stat = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_link_speed = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_rx_dval = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_rx_data = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_rx_sop = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_rx_eop = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_rx_mod = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_rx_err = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_rx_ecc_err = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_rx_ts = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_tx_rdy = 'b0;
assign fifo_top_mux_0_physs0_mse_port_2_pfc_mode = 'b0;
assign fifo_top_mux_0_physs0_icq_port_3_link_stat = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_link_speed = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_rx_dval = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_rx_data = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_rx_sop = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_rx_eop = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_rx_mod = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_rx_err = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_rx_ecc_err = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_rx_ts = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_tx_rdy = 'b0;
assign fifo_top_mux_0_physs0_mse_port_3_pfc_mode = 'b0;
assign fifo_top_mux_0_physs1_icq_port_4_link_stat = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_link_speed = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_rx_dval = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_rx_data = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_rx_sop = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_rx_eop = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_rx_mod = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_rx_err = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_rx_ecc_err = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_rx_ts = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_tx_rdy = 'b0;
assign fifo_top_mux_0_physs1_mse_port_4_pfc_mode = 'b0;
assign fifo_top_mux_0_physs1_icq_port_5_link_stat = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_link_speed = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_rx_dval = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_rx_data = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_rx_sop = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_rx_eop = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_rx_mod = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_rx_err = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_rx_ecc_err = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_rx_ts = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_tx_rdy = 'b0;
assign fifo_top_mux_0_physs1_mse_port_5_pfc_mode = 'b0;
assign fifo_top_mux_0_physs1_icq_port_6_link_stat = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_link_speed = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_rx_dval = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_rx_data = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_rx_sop = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_rx_eop = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_rx_mod = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_rx_err = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_rx_ecc_err = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_rx_ts = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_tx_rdy = 'b0;
assign fifo_top_mux_0_physs1_mse_port_6_pfc_mode = 'b0;
assign fifo_top_mux_0_physs1_icq_port_7_link_stat = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_link_speed = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_rx_dval = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_rx_data = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_rx_sop = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_rx_eop = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_rx_mod = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_rx_err = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_rx_ecc_err = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_rx_ts = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_tx_rdy = 'b0;
assign fifo_top_mux_0_physs1_mse_port_7_pfc_mode = 'b0;
assign physs_registers_wrapper_0_reset_ref_clk_override = 'b0;
assign physs_registers_wrapper_0_reset_pcs100_override_en = 'b0;
assign physs_registers_wrapper_0_clk_gate_en_100G_mac_pcs = 'b0;
assign physs_registers_wrapper_0_power_fsm_clk_gate_en = 'b0;
assign physs_registers_wrapper_0_power_fsm_reset_gate_en = 'b0;
assign physs_registers_wrapper_1_reset_ref_clk_override = 'b0;
assign physs_registers_wrapper_1_reset_pcs100_override_en = 'b0;
assign physs_registers_wrapper_1_clk_gate_en_100G_mac_pcs = 'b0;
assign physs_registers_wrapper_1_power_fsm_clk_gate_en = 'b0;
assign physs_registers_wrapper_1_power_fsm_reset_gate_en = 'b0;
assign physs_registers_wrapper_0_clk_gate_en_800G_mac_pcs = 'b0;
assign parmisc_physs0_pd_vinf_0_2_bisr_so = 'b0;
assign parmisc_physs0_pd_vinf_1_2_bisr_so = 'b0;
assign parmisc_physs0_pd_vinf_2_2_bisr_so = 'b0;
assign parmisc_physs0_pd_vinf_3_2_bisr_so = 'b0;
assign parmisc_physs0_pd_vinf_4_2_bisr_so = 'b0;
assign parmisc_physs0_pd_vinf_5_bisr_so = 'b0;
assign parmisc_physs0_pd_vinf_5_2_bisr_so = 'b0;
assign parmisc_physs0_pd_vinf_6_bisr_so = 'b0;
assign parmisc_physs0_pd_vinf_6_2_bisr_so = 'b0;
assign physs_synce_top_mux_0_clkout = 'b0;
assign physs_synce_top_mux_1_clkout = 'b0;
assign parmisc_physs0_DIAG_AGGR_parmisc0_mbist_diag_done = 'b0;
assign hlp_mac_rx_throttle_0_stop = 'b0;
assign hlp_mac_rx_throttle_1_stop = 'b0;
assign hlp_mac_rx_throttle_2_stop = 'b0;
assign hlp_mac_rx_throttle_3_stop = 'b0;
assign physs_registers_wrapper_1_reset_sd_tx_clk_override_800G_0 = 'b0;
assign physs_registers_wrapper_1_reset_sd_rx_clk_override_800G_0 = 'b0;
assign mac100_0_magic_ind_0 = 'b0;
assign mac100_1_magic_ind_0 = 'b0;
assign mac100_2_magic_ind_0 = 'b0;
assign mac100_3_magic_ind_0 = 'b0;
assign mac100_4_magic_ind_0 = 'b0;
assign mac100_5_magic_ind_0 = 'b0;
assign mac100_6_magic_ind_0 = 'b0;
assign mac100_7_magic_ind_0 = 'b0;
assign mac100_0_pause_on_0 = 'b0;
assign mac100_1_pause_on_0 = 'b0;
assign mac100_2_pause_on_0 = 'b0;
assign mac100_3_pause_on_0 = 'b0;
assign mac100_4_pause_on_0 = 'b0;
assign mac100_5_pause_on_0 = 'b0;
assign mac100_6_pause_on_0 = 'b0;
assign mac100_7_pause_on_0 = 'b0;
assign fifo_top_mux_0_physs_mse_800g_en_0 = 'b0;
assign physs_uart_demux_out2 = 'b0;
assign physs_uart_demux_out3 = 'b0;
assign physs_uart_mux_out = 'b0;
assign versa_xmp_0_o_rst_ucss_srds_pcs_rx_reset_pma0_l0_b_a_0 = 'b0;
assign versa_xmp_0_o_rst_ucss_srds_pcs_rx_reset_pma1_l0_b_a_0 = 'b0;
assign versa_xmp_0_o_rst_ucss_srds_pcs_rx_reset_pma2_l0_b_a_0 = 'b0;
assign versa_xmp_0_o_rst_ucss_srds_pcs_rx_reset_pma3_l0_b_a_0 = 'b0;
assign versa_xmp_1_o_rst_ucss_srds_pcs_rx_reset_pma0_l0_b_a_0 = 'b0;
assign versa_xmp_1_o_rst_ucss_srds_pcs_rx_reset_pma1_l0_b_a_0 = 'b0;
assign versa_xmp_1_o_rst_ucss_srds_pcs_rx_reset_pma2_l0_b_a_0 = 'b0;
assign versa_xmp_1_o_rst_ucss_srds_pcs_rx_reset_pma3_l0_b_a_0 = 'b0;
assign ethphyss_post_agg_mquad_0_post_pass_agg = 'b0;
assign ethphyss_post_agg_mquad_0_post_complete_agg = 'b0;
assign ethphyss_post_agg_mquad_1_post_pass_agg = 'b0;
assign ethphyss_post_agg_mquad_1_post_complete_agg = 'b0;
assign ethphyss_post_agg_mquad_2_post_pass_agg = 'b0;
assign ethphyss_post_agg_mquad_2_post_complete_agg = 'b0;
assign ethphyss_post_agg_mquad_3_post_pass_agg = 'b0;
assign ethphyss_post_agg_mquad_3_post_complete_agg = 'b0;
assign ethphyss_post_agg_pquad_4_post_pass_agg = 'b0;
assign ethphyss_post_agg_pquad_4_post_complete_agg = 'b0;
assign ethphyss_post_agg_pquad_5_post_pass_agg = 'b0;
assign ethphyss_post_agg_pquad_5_post_complete_agg = 'b0;
assign ethphyss_post_agg_par800g_6_post_pass_agg = 'b0;
assign ethphyss_post_agg_par800g_6_post_complete_agg = 'b0;
assign ethphyss_post_agg_par400g0_7_post_pass_agg = 'b0;
assign ethphyss_post_agg_par400g0_7_post_complete_agg = 'b0;
assign ethphyss_post_agg_par400g0_8_post_pass_agg = 'b0;
assign ethphyss_post_agg_par400g0_8_post_complete_agg = 'b0;
assign ethphyss_post_agg_par400g1_9_post_pass_agg = 'b0;
assign ethphyss_post_agg_par400g1_9_post_complete_agg = 'b0;
assign ethphyss_post_agg_par400g1_10_post_pass_agg = 'b0;
assign ethphyss_post_agg_par400g1_10_post_complete_agg = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_pma0_txdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_pma1_txdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_pma2_txdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_pma3_txdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma0_rx = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma1_rx = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma2_rx = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma3_rx = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_pma0_rxdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_pma1_rxdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_pma2_rxdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_pma3_rxdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma0_cmnplla_postdiv = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma1_cmnplla_postdiv = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma2_cmnplla_postdiv = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_pma3_cmnplla_postdiv = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_slv_pcs1 = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_ucss_mem_dram = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_ucss_mem_iram = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad0_o_ck_ucss_mem_tracemem = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_pma0_txdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_pma1_txdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_pma2_txdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_pma3_txdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma0_rx = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma1_rx = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma2_rx = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma3_rx = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_pma0_rxdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_pma1_rxdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_pma2_rxdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_pma3_rxdat = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma0_cmnplla_postdiv = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma1_cmnplla_postdiv = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma2_cmnplla_postdiv = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_pma3_cmnplla_postdiv = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_slv_pcs1 = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_ucss_mem_dram = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_ucss_mem_iram = 'b0;
assign parmisc_physs0_trig_clock_stop_to_parpquad1_o_ck_ucss_mem_tracemem = 'b0;
assign quadpcs100_0_pcs_desk_buf_rlevel_0 = 'b0;
assign quadpcs100_0_pcs_sd_bit_slip_0 = 'b0;
assign quadpcs100_0_pcs_link_status_tsu_0 = 'b0;
assign quadpcs100_1_pcs_desk_buf_rlevel_0 = 'b0;
assign quadpcs100_1_pcs_sd_bit_slip_0 = 'b0;
assign quadpcs100_1_pcs_link_status_tsu_0 = 'b0;
assign versa_xmp_0_xoa_pma0_dcmon1 = 'b0;
assign versa_xmp_0_xoa_pma0_dcmon2 = 'b0;
assign versa_xmp_0_xoa_pma1_dcmon1 = 'b0;
assign versa_xmp_0_xoa_pma1_dcmon2 = 'b0;
assign versa_xmp_0_xoa_pma2_dcmon1 = 'b0;
assign versa_xmp_0_xoa_pma2_dcmon2 = 'b0;
assign versa_xmp_0_xoa_pma3_dcmon1 = 'b0;
assign versa_xmp_0_xoa_pma3_dcmon2 = 'b0;
assign versa_xmp_1_xoa_pma0_dcmon1 = 'b0;
assign versa_xmp_1_xoa_pma0_dcmon2 = 'b0;
assign versa_xmp_1_xoa_pma1_dcmon1 = 'b0;
assign versa_xmp_1_xoa_pma1_dcmon2 = 'b0;
assign versa_xmp_1_xoa_pma2_dcmon1 = 'b0;
assign versa_xmp_1_xoa_pma2_dcmon2 = 'b0;
assign versa_xmp_1_xoa_pma3_dcmon1 = 'b0;
assign versa_xmp_1_xoa_pma3_dcmon2 = 'b0;
assign interrupts_counter_level_fatal_int_0_out_signal_sync = 'b0;
assign interrupts_counter_level_imc_int_0_out_signal_sync = 'b0;
assign quad_interrupts_0_mac800_int = 'b0;
assign versa_xmp_0_o_ucss_irq_cpi_0_a = 'b0;
assign versa_xmp_1_o_ucss_irq_cpi_0_a = 'b0;
assign versa_xmp_0_o_ucss_irq_cpi_1_a = 'b0;
assign versa_xmp_1_o_ucss_irq_cpi_1_a = 'b0;
assign versa_xmp_0_o_ucss_irq_cpi_2_a = 'b0;
assign versa_xmp_1_o_ucss_irq_cpi_2_a = 'b0;
assign versa_xmp_0_o_ucss_irq_cpi_3_a = 'b0;
assign versa_xmp_1_o_ucss_irq_cpi_3_a = 'b0;
assign versa_xmp_0_o_ucss_irq_cpi_4_a = 'b0;
assign versa_xmp_1_o_ucss_irq_cpi_4_a = 'b0;
assign versa_xmp_0_o_ucss_irq_to_soc_l0_a = 'b0;
assign versa_xmp_0_o_ucss_irq_to_soc_l1_a = 'b0;
assign versa_xmp_0_o_ucss_irq_to_soc_l2_a = 'b0;
assign versa_xmp_0_o_ucss_irq_to_soc_l3_a = 'b0;
assign versa_xmp_1_o_ucss_irq_to_soc_l0_a = 'b0;
assign versa_xmp_1_o_ucss_irq_to_soc_l1_a = 'b0;
assign versa_xmp_1_o_ucss_irq_to_soc_l2_a = 'b0;
assign versa_xmp_1_o_ucss_irq_to_soc_l3_a = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac0_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu0_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu0_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu0_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac1_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu1_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu1_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu1_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac2_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu2_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu2_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu2_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac3_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu3_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu3_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_tsu3_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac0_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac0_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac0_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac0_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac1_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac1_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac1_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac1_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac2_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac2_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac2_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac2_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac3_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac3_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac3_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad0_mac3_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs0_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs0_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs1_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs1_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs2_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs2_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs3_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs3_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs0_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs0_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs1_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs1_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs2_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs2_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs3_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_nss_pcs3_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac0_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu0_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu0_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu0_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac1_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu1_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu1_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu1_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac2_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu2_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu2_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu2_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac3_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu3_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu3_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_tsu3_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac0_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac0_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac0_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac0_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac1_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac1_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac1_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac1_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac2_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac2_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac2_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac2_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac3_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac3_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac3_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_mquad1_mac3_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac0_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs0_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs0_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu0_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu0_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu0_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac1_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs1_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs1_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu1_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu1_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu1_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac2_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs2_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs2_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu2_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu2_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu2_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac3_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs3_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs3_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu3_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu3_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_tsu3_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac0_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac0_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac0_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac0_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs0_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs0_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac1_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac1_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac1_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac1_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs1_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs1_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac2_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac2_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac2_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac2_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs2_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs2_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac3_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac3_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac3_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_mac3_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs3_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad0_1_pcs3_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac0_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs0_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs0_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu0_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu0_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu0_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac1_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs1_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs1_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu1_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu1_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu1_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac2_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs2_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs2_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu2_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu2_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu2_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac3_xlgmii_rxt0_next = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs3_xlgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs3_xlgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu3_xlgmii_rx_sd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu3_xlgmii_rx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_tsu3_xlgmii_tx_tsu = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac0_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac0_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac0_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac0_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs0_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs0_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac1_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac1_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac1_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac1_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs1_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs1_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac2_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac2_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac2_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac2_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs2_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs2_cgmii_tx_txd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac3_cgmii_tx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac3_cgmii_rx_clkena = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac3_cgmii_rx_rxc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_mac3_cgmii_rx_rxd = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs3_cgmii_tx_txc = 'b0;
assign pcs_mac_pipeline_top_wrap_pquad1_1_pcs3_cgmii_tx_txd = 'b0;
assign quad_interrupts_0_mac400_int = 'b0;
assign quad_interrupts_1_mac400_int = 'b0;
assign nic400_physs_0_awready_slave_physs = 'b0;
assign nic400_physs_0_wready_slave_physs = 'b0;
assign nic400_physs_0_bid_slave_physs = 'b0;
assign nic400_physs_0_bresp_slave_physs = 'b0;
assign nic400_physs_0_bvalid_slave_physs = 'b0;
assign nic400_physs_0_arready_slave_physs = 'b0;
assign nic400_physs_0_rid_slave_physs = 'b0;
assign nic400_physs_0_rdata_slave_physs = 'b0;
assign nic400_physs_0_rresp_slave_physs = 'b0;
assign nic400_physs_0_rlast_slave_physs = 'b0;
assign nic400_physs_0_rvalid_slave_physs = 'b0;
assign mac100_0_mdc = 'b0;
assign mac100_0_mdio_out = 'b0;
assign mac100_0_mdio_oen_0 = 'b0;
assign socviewpin_4to1digimux_0_outmux = 'b0;
assign quad_interrupts_0_mac100_int = 'b0;
assign quad_interrupts_1_mac100_int = 'b0;
assign interrupts_counter_level_imc_ts_int_out_signal_sync = 'b0;
assign quad_interrupts_0_ts_int_o = 'b0;
assign quad_interrupts_1_ts_int_o = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_scan_in = 'b0;
assign parmisc_physs0_BSCAN_PIPE_IN_FROM_parmisc_physs1_scan_final_out = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_force_disable = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_select_jtag_input = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_select_jtag_output = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_ac_init_clock0 = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_ac_init_clock1 = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_ac_signal = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_ac_mode_en = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_intel_update_clk = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_intel_clamp_en = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_intel_bscan_mode = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_select = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_bscan_clock = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_capture_en = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_shift_en = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_TO_parmisc_physs1_update_en = 'b0;
assign parmisc_physs0_BSCAN_PIPE_OUT_2_bscan_to_intel_d6actestsig_b = 'b0;
assign parmisc_physs0_NW_IN_tdo_en = 'b0;
assign parmisc_physs0_NW_IN_tdo = 'b0;
assign parmisc_physs0_NW_IN_ijtag_so = 'b0;
assign parmisc_physs0_NW_IN_tap_sel_out = 'b0;
assign parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_reset = 'b0;
assign parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_ce = 'b0;
assign parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_se = 'b0;
assign parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_ue = 'b0;
assign parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_sel = 'b0;
assign parmisc_physs0_NW_OUT_parmisc_physs1_ijtag_to_si = 'b0;

endmodule
