// fpt_misc_sa_mm_nw_merlin_apb_translator_0.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module fpt_misc_sa_mm_nw_merlin_apb_translator_0 #(
		parameter ADDR_WIDTH     = 13,
		parameter DATA_WIDTH     = 32,
		parameter USE_S0_PADDR31 = 0,
		parameter USE_M0_PADDR31 = 0,
		parameter USE_M0_PSLVERR = 0
	) (
		input  wire [12:0] s0_paddr,   //        s0.paddr
		input  wire        s0_psel,    //          .psel
		input  wire        s0_penable, //          .penable
		input  wire        s0_pwrite,  //          .pwrite
		input  wire [31:0] s0_pwdata,  //          .pwdata
		output wire [31:0] s0_prdata,  //          .prdata
		output wire        s0_pslverr, //          .pslverr
		output wire        s0_pready,  //          .pready
		input  wire        clk,        //       clk.clk
		input  wire        reset,      // clk_reset.reset
		output wire [12:0] m0_paddr,   //        m0.paddr
		output wire        m0_psel,    //          .psel
		output wire        m0_penable, //          .penable
		output wire        m0_pwrite,  //          .pwrite
		output wire [31:0] m0_pwdata,  //          .pwdata
		input  wire [31:0] m0_prdata,  //          .prdata
		input  wire        m0_pready   //          .pready
	);

	fpt_misc_sa_mm_nw_merlin_apb_translator_0_altera_merlin_apb_translator_1920_wdrqxna #(
		.ADDR_WIDTH     (ADDR_WIDTH),
		.DATA_WIDTH     (DATA_WIDTH),
		.USE_S0_PADDR31 (USE_S0_PADDR31),
		.USE_M0_PADDR31 (USE_M0_PADDR31),
		.USE_M0_PSLVERR (USE_M0_PSLVERR)
	) merlin_apb_translator_0 (
		.s0_paddr   (s0_paddr),   //   input,  width = 13,        s0.paddr
		.s0_psel    (s0_psel),    //   input,   width = 1,          .psel
		.s0_penable (s0_penable), //   input,   width = 1,          .penable
		.s0_pwrite  (s0_pwrite),  //   input,   width = 1,          .pwrite
		.s0_pwdata  (s0_pwdata),  //   input,  width = 32,          .pwdata
		.s0_prdata  (s0_prdata),  //  output,  width = 32,          .prdata
		.s0_pslverr (s0_pslverr), //  output,   width = 1,          .pslverr
		.s0_pready  (s0_pready),  //  output,   width = 1,          .pready
		.clk        (clk),        //   input,   width = 1,       clk.clk
		.reset      (reset),      //   input,   width = 1, clk_reset.reset
		.m0_paddr   (m0_paddr),   //  output,  width = 13,        m0.paddr
		.m0_psel    (m0_psel),    //  output,   width = 1,          .psel
		.m0_penable (m0_penable), //  output,   width = 1,          .penable
		.m0_pwrite  (m0_pwrite),  //  output,   width = 1,          .pwrite
		.m0_pwdata  (m0_pwdata),  //  output,  width = 32,          .pwdata
		.m0_prdata  (m0_prdata),  //   input,  width = 32,          .prdata
		.m0_pready  (m0_pready),  //   input,   width = 1,          .pready
		.s0_paddr31 (1'b0),       // (terminated),                        
		.m0_pslverr (1'b0),       // (terminated),                        
		.m0_paddr31 ()            // (terminated),                        
	);

endmodule
