// mdio_ethernet_ip.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module mdio_ethernet_ip #(
		parameter MDC_DIVISOR = 32
	) (
		input  wire        clk,             //       clock.clk
		input  wire        reset,           // clock_reset.reset
		input  wire        csr_write,       //         csr.write
		input  wire        csr_read,        //            .read
		input  wire [5:0]  csr_address,     //            .address
		input  wire [31:0] csr_writedata,   //            .writedata
		output wire [31:0] csr_readdata,    //            .readdata
		output wire        csr_waitrequest, //            .waitrequest
		output wire        mdc,             //        mdio.mdc
		input  wire        mdio_in,         //            .mdio_in
		output wire        mdio_out,        //            .mdio_out
		output wire        mdio_oen         //            .mdio_oen
	);

	altera_eth_mdio #(
		.MDC_DIVISOR (MDC_DIVISOR)
	) eth_mdio_0 (
		.clk             (clk),             //   input,   width = 1,       clock.clk
		.reset           (reset),           //   input,   width = 1, clock_reset.reset
		.csr_write       (csr_write),       //   input,   width = 1,         csr.write
		.csr_read        (csr_read),        //   input,   width = 1,            .read
		.csr_address     (csr_address),     //   input,   width = 6,            .address
		.csr_writedata   (csr_writedata),   //   input,  width = 32,            .writedata
		.csr_readdata    (csr_readdata),    //  output,  width = 32,            .readdata
		.csr_waitrequest (csr_waitrequest), //  output,   width = 1,            .waitrequest
		.mdc             (mdc),             //  output,   width = 1,        mdio.mdc
		.mdio_in         (mdio_in),         //   input,   width = 1,            .mdio_in
		.mdio_out        (mdio_out),        //  output,   width = 1,            .mdio_out
		.mdio_oen        (mdio_oen)         //  output,   width = 1,            .mdio_oen
	);

endmodule
