set_default_station_parameters -width 512 -depth 1024 -pipeline 4
add_station -name "mki" -clock {"uhfi_100mhz_clk"} -width 512
add_probe -station "mki" {"mki_wrapper.sys_rst_n"}
add_probe -station "mki" {"mki_wrapper.rst"}
add_probe -station "mki" {"mki_wrapper.count"}
add_probe -station "mki" {"mki_wrapper.flag"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_seq_fsm_inst.seq_fsm_cs"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_seq_fsm_inst.seq_fsm_ns"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_seq_fsm_inst.current_cmd_idx"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.rsc_clk_pdop_parrst.u_mci_ctech_pdop.u_ctech_lib_clk_pdop.nen"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.rsc_clk_pdop_parrst.u_mci_ctech_pdop.u_ctech_lib_clk_pdop.clken"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.rsc_clk_pdop_parrst.u_mci_ctech_pdop.u_ctech_lib_clk_pdop.clkbuf"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.rsc_clk_pdop_parrst.u_mci_ctech_pdop.u_ctech_lib_clk_pdop.clkin"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_treg_new.HWRS_WAIT_PINS_PHASE_3_1.xtal_clk_valid"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_treg_new.HWRS_WAIT_PINS_PHASE_3_1.rclk_pad_valid"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_treg_new.HWRS_WAIT_PINS_PHASE_3_1.cro_clk_valid"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_treg_new.HWRS_WAIT_PINS_PHASE_3_1.fuse_sense_done"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_treg_new.HWRS_WAIT_PINS_PHASE_3_1.dfxagg_early_boot_done"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_treg_new.HWRS_WAIT_PINS_PHASE_3_1.vnn_early_boot_done"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_treg_new.HWRS_WAIT_PINS_PHASE_3_1.s0_powergood"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.hwrs_treg_new.HWRS_WAIT_PINS_PHASE_3_1.s5_early_boot_done"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.dfx_agg.i_dfxagg_core.i_dfxagg_glue_logic.dfxagg_vad_en_fuse"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parfuse.fuse_top.i_chassis_fuse_controller_top.i_fuse_array_cntrl.i_fuse_sense_fsm.bypass_pwron_sense"}
add_probe -station "mki" {"mki_wrapper.mki.YY_S0_PWRGOOD"}
add_probe -station "mki" {"mki_wrapper.mki.YY_S0_RESET_N"}
add_probe -station "mki" {"mki_wrapper.mki.xtal_valid"}
add_probe -station "mki" {"mki_wrapper.mki.YY_TDI"}
#add_probe -station "mki" {"mki_wrapper.mki.YY_TCK"}
add_probe -station "mki" {"mki_wrapper.mki.YY_TMS"}
add_probe -station "mki" {"mki_wrapper.mki.YY_S5_RESET_N"}
add_probe -station "mki" {"mki_wrapper.mki.YY_S5_POWERGOOD"}
add_probe -station "mki" {"mki_wrapper.mki.YY_S0_CHIPLET"}
add_probe -station "mki" {"mki_wrapper.mki.YY_S5_CHIPLET"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.cic_inf_boot_ack"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.spa_passed"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.cic_secure_done"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.sbb_wrap_inst.u_sbb.efuse_rdy_i"}
add_probe -station "mki" {"mki_wrapper.mki.ucie_cxl0.cxl_misc.isa_cxl.adapt_isa_clk_halt_b"}
add_probe -station "mki" {"mki_wrapper.mki.ucie_cxl0.ucie_misc.isa_ucie.adapt_isa_clk_halt_b"}
add_probe -station "mki" {"mki_wrapper.mki.ucie_cxl0.cxl_misc.rstw_cxl.ip_ready"}
add_probe -station "mki" {"mki_wrapper.mki.ucie_cxl0.ucie_misc.rstw_ucie_sb.fuse_rstw_ip_cfg_done"}
add_probe -station "mki" {"mki_wrapper.mki.ucie_cxl0.cxl_misc.rstw_cxl.fuse_rstw_prerst_cfg_done"}
add_probe -station "mki" {"mki_wrapper.mki.ucie_cxl0.ucie_misc.rstw_ucie_mb.fuse_rstw_prerst_cfg_done"}
add_probe -station "mki" {"mki_wrapper.mki.ucie_cxl0.ucie_misc.rstw_ucie_pll_0.fuse_rstw_ip_cfg_done"}
add_probe -station "mki" {"mki_wrapper.mki.ucie_cxl0.ucie_misc.rstw_ucie_pll_1.fuse_rstw_ip_cfg_done"}
add_probe -station "mki" {"mki_wrapper.mki.ucie_cxl0.ucie_misc.rstw_ucie_sb_bridge.fuse_rstw_prerst_cfg_done"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.cisbr_glb0.p5_pok"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.cisbr_glb0.p3_pok"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.cisbr_glb0.p0_pok"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.mci_cmn_reset_widget_error"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.hwrs_ucie_sb_ip_ready"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.pargpio.mci_cmnio_top.a0_debug_zi"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.hwrs_cmlb_pll_en_dig"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.dfx_agg_dfxagg_early_boot_done"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.cro_clk_en"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.cro_clk_valid"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parrst.hwrs.infra_rstbus_rst_b"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.pargpio.bgr1.i_bgr_vinf_pwrgood"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.pargpio.rstw_rsrc_adapt_bgr1.reset_cmd_data"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.pargpio.rstw_rsrc_adapt_cgu_dts.rst_b"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.pargpio.rstw_rsrc_adapt_cgu_dts.reset_cmd_data"}
#add_station -name "cro800_pll" -clock {"cro800_pll"} -width 12
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parcgu.rsc_clk_adop_parcgu.u_mci_ctech_pdop.u_ctech_lib_clk_pdop.nen"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parcgu.rsc_clk_adop_parcgu.u_mci_ctech_pdop.u_ctech_lib_clk_pdop.clkbuf"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parcgu.rsc_clk_adop_parcgu.u_mci_ctech_pdop.u_ctech_lib_clk_pdop.clken"}
add_probe -station "mki" {"mki_wrapper.mki.mki_uncore_misc.mci_cmn.parcgu.rsc_clk_adop_parcgu.u_mci_ctech_pdop.u_ctech_lib_clk_pdop.clkin"}
