// ddr_emif_usr_clk_0.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module ddr_emif_usr_clk_0 (
		input  wire  in_clk,  //  in_clk.clk
		output wire  out_clk  // out_clk.clk
	);

	assign out_clk = in_clk;

endmodule
