//=================================================================================================================================
// CXL_CACHE_V3_HOST connections - USER MUST EDIT THE RIGHT HAND SIDE OF THE FOLLOWING ASSIGNMENTS AND DEFINE - WHEN NEEDED
//=================================================================================================================================
// CXL_CACHE_V3_HOST   connection #0

			`define 	CXL_CACHE_DEVICE_0 					`FPGA_TRANSACTORS_TOP       // example:  fpga_tcss_top.tcss_val_rtl.tcss.par_iom

assign 		`TRANSACTORS_PATH.cxl_cache_v3_host_clk[0] 				     = `CXL_CACHE_DEVICE_0.cxl_cache_v3_device_clock_0; 
assign 		`TRANSACTORS_PATH.cxl_cache_v3_host_rstn[0] 			     = `CXL_CACHE_DEVICE_0.cxl_cache_v3_device_rstn_0; 
                                                                                      
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_REQ_VALID[0]           = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_REQ_VALID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_REQ_OPCODE[0]          = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_REQ_OPCODE;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_REQ_ADDRESS[0]         = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_REQ_ADDRESS;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_REQ_CQID[0]            = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_REQ_CQID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_REQ_RSVD[0]            = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_REQ_RSVD;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_REQ_ADDRPARITY[0]      = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_REQ_ADDRPARITY;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_REQ_CACHEID[0]         = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_REQ_CACHEID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_REQ_PORTID[0]          = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_REQ_PORTID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_REQ_NONTEMPORAL[0]     = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_REQ_NONTEMPORAL;

assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_VALID[0]          = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_VALID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_UQID[0]           = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_UQID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_BOGUS[0]          = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_BOGUS;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_POISON[0]         = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_POISON;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_DATA[0]           = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_DATA;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_DATAPARITY[0]     = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_DATAPARITY;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_BYTEEN[0]         = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_BYTEEN;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_PORTID[0]         = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_PORTID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_RSVD[0]           = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_RSVD;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_DATA_BEPARITY[0]       = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_DATA_BEPARITY;

assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_RSP_VALID[0]           = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_RSP_VALID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_RSP_OPCODE[0]          = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_RSP_OPCODE;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_RSP_UQID[0]            = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_RSP_UQID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_RSP_PORTID[0]          = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_RSP_PORTID;
assign `TRANSACTORS_PATH.CXL_CACHE_V3_D2H_RSP_RSVD[0]            = `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_D2H_RSP_RSVD;

//=================================================================================================================================
// CXL_CACHE_HOST connections - USER MUST EDIT THE LEFT HAND SIDE OF THE FOLLOWING ASSIGNMENTS 
//=================================================================================================================================
// Connect H2D (Host to Device) interface from Host to Device
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_REQ_VALID              = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_REQ_VALID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_REQ_OPCODE             = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_REQ_OPCODE[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_REQ_ADDRESS            = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_REQ_ADDRESS[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_REQ_UQID               = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_REQ_UQID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_REQ_ADDRPARITY         = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_REQ_ADDRPARITY[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_REQ_CACHEID            = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_REQ_CACHEID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_REQ_PORTID             = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_REQ_PORTID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_REQ_RSVD               = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_REQ_RSVD[0];

assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_DATA_VALID             = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_DATA_VALID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_DATA_CQID              = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_DATA_CQID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_DATA_GO_ERR            = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_DATA_GO_ERR[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_DATA_POISON            = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_DATA_POISON[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_DATA_DATA              = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_DATA_DATA[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_DATA_DATAPARITY        = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_DATA_DATAPARITY[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_DATA_PORTID            = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_DATA_PORTID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_DATA_RSVD              = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_DATA_RSVD[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_DATA_CACHEID           = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_DATA_CACHEID[0];

assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_RSP_VALID              = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_RSP_VALID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_RSP_OPCODE             = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_RSP_OPCODE[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_RSP_DATA               = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_RSP_DATA[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_RSP_PRE                = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_RSP_PRE[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_RSP_CQID               = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_RSP_CQID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_RSP_RSVD               = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_RSP_RSVD[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_RSP_CACHEID            = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_RSP_CACHEID[0];
assign `CXL_CACHE_DEVICE_0.cxl_CACHE_V3_H2D_RSP_PORTID             = `TRANSACTORS_PATH.CXL_CACHE_V3_H2D_RSP_PORTID[0];

// Note: Credit flow wires need to be connected appropriately based on the credit management scheme


// Additional connections for AXI-MM interface, FIFOs, etc., should be made here following the same pattern

