/*------------------------------------------------------------------------------
  INTEL CONFIDENTIAL
  Copyright 2022 Intel Corporation All Rights Reserved.
  -----------------------------------------------------------------------------*/

module parhlpport4
// EDIT_PORT BEGIN
 ( 
input clk,
input [1:0] i_tsu_sync_val,
input [6:0] fary_ffuse_hd2prf_trim,
input [9:0] fary_ffuse_rfhs2r2w_trim,
input [16:0] fary_ffuse_hdusplr_trim,
input [16:0] fary_ffuse_hduspsr_trim,
input i_force_clk_en,
input [2:0] i_id,
input [1:0] i_mac_limit,
input i_port4_disable,
input i_switch_ready,
input mem_rst_n,
input powergood_rst_n,
input rst_n,
input swclk_mem_rst_n,
input switch_clk,
input switch_rst_n,
input pd_vinf_bisr_si,
input pd_vinf_bisr_reset,
input pd_vinf_bisr_clk,
input pd_vinf_bisr_shift_en,
output pd_vinf_bisr_so,
output pd_vinf_bisr_clk_out,
output pd_vinf_bisr_reset_out,
output pd_vinf_bisr_shift_en_out,
input JT_IN_mbist_ijtag_reset_b,
input JT_IN_mbist_ijtag_tck,
input JT_IN_mbist_ijtag_select,
input JT_IN_mbist_ijtag_capture,
input JT_IN_mbist_ijtag_shift,
input JT_IN_mbist_ijtag_update,
input JT_IN_mbist_ijtag_si,
input JT_IN_scan_ijtag_reset_b,
input JT_IN_scan_ijtag_tck,
input JT_IN_scan_ijtag_select,
input JT_IN_scan_ijtag_capture,
input JT_IN_scan_ijtag_shift,
input JT_IN_scan_ijtag_update,
input JT_IN_scan_ijtag_si,
output JT_OUT_mbist_ijtag_so,
output JT_OUT_scan_ijtag_so,
input fdfx_powergood,
input secure_group_a,
input secure_group_b,
input secure_group_c,
input secure_group_d,
input secure_group_e,
input secure_group_g,
input secure_group_h,
input secure_group_f,
input secure_group_z,
output DIAG_AGGR_mbist_diag_done_0,
output DIAG_AGGR_mbist_diag_done_1,
output DIAG_AGGR_mbist_diag_done_2,
output DIAG_AGGR_mbist_diag_done_3,
input SSN_START_0_bus_clock_in,
input [31:0] SSN_START_0_bus_data_in,
output [31:0] SSN_END_0_bus_data_out,
input fary_post_pass_rf,
input fary_post_pass_sram,
input fary_trigger_post_rf,
input fary_trigger_post_sram,
input fvisa_rddata_msec_0,
input fvisa_rddata_msec_1,
input fvisa_rddata_msec_2,
input fvisa_rddata_msec_3,
input fvisa_rddata_port4,
input [8:0] fvisa_unit_id,
input i_msec0_disable,
input i_msec1_disable,
input i_msec2_disable,
input i_msec3_disable,
input [0:0] i_msec_mac_rx_e_0,
input [0:0] i_msec_mac_rx_e_1,
input [0:0] i_msec_mac_rx_e_2,
input [0:0] i_msec_mac_rx_e_3,
input [0:0] i_msec_switch_tx_e_0,
input [0:0] i_msec_switch_tx_e_1,
input [0:0] i_msec_switch_tx_e_2,
input [0:0] i_msec_switch_tx_e_3,
input [37:0] i_pause_ripple,
input [37:0] i_pause_ripple_ret,
input i_pause_ripple_ret_v,
input i_pause_ripple_v,
input [4:0] i_port1_id_0,
input [4:0] i_port1_id_1,
input [4:0] i_port1_id_2,
input [4:0] i_port1_id_3,
input [0:0] i_rpl_bkwd,
input [130:0] i_rpl_frwd,
input [4:0] i_rx_grant,
input i_rx_grant_v,
input [31:0] i_rx_req,
input [2084:0] i_rx_ripple,
input i_rx_ripple_v,
input [7:0] i_time_scale_pulse,
input [63:0] i_tx_cred,
input [2857:0] i_tx_ripple,
input i_tx_ripple_v,
output aary_post_complete_rf,
output aary_post_complete_sram,
output aary_post_pass_rf,
output aary_post_pass_sram,
output avisa_rddata,
output [8:0] avisa_unit_id_p1,
output [8:0] avisa_unit_id_p3,
output [8:0] avisa_unit_id_p5,
output [0:0] o_msec_mac_tx_e_0,
output [0:0] o_msec_mac_tx_e_1,
output [0:0] o_msec_mac_tx_e_2,
output [0:0] o_msec_mac_tx_e_3,
output [0:0] o_msec_switch_rx_e_0,
output [0:0] o_msec_switch_rx_e_1,
output [0:0] o_msec_switch_rx_e_2,
output [0:0] o_msec_switch_rx_e_3,
output [37:0] o_pause_ripple,
output [37:0] o_pause_ripple_ret,
output o_pause_ripple_ret_v,
output o_pause_ripple_v,
output [0:0] o_rpl_bkwd,
output [130:0] o_rpl_frwd,
output [4:0] o_rx_grant,
output o_rx_grant_v,
output [31:0] o_rx_req,
output [2084:0] o_rx_ripple,
output o_rx_ripple_v,
output [7:0] o_time_scale_pulse,
output [63:0] o_tx_cred,
output [2857:0] o_tx_ripple,
output o_tx_ripple_v,
input [0:0][207:0] i_msec_mac_tx_0,
input [0:0][207:0] i_msec_mac_tx_1,
input [0:0][207:0] i_msec_mac_tx_2,
input [0:0][207:0] i_msec_mac_tx_3,
input [0:0] i_msec_mac_tx_v_0,
input [0:0] i_msec_mac_tx_v_1,
input [0:0] i_msec_mac_tx_v_2,
input [0:0] i_msec_mac_tx_v_3,
input [0:0][231:0] i_msec_switch_rx_0,
input [0:0][231:0] i_msec_switch_rx_1,
input [0:0][231:0] i_msec_switch_rx_2,
input [0:0][231:0] i_msec_switch_rx_3,
input [0:0] i_msec_switch_rx_v_0,
input [0:0] i_msec_switch_rx_v_1,
input [0:0] i_msec_switch_rx_v_2,
input [0:0] i_msec_switch_rx_v_3,
input [221:0] mii_rx_0,
input [221:0] mii_rx_1,
input [221:0] mii_rx_2,
input [221:0] mii_rx_3,
input [21:0] mii_tsu_in_0,
input [21:0] mii_tsu_in_1,
input [21:0] mii_tsu_in_2,
input [21:0] mii_tsu_in_3,
output o_rx_throttle_0,
output o_rx_throttle_1,
output o_rx_throttle_2,
output o_rx_throttle_3,
input i_tx_stop_0,
input i_tx_stop_1,
input i_tx_stop_2,
input i_tx_stop_3,
output [0:0][208:0] o_msec_mac_rx_0,
output [0:0][208:0] o_msec_mac_rx_1,
output [0:0][208:0] o_msec_mac_rx_2,
output [0:0][208:0] o_msec_mac_rx_3,
output [0:0] o_msec_mac_rx_v_0,
output [0:0] o_msec_mac_rx_v_1,
output [0:0] o_msec_mac_rx_v_2,
output [0:0] o_msec_mac_rx_v_3,
output [0:0][217:0] o_msec_switch_tx_0,
output [0:0][217:0] o_msec_switch_tx_1,
output [0:0][217:0] o_msec_switch_tx_2,
output [0:0][217:0] o_msec_switch_tx_3,
output [0:0] o_msec_switch_tx_v_0,
output [0:0] o_msec_switch_tx_v_1,
output [0:0] o_msec_switch_tx_v_2,
output [0:0] o_msec_switch_tx_v_3,
output [215:0] mii_tx_0,
output [215:0] mii_tx_1,
output [215:0] mii_tx_2,
output [215:0] mii_tx_3,
input [1279:0] i_ports_cfg );
// EDIT_PORT END


// EDIT_NET BEGIN
logic [8:0] port4_apr_0_0_avisa_unit_id_p2 ; 
logic port4_apr_0_0_avisa_all_dis ; 
logic [3:0] port4_apr_0_0_avisa_clk ; 
logic [3:0] port4_apr_0_1_avisa_clk ; 
logic [3:0] port4_apr_0_2_avisa_clk ; 
logic port4_apr_0_0_avisa_customer_dis ; 
logic [31:0] port4_apr_0_0_avisa_dbg_lane ; 
logic [31:0] port4_apr_0_1_avisa_dbg_lane ; 
logic [31:0] port4_apr_0_2_avisa_dbg_lane ; 
logic port4_apr_0_0_avisa_frame ; 
logic port4_apr_0_0_avisa_rddata ; 
logic port4_apr_0_1_avisa_rddata ; 
logic port4_apr_0_2_avisa_rddata ; 
logic port4_apr_0_0_avisa_serdata ; 
logic port4_apr_0_0_avisa_serstb ; 
logic [0:0][21:0] port4_apr_0_0_o_cfg_tx_jitter ; 
logic [0:0][21:0] port4_apr_0_1_o_cfg_tx_jitter ; 
logic [0:0][21:0] port4_apr_0_2_o_cfg_tx_jitter ; 
logic [0:0][21:0] port4_apr_0_3_o_cfg_tx_jitter ; 
logic [11:0] port4_apr_0_0_o_cfg_txram_port_bound ; 
logic [11:0] port4_apr_0_1_o_cfg_txram_port_bound ; 
logic [11:0] port4_apr_0_2_o_cfg_txram_port_bound ; 
logic [11:0] port4_apr_0_3_o_cfg_txram_port_bound ; 
logic [5:0] port4_apr_0_0_o_iarb_token_rate ; 
logic [2084:0] port4_apr_0_0_o_obuf_data ; 
logic [2084:0] port4_apr_0_1_o_obuf_data ; 
logic [2084:0] port4_apr_0_2_o_obuf_data ; 
logic [2084:0] port4_apr_0_3_o_obuf_data ; 
logic port4_apr_0_0_o_p0_mode ; 
logic [0:0] port4_apr_0_0_o_port_en ; 
logic [0:0] port4_apr_0_1_o_port_en ; 
logic [0:0] port4_apr_0_2_o_port_en ; 
logic [0:0] port4_apr_0_3_o_port_en ; 
logic [0:0] port4_apr_0_0_o_rpl_bkwd ; 
logic [0:0] port4_apr_0_1_o_rpl_bkwd ; 
logic [0:0] port4_apr_0_2_o_rpl_bkwd ; 
logic port4_apr_0_0_o_rx_grant_fifo_afull ; 
logic port4_apr_0_1_o_rx_grant_fifo_afull ; 
logic port4_apr_0_2_o_rx_grant_fifo_afull ; 
logic port4_apr_0_3_o_rx_grant_fifo_afull ; 
logic [0:0][1:0] port4_apr_0_0_o_rx_q_xoff ; 
logic [0:0][1:0] port4_apr_0_1_o_rx_q_xoff ; 
logic [0:0][1:0] port4_apr_0_2_o_rx_q_xoff ; 
logic [0:0][1:0] port4_apr_0_3_o_rx_q_xoff ; 
logic [0:0][3:0] port4_apr_0_0_o_rx_tap_port_cfg ; 
logic [0:0][3:0] port4_apr_0_1_o_rx_tap_port_cfg ; 
logic [0:0][3:0] port4_apr_0_2_o_rx_tap_port_cfg ; 
logic [0:0][3:0] port4_apr_0_3_o_rx_tap_port_cfg ; 
logic [0:0][2:0] port4_apr_0_0_o_seg_valid ; 
logic [0:0][2:0] port4_apr_0_1_o_seg_valid ; 
logic [0:0][2:0] port4_apr_0_2_o_seg_valid ; 
logic [0:0][2:0] port4_apr_0_3_o_seg_valid ; 
logic [0:0][7:0] port4_apr_0_0_o_switch_rx_pc_xoff ; 
logic [0:0][7:0] port4_apr_0_1_o_switch_rx_pc_xoff ; 
logic [0:0][7:0] port4_apr_0_2_o_switch_rx_pc_xoff ; 
logic [0:0][7:0] port4_apr_0_3_o_switch_rx_pc_xoff ; 
logic [7:0] port4_apr_0_0_o_time_scale_pulse ; 
logic [7:0] port4_apr_0_1_o_time_scale_pulse ; 
logic [7:0] port4_apr_0_2_o_time_scale_pulse ; 
logic [0:0][1:0] port4_apr_0_0_o_txram_credit ; 
logic [0:0][1:0] port4_apr_0_1_o_txram_credit ; 
logic [0:0][1:0] port4_apr_0_2_o_txram_credit ; 
logic [0:0][1:0] port4_apr_0_3_o_txram_credit ; 
logic [8:0] port4_apr_0_1_avisa_unit_id_p2 ; 
logic [8:0] port4_apr_0_2_avisa_unit_id_p2 ; 
logic [8:0] port4_apr_0_3_avisa_unit_id_p2 ; 
logic port4_apr_0_1_aary_post_complete_rf ; 
logic port4_apr_0_1_aary_post_complete_sram ; 
logic port4_apr_0_1_aary_post_pass_rf ; 
logic port4_apr_0_1_aary_post_pass_sram ; 
logic port4_apr_0_2_aary_post_complete_rf ; 
logic port4_apr_0_2_aary_post_complete_sram ; 
logic port4_apr_0_2_aary_post_pass_rf ; 
logic port4_apr_0_2_aary_post_pass_sram ; 
logic port4_apr_0_3_aary_post_complete_rf ; 
logic port4_apr_0_3_aary_post_complete_sram ; 
logic port4_apr_0_3_aary_post_pass_rf ; 
logic port4_apr_0_3_aary_post_pass_sram ; 
logic port4_apr_0_1_avisa_all_dis ; 
logic port4_apr_0_1_avisa_customer_dis ; 
logic port4_apr_0_1_avisa_frame ; 
logic port4_apr_0_1_avisa_serdata ; 
logic port4_apr_0_1_avisa_serstb ; 
logic [130:0] port4_apr_0_1_o_rpl_frwd ; 
logic [130:0] port4_apr_0_2_o_rpl_frwd ; 
logic [130:0] port4_apr_0_3_o_rpl_frwd ; 
logic port4_apr_0_2_avisa_all_dis ; 
logic port4_apr_0_2_avisa_customer_dis ; 
logic port4_apr_0_2_avisa_frame ; 
logic port4_apr_0_2_avisa_serdata ; 
logic port4_apr_0_2_avisa_serstb ; 
logic port4_apr_0_3_avisa_all_dis ; 
logic port4_apr_0_3_avisa_customer_dis ; 
logic port4_apr_0_3_avisa_frame ; 
logic port4_apr_0_3_avisa_serdata ; 
logic port4_apr_0_3_avisa_serstb ; 
logic sia_tap_0_o_rx_grant_fifo_push_0 ; 
logic [0:0] sia_tap_0_o_rx_grant_fifo_push_data_0 ; 
logic sia_tap_0_o_rx_grant_fifo_push_1 ; 
logic [0:0] sia_tap_0_o_rx_grant_fifo_push_data_1 ; 
logic sia_tap_0_o_rx_grant_fifo_push_2 ; 
logic [0:0] sia_tap_0_o_rx_grant_fifo_push_data_2 ; 
logic sia_tap_0_o_rx_grant_fifo_push_3 ; 
logic [0:0] sia_tap_0_o_rx_grant_fifo_push_data_3 ; 
logic [0:0][1:0] sia_tap_0_o_rx_pause_gen_smp_xoff_0 ; 
logic [1:0][0:0] sia_tap_0_o_rx_pause_gen_smp_xoff_1 ; 
logic [1:0][0:0] sia_tap_0_o_rx_pause_gen_smp_xoff_2 ; 
logic [1:0][0:0] sia_tap_0_o_rx_pause_gen_smp_xoff_3 ; 
logic [0:0][7:0][1:0] sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_0 ; 
logic [0:0][7:0][1:0] sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_1 ; 
logic [0:0][7:0][1:0] sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_2 ; 
logic [0:0][7:0][1:0] sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_3 ; 
logic [8:0] sia_tap_0_o_sia_tx_tap_int_0 ; 
logic [8:0] sia_tap_0_o_sia_tx_tap_int_1 ; 
logic [8:0] sia_tap_0_o_sia_tx_tap_int_2 ; 
logic [8:0] sia_tap_0_o_sia_tx_tap_int_3 ; 
logic [1295:0] sia_tap_0_o_txram_win_0 ; 
logic [1295:0] sia_tap_0_o_txram_win_1 ; 
logic [1295:0] sia_tap_0_o_txram_win_2 ; 
logic [1295:0] sia_tap_0_o_txram_win_3 ; 
logic [294:0] sia_tap_0_o_txmetaram_win_0 ; 
logic [294:0] sia_tap_0_o_txmetaram_win_1 ; 
logic [294:0] sia_tap_0_o_txmetaram_win_2 ; 
logic [294:0] sia_tap_0_o_txmetaram_win_3 ; 
logic sia_tap_0_o_tx_switch_ready_0 ; 
logic sia_tap_0_o_tx_switch_ready_1 ; 
logic sia_tap_0_o_tx_switch_ready_2 ; 
logic sia_tap_0_o_tx_switch_ready_3 ; 
logic [0:0] sia_tap_0_o_jitter_cred_tgl_0 ; 
logic [0:0] sia_tap_0_o_jitter_cred_tgl_1 ; 
logic [0:0] sia_tap_0_o_jitter_cred_tgl_2 ; 
logic [0:0] sia_tap_0_o_jitter_cred_tgl_3 ; 
logic [0:0] sia_tap_0_o_txram_wr_tgl_0 ; 
logic [0:0] sia_tap_0_o_txram_wr_tgl_1 ; 
logic [0:0] sia_tap_0_o_txram_wr_tgl_2 ; 
logic [0:0] sia_tap_0_o_txram_wr_tgl_3 ; 
logic port4_0_clk_pdop_parhlpport4_clkout ; 
logic port4_0_switch_clk_pdop_parhlpport4_clkout ; 
// EDIT_NET END

// EDIT_INSTANCE BEGIN
//User inserted instance
hlp_port4_apr #(.MACS(1)) port4_apr_0 (
    .fary_ffuse_hd2prf_trim(fary_ffuse_hd2prf_trim), 
    .fary_ffuse_rfhs2r2w_trim(fary_ffuse_rfhs2r2w_trim), 
    .fary_ffuse_hdusplr_trim(fary_ffuse_hdusplr_trim), 
    .fary_ffuse_hduspsr_trim(fary_ffuse_hduspsr_trim), 
    .i_force_clk_en(i_force_clk_en), 
    .i_id(i_id), 
    .i_mac_limit(i_mac_limit), 
    .i_port4_disable(i_port4_disable), 
    .i_switch_ready(i_switch_ready), 
    .mem_rst_n(mem_rst_n), 
    .powergood_rst_n(powergood_rst_n), 
    .DFT_AFD_RESET_B(powergood_rst_n), 
    .rst_n(rst_n), 
    .swclk_mem_rst_n(swclk_mem_rst_n), 
    .switch_rst_n(switch_rst_n), 
    .i_mac_id(2'h0), 
    .fvisa_rddata_msec(fvisa_rddata_msec_0), 
    .i_msec_disable(i_msec0_disable), 
    .i_msec_mac_rx_e(i_msec_mac_rx_e_0), 
    .i_msec_switch_tx_e(i_msec_switch_tx_e_0), 
    .i_port1_id(i_port1_id_0), 
    .i_rpl_bkwd(i_rpl_bkwd), 
    .i_time_scale_pulse(i_time_scale_pulse), 
    .aary_post_complete_rf(aary_post_complete_rf), 
    .aary_post_complete_sram(aary_post_complete_sram), 
    .aary_post_pass_rf(aary_post_pass_rf), 
    .aary_post_pass_sram(aary_post_pass_sram), 
    .avisa_unit_id_p1(avisa_unit_id_p3), 
    .avisa_unit_id_p3(avisa_unit_id_p5), 
    .o_msec_mac_tx_e(o_msec_mac_tx_e_0), 
    .o_msec_switch_rx_e(o_msec_switch_rx_e_0), 
    .o_rpl_frwd(o_rpl_frwd), 
    .i_msec_mac_tx(i_msec_mac_tx_0), 
    .i_msec_mac_tx_v(i_msec_mac_tx_v_0), 
    .i_msec_switch_rx(i_msec_switch_rx_0), 
    .i_msec_switch_rx_v(i_msec_switch_rx_v_0), 
    .mii_rx(mii_rx_0), 
    .mii_tsu_in(mii_tsu_in_0), 
    .o_rx_throttle(o_rx_throttle_0), 
    .i_tx_stop(i_tx_stop_0), 
    .o_msec_mac_rx(o_msec_mac_rx_0), 
    .o_msec_mac_rx_v(o_msec_mac_rx_v_0), 
    .o_msec_switch_tx(o_msec_switch_tx_0), 
    .o_msec_switch_tx_v(o_msec_switch_tx_v_0), 
    .mii_tx(mii_tx_0), 
    .avisa_unit_id_p2(port4_apr_0_0_avisa_unit_id_p2), 
    .avisa_all_dis(port4_apr_0_0_avisa_all_dis), 
    .avisa_clk(port4_apr_0_0_avisa_clk), 
    .avisa_customer_dis(port4_apr_0_0_avisa_customer_dis), 
    .avisa_dbg_lane(port4_apr_0_0_avisa_dbg_lane), 
    .avisa_frame(port4_apr_0_0_avisa_frame), 
    .avisa_rddata(port4_apr_0_0_avisa_rddata), 
    .avisa_serdata(port4_apr_0_0_avisa_serdata), 
    .avisa_serstb(port4_apr_0_0_avisa_serstb), 
    .o_cfg_tx_jitter(port4_apr_0_0_o_cfg_tx_jitter), 
    .o_cfg_txram_port_bound(port4_apr_0_0_o_cfg_txram_port_bound), 
    .o_iarb_token_rate(port4_apr_0_0_o_iarb_token_rate), 
    .o_obuf_data(port4_apr_0_0_o_obuf_data), 
    .o_p0_mode(port4_apr_0_0_o_p0_mode), 
    .o_port_en(port4_apr_0_0_o_port_en), 
    .o_rpl_bkwd(port4_apr_0_0_o_rpl_bkwd), 
    .o_rx_grant_fifo_afull(port4_apr_0_0_o_rx_grant_fifo_afull), 
    .o_rx_q_xoff(port4_apr_0_0_o_rx_q_xoff), 
    .o_rx_tap_port_cfg(port4_apr_0_0_o_rx_tap_port_cfg), 
    .o_seg_valid(port4_apr_0_0_o_seg_valid), 
    .o_switch_rx_pc_xoff(port4_apr_0_0_o_switch_rx_pc_xoff), 
    .o_time_scale_pulse(port4_apr_0_0_o_time_scale_pulse), 
    .o_txram_credit(port4_apr_0_0_o_txram_credit), 
    .i_tsu_sync_val(i_tsu_sync_val), 
    .i_ports_cfg(i_ports_cfg), 
    .fvisa_unit_id(port4_apr_0_1_avisa_unit_id_p2), 
    .fary_trigger_post_rf(port4_apr_0_1_aary_post_complete_rf), 
    .fary_trigger_post_sram(port4_apr_0_1_aary_post_complete_sram), 
    .fary_post_pass_rf(port4_apr_0_1_aary_post_pass_rf), 
    .fary_post_pass_sram(port4_apr_0_1_aary_post_pass_sram), 
    .fvisa_all_dis(port4_apr_0_1_avisa_all_dis), 
    .fvisa_customer_dis(port4_apr_0_1_avisa_customer_dis), 
    .fvisa_frame(port4_apr_0_1_avisa_frame), 
    .fvisa_serdata(port4_apr_0_1_avisa_serdata), 
    .fvisa_serstb(port4_apr_0_1_avisa_serstb), 
    .i_rpl_frwd(port4_apr_0_1_o_rpl_frwd), 
    .i_rx_grant_fifo_push(sia_tap_0_o_rx_grant_fifo_push_0), 
    .i_rx_grant_fifo_push_data(sia_tap_0_o_rx_grant_fifo_push_data_0), 
    .i_rx_pause_gen_smp_xoff(sia_tap_0_o_rx_pause_gen_smp_xoff_0), 
    .i_rx_pause_gen_pfc_smp_xoff(sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_0), 
    .i_sia_tx_tap_int(sia_tap_0_o_sia_tx_tap_int_0), 
    .i_txram_win(sia_tap_0_o_txram_win_0), 
    .i_txmetaram_win(sia_tap_0_o_txmetaram_win_0), 
    .i_tx_switch_ready(sia_tap_0_o_tx_switch_ready_0), 
    .i_jitter_cred_tgl(sia_tap_0_o_jitter_cred_tgl_0), 
    .i_txram_wr_tgl(sia_tap_0_o_txram_wr_tgl_0), 
    .clk(port4_0_clk_pdop_parhlpport4_clkout), 
    .switch_clk(port4_0_switch_clk_pdop_parhlpport4_clkout), 
    .fet_ack_b(), 
    .fet_en_b(1'b0), 
    .fdfx_jta_force_latch_mem_fuses(1'b0), 
    .clk_rscclk(1'b0), 
    .mbist_diag_done(), 
    .fsta_afd_en(1'b0), 
    .DFTMASK(1'b0), 
    .DFTSHIFTEN(1'b0), 
    .DFT_ARRAY_FREEZE(1'b0), 
    .fary_ffuse_rf_sleep(2'b0), 
    .fary_ffuse_sram_sleep(2'b0), 
    .fary_output_reset(1'b0), 
    .fscan_byprst_b(1'b0), 
    .fscan_clkgenctrl(1'b0), 
    .fscan_clkgenctrlen(1'b0), 
    .fscan_clkungate(1'b0), 
    .fscan_clkungate_syn(1'b0), 
    .fscan_latchclosed_b(1'b0), 
    .fscan_latchopen(1'b0), 
    .fscan_mode(1'b0), 
    .fscan_mode_atspeed(1'b0), 
    .fscan_ram_bypsel_rf(1'b0), 
    .fscan_ram_bypsel_sram(1'b0), 
    .fscan_ram_init_en(1'b0), 
    .fscan_ram_init_val(1'b0), 
    .fscan_ram_rdis_b(1'b0), 
    .fscan_ram_wdis_b(1'b0), 
    .fscan_ret_ctrl(1'b0), 
    .fscan_rstbypen(1'b0), 
    .fscan_sdi(360'b0), 
    .fscan_shiften(1'b0), 
    .fsta_dfxact_afd(1'b0), 
    .fvisa_clk_msec(4'b0), 
    .fvisa_clk_port4(4'b0), 
    .fvisa_dbg_lane_msec(32'b0), 
    .fvisa_dbg_lane_port4(32'b0), 
    .fvisa_rddata_port4(1'b0), 
    .fvisa_resetb(1'b0), 
    .isol_en_b(1'b0), 
    .pwr_mgmt_in_rf(5'b0), 
    .pwr_mgmt_in_sram(6'b0), 
    .ascan_sdo(), 
    .isol_ack_b(), 
    .o_ports_info(), 
    .fary_ijtag_tck(1'b0), 
    .fary_ijtag_rst_b(1'b0), 
    .fary_ijtag_capture(1'b0), 
    .fary_ijtag_shift(1'b0), 
    .fary_ijtag_update(1'b0), 
    .fary_ijtag_select(1'b0), 
    .fary_ijtag_si(1'b0), 
    .aary_ijtag_so(), 
    .bisr_so_pd_vinf(), 
    .bisr_si_pd_vinf(1'b0), 
    .bisr_shift_en_pd_vinf(1'b0), 
    .bisr_clk_pd_vinf(1'b0), 
    .bisr_reset_pd_vinf(1'b0), 
    .fary_trigger_post(1'b0), 
    .aary_post_pass(), 
    .aary_post_busy(), 
    .aary_post_complete(), 
    .fary_post_force_fail(1'b0), 
    .fary_post_algo_select(6'b0), 
    .core_rst_b(1'b0)
) ; 
//User inserted instance
hlp_port4_apr #(.MACS(1)) port4_apr_1 (
    .fary_ffuse_hd2prf_trim(fary_ffuse_hd2prf_trim), 
    .fary_ffuse_rfhs2r2w_trim(fary_ffuse_rfhs2r2w_trim), 
    .fary_ffuse_hdusplr_trim(fary_ffuse_hdusplr_trim), 
    .fary_ffuse_hduspsr_trim(fary_ffuse_hduspsr_trim), 
    .i_force_clk_en(i_force_clk_en), 
    .i_id(i_id), 
    .i_mac_limit(i_mac_limit), 
    .i_port4_disable(i_port4_disable), 
    .i_switch_ready(i_switch_ready), 
    .mem_rst_n(mem_rst_n), 
    .powergood_rst_n(powergood_rst_n), 
    .DFT_AFD_RESET_B(powergood_rst_n), 
    .rst_n(rst_n), 
    .swclk_mem_rst_n(swclk_mem_rst_n), 
    .switch_rst_n(switch_rst_n), 
    .i_mac_id(2'h1), 
    .fvisa_rddata_msec(fvisa_rddata_msec_1), 
    .i_msec_disable(i_msec1_disable), 
    .i_msec_mac_rx_e(i_msec_mac_rx_e_1), 
    .i_msec_switch_tx_e(i_msec_switch_tx_e_1), 
    .i_port1_id(i_port1_id_1), 
    .o_msec_mac_tx_e(o_msec_mac_tx_e_1), 
    .o_msec_switch_rx_e(o_msec_switch_rx_e_1), 
    .i_msec_mac_tx(i_msec_mac_tx_1), 
    .i_msec_mac_tx_v(i_msec_mac_tx_v_1), 
    .i_msec_switch_rx(i_msec_switch_rx_1), 
    .i_msec_switch_rx_v(i_msec_switch_rx_v_1), 
    .mii_rx(mii_rx_1), 
    .mii_tsu_in(mii_tsu_in_1), 
    .o_rx_throttle(o_rx_throttle_1), 
    .i_tx_stop(i_tx_stop_1), 
    .o_msec_mac_rx(o_msec_mac_rx_1), 
    .o_msec_mac_rx_v(o_msec_mac_rx_v_1), 
    .o_msec_switch_tx(o_msec_switch_tx_1), 
    .o_msec_switch_tx_v(o_msec_switch_tx_v_1), 
    .mii_tx(mii_tx_1), 
    .fvisa_clk_port4(port4_apr_0_0_avisa_clk), 
    .avisa_clk(port4_apr_0_1_avisa_clk), 
    .fvisa_dbg_lane_port4(port4_apr_0_0_avisa_dbg_lane), 
    .avisa_dbg_lane(port4_apr_0_1_avisa_dbg_lane), 
    .fvisa_rddata_port4(port4_apr_0_0_avisa_rddata), 
    .avisa_rddata(port4_apr_0_1_avisa_rddata), 
    .o_cfg_tx_jitter(port4_apr_0_1_o_cfg_tx_jitter), 
    .o_cfg_txram_port_bound(port4_apr_0_1_o_cfg_txram_port_bound), 
    .o_obuf_data(port4_apr_0_1_o_obuf_data), 
    .o_port_en(port4_apr_0_1_o_port_en), 
    .i_rpl_bkwd(port4_apr_0_0_o_rpl_bkwd), 
    .o_rpl_bkwd(port4_apr_0_1_o_rpl_bkwd), 
    .o_rx_grant_fifo_afull(port4_apr_0_1_o_rx_grant_fifo_afull), 
    .o_rx_q_xoff(port4_apr_0_1_o_rx_q_xoff), 
    .o_rx_tap_port_cfg(port4_apr_0_1_o_rx_tap_port_cfg), 
    .o_seg_valid(port4_apr_0_1_o_seg_valid), 
    .o_switch_rx_pc_xoff(port4_apr_0_1_o_switch_rx_pc_xoff), 
    .i_time_scale_pulse(port4_apr_0_0_o_time_scale_pulse), 
    .o_time_scale_pulse(port4_apr_0_1_o_time_scale_pulse), 
    .o_txram_credit(port4_apr_0_1_o_txram_credit), 
    .i_tsu_sync_val(i_tsu_sync_val), 
    .i_ports_cfg(i_ports_cfg), 
    .avisa_unit_id_p2(port4_apr_0_1_avisa_unit_id_p2), 
    .fvisa_unit_id(port4_apr_0_2_avisa_unit_id_p2), 
    .aary_post_complete_rf(port4_apr_0_1_aary_post_complete_rf), 
    .aary_post_complete_sram(port4_apr_0_1_aary_post_complete_sram), 
    .aary_post_pass_rf(port4_apr_0_1_aary_post_pass_rf), 
    .aary_post_pass_sram(port4_apr_0_1_aary_post_pass_sram), 
    .fary_trigger_post_rf(port4_apr_0_2_aary_post_complete_rf), 
    .fary_trigger_post_sram(port4_apr_0_2_aary_post_complete_sram), 
    .fary_post_pass_rf(port4_apr_0_2_aary_post_pass_rf), 
    .fary_post_pass_sram(port4_apr_0_2_aary_post_pass_sram), 
    .avisa_all_dis(port4_apr_0_1_avisa_all_dis), 
    .avisa_customer_dis(port4_apr_0_1_avisa_customer_dis), 
    .avisa_frame(port4_apr_0_1_avisa_frame), 
    .avisa_serdata(port4_apr_0_1_avisa_serdata), 
    .avisa_serstb(port4_apr_0_1_avisa_serstb), 
    .o_rpl_frwd(port4_apr_0_1_o_rpl_frwd), 
    .i_rpl_frwd(port4_apr_0_2_o_rpl_frwd), 
    .fvisa_all_dis(port4_apr_0_2_avisa_all_dis), 
    .fvisa_customer_dis(port4_apr_0_2_avisa_customer_dis), 
    .fvisa_frame(port4_apr_0_2_avisa_frame), 
    .fvisa_serdata(port4_apr_0_2_avisa_serdata), 
    .fvisa_serstb(port4_apr_0_2_avisa_serstb), 
    .i_rx_grant_fifo_push(sia_tap_0_o_rx_grant_fifo_push_1), 
    .i_rx_grant_fifo_push_data(sia_tap_0_o_rx_grant_fifo_push_data_1), 
    .i_rx_pause_gen_smp_xoff(sia_tap_0_o_rx_pause_gen_smp_xoff_1), 
    .i_rx_pause_gen_pfc_smp_xoff(sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_1), 
    .i_sia_tx_tap_int(sia_tap_0_o_sia_tx_tap_int_1), 
    .i_txram_win(sia_tap_0_o_txram_win_1), 
    .i_txmetaram_win(sia_tap_0_o_txmetaram_win_1), 
    .i_tx_switch_ready(sia_tap_0_o_tx_switch_ready_1), 
    .i_jitter_cred_tgl(sia_tap_0_o_jitter_cred_tgl_1), 
    .i_txram_wr_tgl(sia_tap_0_o_txram_wr_tgl_1), 
    .clk(port4_0_clk_pdop_parhlpport4_clkout), 
    .switch_clk(port4_0_switch_clk_pdop_parhlpport4_clkout), 
    .fet_ack_b(), 
    .fet_en_b(1'b0), 
    .avisa_unit_id_p1(), 
    .avisa_unit_id_p3(), 
    .fdfx_jta_force_latch_mem_fuses(1'b0), 
    .clk_rscclk(1'b0), 
    .mbist_diag_done(), 
    .fsta_afd_en(1'b0), 
    .DFTMASK(1'b0), 
    .DFTSHIFTEN(1'b0), 
    .DFT_ARRAY_FREEZE(1'b0), 
    .fary_ffuse_rf_sleep(2'b0), 
    .fary_ffuse_sram_sleep(2'b0), 
    .fary_output_reset(1'b0), 
    .fscan_byprst_b(1'b0), 
    .fscan_clkgenctrl(1'b0), 
    .fscan_clkgenctrlen(1'b0), 
    .fscan_clkungate(1'b0), 
    .fscan_clkungate_syn(1'b0), 
    .fscan_latchclosed_b(1'b0), 
    .fscan_latchopen(1'b0), 
    .fscan_mode(1'b0), 
    .fscan_mode_atspeed(1'b0), 
    .fscan_ram_bypsel_rf(1'b0), 
    .fscan_ram_bypsel_sram(1'b0), 
    .fscan_ram_init_en(1'b0), 
    .fscan_ram_init_val(1'b0), 
    .fscan_ram_rdis_b(1'b0), 
    .fscan_ram_wdis_b(1'b0), 
    .fscan_ret_ctrl(1'b0), 
    .fscan_rstbypen(1'b0), 
    .fscan_sdi(360'b0), 
    .fscan_shiften(1'b0), 
    .fsta_dfxact_afd(1'b0), 
    .fvisa_clk_msec(4'b0), 
    .fvisa_dbg_lane_msec(32'b0), 
    .fvisa_resetb(1'b0), 
    .isol_en_b(1'b0), 
    .pwr_mgmt_in_rf(5'b0), 
    .pwr_mgmt_in_sram(6'b0), 
    .ascan_sdo(), 
    .isol_ack_b(), 
    .o_iarb_token_rate(), 
    .o_p0_mode(), 
    .o_ports_info(), 
    .fary_ijtag_tck(1'b0), 
    .fary_ijtag_rst_b(1'b0), 
    .fary_ijtag_capture(1'b0), 
    .fary_ijtag_shift(1'b0), 
    .fary_ijtag_update(1'b0), 
    .fary_ijtag_select(1'b0), 
    .fary_ijtag_si(1'b0), 
    .aary_ijtag_so(), 
    .bisr_so_pd_vinf(), 
    .bisr_si_pd_vinf(1'b0), 
    .bisr_shift_en_pd_vinf(1'b0), 
    .bisr_clk_pd_vinf(1'b0), 
    .bisr_reset_pd_vinf(1'b0), 
    .fary_trigger_post(1'b0), 
    .aary_post_pass(), 
    .aary_post_busy(), 
    .aary_post_complete(), 
    .fary_post_force_fail(1'b0), 
    .fary_post_algo_select(6'b0), 
    .core_rst_b(1'b0)
) ; 
//User inserted instance
hlp_port4_apr #(.MACS(1)) port4_apr_2 (
    .fary_ffuse_hd2prf_trim(fary_ffuse_hd2prf_trim), 
    .fary_ffuse_rfhs2r2w_trim(fary_ffuse_rfhs2r2w_trim), 
    .fary_ffuse_hdusplr_trim(fary_ffuse_hdusplr_trim), 
    .fary_ffuse_hduspsr_trim(fary_ffuse_hduspsr_trim), 
    .i_force_clk_en(i_force_clk_en), 
    .i_id(i_id), 
    .i_mac_limit(i_mac_limit), 
    .i_port4_disable(i_port4_disable), 
    .i_switch_ready(i_switch_ready), 
    .mem_rst_n(mem_rst_n), 
    .powergood_rst_n(powergood_rst_n), 
    .DFT_AFD_RESET_B(powergood_rst_n), 
    .rst_n(rst_n), 
    .swclk_mem_rst_n(swclk_mem_rst_n), 
    .switch_rst_n(switch_rst_n), 
    .i_mac_id(2'h2), 
    .fvisa_rddata_msec(fvisa_rddata_msec_2), 
    .i_msec_disable(i_msec2_disable), 
    .i_msec_mac_rx_e(i_msec_mac_rx_e_2), 
    .i_msec_switch_tx_e(i_msec_switch_tx_e_2), 
    .i_port1_id(i_port1_id_2), 
    .o_msec_mac_tx_e(o_msec_mac_tx_e_2), 
    .o_msec_switch_rx_e(o_msec_switch_rx_e_2), 
    .i_msec_mac_tx(i_msec_mac_tx_2), 
    .i_msec_mac_tx_v(i_msec_mac_tx_v_2), 
    .i_msec_switch_rx(i_msec_switch_rx_2), 
    .i_msec_switch_rx_v(i_msec_switch_rx_v_2), 
    .mii_rx(mii_rx_2), 
    .mii_tsu_in(mii_tsu_in_2), 
    .o_rx_throttle(o_rx_throttle_2), 
    .i_tx_stop(i_tx_stop_2), 
    .o_msec_mac_rx(o_msec_mac_rx_2), 
    .o_msec_mac_rx_v(o_msec_mac_rx_v_2), 
    .o_msec_switch_tx(o_msec_switch_tx_2), 
    .o_msec_switch_tx_v(o_msec_switch_tx_v_2), 
    .mii_tx(mii_tx_2), 
    .fvisa_clk_port4(port4_apr_0_1_avisa_clk), 
    .avisa_clk(port4_apr_0_2_avisa_clk), 
    .fvisa_dbg_lane_port4(port4_apr_0_1_avisa_dbg_lane), 
    .avisa_dbg_lane(port4_apr_0_2_avisa_dbg_lane), 
    .fvisa_rddata_port4(port4_apr_0_1_avisa_rddata), 
    .avisa_rddata(port4_apr_0_2_avisa_rddata), 
    .o_cfg_tx_jitter(port4_apr_0_2_o_cfg_tx_jitter), 
    .o_cfg_txram_port_bound(port4_apr_0_2_o_cfg_txram_port_bound), 
    .o_obuf_data(port4_apr_0_2_o_obuf_data), 
    .o_port_en(port4_apr_0_2_o_port_en), 
    .i_rpl_bkwd(port4_apr_0_1_o_rpl_bkwd), 
    .o_rpl_bkwd(port4_apr_0_2_o_rpl_bkwd), 
    .o_rx_grant_fifo_afull(port4_apr_0_2_o_rx_grant_fifo_afull), 
    .o_rx_q_xoff(port4_apr_0_2_o_rx_q_xoff), 
    .o_rx_tap_port_cfg(port4_apr_0_2_o_rx_tap_port_cfg), 
    .o_seg_valid(port4_apr_0_2_o_seg_valid), 
    .o_switch_rx_pc_xoff(port4_apr_0_2_o_switch_rx_pc_xoff), 
    .i_time_scale_pulse(port4_apr_0_1_o_time_scale_pulse), 
    .o_time_scale_pulse(port4_apr_0_2_o_time_scale_pulse), 
    .o_txram_credit(port4_apr_0_2_o_txram_credit), 
    .i_tsu_sync_val(i_tsu_sync_val), 
    .i_ports_cfg(i_ports_cfg), 
    .avisa_unit_id_p2(port4_apr_0_2_avisa_unit_id_p2), 
    .fvisa_unit_id(port4_apr_0_3_avisa_unit_id_p2), 
    .aary_post_complete_rf(port4_apr_0_2_aary_post_complete_rf), 
    .aary_post_complete_sram(port4_apr_0_2_aary_post_complete_sram), 
    .aary_post_pass_rf(port4_apr_0_2_aary_post_pass_rf), 
    .aary_post_pass_sram(port4_apr_0_2_aary_post_pass_sram), 
    .fary_trigger_post_rf(port4_apr_0_3_aary_post_complete_rf), 
    .fary_trigger_post_sram(port4_apr_0_3_aary_post_complete_sram), 
    .fary_post_pass_rf(port4_apr_0_3_aary_post_pass_rf), 
    .fary_post_pass_sram(port4_apr_0_3_aary_post_pass_sram), 
    .o_rpl_frwd(port4_apr_0_2_o_rpl_frwd), 
    .i_rpl_frwd(port4_apr_0_3_o_rpl_frwd), 
    .avisa_all_dis(port4_apr_0_2_avisa_all_dis), 
    .avisa_customer_dis(port4_apr_0_2_avisa_customer_dis), 
    .avisa_frame(port4_apr_0_2_avisa_frame), 
    .avisa_serdata(port4_apr_0_2_avisa_serdata), 
    .avisa_serstb(port4_apr_0_2_avisa_serstb), 
    .fvisa_all_dis(port4_apr_0_3_avisa_all_dis), 
    .fvisa_customer_dis(port4_apr_0_3_avisa_customer_dis), 
    .fvisa_frame(port4_apr_0_3_avisa_frame), 
    .fvisa_serdata(port4_apr_0_3_avisa_serdata), 
    .fvisa_serstb(port4_apr_0_3_avisa_serstb), 
    .i_rx_grant_fifo_push(sia_tap_0_o_rx_grant_fifo_push_2), 
    .i_rx_grant_fifo_push_data(sia_tap_0_o_rx_grant_fifo_push_data_2), 
    .i_rx_pause_gen_smp_xoff(sia_tap_0_o_rx_pause_gen_smp_xoff_2), 
    .i_rx_pause_gen_pfc_smp_xoff(sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_2), 
    .i_sia_tx_tap_int(sia_tap_0_o_sia_tx_tap_int_2), 
    .i_txram_win(sia_tap_0_o_txram_win_2), 
    .i_txmetaram_win(sia_tap_0_o_txmetaram_win_2), 
    .i_tx_switch_ready(sia_tap_0_o_tx_switch_ready_2), 
    .i_jitter_cred_tgl(sia_tap_0_o_jitter_cred_tgl_2), 
    .i_txram_wr_tgl(sia_tap_0_o_txram_wr_tgl_2), 
    .clk(port4_0_clk_pdop_parhlpport4_clkout), 
    .switch_clk(port4_0_switch_clk_pdop_parhlpport4_clkout), 
    .fet_ack_b(), 
    .fet_en_b(1'b0), 
    .avisa_unit_id_p1(), 
    .avisa_unit_id_p3(), 
    .fdfx_jta_force_latch_mem_fuses(1'b0), 
    .clk_rscclk(1'b0), 
    .mbist_diag_done(), 
    .fsta_afd_en(1'b0), 
    .DFTMASK(1'b0), 
    .DFTSHIFTEN(1'b0), 
    .DFT_ARRAY_FREEZE(1'b0), 
    .fary_ffuse_rf_sleep(2'b0), 
    .fary_ffuse_sram_sleep(2'b0), 
    .fary_output_reset(1'b0), 
    .fscan_byprst_b(1'b0), 
    .fscan_clkgenctrl(1'b0), 
    .fscan_clkgenctrlen(1'b0), 
    .fscan_clkungate(1'b0), 
    .fscan_clkungate_syn(1'b0), 
    .fscan_latchclosed_b(1'b0), 
    .fscan_latchopen(1'b0), 
    .fscan_mode(1'b0), 
    .fscan_mode_atspeed(1'b0), 
    .fscan_ram_bypsel_rf(1'b0), 
    .fscan_ram_bypsel_sram(1'b0), 
    .fscan_ram_init_en(1'b0), 
    .fscan_ram_init_val(1'b0), 
    .fscan_ram_rdis_b(1'b0), 
    .fscan_ram_wdis_b(1'b0), 
    .fscan_ret_ctrl(1'b0), 
    .fscan_rstbypen(1'b0), 
    .fscan_sdi(360'b0), 
    .fscan_shiften(1'b0), 
    .fsta_dfxact_afd(1'b0), 
    .fvisa_clk_msec(4'b0), 
    .fvisa_dbg_lane_msec(32'b0), 
    .fvisa_resetb(1'b0), 
    .isol_en_b(1'b0), 
    .pwr_mgmt_in_rf(5'b0), 
    .pwr_mgmt_in_sram(6'b0), 
    .ascan_sdo(), 
    .isol_ack_b(), 
    .o_iarb_token_rate(), 
    .o_p0_mode(), 
    .o_ports_info(), 
    .fary_ijtag_tck(1'b0), 
    .fary_ijtag_rst_b(1'b0), 
    .fary_ijtag_capture(1'b0), 
    .fary_ijtag_shift(1'b0), 
    .fary_ijtag_update(1'b0), 
    .fary_ijtag_select(1'b0), 
    .fary_ijtag_si(1'b0), 
    .aary_ijtag_so(), 
    .bisr_so_pd_vinf(), 
    .bisr_si_pd_vinf(1'b0), 
    .bisr_shift_en_pd_vinf(1'b0), 
    .bisr_clk_pd_vinf(1'b0), 
    .bisr_reset_pd_vinf(1'b0), 
    .fary_trigger_post(1'b0), 
    .aary_post_pass(), 
    .aary_post_busy(), 
    .aary_post_complete(), 
    .fary_post_force_fail(1'b0), 
    .fary_post_algo_select(6'b0), 
    .core_rst_b(1'b0)
) ; 
//User inserted instance
hlp_port4_apr #(.MACS(1)) port4_apr_3 (
    .fary_ffuse_hd2prf_trim(fary_ffuse_hd2prf_trim), 
    .fary_ffuse_rfhs2r2w_trim(fary_ffuse_rfhs2r2w_trim), 
    .fary_ffuse_hdusplr_trim(fary_ffuse_hdusplr_trim), 
    .fary_ffuse_hduspsr_trim(fary_ffuse_hduspsr_trim), 
    .i_force_clk_en(i_force_clk_en), 
    .i_id(i_id), 
    .i_mac_limit(i_mac_limit), 
    .i_port4_disable(i_port4_disable), 
    .i_switch_ready(i_switch_ready), 
    .mem_rst_n(mem_rst_n), 
    .powergood_rst_n(powergood_rst_n), 
    .DFT_AFD_RESET_B(powergood_rst_n), 
    .rst_n(rst_n), 
    .swclk_mem_rst_n(swclk_mem_rst_n), 
    .switch_rst_n(switch_rst_n), 
    .i_mac_id(2'h3), 
    .fary_post_pass_rf(fary_post_pass_rf), 
    .fary_post_pass_sram(fary_post_pass_sram), 
    .fary_trigger_post_rf(fary_trigger_post_rf), 
    .fary_trigger_post_sram(fary_trigger_post_sram), 
    .fvisa_rddata_msec(fvisa_rddata_msec_3), 
    .fvisa_unit_id(fvisa_unit_id), 
    .i_msec_disable(i_msec3_disable), 
    .i_msec_mac_rx_e(i_msec_mac_rx_e_3), 
    .i_msec_switch_tx_e(i_msec_switch_tx_e_3), 
    .i_port1_id(i_port1_id_3), 
    .i_rpl_frwd(i_rpl_frwd), 
    .avisa_rddata(avisa_rddata), 
    .avisa_unit_id_p1(avisa_unit_id_p1), 
    .o_msec_mac_tx_e(o_msec_mac_tx_e_3), 
    .o_msec_switch_rx_e(o_msec_switch_rx_e_3), 
    .o_rpl_bkwd(o_rpl_bkwd), 
    .o_time_scale_pulse(o_time_scale_pulse), 
    .i_msec_mac_tx(i_msec_mac_tx_3), 
    .i_msec_mac_tx_v(i_msec_mac_tx_v_3), 
    .i_msec_switch_rx(i_msec_switch_rx_3), 
    .i_msec_switch_rx_v(i_msec_switch_rx_v_3), 
    .mii_rx(mii_rx_3), 
    .mii_tsu_in(mii_tsu_in_3), 
    .o_rx_throttle(o_rx_throttle_3), 
    .i_tx_stop(i_tx_stop_3), 
    .o_msec_mac_rx(o_msec_mac_rx_3), 
    .o_msec_mac_rx_v(o_msec_mac_rx_v_3), 
    .o_msec_switch_tx(o_msec_switch_tx_3), 
    .o_msec_switch_tx_v(o_msec_switch_tx_v_3), 
    .mii_tx(mii_tx_3), 
    .fvisa_clk_port4(port4_apr_0_2_avisa_clk), 
    .fvisa_dbg_lane_port4(port4_apr_0_2_avisa_dbg_lane), 
    .fvisa_rddata_port4(port4_apr_0_2_avisa_rddata), 
    .o_cfg_tx_jitter(port4_apr_0_3_o_cfg_tx_jitter), 
    .o_cfg_txram_port_bound(port4_apr_0_3_o_cfg_txram_port_bound), 
    .o_obuf_data(port4_apr_0_3_o_obuf_data), 
    .o_port_en(port4_apr_0_3_o_port_en), 
    .i_rpl_bkwd(port4_apr_0_2_o_rpl_bkwd), 
    .o_rx_grant_fifo_afull(port4_apr_0_3_o_rx_grant_fifo_afull), 
    .o_rx_q_xoff(port4_apr_0_3_o_rx_q_xoff), 
    .o_rx_tap_port_cfg(port4_apr_0_3_o_rx_tap_port_cfg), 
    .o_seg_valid(port4_apr_0_3_o_seg_valid), 
    .o_switch_rx_pc_xoff(port4_apr_0_3_o_switch_rx_pc_xoff), 
    .i_time_scale_pulse(port4_apr_0_2_o_time_scale_pulse), 
    .o_txram_credit(port4_apr_0_3_o_txram_credit), 
    .i_tsu_sync_val(i_tsu_sync_val), 
    .i_ports_cfg(i_ports_cfg), 
    .avisa_unit_id_p2(port4_apr_0_3_avisa_unit_id_p2), 
    .aary_post_complete_rf(port4_apr_0_3_aary_post_complete_rf), 
    .aary_post_complete_sram(port4_apr_0_3_aary_post_complete_sram), 
    .aary_post_pass_rf(port4_apr_0_3_aary_post_pass_rf), 
    .aary_post_pass_sram(port4_apr_0_3_aary_post_pass_sram), 
    .o_rpl_frwd(port4_apr_0_3_o_rpl_frwd), 
    .avisa_all_dis(port4_apr_0_3_avisa_all_dis), 
    .avisa_customer_dis(port4_apr_0_3_avisa_customer_dis), 
    .avisa_frame(port4_apr_0_3_avisa_frame), 
    .avisa_serdata(port4_apr_0_3_avisa_serdata), 
    .avisa_serstb(port4_apr_0_3_avisa_serstb), 
    .i_rx_grant_fifo_push(sia_tap_0_o_rx_grant_fifo_push_3), 
    .i_rx_grant_fifo_push_data(sia_tap_0_o_rx_grant_fifo_push_data_3), 
    .i_rx_pause_gen_smp_xoff(sia_tap_0_o_rx_pause_gen_smp_xoff_3), 
    .i_rx_pause_gen_pfc_smp_xoff(sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_3), 
    .i_sia_tx_tap_int(sia_tap_0_o_sia_tx_tap_int_3), 
    .i_txram_win(sia_tap_0_o_txram_win_3), 
    .i_txmetaram_win(sia_tap_0_o_txmetaram_win_3), 
    .i_tx_switch_ready(sia_tap_0_o_tx_switch_ready_3), 
    .i_jitter_cred_tgl(sia_tap_0_o_jitter_cred_tgl_3), 
    .i_txram_wr_tgl(sia_tap_0_o_txram_wr_tgl_3), 
    .clk(port4_0_clk_pdop_parhlpport4_clkout), 
    .switch_clk(port4_0_switch_clk_pdop_parhlpport4_clkout), 
    .fet_ack_b(), 
    .fet_en_b(1'b0), 
    .avisa_unit_id_p3(), 
    .fdfx_jta_force_latch_mem_fuses(1'b0), 
    .clk_rscclk(1'b0), 
    .mbist_diag_done(), 
    .fsta_afd_en(1'b0), 
    .DFTMASK(1'b0), 
    .DFTSHIFTEN(1'b0), 
    .DFT_ARRAY_FREEZE(1'b0), 
    .fary_ffuse_rf_sleep(2'b0), 
    .fary_ffuse_sram_sleep(2'b0), 
    .fary_output_reset(1'b0), 
    .fscan_byprst_b(1'b0), 
    .fscan_clkgenctrl(1'b0), 
    .fscan_clkgenctrlen(1'b0), 
    .fscan_clkungate(1'b0), 
    .fscan_clkungate_syn(1'b0), 
    .fscan_latchclosed_b(1'b0), 
    .fscan_latchopen(1'b0), 
    .fscan_mode(1'b0), 
    .fscan_mode_atspeed(1'b0), 
    .fscan_ram_bypsel_rf(1'b0), 
    .fscan_ram_bypsel_sram(1'b0), 
    .fscan_ram_init_en(1'b0), 
    .fscan_ram_init_val(1'b0), 
    .fscan_ram_rdis_b(1'b0), 
    .fscan_ram_wdis_b(1'b0), 
    .fscan_ret_ctrl(1'b0), 
    .fscan_rstbypen(1'b0), 
    .fscan_sdi(360'b0), 
    .fscan_shiften(1'b0), 
    .fsta_dfxact_afd(1'b0), 
    .fvisa_all_dis(1'b0), 
    .fvisa_clk_msec(4'b0), 
    .fvisa_customer_dis(1'b0), 
    .fvisa_dbg_lane_msec(32'b0), 
    .fvisa_frame(1'b0), 
    .fvisa_resetb(1'b0), 
    .fvisa_serdata(1'b0), 
    .fvisa_serstb(1'b0), 
    .isol_en_b(1'b0), 
    .pwr_mgmt_in_rf(5'b0), 
    .pwr_mgmt_in_sram(6'b0), 
    .ascan_sdo(), 
    .avisa_clk(), 
    .avisa_dbg_lane(), 
    .isol_ack_b(), 
    .o_iarb_token_rate(), 
    .o_p0_mode(), 
    .o_ports_info(), 
    .fary_ijtag_tck(1'b0), 
    .fary_ijtag_rst_b(1'b0), 
    .fary_ijtag_capture(1'b0), 
    .fary_ijtag_shift(1'b0), 
    .fary_ijtag_update(1'b0), 
    .fary_ijtag_select(1'b0), 
    .fary_ijtag_si(1'b0), 
    .aary_ijtag_so(), 
    .bisr_so_pd_vinf(), 
    .bisr_si_pd_vinf(1'b0), 
    .bisr_shift_en_pd_vinf(1'b0), 
    .bisr_clk_pd_vinf(1'b0), 
    .bisr_reset_pd_vinf(1'b0), 
    .fary_trigger_post(1'b0), 
    .aary_post_pass(), 
    .aary_post_busy(), 
    .aary_post_complete(), 
    .fary_post_force_fail(1'b0), 
    .fary_post_algo_select(6'b0), 
    .core_rst_b(1'b0)
) ; 
pdop mbist_clk_pdop_parhlpport4 (
    .clken(1'b0), 
    .clkenfree(1'b0), 
    .clkfree(), 
    .clkin(1'b0), 
    .clkout(), 
    .scanclk(1'b0), 
    .soft_high_out()
) ; 
pdop port4_clk_pdop_parhlpport4 (
    .clken(1'b1), 
    .clkenfree(1'b1), 
    .clkin(clk), 
    .clkout(port4_0_clk_pdop_parhlpport4_clkout), 
    .clkfree(), 
    .scanclk(1'b0), 
    .soft_high_out()
) ; 
pdop port4_switch_clk_pdop_parhlpport4 (
    .clken(1'b1), 
    .clkenfree(1'b1), 
    .clkin(switch_clk), 
    .clkout(port4_0_switch_clk_pdop_parhlpport4_clkout), 
    .clkfree(), 
    .scanclk(1'b0), 
    .soft_high_out()
) ; 
hlp_sia_tap sia_tap (
    .i_quad_id(i_id), 
    .i_switch_ready(i_switch_ready), 
    .switch_rst_n(switch_rst_n), 
    .fvisa_rddata(fvisa_rddata_port4), 
    .i_pause_ripple(i_pause_ripple), 
    .i_pause_ripple_ret(i_pause_ripple_ret), 
    .i_pause_ripple_ret_v(i_pause_ripple_ret_v), 
    .i_pause_ripple_v(i_pause_ripple_v), 
    .i_rx_grant(i_rx_grant), 
    .i_rx_grant_v(i_rx_grant_v), 
    .i_rx_req(i_rx_req), 
    .i_rx_ripple(i_rx_ripple), 
    .i_rx_ripple_v(i_rx_ripple_v), 
    .i_tx_cred(i_tx_cred), 
    .i_tx_ripple(i_tx_ripple), 
    .i_tx_ripple_v(i_tx_ripple_v), 
    .o_pause_ripple(o_pause_ripple), 
    .o_pause_ripple_ret(o_pause_ripple_ret), 
    .o_pause_ripple_ret_v(o_pause_ripple_ret_v), 
    .o_pause_ripple_v(o_pause_ripple_v), 
    .o_rx_grant(o_rx_grant), 
    .o_rx_grant_v(o_rx_grant_v), 
    .o_rx_req(o_rx_req), 
    .o_rx_ripple(o_rx_ripple), 
    .o_rx_ripple_v(o_rx_ripple_v), 
    .o_tx_cred(o_tx_cred), 
    .o_tx_ripple(o_tx_ripple), 
    .o_tx_ripple_v(o_tx_ripple_v), 
    .fvisa_unit_id(port4_apr_0_0_avisa_unit_id_p2), 
    .fvisa_all_dis(port4_apr_0_0_avisa_all_dis), 
    .fvisa_customer_dis(port4_apr_0_0_avisa_customer_dis), 
    .fvisa_frame(port4_apr_0_0_avisa_frame), 
    .fvisa_serdata(port4_apr_0_0_avisa_serdata), 
    .fvisa_serstb(port4_apr_0_0_avisa_serstb), 
    .i_cfg_tx_jitter_0(port4_apr_0_0_o_cfg_tx_jitter), 
    .i_cfg_tx_jitter_1(port4_apr_0_1_o_cfg_tx_jitter), 
    .i_cfg_tx_jitter_2(port4_apr_0_2_o_cfg_tx_jitter), 
    .i_cfg_tx_jitter_3(port4_apr_0_3_o_cfg_tx_jitter), 
    .i_cfg_txram_port_bound_0(port4_apr_0_0_o_cfg_txram_port_bound), 
    .i_cfg_txram_port_bound_1(port4_apr_0_1_o_cfg_txram_port_bound), 
    .i_cfg_txram_port_bound_2(port4_apr_0_2_o_cfg_txram_port_bound), 
    .i_cfg_txram_port_bound_3(port4_apr_0_3_o_cfg_txram_port_bound), 
    .i_iarb_token_rate(port4_apr_0_0_o_iarb_token_rate), 
    .i_obuf_data_0(port4_apr_0_0_o_obuf_data), 
    .i_obuf_data_1(port4_apr_0_1_o_obuf_data), 
    .i_obuf_data_2(port4_apr_0_2_o_obuf_data), 
    .i_obuf_data_3(port4_apr_0_3_o_obuf_data), 
    .i_p0_mode(port4_apr_0_0_o_p0_mode), 
    .i_port_en_0(port4_apr_0_0_o_port_en), 
    .i_port_en_1(port4_apr_0_1_o_port_en), 
    .i_port_en_2(port4_apr_0_2_o_port_en), 
    .i_port_en_3(port4_apr_0_3_o_port_en), 
    .i_rx_grant_fifo_afull_0(port4_apr_0_0_o_rx_grant_fifo_afull), 
    .i_rx_grant_fifo_afull_1(port4_apr_0_1_o_rx_grant_fifo_afull), 
    .i_rx_grant_fifo_afull_2(port4_apr_0_2_o_rx_grant_fifo_afull), 
    .i_rx_grant_fifo_afull_3(port4_apr_0_3_o_rx_grant_fifo_afull), 
    .i_rx_q_xoff_0(port4_apr_0_0_o_rx_q_xoff), 
    .i_rx_q_xoff_1(port4_apr_0_1_o_rx_q_xoff), 
    .i_rx_q_xoff_2(port4_apr_0_2_o_rx_q_xoff), 
    .i_rx_q_xoff_3(port4_apr_0_3_o_rx_q_xoff), 
    .i_rx_tap_port_cfg_0(port4_apr_0_0_o_rx_tap_port_cfg), 
    .i_rx_tap_port_cfg_1(port4_apr_0_1_o_rx_tap_port_cfg), 
    .i_rx_tap_port_cfg_2(port4_apr_0_2_o_rx_tap_port_cfg), 
    .i_rx_tap_port_cfg_3(port4_apr_0_3_o_rx_tap_port_cfg), 
    .i_seg_valid_0(port4_apr_0_0_o_seg_valid), 
    .i_seg_valid_1(port4_apr_0_1_o_seg_valid), 
    .i_seg_valid_2(port4_apr_0_2_o_seg_valid), 
    .i_seg_valid_3(port4_apr_0_3_o_seg_valid), 
    .i_switch_rx_pc_xoff_0(port4_apr_0_0_o_switch_rx_pc_xoff), 
    .i_switch_rx_pc_xoff_1(port4_apr_0_1_o_switch_rx_pc_xoff), 
    .i_switch_rx_pc_xoff_2(port4_apr_0_2_o_switch_rx_pc_xoff), 
    .i_switch_rx_pc_xoff_3(port4_apr_0_3_o_switch_rx_pc_xoff), 
    .i_txram_credit_0(port4_apr_0_0_o_txram_credit), 
    .i_txram_credit_1(port4_apr_0_1_o_txram_credit), 
    .i_txram_credit_2(port4_apr_0_2_o_txram_credit), 
    .i_txram_credit_3(port4_apr_0_3_o_txram_credit), 
    .o_rx_grant_fifo_push_0(sia_tap_0_o_rx_grant_fifo_push_0), 
    .o_rx_grant_fifo_push_data_0(sia_tap_0_o_rx_grant_fifo_push_data_0), 
    .o_rx_grant_fifo_push_1(sia_tap_0_o_rx_grant_fifo_push_1), 
    .o_rx_grant_fifo_push_data_1(sia_tap_0_o_rx_grant_fifo_push_data_1), 
    .o_rx_grant_fifo_push_2(sia_tap_0_o_rx_grant_fifo_push_2), 
    .o_rx_grant_fifo_push_data_2(sia_tap_0_o_rx_grant_fifo_push_data_2), 
    .o_rx_grant_fifo_push_3(sia_tap_0_o_rx_grant_fifo_push_3), 
    .o_rx_grant_fifo_push_data_3(sia_tap_0_o_rx_grant_fifo_push_data_3), 
    .o_rx_pause_gen_smp_xoff_0(sia_tap_0_o_rx_pause_gen_smp_xoff_0), 
    .o_rx_pause_gen_smp_xoff_1(sia_tap_0_o_rx_pause_gen_smp_xoff_1), 
    .o_rx_pause_gen_smp_xoff_2(sia_tap_0_o_rx_pause_gen_smp_xoff_2), 
    .o_rx_pause_gen_smp_xoff_3(sia_tap_0_o_rx_pause_gen_smp_xoff_3), 
    .o_rx_pause_gen_pfc_smp_xoff_0(sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_0), 
    .o_rx_pause_gen_pfc_smp_xoff_1(sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_1), 
    .o_rx_pause_gen_pfc_smp_xoff_2(sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_2), 
    .o_rx_pause_gen_pfc_smp_xoff_3(sia_tap_0_o_rx_pause_gen_pfc_smp_xoff_3), 
    .o_sia_tx_tap_int_0(sia_tap_0_o_sia_tx_tap_int_0), 
    .o_sia_tx_tap_int_1(sia_tap_0_o_sia_tx_tap_int_1), 
    .o_sia_tx_tap_int_2(sia_tap_0_o_sia_tx_tap_int_2), 
    .o_sia_tx_tap_int_3(sia_tap_0_o_sia_tx_tap_int_3), 
    .o_txram_win_0(sia_tap_0_o_txram_win_0), 
    .o_txram_win_1(sia_tap_0_o_txram_win_1), 
    .o_txram_win_2(sia_tap_0_o_txram_win_2), 
    .o_txram_win_3(sia_tap_0_o_txram_win_3), 
    .o_txmetaram_win_0(sia_tap_0_o_txmetaram_win_0), 
    .o_txmetaram_win_1(sia_tap_0_o_txmetaram_win_1), 
    .o_txmetaram_win_2(sia_tap_0_o_txmetaram_win_2), 
    .o_txmetaram_win_3(sia_tap_0_o_txmetaram_win_3), 
    .o_tx_switch_ready_0(sia_tap_0_o_tx_switch_ready_0), 
    .o_tx_switch_ready_1(sia_tap_0_o_tx_switch_ready_1), 
    .o_tx_switch_ready_2(sia_tap_0_o_tx_switch_ready_2), 
    .o_tx_switch_ready_3(sia_tap_0_o_tx_switch_ready_3), 
    .o_jitter_cred_tgl_0(sia_tap_0_o_jitter_cred_tgl_0), 
    .o_jitter_cred_tgl_1(sia_tap_0_o_jitter_cred_tgl_1), 
    .o_jitter_cred_tgl_2(sia_tap_0_o_jitter_cred_tgl_2), 
    .o_jitter_cred_tgl_3(sia_tap_0_o_jitter_cred_tgl_3), 
    .o_txram_wr_tgl_0(sia_tap_0_o_txram_wr_tgl_0), 
    .o_txram_wr_tgl_1(sia_tap_0_o_txram_wr_tgl_1), 
    .o_txram_wr_tgl_2(sia_tap_0_o_txram_wr_tgl_2), 
    .o_txram_wr_tgl_3(sia_tap_0_o_txram_wr_tgl_3), 
    .switch_clk(port4_0_switch_clk_pdop_parhlpport4_clkout), 
    .avisa_serstb(), 
    .avisa_frame(), 
    .avisa_serdata(), 
    .avisa_rddata(), 
    .avisa_customer_dis(), 
    .avisa_all_dis(), 
    .fvisa_dbg_lane(32'b0), 
    .fvisa_clk(4'b0), 
    .avisa_dbg_lane(), 
    .avisa_clk(), 
    .fvisa_resetb(1'b0), 
    .isol_en_b(1'b0), 
    .fet_en_b(1'b0), 
    .isol_ack_b(), 
    .fet_ack_b(), 
    .fscan_mode(1'b0), 
    .fscan_shiften(1'b0), 
    .fscan_clkungate(1'b0), 
    .fscan_clkungate_syn(1'b0), 
    .fscan_rstbypen(1'b0), 
    .fscan_byprst_b(1'b0) 
  //  .visaRt_unit_id_to_parhlpports_parhlpport4_0_sia_tap_visa_unit_mux_regout_1(8'b0), 
  //  .visaRt_cfg_wr_bus_in_to_parhlpmod_mod_apr_mod_ngvisa_top_junc(2'b0), 
  //  .visaRt_cfg_rd_bus_out_from_parhlpports_parhlpport4_0_sia_tap_sia_tap0_ngvisa_top_junc(), 
  //  .visaRt_cfg_wr_bus_in_from_parhlpport4_0_sia_tap_sia_tap0_ngvisa_top_junc(), 
  //  .visaRt_lane_out_from_parhlpports_parhlpport4_0_sia_tap_sia_tap0_ngvisa_top_junc(), 
  //  .visaRt_lane_valid_out_from_parhlpports_parhlpport4_0_sia_tap_sia_tap0_ngvisa_top_junc(), 
  //  .visaRt_cfg_rd_bus_out_to_parhlpport4_0_sia_tap(2'b0), 
  //  .visaRt_lane_out_to_parhlpport4_0_sia_tap({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,
  //          1'b0}), 
  //  .visaRt_lane_valid_out_to_parhlpport4_0_sia_tap(2'b0)
) ; 
// EDIT_INSTANCE END

// EDIT_CONTINUOUS_ASSIGN BEGIN
assign pd_vinf_bisr_shift_en_out = pd_vinf_bisr_shift_en ; 
assign pd_vinf_bisr_reset_out = pd_vinf_bisr_reset ; 
assign pd_vinf_bisr_clk_out = pd_vinf_bisr_clk ; 
// EDIT_CONTINUOUS_ASSIGN END
endmodule
