
/*AUTO_LISP(setq verilog-auto-unused-ignore-regexp
(concat
"^\\("
".*_clk"
"\\|.*aonclk1x"
"\\|.*_rst.*"
"\\|.*_powergood.*"
"\\|.*syscon.*"
"\\|.*hi-f_car_.*_toggle.*"
"\\|.*fuse.*"
"\\|fabric_reset_shield"
"\\|.*_ssn_.*"
"\\|.*_ecc_stop.*"
"\\|.*rxelecidle.*"
"\\|.*pm_linkst.*"
"\\|.*smlh_in_rl0s.*"
"\\|.*syscon.*"
"\\|.*perf_win_sync.*"
"\\)$"
))*/

/*AUTO_LISP(setq verilog-active-low-regexp
(concat
"^\\("
".*pready.*"
"\\)$"
))*/

module parhif_pcie_ss_dwc_ctlx16_stub(
/*AUTOINOUTMODULE("parhif_pcie_ss_dwc_ctlx16")*/
// Beginning of automatic in/out/inouts (from specific module)
output			o_visa_all_dis_to_idex16,
output			o_visa_customer_dis_to_idex16,
output [15:0]		phy_pcie0_pipe_clk,
output [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phycrif_prdata__pcie_ss_control0__phycrif_prdata,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phycrif_pready__pcie_ss_control0__phycrif_pready,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phycrif_pslverr__pcie_ss_control0__phycrif_pslverr,
output [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phyctrl_prdata__pcie_ss_control0__phyctrl_prdata,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phyctrl_pready__pcie_ss_control0__phyctrl_pready,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phyctrl_pslverr__pcie_ss_control0__phyctrl_pslverr,
output [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_paddr__hif_core__hif_t_pcie_phycrif_paddr,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_penable__hif_core__hif_t_pcie_phycrif_penable,
output [2:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_pprot__hif_core__hif_t_pcie_phycrif_pprot,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_psel__hif_core__hif_t_pcie_phycrif_psel,
output [3:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_pstrb__hif_core__hif_t_pcie_phycrif_pstrb,
output [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_pwdata__hif_core__hif_t_pcie_phycrif_pwdata,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_pwrite__hif_core__hif_t_pcie_phycrif_pwrite,
output [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_paddr__hif_core__hif_t_pcie_phyctrl_paddr,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_penable__hif_core__hif_t_pcie_phyctrl_penable,
output [2:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_pprot__hif_core__hif_t_pcie_phyctrl_pprot,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_psel__hif_core__hif_t_pcie_phyctrl_psel,
output [3:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_pstrb__hif_core__hif_t_pcie_phyctrl_pstrb,
output [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_pwdata__hif_core__hif_t_pcie_phyctrl_pwdata,
output			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_pwrite__hif_core__hif_t_pcie_phyctrl_pwrite,
output [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_prdata,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pready,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pslverr,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_core_clk,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_abort,
output [1023:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_data,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_dlp_abort,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_dv,
output [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_dwen,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_ecrc_err,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_eot,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_fm_format,
output [447:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_hdr,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_hv,
output [13:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_hwen,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_nullified,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_poisoned,
output [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_porder,
output [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_soh,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_status,
output [159:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_trailer,
output [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_twen,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_abort,
output [1023:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_data,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_dlp_abort,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_dv,
output [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_dwen,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_ecrc_err,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_eot,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_fm_format,
output [447:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_hdr,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_hv,
output [13:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_hwen,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_in_membar_range,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_io_req_in_range,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_nullified,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_poisoned,
output [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_porder,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_rom_in_range,
output [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_soh,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_status,
output [159:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_trailer,
output [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_twen,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_abort,
output [1023:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_data,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_dlp_abort,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_dv,
output [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_dwen,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_ecrc_err,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_eot,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_fm_format,
output [447:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_hdr,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_hv,
output [13:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_hwen,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_in_membar_range,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_io_req_in_range,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_nullified,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_pending,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_poisoned,
output [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_porder,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_rom_in_range,
output [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_soh,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_status,
output [159:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_trailer,
output [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_twen,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_halt,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_halt,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_halt,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_aspm_event,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_bme_change,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_cfg_2nd_reset,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_cfg_cii_access,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_hp_pme,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_hp_slot_ctrl_access,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_link_req_rst_not,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_link_up,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_pcie_int,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_phy_sram_ecc_int,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_spare0,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_spare1,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_spare2,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_spare3,
output [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_paddr_in,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_penable_in,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pprot_in,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_psel_in,
output [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pwdata_in,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pwrite_in,
output [9:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_addr,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_cs,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_device_type,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_flit_mode_en,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_flr_rst,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_from_wire,
output [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_ide_dw_next_ptr,
output [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_ide_up_next_ptr,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_ro_wr_en,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_segment_captured,
output [7:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_segment_id,
output [8:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_send_stream_to_insecure,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_tee_io_supported,
output [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_wdata,
output [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_wr_en,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_core_rst,
output [107:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_ctl_regs_req,
output [14:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_paddr_in,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_penable_in,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pprot_in,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_psel_in,
output [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pwdata_in,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pwrite_in,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_grant,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_non_sticky_rst,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_sticky_rst,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_phy_rxelecidle,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_pm_linkst_in_l0s,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_pm_linkst_in_l1,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_pm_linkst_in_l2,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_smlh_in_rl0s,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_asyncpowerchangeack,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_commonclock_enable,
output [127:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_messagebus,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_pclk_rate,
output [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_pclkchangeack,
output [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_powerdown,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_rate,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_rxelecidle_disable,
output [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_rxstandby,
output [1:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_rxwidth,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_serdes_arch,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_sris_enable,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txcommonmode_disable,
output [1279:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txdata,
output [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txdatavalid,
output [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txdetectrx_loopback,
output [63:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txelecidle,
output [1:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_width,
output [36:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_ack,
output [191:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_control,
output [1151:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_data,
output [5:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_data_size,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_dllp_error,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_e2e_prefix_size,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_eop,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_halt,
output [503:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_hdr,
output [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_hdr_size,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_local_prefix_size,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_order,
output [143:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_pcrc_mac,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_pcrc_mac_size,
output [143:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_prefix,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_sop,
output [230:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_control,
output [1151:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_data,
output [5:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_data_size,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_dllp_error,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_e2e_prefix_size,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_eop,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_halt,
output [503:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_hdr,
output [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_hdr_size,
output [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_local_prefix_size,
output [8:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_ohc_req_seg,
output [143:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_prefix,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_sop,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_tlp_t_bit,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_o_core_rst_n,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_o_muxd_aux_clk,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_perst_pre_ind_nss_hif_n,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_perst_pre_ind_pcie_o_muxd_aux_n,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_reset_n,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_rst_n,
output			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ptm_context_valid,
output [63:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ptm_local_clock,
output [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_rtlh_fc_allctd_pd,
output [7:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_rtlh_fc_allctd_ph,
output [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_rtlh_fc_rcvd_pd,
output [7:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_rtlh_fc_rcvd_ph,
inout [5:0]		pcie_ss_PVTC0RTS01_pvt_sns,
input			aonclk1x,
input			nss_hif_clk,
input			phy_pcie0_max_pclk,
input [15:0]		phy_pcie0_pipe_rx_clk,
input			scon_hif_powergood,
input			scon_hifcar_rst_n,
input			soc_per_clk,
input			visa_all_dis,
input			visa_customer_dis,
input			visa_resetb,
input [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phycrif_prdata__pcie_ss_control0__phycrif_prdata,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phycrif_pready__pcie_ss_control0__phycrif_pready,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phycrif_pslverr__pcie_ss_control0__phycrif_pslverr,
input [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phyctrl_prdata__pcie_ss_control0__phyctrl_prdata,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phyctrl_pready__pcie_ss_control0__phyctrl_pready,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phyctrl_pslverr__pcie_ss_control0__phyctrl_pslverr,
input [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_paddr__hif_core__hif_t_pcie_phycrif_paddr,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_penable__hif_core__hif_t_pcie_phycrif_penable,
input [2:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_pprot__hif_core__hif_t_pcie_phycrif_pprot,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_psel__hif_core__hif_t_pcie_phycrif_psel,
input [3:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_pstrb__hif_core__hif_t_pcie_phycrif_pstrb,
input [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_pwdata__hif_core__hif_t_pcie_phycrif_pwdata,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_pwrite__hif_core__hif_t_pcie_phycrif_pwrite,
input [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_paddr__hif_core__hif_t_pcie_phyctrl_paddr,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_penable__hif_core__hif_t_pcie_phyctrl_penable,
input [2:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_pprot__hif_core__hif_t_pcie_phyctrl_pprot,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_psel__hif_core__hif_t_pcie_phyctrl_psel,
input [3:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_pstrb__hif_core__hif_t_pcie_phyctrl_pstrb,
input [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_pwdata__hif_core__hif_t_pcie_phyctrl_pwdata,
input			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_pwrite__hif_core__hif_t_pcie_phyctrl_pwrite,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_acc_perst_n,
input [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_paddr,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_penable,
input [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pprot,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_psel,
input [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pstrb,
input [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pwdata,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pwrite,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_halt,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_halt,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_halt,
input [1023:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_data,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_dv,
input [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_dwen,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_ecrc_err,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_ecrc_gen,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_eot,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_fm_format,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_grant,
input [447:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_hdr,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_hv,
input [13:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_hwen,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_nullified,
input [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_order_seqnum,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_poisoned,
input [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_soh,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_t_bit,
input [159:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_tlp_trailer,
input [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_twen,
input [1023:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_data,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_dv,
input [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_dwen,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_ecrc_err,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_ecrc_gen,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_eot,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_fm_format,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_grant,
input [447:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_hdr,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_hv,
input [13:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_hwen,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_nullified,
input [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_order_seqnum,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_poisoned,
input [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_soh,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_t_bit,
input [159:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_tlp_trailer,
input [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_twen,
input [1023:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_data,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_dv,
input [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_dwen,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_ecrc_err,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_ecrc_gen,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_eot,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_fm_format,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_grant,
input [447:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_hdr,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_hv,
input [13:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_hwen,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_nullified,
input [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_order_seqnum,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_poisoned,
input [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_soh,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_t_bit,
input [159:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_tlp_trailer,
input [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_twen,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ext_phy_rxelecidle,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ext_pm_linkst_in_l0s,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ext_pm_linkst_in_l1,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ext_pm_linkst_in_l2,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ext_smlh_in_rl0s,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_fuse_ide_disable,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_fuse_pcie_ss_disable,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_fuse_rp_disable,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_car_1us_toggle,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_PERST_n0,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_PERST_n1,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_PERST_n2,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_PERST_n3,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_upp_shim_xfer_pending,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_upp_xfer_pending,
input [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_prdata_out,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pready_out,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pslverr_out,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_ack,
input [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_rdata,
input [36:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_ctl_regs_ack,
input [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_prdata_out,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pready_out,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pslverr_out,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_dst_rid,
input [8:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_dst_segment,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_ep,
input [7:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_func_num,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_req,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_selec_link,
input [7:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_stream_id,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_sync_fail,
input [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_tc,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_td,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_th,
input [191:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_control,
input [1151:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_data,
input [5:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_data_size,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_dllp_error,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_dp_cor_err,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_dp_unc_err,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_eop,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_halt,
input [503:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_hdr,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_ide_check_failed,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_misrouted_ide_tlp,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_order,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_pcrc_check_failed,
input [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_phe_encrypted_addr_size,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_phe_encrypted_be,
input [143:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_prefix,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_report_ide_check_faild,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_sop,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_tdisp_cpl_for_ats_translation_with_tbit_set,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_tdisp_cpl_for_memrd_with_tbit_set,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_tdisp_rcvd_rid_range_check_fail,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_was_on_select_stream,
input [230:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_control,
input [1151:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_data,
input [5:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_data_size,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_discard,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_dllp_error,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_dp_cor_err,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_dp_unc_err,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_eop,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_halt,
input [503:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_hdr,
input [107:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_mac,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_merge_pcrc,
input [35:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_pcrc,
input [143:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_prefix,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_sop,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_imc_perst_n,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_nss_hif_div_clk_en,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_nss_hif_div_clk_sel,
input [107:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_perf_win_sync,
input [127:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_messagebus,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_pclkchangeok,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_phystatus,
input [1279:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_rxdata,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_rxelecidle,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_rxstandbystatus,
input [47:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_rxstatus,
input [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_rxvalid,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_syscon_Int_only_l2_dis,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_syscon_dfd_l0_dis,
input			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_syscon_dfd_l1_dis
// End of automatics
//ADDON_INCLUDE_STUB_PORTS
);

assign pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_prdata = 'hdeadbeef;


wire pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req_valid = pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req[107];
wire [3:0] pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req_opcode = pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req[106:103];

wire pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_ack_read_valid;
wire pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_ack_write_valid;

assign pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_ack_read_valid = (pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req_opcode[0] == 1'b0)&&(|pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req_opcode[3:0]) ? pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req_valid : 1'b0;

assign pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_ack_write_valid = (pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req_opcode[0] == 1'b1)&&(|pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req_opcode[3:0]) ? pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req_valid : 1'b0;

assign pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_ack = {
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_ack_read_valid,
    1'b0,//read_miss
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_ack_write_valid,
    1'b0,//write_miss
    1'b1,//sai_successfull
    32'hdeadbeef
};

/*AUTOTIEOFF*/
// Beginning of automatic tieoffs (for this module's unterminated outputs)
wire			o_visa_all_dis_to_idex16= 1'h0;
wire			o_visa_customer_dis_to_idex16= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phycrif_prdata__pcie_ss_control0__phycrif_prdata= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phycrif_pready__pcie_ss_control0__phycrif_pready= ~1'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phycrif_pslverr__pcie_ss_control0__phycrif_pslverr= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phyctrl_prdata__pcie_ss_control0__phyctrl_prdata= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phyctrl_pready__pcie_ss_control0__phyctrl_pready= ~1'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__hif_core__hif_t_pcie_phyctrl_pslverr__pcie_ss_control0__phyctrl_pslverr= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_paddr__hif_core__hif_t_pcie_phycrif_paddr= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_penable__hif_core__hif_t_pcie_phycrif_penable= 1'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_pprot__hif_core__hif_t_pcie_phycrif_pprot= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_psel__hif_core__hif_t_pcie_phycrif_psel= 1'h0;
wire [3:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_pstrb__hif_core__hif_t_pcie_phycrif_pstrb= 4'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_pwdata__hif_core__hif_t_pcie_phycrif_pwdata= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phycrif_pwrite__hif_core__hif_t_pcie_phycrif_pwrite= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_paddr__hif_core__hif_t_pcie_phyctrl_paddr= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_penable__hif_core__hif_t_pcie_phyctrl_penable= 1'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_pprot__hif_core__hif_t_pcie_phyctrl_pprot= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_psel__hif_core__hif_t_pcie_phyctrl_psel= 1'h0;
wire [3:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_pstrb__hif_core__hif_t_pcie_phyctrl_pstrb= 4'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_pwdata__hif_core__hif_t_pcie_phyctrl_pwdata= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_o__pcie_ss_control0__phyctrl_pwrite__hif_core__hif_t_pcie_phyctrl_pwrite= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pready= ~1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pslverr= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_core_clk= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_abort= 1'h0;
wire [1023:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_data= 1024'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_dlp_abort= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_dv= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_dwen= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_ecrc_err= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_eot= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_fm_format= 1'h0;
wire [447:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_hdr= 448'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_hv= 1'h0;
wire [13:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_hwen= 14'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_nullified= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_poisoned= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_porder= 16'h0;
wire [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_soh= 5'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_status= 3'h0;
wire [159:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_trailer= 160'h0;
wire [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_twen= 5'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_abort= 1'h0;
wire [1023:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_data= 1024'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_dlp_abort= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_dv= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_dwen= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_ecrc_err= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_eot= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_fm_format= 1'h0;
wire [447:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_hdr= 448'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_hv= 1'h0;
wire [13:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_hwen= 14'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_in_membar_range= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_io_req_in_range= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_nullified= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_poisoned= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_porder= 16'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_rom_in_range= 1'h0;
wire [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_soh= 5'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_status= 3'h0;
wire [159:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_trailer= 160'h0;
wire [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_twen= 5'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_abort= 1'h0;
wire [1023:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_data= 1024'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_dlp_abort= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_dv= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_dwen= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_ecrc_err= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_eot= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_fm_format= 1'h0;
wire [447:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_hdr= 448'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_hv= 1'h0;
wire [13:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_hwen= 14'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_in_membar_range= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_io_req_in_range= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_nullified= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_pending= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_poisoned= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_porder= 16'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_rom_in_range= 1'h0;
wire [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_soh= 5'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_status= 3'h0;
wire [159:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_trailer= 160'h0;
wire [4:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_twen= 5'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_halt= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_halt= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_halt= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_aspm_event= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_bme_change= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_cfg_2nd_reset= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_cfg_cii_access= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_hp_pme= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_hp_slot_ctrl_access= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_link_req_rst_not= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_link_up= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_pcie_int= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_phy_sram_ecc_int= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_spare0= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_spare1= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_spare2= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_sw_spare3= 1'h0;
wire [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_paddr_in= 12'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_penable_in= 1'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pprot_in= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_psel_in= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pwdata_in= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pwrite_in= 1'h0;
wire [9:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_addr= 10'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_cs= 1'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_device_type= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_flit_mode_en= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_flr_rst= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_from_wire= 1'h0;
wire [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_ide_dw_next_ptr= 12'h0;
wire [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_ide_up_next_ptr= 12'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_ro_wr_en= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_segment_captured= 1'h0;
wire [7:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_segment_id= 8'h0;
wire [8:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_send_stream_to_insecure= 9'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_tee_io_supported= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_wdata= 32'h0;
wire [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_wr_en= 4'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_core_rst= 1'h0;
wire [107:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_ctl_regs_req= 108'h0;
wire [14:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_paddr_in= 15'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_penable_in= 1'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pprot_in= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_psel_in= 1'h0;
wire [31:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pwdata_in= 32'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pwrite_in= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_grant= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_non_sticky_rst= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_sticky_rst= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_phy_rxelecidle= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_pm_linkst_in_l0s= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_pm_linkst_in_l1= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_pm_linkst_in_l2= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_local_smlh_in_rl0s= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_asyncpowerchangeack= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_commonclock_enable= 1'h0;
wire [127:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_messagebus= 128'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_pclk_rate= 3'h0;
wire [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_pclkchangeack= 16'h0;
wire [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_powerdown= 4'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_rate= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_rxelecidle_disable= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_rxstandby= 16'h0;
wire [1:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_rxwidth= 2'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_serdes_arch= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_sris_enable= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txcommonmode_disable= 1'h0;
wire [1279:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txdata= 1280'h0;
wire [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txdatavalid= 16'h0;
wire [15:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txdetectrx_loopback= 16'h0;
wire [63:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_txelecidle= 64'h0;
wire [1:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_mac_phy_width= 2'h0;
wire [191:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_control= 192'h0;
wire [1151:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_data= 1152'h0;
wire [5:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_data_size= 6'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_dllp_error= 1'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_e2e_prefix_size= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_eop= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_halt= 1'h0;
wire [503:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_hdr= 504'h0;
wire [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_hdr_size= 4'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_local_prefix_size= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_order= 1'h0;
wire [143:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_pcrc_mac= 144'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_pcrc_mac_size= 3'h0;
wire [143:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_prefix= 144'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_rx_sop= 1'h0;
wire [230:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_control= 231'h0;
wire [1151:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_data= 1152'h0;
wire [5:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_data_size= 6'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_dllp_error= 1'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_e2e_prefix_size= 3'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_eop= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_halt= 1'h0;
wire [503:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_hdr= 504'h0;
wire [3:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_hdr_size= 4'h0;
wire [2:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_local_prefix_size= 3'h0;
wire [8:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_ohc_req_seg= 9'h0;
wire [143:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_prefix= 144'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_sop= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ide_tx_tlp_t_bit= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_o_core_rst_n= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_o_muxd_aux_clk= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_perst_pre_ind_nss_hif_n= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_perst_pre_ind_pcie_o_muxd_aux_n= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_reset_n= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_rst_n= 1'h0;
wire			pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ptm_context_valid= 1'h0;
wire [63:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ptm_local_clock= 64'h0;
wire [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_rtlh_fc_allctd_pd= 12'h0;
wire [7:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_rtlh_fc_allctd_ph= 8'h0;
wire [11:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_rtlh_fc_rcvd_pd= 12'h0;
wire [7:0]		pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_rtlh_fc_rcvd_ph= 8'h0;
wire [15:0]		phy_pcie0_pipe_clk	= 16'h0;
// End of automatics

//ADDON_INCLUDE_STUB_TIEOFF

`ifndef INTEL_SVA_OFF
`ifdef HIF_ASSERT_STUB_INPUTS_NO_TOGGLE

import intel_checkers_pkg::*;
reg unused_xor_d,sva_clk,sva_rst;
wire unused_xor = ^{
    /*AUTOUNUSED*/
    // Beginning of automatic unused inputs
    pcie_ss_PVTC0RTS01_pvt_sns,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phycrif_prdata__pcie_ss_control0__phycrif_prdata,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phycrif_pready__pcie_ss_control0__phycrif_pready,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phycrif_pslverr__pcie_ss_control0__phycrif_pslverr,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phyctrl_prdata__pcie_ss_control0__phyctrl_prdata,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phyctrl_pready__pcie_ss_control0__phyctrl_pready,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__hif_core__hif_t_pcie_phyctrl_pslverr__pcie_ss_control0__phyctrl_pslverr,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_paddr__hif_core__hif_t_pcie_phycrif_paddr,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_penable__hif_core__hif_t_pcie_phycrif_penable,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_pprot__hif_core__hif_t_pcie_phycrif_pprot,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_psel__hif_core__hif_t_pcie_phycrif_psel,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_pstrb__hif_core__hif_t_pcie_phycrif_pstrb,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_pwdata__hif_core__hif_t_pcie_phycrif_pwdata,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phycrif_pwrite__hif_core__hif_t_pcie_phycrif_pwrite,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_paddr__hif_core__hif_t_pcie_phyctrl_paddr,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_penable__hif_core__hif_t_pcie_phyctrl_penable,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_pprot__hif_core__hif_t_pcie_phyctrl_pprot,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_psel__hif_core__hif_t_pcie_phyctrl_psel,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_pstrb__hif_core__hif_t_pcie_phyctrl_pstrb,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_pwdata__hif_core__hif_t_pcie_phyctrl_pwdata,
    pcie_ss_dwc_ctlx16_apr_hif_pcie_ss_dwc_ctlx16_apr_FT_wrapper_i__pcie_ss_control0__phyctrl_pwrite__hif_core__hif_t_pcie_phyctrl_pwrite,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_acc_perst_n,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_paddr,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_penable,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pprot,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_psel,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pstrb,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pwdata,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_apbslv_pwrite,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_cpl0_halt,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_np0_halt,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_rtrgt1_tlp_p0_halt,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_data,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_dv,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_dwen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_ecrc_err,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_ecrc_gen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_eot,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_fm_format,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_grant,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_hdr,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_hv,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_hwen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_nullified,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_order_seqnum,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_poisoned,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_soh,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_t_bit,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_tlp_trailer,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_cpl0_twen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_data,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_dv,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_dwen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_ecrc_err,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_ecrc_gen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_eot,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_fm_format,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_grant,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_hdr,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_hv,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_hwen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_nullified,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_order_seqnum,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_poisoned,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_soh,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_t_bit,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_tlp_trailer,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_np0_twen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_data,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_dv,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_dwen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_ecrc_err,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_ecrc_gen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_eot,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_fm_format,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_grant,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_hdr,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_hv,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_hwen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_nullified,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_order_seqnum,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_poisoned,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_soh,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_t_bit,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_tlp_trailer,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_dwc_xali_tlp_vc0_p0_twen,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_car_1us_toggle,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_PERST_n0,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_PERST_n1,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_PERST_n2,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_pcie_PERST_n3,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_upp_shim_xfer_pending,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_hif_upp_xfer_pending,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_prdata_out,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pready_out,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_aes_hcfg_pslverr_out,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_ack,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_cfg_rdata,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_ctl_regs_ack,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_prdata_out,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pready_out,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_hcfg_pslverr_out,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_dst_rid,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_dst_segment,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_ep,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_func_num,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_req,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_selec_link,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_stream_id,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_sync_fail,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_tc,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_td,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_msg_th,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_control,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_data,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_data_size,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_dllp_error,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_dp_cor_err,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_dp_unc_err,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_eop,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_halt,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_hdr,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_ide_check_failed,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_misrouted_ide_tlp,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_order,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_pcrc_check_failed,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_phe_encrypted_addr_size,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_phe_encrypted_be,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_prefix,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_report_ide_check_faild,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_sop,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_tdisp_cpl_for_ats_translation_with_tbit_set,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_tdisp_cpl_for_memrd_with_tbit_set,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_tdisp_rcvd_rid_range_check_fail,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_rx_was_on_select_stream,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_control,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_data,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_data_size,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_discard,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_dllp_error,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_dp_cor_err,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_dp_unc_err,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_eop,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_halt,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_hdr,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_mac,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_merge_pcrc,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_pcrc,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_prefix,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_ide_pcie_tx_sop,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_imc_perst_n,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_nss_hif_div_clk_en,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_nss_hif_div_clk_sel,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_pcie_ctl_regs_req,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_messagebus,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_pclkchangeok,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_phystatus,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_rxdata,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_rxstandbystatus,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_rxstatus,
    pcie_ss_dwc_ctlx16_apr_pcie_ss_dwc_ctlx16_func_logic_pcie_ss_dwc_ctlx16_phy_mac_rxvalid,
    phy_pcie0_max_pclk,
    visa_all_dis,
    visa_customer_dis,
    visa_resetb,
    // End of automatics
    1'b0
};

initial sva_clk = 1'b0;
initial begin
    sva_rst = 1'b0;
    #10ns;
    sva_rst = 1'b1;
end

always #1ns sva_clk = ~sva_clk;

always @(posedge sva_clk) unused_xor_d <= unused_xor;

`ASSERTS_FORBIDDEN(hif_stub_inputs_no_toggle, (unused_xor_d !== unused_xor) , sva_clk, ~sva_rst, `ERR_MSG("Stub input toggle"));

`endif//`ifdef HIF_ASSERT_STUB_INPUTS_NO_TOGGLE
`endif//`ifndef INTEL_SVA_OFF

endmodule

// Local Variables:
// verilog-library-files:("/nfs/site/disks/nhdk.zsc7.mmg800.ipm.211/hif/hif_r15_pre_dft-mmg800-a0-25ww22a/output/hif_core/collage/trial/gen/rtl/parhif_pcie_ss_dwc_ctlx16.sv")
// end:

