/*------------------------------------------------------------------------------
  INTEL CONFIDENTIAL
  Copyright 2022 Intel Corporation All Rights Reserved.
  -----------------------------------------------------------------------------*/

module parhlpparser
// EDIT_PORT BEGIN
 ( 
input clk,
input pd_vinf_bisr_si,
input pd_vinf_bisr_reset,
input pd_vinf_bisr_clk,
input pd_vinf_bisr_shift_en,
output pd_vinf_bisr_so,
output pd_vinf_bisr_clk_out,
output pd_vinf_bisr_reset_out,
output pd_vinf_bisr_shift_en_out,
input JT_IN_mbist_ijtag_reset_b,
input JT_IN_mbist_ijtag_tck,
input JT_IN_mbist_ijtag_select,
input JT_IN_mbist_ijtag_capture,
input JT_IN_mbist_ijtag_shift,
input JT_IN_mbist_ijtag_update,
input JT_IN_mbist_ijtag_si,
input JT_IN_misc_ijtag_reset_b,
input JT_IN_misc_ijtag_tck,
input JT_IN_misc_ijtag_select,
input JT_IN_misc_ijtag_capture,
input JT_IN_misc_ijtag_shift,
input JT_IN_misc_ijtag_update,
input JT_IN_misc_ijtag_si,
input JT_IN_scan_ijtag_reset_b,
input JT_IN_scan_ijtag_tck,
input JT_IN_scan_ijtag_select,
input JT_IN_scan_ijtag_capture,
input JT_IN_scan_ijtag_shift,
input JT_IN_scan_ijtag_update,
input JT_IN_scan_ijtag_si,
output JT_OUT_mbist_ijtag_so,
output JT_OUT_misc_ijtag_so,
output JT_OUT_scan_ijtag_so,
input fdfx_powergood,
input secure_group_a,
input secure_group_b,
input secure_group_c,
input secure_group_d,
input secure_group_e,
input secure_group_g,
input secure_group_h,
input secure_group_f,
input secure_group_z,
output DIAG_AGGR_mbist_diag_done,
input chain_rpt_ffu_parser_pm_start_bus_clock_in,
input SSN_START_0_bus_clock_in,
input [31:0] chain_rpt_ffu_parser_pm_start_bus_data_in,
input [31:0] SSN_START_0_bus_data_in,
output [31:0] chain_rpt_ffu_parser_pm_end_bus_data_out,
output [31:0] SSN_END_0_bus_data_out,
input [37:0] parhlpport4_7_o_pause_ripple,
input parhlpport4_7_o_pause_ripple_v,
input [2084:0] parhlpport4_7_o_rx_ripple,
input parhlpport4_7_o_rx_ripple_v,
input [130:0] parhlpffu_parhlpfcmn_o_rpl_frwd,
input parhlpfgrp_0_avisa_rddata,
input parhlpffu_visa_out_0_VISA_CLK,
input parhlpffu_visa_out_1_VISA_CLK,
input parhlpffu_visa_out_2_VISA_CLK,
input parhlpffu_visa_out_3_VISA_CLK,
input [7:0] parhlpffu_visa_out_0_VISA_DBG_LANE,
input [15:8] parhlpffu_visa_out_1_VISA_DBG_LANE,
input [24:16] parhlpffu_visa_out_2_VISA_DBG_LANE,
input [31:25] parhlpffu_visa_out_3_VISA_DBG_LANE,
output parser_apr_aary_post_complete_rf,
output parser_apr_aary_post_pass_rf,
input [6:0] fary_ffuse_hd2prf_trim,
output [37:0] parser_apr_o_pause_ripple_ret,
output parser_apr_o_pause_ripple_ret_v,
output [1:0] parser_apr_o_l2l_info,
output [1749:0] parser_apr_o_parser_out,
output parser_apr_o_parser_out_v,
output [255:0] parser_apr_o_pkt_meta,
output parser_apr_o_pkt_meta_v,
output [2127:0] parser_apr_o_pm_write,
output [130:0] parser_apr_o_rpl_frwd,
output [0:0] parser_apr_o_rpl_bkwd,
output [31:0] parser_apr_o_rx_req,
output [63:0] parser_apr_o_tx_credits,
output [77:0] parser_apr_o_tail_info,
output parser_apr_o_tail_info_v,
output [8:0] parser_apr_avisa_unit_id_p1,
input lsm_apr_o_switch_rst_n,
input lsm_apr_o_switch_mem_rst_n,
input lsm_apr_o_switch_powergood_rst_n,
input [37:0] fwd_apr_o_pm_head_padding,
input [521:0] fwd_apr_o_sop_info,
input fwd_apr_o_sop_info_v,
input [0:0] pm_apr_o_rpl_bkwd,
output parser_apr_pm_trigger_post_ft_out );
// EDIT_PORT END


// EDIT_NET BEGIN
logic parser_clk_pdop_parhlpparser_clkout ; 
// EDIT_NET END

// EDIT_INSTANCE BEGIN

  /* Added by UltiBuild Nets Start */
  wire parser_apr_so, sib_parser_apr_to_select, 
       parser_clk_pdop_parhlpparser_fdop_scanclk, clkfree, 
       parser_clk_pdop_parhlpparser_fdop_clken, 
       mbist_clk_pdop_parhlpparser__clkout_fdop_scanclk, clkout, clkfree_ts1, 
       mbist_clk_pdop_parhlpparser__clkout_fdop_clken, fscan_byprst_b, 
       fscan_clkgenctrl, fscan_clkgenctrlen, fscan_clkungate, 
       fscan_clkungate_syn_rtl, fscan_latchclosed_b, fscan_latchopen, 
       fscan_mode, fscan_mode_atspeed, fscan_ram_init_en, fscan_ram_init_val, 
       fscan_ret_ctrl, fscan_rstbypen, ijtag_tck;
  /* Added by UltiBuild Nets End */
pdop mbist_clk_pdop_parhlpparser (
    .clken(mbist_clk_pdop_parhlpparser__clkout_fdop_clken), 
    .clkenfree(1'b0), 
    .clkfree(clkfree_ts1), 
    .clkin(ijtag_tck), 
    .clkout(clkout), 
    .scanclk(mbist_clk_pdop_parhlpparser__clkout_fdop_scanclk), 
    .soft_high_out()
) ; 
pdop parser_clk_pdop_parhlpparser (
    .clkin(clk), 
    .clkout(parser_clk_pdop_parhlpparser_clkout), 
    .clken(parser_clk_pdop_parhlpparser_fdop_clken), 
    .clkenfree(1'b1), 
    .clkfree(clkfree), 
    .scanclk(parser_clk_pdop_parhlpparser_fdop_scanclk), 
    .soft_high_out()
) ; 
hlp_parser_apr parser_apr (
    .i_pause_ripple(parhlpport4_7_o_pause_ripple), 
    .i_pause_ripple_v(parhlpport4_7_o_pause_ripple_v), 
    .i_seg(parhlpport4_7_o_rx_ripple), 
    .i_seg_v(parhlpport4_7_o_rx_ripple_v), 
    .i_rpl_frwd(parhlpffu_parhlpfcmn_o_rpl_frwd), 
    .fvisa_rddata_switch(parhlpfgrp_0_avisa_rddata), 
    .fvisa_clk_switch({parhlpffu_visa_out_3_VISA_CLK,parhlpffu_visa_out_2_VISA_CLK,parhlpffu_visa_out_1_VISA_CLK,parhlpffu_visa_out_0_VISA_CLK}), 
    .fvisa_dbg_lane_switch({parhlpffu_visa_out_3_VISA_DBG_LANE,parhlpffu_visa_out_2_VISA_DBG_LANE,parhlpffu_visa_out_1_VISA_DBG_LANE,parhlpffu_visa_out_0_VISA_DBG_LANE}), 
    .aary_post_complete_rf(parser_apr_aary_post_complete_rf), 
    .aary_post_pass_rf(parser_apr_aary_post_pass_rf), 
    .fary_ffuse_hd2prf_trim(fary_ffuse_hd2prf_trim), 
    .o_pause_ripple_ret(parser_apr_o_pause_ripple_ret), 
    .o_pause_ripple_ret_v(parser_apr_o_pause_ripple_ret_v), 
    .o_l2l_info(parser_apr_o_l2l_info), 
    .o_parser_out(parser_apr_o_parser_out), 
    .o_parser_out_v(parser_apr_o_parser_out_v), 
    .o_pkt_meta(parser_apr_o_pkt_meta), 
    .o_pkt_meta_v(parser_apr_o_pkt_meta_v), 
    .o_pm_write(parser_apr_o_pm_write), 
    .o_rpl_frwd(parser_apr_o_rpl_frwd), 
    .o_rpl_bkwd(parser_apr_o_rpl_bkwd), 
    .o_rx_req(parser_apr_o_rx_req), 
    .o_tx_credits(parser_apr_o_tx_credits), 
    .o_tail_info(parser_apr_o_tail_info), 
    .o_tail_info_v(parser_apr_o_tail_info_v), 
    .avisa_unit_id_p1(parser_apr_avisa_unit_id_p1), 
    .clk(parser_clk_pdop_parhlpparser_clkout), 
    .rst_n(lsm_apr_o_switch_rst_n), 
    .i_broadcast({lsm_apr_o_switch_powergood_rst_n,lsm_apr_o_switch_mem_rst_n}), 
    .DFT_AFD_RESET_B(lsm_apr_o_switch_powergood_rst_n), 
    .i_pm_head_padding(fwd_apr_o_pm_head_padding), 
    .i_sop_info(fwd_apr_o_sop_info), 
    .i_sop_info_v(fwd_apr_o_sop_info_v), 
    .i_rpl_bkwd(pm_apr_o_rpl_bkwd), 
    .pm_trigger_post_ft_out(parser_apr_pm_trigger_post_ft_out), 
    .fet_ack_b(), 
    .fet_en_b(1'b0), 
    .fdfx_jta_force_latch_mem_fuses(1'b0), 
    .fary_trigger_post_rf(1'b0), 
    .fvisa_serstb(1'b0), 
    .fvisa_frame(1'b0), 
    .fvisa_serdata(1'b0), 
    .fvisa_rddata_ports(1'b0), 
    .avisa_serstb(), 
    .avisa_frame(), 
    .avisa_serdata(), 
    .avisa_rddata(), 
    .fvisa_customer_dis(1'b0), 
    .fvisa_all_dis(1'b0), 
    .avisa_customer_dis(), 
    .avisa_all_dis(), 
    .fvisa_dbg_lane_ports(32'b0), 
    .fvisa_clk_ports(4'b0), 
    .avisa_dbg_lane(), 
    .avisa_clk(), 
    .fvisa_unit_id(9'b0), 
    .avisa_unit_id_p32(), 
    .fvisa_resetb(1'b0), 
    .pm_trigger_post_ft_in(), 
    .pm_post_complete_ft_in(1'b0), 
    .pm_post_complete_ft_out(), 
    .pm_post_pass_ft_in(1'b0), 
    .pm_post_pass_ft_out(), 
    .clk_rscclk(clkout), 
    .mbist_diag_done(DIAG_AGGR_mbist_diag_done), 
    .fsta_afd_en(1'b0), 
    .DFTMASK(1'b0), 
    .DFTSHIFTEN(1'b0), 
    .DFT_ARRAY_FREEZE(1'b0), 
    .fary_ffuse_rf_sleep(2'b0), 
    .fary_output_reset(1'b0), 
    .fscan_byprst_b(fscan_byprst_b), 
    .fscan_clkgenctrl(fscan_clkgenctrl), 
    .fscan_clkgenctrlen(fscan_clkgenctrlen), 
    .fscan_clkungate(fscan_clkungate), 
    .fscan_clkungate_syn(fscan_clkungate_syn_rtl), 
    .fscan_latchclosed_b(fscan_latchclosed_b), 
    .fscan_latchopen(fscan_latchopen), 
    .fscan_mode(fscan_mode), 
    .fscan_mode_atspeed(fscan_mode_atspeed), 
    .fscan_ram_bypsel_rf(1'b0), 
    .fscan_ram_init_en(fscan_ram_init_en), 
    .fscan_ram_init_val(fscan_ram_init_val), 
    .fscan_ram_rdis_b(1'b0), 
    .fscan_ram_wdis_b(1'b0), 
    .fscan_ret_ctrl(fscan_ret_ctrl), 
    .fscan_rstbypen(fscan_rstbypen), 
    .fscan_sdi(408'b0), 
    .fscan_shiften(1'b0), 
    .fsta_dfxact_afd(1'b0), 
    .isol_en_b(1'b0), 
    .pwr_mgmt_in_rf(5'b0), 
    .ascan_sdo(), 
    .isol_ack_b(), 
  //  .visaRt_unit_id_to_parhlpparser_parser_apr_u_parser_apr_func_logic_visa_unit_mux_regout_0(8'b0), 
  //  .visaRt_unit_id_to_parhlpparser_parser_apr_u_parser_apr_func_logic_visa_unit_mux_regout_1(8'b0), 
  //  .visaRt_unit_id_to_parhlpparser_parser_apr_u_parser_apr_func_logic_visa_unit_mux_regout_2(8'b0), 
  //  .visaRt_clk_to_parhlpparser_parser_apr_fcmn_ngvisa_top_junc(1'b0), 
  //  .visaRt_cfg_rd_bus_out_to_parhlpparser_parser_apr(2'b0), 
  //  .visaRt_lane_out_to_parhlpparser_parser_apr({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,
  //          1'b0}), 
  //  .visaRt_lane_valid_out_to_parhlpparser_parser_apr(2'b0), 
  //  .visaRt_cfg_rd_bus_out_to_parhlpparser_parser_apr_1(2'b0), 
  //  .visaRt_lane_out_to_parhlpparser_parser_apr_1({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,
  //          1'b0}), 
  //  .visaRt_lane_valid_out_to_parhlpparser_parser_apr_1(2'b0), 
  //  .visaRt_cfg_rd_bus_out_to_parhlpparser_parser_apr_2(2'b0), 
  //  .visaRt_lane_out_to_parhlpparser_parser_apr_2({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,
  //          1'b0}), 
  //  .visaRt_lane_valid_out_to_parhlpparser_parser_apr_2(2'b0), 
  //  .visaRt_cfg_wr_bus_in_to_parhlpparser_parser_apr_parser_ngvisa_top_junc(2'b0), 
  //  .visaRt_cfg_wr_bus_in_from_parhlpparser_parser_apr_fcmn_ngvisa_top_junc(), 
  //  .visaRt_cfg_rd_bus_out_from_parhlpparser_parser_apr_parser_ngvisa_top_junc(), 
  //  .visaRt_lane_out_from_parhlpparser_parser_apr_parser_ngvisa_top_junc(), 
  //  .visaRt_lane_valid_out_from_parhlpparser_parser_apr_parser_ngvisa_top_junc(), 
    .fary_ijtag_tck(JT_IN_mbist_ijtag_tck), 
    .fary_ijtag_rst_b(JT_IN_mbist_ijtag_reset_b), 
    .fary_ijtag_capture(JT_IN_mbist_ijtag_capture), 
    .fary_ijtag_shift(JT_IN_mbist_ijtag_shift), 
    .fary_ijtag_update(JT_IN_mbist_ijtag_update), 
    .fary_ijtag_select(sib_parser_apr_to_select), 
    .fary_ijtag_si(JT_IN_mbist_ijtag_si), 
    .aary_ijtag_so(parser_apr_so), 
    .bisr_so_pd_vinf(pd_vinf_bisr_so), 
    .bisr_si_pd_vinf(pd_vinf_bisr_si), 
    .bisr_shift_en_pd_vinf(pd_vinf_bisr_shift_en), 
    .bisr_clk_pd_vinf(pd_vinf_bisr_clk), 
    .bisr_reset_pd_vinf(pd_vinf_bisr_reset), 
    .fary_trigger_post(1'b0), 
    .aary_post_pass(), 
    .aary_post_busy(), 
    .aary_post_complete(), 
    .fary_post_force_fail(1'b0), 
    .fary_post_algo_select(6'b0), 
    .core_rst_b(1'b0)
) ; 
// EDIT_INSTANCE END

// EDIT_CONTINUOUS_ASSIGN BEGIN
assign pd_vinf_bisr_shift_en_out = pd_vinf_bisr_shift_en ; 
assign pd_vinf_bisr_reset_out = pd_vinf_bisr_reset ; 
assign pd_vinf_bisr_clk_out = pd_vinf_bisr_clk ; 
// EDIT_CONTINUOUS_ASSIGN END

  /* Added by UltiBuild Instances Start */
  parhlpparser_ub parhlpparser_ub(.sib_scan_so(JT_OUT_scan_ijtag_so), 
                                  .sib_parser_apr_so(JT_OUT_mbist_ijtag_so), 
                                  .JT_IN_mbist_ijtag_si(JT_IN_mbist_ijtag_si), 
                                  .parser_apr_so(parser_apr_so), 
                                  .JT_IN_mbist_ijtag_select(JT_IN_mbist_ijtag_select), 
                                  .JT_IN_scan_ijtag_si(JT_IN_scan_ijtag_si), 
                                  .JT_IN_scan_ijtag_select(JT_IN_scan_ijtag_select), 
                                  .sib_parser_apr_to_select(sib_parser_apr_to_select), 
                                  .JT_IN_scan_ijtag_update(JT_IN_scan_ijtag_update), 
                                  .JT_IN_scan_ijtag_reset_b(JT_IN_scan_ijtag_reset_b), 
                                  .JT_IN_scan_ijtag_capture(JT_IN_scan_ijtag_capture), 
                                  .JT_IN_mbist_ijtag_tck(JT_IN_mbist_ijtag_tck), 
                                  .JT_IN_mbist_ijtag_shift(JT_IN_mbist_ijtag_shift), 
                                  .JT_IN_mbist_ijtag_update(JT_IN_mbist_ijtag_update), 
                                  .JT_IN_scan_ijtag_tck(JT_IN_scan_ijtag_tck), 
                                  .JT_IN_scan_ijtag_shift(JT_IN_scan_ijtag_shift), 
                                  .JT_IN_mbist_ijtag_reset_b(JT_IN_mbist_ijtag_reset_b), 
                                  .JT_IN_mbist_ijtag_capture(JT_IN_mbist_ijtag_capture), 
                                  .bus_data_out(SSN_END_0_bus_data_out), 
                                  .bus_data_out_ts3(chain_rpt_ffu_parser_pm_end_bus_data_out), 
                                  .SSN_START_0_bus_data_in(SSN_START_0_bus_data_in), 
                                  .chain_rpt_ffu_parser_pm_start_bus_data_in(chain_rpt_ffu_parser_pm_start_bus_data_in), 
                                  .SSN_START_0_bus_clock_in(SSN_START_0_bus_clock_in), 
                                  .chain_rpt_ffu_parser_pm_start_bus_clock_in(chain_rpt_ffu_parser_pm_start_bus_clock_in), 
                                  .parser_clk_pdop_parhlpparser_fdop_scanclk(parser_clk_pdop_parhlpparser_fdop_scanclk), 
                                  .clkout(parser_clk_pdop_parhlpparser_clkout), 
                                  .clkfree(clkfree), 
                                  .parser_clk_pdop_parhlpparser_fdop_clken(parser_clk_pdop_parhlpparser_fdop_clken), 
                                  .mbist_clk_pdop_parhlpparser__clkout_fdop_scanclk(mbist_clk_pdop_parhlpparser__clkout_fdop_scanclk), 
                                  .clkout_ts1(clkout), .clkfree_ts1(clkfree_ts1), 
                                  .mbist_clk_pdop_parhlpparser__clkout_fdop_clken(mbist_clk_pdop_parhlpparser__clkout_fdop_clken), 
                                  .fscan_byprst_b(fscan_byprst_b), 
                                  .fscan_clkgenctrl(fscan_clkgenctrl), 
                                  .fscan_clkgenctrlen(fscan_clkgenctrlen), 
                                  .fscan_clkungate(fscan_clkungate), 
                                  .fscan_clkungate_syn_rtl(fscan_clkungate_syn_rtl), 
                                  .fscan_latchclosed_b(fscan_latchclosed_b), 
                                  .fscan_latchopen(fscan_latchopen), 
                                  .fscan_mode(fscan_mode), 
                                  .fscan_mode_atspeed(fscan_mode_atspeed), 
                                  .fscan_ram_init_en(fscan_ram_init_en), 
                                  .fscan_ram_init_val(fscan_ram_init_val), 
                                  .fscan_ret_ctrl(fscan_ret_ctrl), 
                                  .fscan_rstbypen(fscan_rstbypen), .ijtag_tck(ijtag_tck), 
                                  .fdfx_powergood(fdfx_powergood), 
                                  .secure_group_f(secure_group_f)
  );
  /* Added by UltiBuild Instances End */
endmodule
