/*------------------------------------------------------------------------------
  INTEL CONFIDENTIAL
  Copyright 2022 Intel Corporation All Rights Reserved.
  -----------------------------------------------------------------------------*/

module parhlpsched
// EDIT_PORT BEGIN
 ( 
input clk,
input pd_vinf_bisr_si,
input pd_vinf_bisr_reset,
input pd_vinf_bisr_clk,
input pd_vinf_bisr_shift_en,
output pd_vinf_bisr_so,
output pd_vinf_bisr_clk_out,
output pd_vinf_bisr_reset_out,
output pd_vinf_bisr_shift_en_out,
input JT_IN_mbist_ijtag_reset_b,
input JT_IN_mbist_ijtag_tck,
input JT_IN_mbist_ijtag_select,
input JT_IN_mbist_ijtag_capture,
input JT_IN_mbist_ijtag_shift,
input JT_IN_mbist_ijtag_update,
input JT_IN_mbist_ijtag_si,
input JT_IN_misc_ijtag_reset_b,
input JT_IN_misc_ijtag_tck,
input JT_IN_misc_ijtag_select,
input JT_IN_misc_ijtag_capture,
input JT_IN_misc_ijtag_shift,
input JT_IN_misc_ijtag_update,
input JT_IN_misc_ijtag_si,
input JT_IN_scan_ijtag_reset_b,
input JT_IN_scan_ijtag_tck,
input JT_IN_scan_ijtag_select,
input JT_IN_scan_ijtag_capture,
input JT_IN_scan_ijtag_shift,
input JT_IN_scan_ijtag_update,
input JT_IN_scan_ijtag_si,
output JT_OUT_mbist_ijtag_so,
output JT_OUT_misc_ijtag_so,
output JT_OUT_scan_ijtag_so,
input fdfx_powergood,
input secure_group_a,
input secure_group_b,
input secure_group_c,
input secure_group_d,
input secure_group_e,
input secure_group_g,
input secure_group_h,
input secure_group_f,
input secure_group_z,
output DIAG_AGGR_mbist_diag_done,
input SSN_START_0_bus_clock_in,
input [31:0] SSN_START_0_bus_data_in,
output [31:0] SSN_END_0_bus_data_out,
input [37:0] mod_apr_o_pause_ripple_ret,
input mod_apr_o_pause_ripple_ret_v,
input [56:0] mod_apr_o_refcnt_tx_info,
input mod_apr_o_refcnt_tx_info_v,
input [130:0] mod_apr_o_rpl_frwd,
input [63:0] mod_apr_o_tx_credits,
input [31:0] mod_apr_avisa_dbg_lane,
input mod_apr_avisa_rddata,
input [3:0] mod_apr_avisa_clk,
output sched_apr_avisa_all_dis,
output sched_apr_avisa_customer_dis,
output sched_apr_avisa_frame,
output sched_apr_avisa_serdata,
output sched_apr_avisa_serstb,
output [8:0] sched_apr_avisa_unit_id_p1,
input [6:0] fary_ffuse_hd2prf_trim,
input [9:0] fary_ffuse_rfhs2r2w_trim,
input [16:0] fary_ffuse_hdusplr_trim,
input [16:0] fary_ffuse_hduspsr_trim,
input [8:0] tail_apr_avisa_unit_id_p1,
input [130:0] tail_apr_o_fwd_sched,
input [0:0] tail_apr_o_rpl_bkwd,
input [23:0] tail_apr_o_seg_meta,
input tail_apr_o_seg_meta_v,
input lsm_apr_o_switch_mem_rst_n,
input lsm_apr_o_switch_powergood_rst_n,
input lsm_apr_o_switch_rst_n,
output [1903:0] sched_apr_o_cm_apply,
output sched_apr_o_cm_apply_v,
output [9:0] sched_apr_o_fixed_sched,
output sched_apr_o_fixed_sched_v,
output [55:0] sched_apr_o_pm_ctrl,
output sched_apr_o_modify_ecn_v,
output [84:0] sched_apr_o_modify_ecn,
output sched_apr_o_pause_ripple_v,
output [130:0] sched_apr_o_rpl_frwd,
output sched_apr_o_modify_ctrl_v,
output [37:0] sched_apr_o_pause_ripple,
output [140:0] sched_apr_o_modify_ctrl,
output [0:0] sched_apr_o_rpl_bkwd,
output [127:0] sched_apr_o_pfc_xoff,
output [15:0] sched_apr_o_lfc_xoff );
// EDIT_PORT END


// EDIT_NET BEGIN
logic sched_clk_pdop_parhlpsched_clkout ; 
// EDIT_NET END

// EDIT_INSTANCE BEGIN

  /* Added by UltiBuild Nets Start */
  wire sched_apr_so, sib_sched_apr_to_select, 
       sched_clk_pdop_parhlpsched_fdop_scanclk, clkfree, 
       sched_clk_pdop_parhlpsched_fdop_clken, 
       mbist_clk_pdop_parhlpsched__clkout_fdop_scanclk, clkout, clkfree_ts1, 
       mbist_clk_pdop_parhlpsched__clkout_fdop_clken, fscan_byprst_b, 
       fscan_clkgenctrl, fscan_clkgenctrlen, fscan_clkungate, 
       fscan_clkungate_syn_rtl, fscan_latchclosed_b, fscan_latchopen, 
       fscan_mode, fscan_mode_atspeed, fscan_ram_init_en, fscan_ram_init_val, 
       fscan_ret_ctrl, fscan_rstbypen, ijtag_tck;
  /* Added by UltiBuild Nets End */
pdop mbist_clk_pdop_parhlpsched (
    .clken(mbist_clk_pdop_parhlpsched__clkout_fdop_clken), 
    .clkenfree(1'b0), 
    .clkfree(clkfree_ts1), 
    .clkin(ijtag_tck), 
    .clkout(clkout), 
    .scanclk(mbist_clk_pdop_parhlpsched__clkout_fdop_scanclk), 
    .soft_high_out()
) ; 
pdop sched_clk_pdop_parhlpsched (
    .clkin(clk), 
    .clkout(sched_clk_pdop_parhlpsched_clkout), 
    .clken(sched_clk_pdop_parhlpsched_fdop_clken), 
    .clkenfree(1'b1), 
    .clkfree(clkfree), 
    .scanclk(sched_clk_pdop_parhlpsched_fdop_scanclk), 
    .soft_high_out()
) ; 
hlp_sched_apr sched_apr (
    .i_pause_ripple(mod_apr_o_pause_ripple_ret), 
    .i_pause_ripple_v(mod_apr_o_pause_ripple_ret_v), 
    .i_refcnt_tx_info(mod_apr_o_refcnt_tx_info), 
    .i_refcnt_tx_info_v(mod_apr_o_refcnt_tx_info_v), 
    .i_rpl_frwd(mod_apr_o_rpl_frwd), 
    .i_tx_credits(mod_apr_o_tx_credits), 
    .fvisa_dbg_lane(mod_apr_avisa_dbg_lane), 
    .fvisa_rddata(mod_apr_avisa_rddata), 
    .fvisa_clk(mod_apr_avisa_clk), 
    .avisa_all_dis(sched_apr_avisa_all_dis), 
    .avisa_customer_dis(sched_apr_avisa_customer_dis), 
    .avisa_frame(sched_apr_avisa_frame), 
    .avisa_serdata(sched_apr_avisa_serdata), 
    .avisa_serstb(sched_apr_avisa_serstb), 
    .avisa_unit_id_p1(sched_apr_avisa_unit_id_p1), 
    .fary_ffuse_hd2prf_trim(fary_ffuse_hd2prf_trim), 
    .fary_ffuse_rfhs2r2w_trim(fary_ffuse_rfhs2r2w_trim), 
    .fary_ffuse_hdusplr_trim(fary_ffuse_hdusplr_trim), 
    .fary_ffuse_hduspsr_trim(fary_ffuse_hduspsr_trim), 
    .fvisa_unit_id(tail_apr_avisa_unit_id_p1), 
    .i_fwd_sched(tail_apr_o_fwd_sched), 
    .i_rpl_bkwd(tail_apr_o_rpl_bkwd), 
    .i_seg_meta(tail_apr_o_seg_meta), 
    .i_seg_meta_v(tail_apr_o_seg_meta_v), 
    .i_broadcast({lsm_apr_o_switch_powergood_rst_n,lsm_apr_o_switch_mem_rst_n}), 
    .DFT_AFD_RESET_B(lsm_apr_o_switch_powergood_rst_n), 
    .clk(sched_clk_pdop_parhlpsched_clkout), 
    .rst_n(lsm_apr_o_switch_rst_n), 
    .o_cm_apply(sched_apr_o_cm_apply), 
    .o_cm_apply_v(sched_apr_o_cm_apply_v), 
    .o_fixed_sched(sched_apr_o_fixed_sched), 
    .o_fixed_sched_v(sched_apr_o_fixed_sched_v), 
    .o_pm_ctrl(sched_apr_o_pm_ctrl), 
    .o_modify_ecn_v(sched_apr_o_modify_ecn_v), 
    .o_modify_ecn(sched_apr_o_modify_ecn), 
    .o_pause_ripple_v(sched_apr_o_pause_ripple_v), 
    .o_rpl_frwd(sched_apr_o_rpl_frwd), 
    .o_modify_ctrl_v(sched_apr_o_modify_ctrl_v), 
    .o_pause_ripple(sched_apr_o_pause_ripple), 
    .o_modify_ctrl(sched_apr_o_modify_ctrl), 
    .o_rpl_bkwd(sched_apr_o_rpl_bkwd), 
    .o_pfc_xoff(sched_apr_o_pfc_xoff), 
    .o_lfc_xoff(sched_apr_o_lfc_xoff), 
    .fet_ack_b(), 
    .fet_en_b(1'b0), 
    .fdfx_jta_force_latch_mem_fuses(1'b0), 
    .fary_trigger_post(1'b0), 
    .aary_post_complete(), 
    .aary_post_pass(), 
    .clk_rscclk(clkout), 
    .mbist_diag_done(DIAG_AGGR_mbist_diag_done), 
    .fsta_afd_en(1'b0), 
    .DFTMASK(1'b0), 
    .DFTSHIFTEN(1'b0), 
    .DFT_ARRAY_FREEZE(1'b0), 
    .fary_ffuse_rf_sleep(2'b0), 
    .fary_ffuse_sram_sleep(2'b0), 
    .fary_output_reset(1'b0), 
    .fscan_byprst_b(fscan_byprst_b), 
    .fscan_clkgenctrl(fscan_clkgenctrl), 
    .fscan_clkgenctrlen(fscan_clkgenctrlen), 
    .fscan_clkungate(fscan_clkungate), 
    .fscan_clkungate_syn(fscan_clkungate_syn_rtl), 
    .fscan_latchclosed_b(fscan_latchclosed_b), 
    .fscan_latchopen(fscan_latchopen), 
    .fscan_mode(fscan_mode), 
    .fscan_mode_atspeed(fscan_mode_atspeed), 
    .fscan_ram_bypsel_rf(1'b0), 
    .fscan_ram_bypsel_sram(1'b0), 
    .fscan_ram_init_en(fscan_ram_init_en), 
    .fscan_ram_init_val(fscan_ram_init_val), 
    .fscan_ram_rdis_b(1'b0), 
    .fscan_ram_wdis_b(1'b0), 
    .fscan_ret_ctrl(fscan_ret_ctrl), 
    .fscan_rstbypen(fscan_rstbypen), 
    .fscan_sdi(336'b0), 
    .fscan_shiften(1'b0), 
    .fsta_dfxact_afd(1'b0), 
    .fvisa_all_dis(1'b0), 
    .fvisa_customer_dis(1'b0), 
    .fvisa_frame(1'b0), 
    .fvisa_resetb(1'b0), 
    .fvisa_serdata(1'b0), 
    .fvisa_serstb(1'b0), 
    .isol_en_b(1'b0), 
    .pwr_mgmt_in_rf(5'b0), 
    .pwr_mgmt_in_sram(6'b0), 
    .ascan_sdo(), 
    .avisa_clk(), 
    .avisa_dbg_lane(), 
    .avisa_rddata(), 
    .isol_ack_b(), 
   // .visaRt_unit_id_to_parhlpsched_sched_apr_u_sched_apr_func_logic_visa_unit_mux_regout_0(8'b0), 
   // .visaRt_unit_id_to_parhlpsched_sched_apr_u_sched_apr_func_logic_visa_unit_mux_regout_1(8'b0), 
   // .visaRt_cfg_wr_bus_in_to_parhlpsched_sched_apr_sched_ngvisa_top_junc(2'b0), 
   // .visaRt_cfg_rd_bus_out_from_parhlpsched_sched_apr_sched_ngvisa_top_junc(), 
   // .visaRt_cfg_wr_bus_in_from_parhlpsched_sched_apr_sched_ngvisa_top_junc(), 
   // .visaRt_lane_out_from_parhlpsched_sched_apr_sched_ngvisa_top_junc(), 
   // .visaRt_lane_valid_out_from_parhlpsched_sched_apr_sched_ngvisa_top_junc(), 
   // .visaRt_cfg_rd_bus_out_to_parhlpsched_sched_apr(2'b0), 
   // .visaRt_lane_out_to_parhlpsched_sched_apr({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,
   //         1'b0}), 
   // .visaRt_lane_valid_out_to_parhlpsched_sched_apr(2'b0), 
    .fary_ijtag_tck(JT_IN_mbist_ijtag_tck), 
    .fary_ijtag_rst_b(JT_IN_mbist_ijtag_reset_b), 
    .fary_ijtag_capture(JT_IN_mbist_ijtag_capture), 
    .fary_ijtag_shift(JT_IN_mbist_ijtag_shift), 
    .fary_ijtag_update(JT_IN_mbist_ijtag_update), 
    .fary_ijtag_select(sib_sched_apr_to_select), 
    .fary_ijtag_si(JT_IN_mbist_ijtag_si), 
    .aary_ijtag_so(sched_apr_so), 
    .bisr_so_pd_vinf(pd_vinf_bisr_so), 
    .bisr_si_pd_vinf(pd_vinf_bisr_si), 
    .bisr_shift_en_pd_vinf(pd_vinf_bisr_shift_en), 
    .bisr_clk_pd_vinf(pd_vinf_bisr_clk), 
    .bisr_reset_pd_vinf(pd_vinf_bisr_reset)
) ; 
// EDIT_INSTANCE END

// EDIT_CONTINUOUS_ASSIGN BEGIN
assign pd_vinf_bisr_shift_en_out = pd_vinf_bisr_shift_en ; 
assign pd_vinf_bisr_reset_out = pd_vinf_bisr_reset ; 
assign pd_vinf_bisr_clk_out = pd_vinf_bisr_clk ; 
// EDIT_CONTINUOUS_ASSIGN END

  /* Added by UltiBuild Instances Start */
  parhlpsched_ub parhlpsched_ub(
      .secure_group_f(secure_group_f), .sib_scan_so(JT_OUT_scan_ijtag_so), 
                                .sib_sched_apr_so(JT_OUT_mbist_ijtag_so), 
                                .sib_misc_so(JT_OUT_misc_ijtag_so), 
                                .JT_IN_misc_ijtag_si(JT_IN_misc_ijtag_si), 
                                .JT_IN_misc_ijtag_select(JT_IN_misc_ijtag_select), 
                                .JT_IN_mbist_ijtag_si(JT_IN_mbist_ijtag_si), 
                                .sched_apr_so(sched_apr_so), 
                                .JT_IN_mbist_ijtag_select(JT_IN_mbist_ijtag_select), 
                                .JT_IN_scan_ijtag_si(JT_IN_scan_ijtag_si), 
                                .JT_IN_scan_ijtag_select(JT_IN_scan_ijtag_select), 
                                .sib_sched_apr_to_select(sib_sched_apr_to_select), 
                                .JT_IN_scan_ijtag_reset_b(JT_IN_scan_ijtag_reset_b), 
                                .JT_IN_scan_ijtag_capture(JT_IN_scan_ijtag_capture), 
                                .JT_IN_mbist_ijtag_update(JT_IN_mbist_ijtag_update), 
                                .JT_IN_scan_ijtag_shift(JT_IN_scan_ijtag_shift), 
                                .JT_IN_misc_ijtag_tck(JT_IN_misc_ijtag_tck), 
                                .JT_IN_misc_ijtag_update(JT_IN_misc_ijtag_update), 
                                .JT_IN_scan_ijtag_update(JT_IN_scan_ijtag_update), 
                                .JT_IN_misc_ijtag_capture(JT_IN_misc_ijtag_capture), 
                                .JT_IN_misc_ijtag_reset_b(JT_IN_misc_ijtag_reset_b), 
                                .JT_IN_mbist_ijtag_tck(JT_IN_mbist_ijtag_tck), 
                                .JT_IN_misc_ijtag_shift(JT_IN_misc_ijtag_shift), 
                                .JT_IN_mbist_ijtag_capture(JT_IN_mbist_ijtag_capture), 
                                .JT_IN_mbist_ijtag_reset_b(JT_IN_mbist_ijtag_reset_b), 
                                .JT_IN_mbist_ijtag_shift(JT_IN_mbist_ijtag_shift), 
                                .JT_IN_scan_ijtag_tck(JT_IN_scan_ijtag_tck), 
                                .bus_data_out(SSN_END_0_bus_data_out), 
                                .SSN_START_0_bus_data_in(SSN_START_0_bus_data_in), 
                                .SSN_START_0_bus_clock_in(SSN_START_0_bus_clock_in), 
                                .sched_clk_pdop_parhlpsched_fdop_scanclk(sched_clk_pdop_parhlpsched_fdop_scanclk), 
                                .clkout(sched_clk_pdop_parhlpsched_clkout), 
                                .clkfree(clkfree), 
                                .sched_clk_pdop_parhlpsched_fdop_clken(sched_clk_pdop_parhlpsched_fdop_clken), 
                                .mbist_clk_pdop_parhlpsched__clkout_fdop_scanclk(mbist_clk_pdop_parhlpsched__clkout_fdop_scanclk), 
                                .clkout_ts1(clkout), .clkfree_ts1(clkfree_ts1), 
                                .mbist_clk_pdop_parhlpsched__clkout_fdop_clken(mbist_clk_pdop_parhlpsched__clkout_fdop_clken), 
                                .fscan_byprst_b(fscan_byprst_b), 
                                .fscan_clkgenctrl(fscan_clkgenctrl), 
                                .fscan_clkgenctrlen(fscan_clkgenctrlen), 
                                .fscan_clkungate(fscan_clkungate), 
                                .fscan_clkungate_syn_rtl(fscan_clkungate_syn_rtl), 
                                .fscan_latchclosed_b(fscan_latchclosed_b), 
                                .fscan_latchopen(fscan_latchopen), 
                                .fscan_mode(fscan_mode), .fscan_mode_atspeed(fscan_mode_atspeed), 
                                .fscan_ram_init_en(fscan_ram_init_en), 
                                .fscan_ram_init_val(fscan_ram_init_val), 
                                .fscan_ret_ctrl(fscan_ret_ctrl), 
                                .fscan_rstbypen(fscan_rstbypen), .ijtag_tck(ijtag_tck), 
                                .fdfx_powergood(fdfx_powergood)
  );
  /* Added by UltiBuild Instances End */
endmodule
