
/*AUTO_LISP(setq verilog-auto-unused-ignore-regexp
(concat
"^\\("
".*_clk"
"\\|.*aonclk1x"
"\\|.*_rst.*"
"\\|.*_powergood.*"
"\\|.*syscon.*"
"\\|.*hi-f_car_.*_toggle.*"
"\\|.*fuse.*"
"\\|fabric_reset_shield"
"\\|.*_ssn_.*"
"\\|.*_ecc_stop.*"
"\\|.*rxelecidle.*"
"\\|.*pm_linkst.*"
"\\|.*smlh_in_rl0s.*"
"\\|.*syscon.*"
"\\|.*perf_win_sync.*"
"\\)$"
))*/

/*AUTO_LISP(setq verilog-active-low-regexp
(concat
"^\\("
".*pready.*"
"\\)$"
))*/

module parhif_pcie_ss_dwc_idex8_stub(
/*AUTOINOUTMODULE("parhif_pcie_ss_dwc_idex8")*/
// Beginning of automatic in/out/inouts (from specific module)
output [31:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_prdata_out,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pready_out,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pslverr_out,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_ack,
output [31:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_rdata,
output [36:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_ack,
output [31:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_prdata_out,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pready_out,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pslverr_out,
output [15:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_dst_rid,
output [8:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_dst_segment,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_ep,
output [7:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_func_num,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_req,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_selec_link,
output [7:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_stream_id,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_sync_fail,
output [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_tc,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_td,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_th,
output [191:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_control,
output [575:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_data,
output [4:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_data_size,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_dllp_error,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_dp_cor_err,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_dp_unc_err,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_eop,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_halt,
output [503:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_hdr,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_ide_check_failed,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_misrouted_ide_tlp,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_order,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_pcrc_check_failed,
output [3:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_phe_encrypted_addr_size,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_phe_encrypted_be,
output [143:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_prefix,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_report_ide_check_faild,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_sop,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_tdisp_cpl_for_ats_translation_with_tbit_set,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_tdisp_cpl_for_memrd_with_tbit_set,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_tdisp_rcvd_rid_range_check_fail,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_was_on_select_stream,
output [230:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_control,
output [575:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_data,
output [4:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_data_size,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_discard,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_dllp_error,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_dp_cor_err,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_dp_unc_err,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_eop,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_halt,
output [503:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_hdr,
output [107:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_mac,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_merge_pcrc,
output [35:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_pcrc,
output [143:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_prefix,
output			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_sop,
input			core_clk,
input			ide_cfg_flr_rst,
input			ide_core_rst,
input			ide_non_sticky_rst,
input			ide_sticky_rst,
input			pcie_perst_pre_ind_pcie_o_muxd_aux_n,
input			scon_hif_powergood,
input			scon_hifcar_rst_n,
input			soc_per_clk,
input			visa_all_dis,
input			visa_customer_dis,
input			visa_resetb,
input [11:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_paddr_in,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_penable_in,
input [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pprot_in,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_psel_in,
input [31:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pwdata_in,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pwrite_in,
input [9:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_addr,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_cs,
input [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_device_type,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_flit_mode_en,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_from_wire,
input [11:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_ide_dw_next_ptr,
input [11:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_ide_up_next_ptr,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_ro_wr_en,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_segment_captured,
input [7:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_segment_id,
input [8:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_send_stream_to_insecure,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_tee_io_supported,
input [31:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_wdata,
input [3:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_wr_en,
input [107:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req,
input [14:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_paddr_in,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_penable_in,
input [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pprot_in,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_psel_in,
input [31:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pwdata_in,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pwrite_in,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_grant,
input [191:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_control,
input [575:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_data,
input [4:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_data_size,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_dllp_error,
input [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_e2e_prefix_size,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_eop,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_halt,
input [503:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_hdr,
input [3:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_hdr_size,
input [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_local_prefix_size,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_order,
input [143:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_pcrc_mac,
input [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_pcrc_mac_size,
input [143:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_prefix,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_sop,
input [230:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_control,
input [575:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_data,
input [4:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_data_size,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_dllp_error,
input [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_e2e_prefix_size,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_eop,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_halt,
input [503:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_hdr,
input [3:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_hdr_size,
input [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_local_prefix_size,
input [8:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_ohc_req_seg,
input [143:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_prefix,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_sop,
input			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_tlp_t_bit
// End of automatics
//ADDON_INCLUDE_STUB_PORTS
);

assign pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_prdata_out = 'hdeadbeef;
assign pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_apbslv_prdata = 'hdeadbeef;
assign pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_prdata_out = 'hdeadbeef;

wire pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req_valid = pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req[107];
wire [3:0] pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req_opcode = pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req[106:103];

wire pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_ack_read_valid;
wire pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_ack_write_valid;

assign pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_ack_read_valid = (pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req_opcode[0] == 1'b0)&&(|pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req_opcode[3:0]) ? pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req_valid : 1'b0;

assign pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_ack_write_valid = (pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req_opcode[0] == 1'b1)&&(|pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req_opcode[3:0]) ? pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req_valid : 1'b0;

assign pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_ack = {
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_ack_read_valid,
    1'b0,//read_miss
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_ack_write_valid,
    1'b0,//write_miss
    1'b1,//sai_successfull
    32'hdeadbeef
};

/*AUTOTIEOFF*/
// Beginning of automatic tieoffs (for this module's unterminated outputs)
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pready_out= ~1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pslverr_out= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_ack= 1'h0;
wire [31:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_rdata= 32'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pready_out= ~1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pslverr_out= 1'h0;
wire [15:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_dst_rid= 16'h0;
wire [8:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_dst_segment= 9'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_ep= 1'h0;
wire [7:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_func_num= 8'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_req= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_selec_link= 1'h0;
wire [7:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_stream_id= 8'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_sync_fail= 1'h0;
wire [2:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_tc= 3'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_td= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_th= 1'h0;
wire [191:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_control= 192'h0;
wire [575:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_data= 576'h0;
wire [4:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_data_size= 5'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_dllp_error= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_dp_cor_err= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_dp_unc_err= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_eop= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_halt= 1'h0;
wire [503:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_hdr= 504'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_ide_check_failed= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_misrouted_ide_tlp= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_order= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_pcrc_check_failed= 1'h0;
wire [3:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_phe_encrypted_addr_size= 4'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_phe_encrypted_be= 1'h0;
wire [143:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_prefix= 144'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_report_ide_check_faild= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_sop= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_tdisp_cpl_for_ats_translation_with_tbit_set= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_tdisp_cpl_for_memrd_with_tbit_set= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_tdisp_rcvd_rid_range_check_fail= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_rx_was_on_select_stream= 1'h0;
wire [230:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_control= 231'h0;
wire [575:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_data= 576'h0;
wire [4:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_data_size= 5'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_discard= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_dllp_error= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_dp_cor_err= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_dp_unc_err= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_eop= 1'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_halt= 1'h0;
wire [503:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_hdr= 504'h0;
wire [107:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_mac= 108'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_merge_pcrc= 1'h0;
wire [35:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_pcrc= 36'h0;
wire [143:0]		pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_prefix= 144'h0;
wire			pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_pcie_tx_sop= 1'h0;
// End of automatics

//ADDON_INCLUDE_STUB_TIEOFF

`ifndef INTEL_SVA_OFF
`ifdef HIF_ASSERT_STUB_INPUTS_NO_TOGGLE

import intel_checkers_pkg::*;
reg unused_xor_d,sva_clk,sva_rst;
wire unused_xor = ^{
    /*AUTOUNUSED*/
    // Beginning of automatic unused inputs
    pcie_perst_pre_ind_pcie_o_muxd_aux_n,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_paddr_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_penable_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pprot_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_psel_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pwdata_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_aes_hcfg_pwrite_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_addr,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_cs,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_device_type,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_flit_mode_en,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_from_wire,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_ide_dw_next_ptr,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_ide_up_next_ptr,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_ro_wr_en,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_segment_captured,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_segment_id,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_send_stream_to_insecure,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_tee_io_supported,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_wdata,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_cfg_wr_en,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_ctl_regs_req,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_paddr_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_penable_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pprot_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_psel_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pwdata_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_hcfg_pwrite_in,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_ide_msg_grant,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_control,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_data,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_data_size,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_dllp_error,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_e2e_prefix_size,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_eop,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_halt,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_hdr,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_hdr_size,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_local_prefix_size,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_order,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_pcrc_mac,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_pcrc_mac_size,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_prefix,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_rx_sop,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_control,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_data,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_data_size,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_dllp_error,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_e2e_prefix_size,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_eop,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_halt,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_hdr,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_hdr_size,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_local_prefix_size,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_ohc_req_seg,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_prefix,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_sop,
    pcie_ss_dwc_idex8_apr_pcie_ss_dwc_idex8_func_logic_pcie_ss_dwc_idex8_pcie_ide_tx_tlp_t_bit,
    visa_all_dis,
    visa_customer_dis,
    visa_resetb,
    // End of automatics
    1'b0
};

initial sva_clk = 1'b0;
initial begin
    sva_rst = 1'b0;
    #10ns;
    sva_rst = 1'b1;
end

always #1ns sva_clk = ~sva_clk;

always @(posedge sva_clk) unused_xor_d <= unused_xor;

`ASSERTS_FORBIDDEN(hif_stub_inputs_no_toggle, (unused_xor_d !== unused_xor) , sva_clk, ~sva_rst, `ERR_MSG("Stub input toggle"));

`endif//`ifdef HIF_ASSERT_STUB_INPUTS_NO_TOGGLE
`endif//`ifndef INTEL_SVA_OFF

endmodule

// Local Variables:
// verilog-library-files:("/nfs/site/disks/nhdk.zsc7.mmg800.ipm.211/hif/hif_r15_pre_dft-mmg800-a0-25ww22a/output/hif_core/collage/trial/gen/rtl/parhif_pcie_ss_dwc_idex8.sv")
// end:

