/*------------------------------------------------------------------------------
  INTEL CONFIDENTIAL
  Copyright 2022 Intel Corporation All Rights Reserved.
  -----------------------------------------------------------------------------*/

module parhlptail
// EDIT_PORT BEGIN
 ( 
input clk,
input pd_vinf_bisr_si,
input pd_vinf_bisr_reset,
input pd_vinf_bisr_clk,
input pd_vinf_bisr_shift_en,
output pd_vinf_bisr_so,
output pd_vinf_bisr_clk_out,
output pd_vinf_bisr_reset_out,
output pd_vinf_bisr_shift_en_out,
input JT_IN_mbist_ijtag_reset_b,
input JT_IN_mbist_ijtag_tck,
input JT_IN_mbist_ijtag_select,
input JT_IN_mbist_ijtag_capture,
input JT_IN_mbist_ijtag_shift,
input JT_IN_mbist_ijtag_update,
input JT_IN_mbist_ijtag_si,
input JT_IN_misc_ijtag_reset_b,
input JT_IN_misc_ijtag_tck,
input JT_IN_misc_ijtag_select,
input JT_IN_misc_ijtag_capture,
input JT_IN_misc_ijtag_shift,
input JT_IN_misc_ijtag_update,
input JT_IN_misc_ijtag_si,
input JT_IN_scan_ijtag_reset_b,
input JT_IN_scan_ijtag_tck,
input JT_IN_scan_ijtag_select,
input JT_IN_scan_ijtag_capture,
input JT_IN_scan_ijtag_shift,
input JT_IN_scan_ijtag_update,
input JT_IN_scan_ijtag_si,
output JT_OUT_mbist_ijtag_so,
output JT_OUT_misc_ijtag_so,
output JT_OUT_scan_ijtag_so,
input fdfx_powergood,
input secure_group_a,
input secure_group_b,
input secure_group_c,
input secure_group_d,
input secure_group_e,
input secure_group_g,
input secure_group_h,
input secure_group_f,
input secure_group_z,
output DIAG_AGGR_mbist_diag_done,
input SSN_START_0_bus_clock_in,
input [31:0] SSN_START_0_bus_data_in,
output [31:0] SSN_END_0_bus_data_out,
input wire i_hlp_dts_diode1_anode, //CI
inout tri i_hlp_dts_diode1_cathode,
output tail_apr_o_hlp_dts_diode1_anode,
output tail_apr_o_hlp_dts_diode1_cathode,
input [16:0] fary_ffuse_hduspsr_trim,
input [6:0] fary_ffuse_hd2prf_trim,
output [8:0] tail_apr_avisa_unit_id_p1,
output [1903:0] tail_apr_o_cm_apply,
output tail_apr_o_cm_apply_v,
output [130:0] tail_apr_o_fwd_sched,
output [0:0] tail_apr_o_rpl_bkwd,
output [130:0] tail_apr_o_rpl_frwd,
output [23:0] tail_apr_o_seg_meta,
output tail_apr_o_seg_meta_v,
output [521:0] tail_apr_o_sop_info,
output tail_apr_o_sop_info_v,
output [8:0] tail_apr_o_tail_to_l2l,
output tail_apr_o_tail_to_l2l_v,
output [15:0] tail_apr_o_tail_to_trig,
output [5:0] tail_apr_o_tail_to_lag,
input lsm_apr_o_switch_rst_n,
input lsm_apr_o_switch_mem_rst_n,
input lsm_apr_o_switch_powergood_rst_n,
input [676:0] fwd_apr_o_fwd_to_tail,
input fwd_apr_o_fwd_to_tail_v,
input [197:0] fwd_apr_o_pol_in_early,
input fwd_apr_o_pol_in_early_v,
input [0:0] fwd_apr_o_rpl_bkwd,
input [77:0] fwd_apr_o_tail_info,
input fwd_apr_o_tail_info_v,
input [1903:0] sched_apr_o_cm_apply,
input sched_apr_o_cm_apply_v,
input [130:0] sched_apr_o_rpl_frwd );
// EDIT_PORT END


// EDIT_NET BEGIN
logic tail_clk_pdop_parhlptail_clkout ; 
// EDIT_NET END

// EDIT_INSTANCE BEGIN

  /* Added by UltiBuild Nets Start */
  wire tail_apr_so, sib_tail_apr_to_select, 
       tail_clk_pdop_parhlptail_fdop_scanclk, clkfree, 
       tail_clk_pdop_parhlptail_fdop_clken, 
       mbist_clk_pdop_parhlptail__clkout_fdop_scanclk, clkout, clkfree_ts1, 
       mbist_clk_pdop_parhlptail__clkout_fdop_clken, fscan_byprst_b, 
       fscan_clkgenctrl, fscan_clkgenctrlen, fscan_clkungate, 
       fscan_clkungate_syn_rtl, fscan_latchclosed_b, fscan_latchopen, 
       fscan_mode, fscan_mode_atspeed, fscan_ram_init_en, fscan_ram_init_val, 
       fscan_ret_ctrl, fscan_rstbypen, ijtag_tck;
  /* Added by UltiBuild Nets End */
pdop mbist_clk_pdop_parhlptail (
    .clken(mbist_clk_pdop_parhlptail__clkout_fdop_clken), 
    .clkenfree(1'b0), 
    .clkfree(clkfree_ts1), 
    .clkin(ijtag_tck), 
    .clkout(clkout), 
    .scanclk(mbist_clk_pdop_parhlptail__clkout_fdop_scanclk), 
    .soft_high_out()
) ; 
pdop tail_clk_pdop_parhlptail (
    .clkin(clk), 
    .clkout(tail_clk_pdop_parhlptail_clkout), 
    .clken(tail_clk_pdop_parhlptail_fdop_clken), 
    .clkenfree(1'b1), 
    .clkfree(clkfree), 
    .scanclk(tail_clk_pdop_parhlptail_fdop_scanclk), 
    .soft_high_out()
) ; 
hlp_tail_apr tail_apr (
    .i_hlp_dts_diode1_anode(i_hlp_dts_diode1_anode), 
    .i_hlp_dts_diode1_cathode(i_hlp_dts_diode1_cathode), 
    .o_hlp_dts_diode1_anode(tail_apr_o_hlp_dts_diode1_anode), 
    .o_hlp_dts_diode1_cathode(tail_apr_o_hlp_dts_diode1_cathode), 
    .fary_ffuse_hduspsr_trim(fary_ffuse_hduspsr_trim), 
    .fary_ffuse_hd2prf_trim(fary_ffuse_hd2prf_trim), 
    .avisa_unit_id_p1(tail_apr_avisa_unit_id_p1), 
    .o_cm_apply(tail_apr_o_cm_apply), 
    .o_cm_apply_v(tail_apr_o_cm_apply_v), 
    .o_fwd_sched(tail_apr_o_fwd_sched), 
    .o_rpl_bkwd(tail_apr_o_rpl_bkwd), 
    .o_rpl_frwd(tail_apr_o_rpl_frwd), 
    .o_seg_meta(tail_apr_o_seg_meta), 
    .o_seg_meta_v(tail_apr_o_seg_meta_v), 
    .o_sop_info(tail_apr_o_sop_info), 
    .o_sop_info_v(tail_apr_o_sop_info_v), 
    .o_tail_to_l2l(tail_apr_o_tail_to_l2l), 
    .o_tail_to_l2l_v(tail_apr_o_tail_to_l2l_v), 
    .o_tail_to_trig(tail_apr_o_tail_to_trig), 
    .o_tail_to_lag(tail_apr_o_tail_to_lag), 
    .clk(tail_clk_pdop_parhlptail_clkout), 
    .rst_n(lsm_apr_o_switch_rst_n), 
    .i_broadcast({lsm_apr_o_switch_powergood_rst_n,lsm_apr_o_switch_mem_rst_n}), 
    .DFT_AFD_RESET_B(lsm_apr_o_switch_powergood_rst_n), 
    .i_fwd_to_tail(fwd_apr_o_fwd_to_tail), 
    .i_fwd_to_tail_v(fwd_apr_o_fwd_to_tail_v), 
    .i_pol_in_early(fwd_apr_o_pol_in_early), 
    .i_pol_in_early_v(fwd_apr_o_pol_in_early_v), 
    .i_rpl_bkwd(fwd_apr_o_rpl_bkwd), 
    .i_tail_info(fwd_apr_o_tail_info), 
    .i_tail_info_v(fwd_apr_o_tail_info_v), 
    .i_cm_apply(sched_apr_o_cm_apply), 
    .i_cm_apply_v(sched_apr_o_cm_apply_v), 
    .i_rpl_frwd(sched_apr_o_rpl_frwd), 
    .fet_ack_b(), 
    .fet_en_b(1'b0), 
    .fdfx_jta_force_latch_mem_fuses(1'b0), 
    .fary_trigger_post(1'b0), 
    .aary_post_complete(), 
    .aary_post_pass(), 
    .clk_rscclk(clkout), 
    .mbist_diag_done(DIAG_AGGR_mbist_diag_done), 
    .fsta_afd_en(1'b0), 
    .DFTMASK(1'b0), 
    .DFTSHIFTEN(1'b0), 
    .DFT_ARRAY_FREEZE(1'b0), 
    .fary_ffuse_hdusplr_trim(17'b0), 
    .fary_ffuse_rf_sleep(2'b0), 
    .fary_ffuse_sram_sleep(2'b0), 
    .fary_output_reset(1'b0), 
    .fscan_byprst_b(fscan_byprst_b), 
    .fscan_clkgenctrl(fscan_clkgenctrl), 
    .fscan_clkgenctrlen(fscan_clkgenctrlen), 
    .fscan_clkungate(fscan_clkungate), 
    .fscan_clkungate_syn(fscan_clkungate_syn_rtl), 
    .fscan_latchclosed_b(fscan_latchclosed_b), 
    .fscan_latchopen(fscan_latchopen), 
    .fscan_mode(fscan_mode), 
    .fscan_mode_atspeed(fscan_mode_atspeed), 
    .fscan_ram_bypsel_rf(1'b0), 
    .fscan_ram_bypsel_sram(1'b0), 
    .fscan_ram_init_en(fscan_ram_init_en), 
    .fscan_ram_init_val(fscan_ram_init_val), 
    .fscan_ram_rdis_b(1'b0), 
    .fscan_ram_wdis_b(1'b0), 
    .fscan_ret_ctrl(fscan_ret_ctrl), 
    .fscan_rstbypen(fscan_rstbypen), 
    .fscan_sdi(192'b0), 
    .fscan_shiften(1'b0), 
    .fsta_dfxact_afd(1'b0), 
    .fvisa_all_dis(1'b0), 
    .fvisa_clk(4'b0), 
    .fvisa_customer_dis(1'b0), 
    .fvisa_dbg_lane(32'b0), 
    .fvisa_frame(1'b0), 
    .fvisa_rddata(1'b0), 
    .fvisa_resetb(1'b0), 
    .fvisa_serdata(1'b0), 
    .fvisa_serstb(1'b0), 
    .fvisa_unit_id(9'b0), 
    .isol_en_b(1'b0), 
    .pwr_mgmt_in_rf(5'b0), 
    .pwr_mgmt_in_sram(6'b0), 
    .ascan_sdo(), 
    .avisa_all_dis(), 
    .avisa_clk(), 
    .avisa_customer_dis(), 
    .avisa_dbg_lane(), 
    .avisa_frame(), 
    .avisa_rddata(), 
    .avisa_serdata(), 
    .avisa_serstb(), 
    .isol_ack_b(), 
   // .visaRt_unit_id_to_parhlptail_tail_apr_u_tail_apr_func_logic_visa_unit_mux_regout_0(8'b0), 
   // .visaRt_unit_id_to_parhlptail_tail_apr_u_tail_apr_func_logic_visa_unit_mux_regout_1(8'b0), 
   // .visaRt_cfg_rd_bus_out_to_parhlptail_tail_apr(2'b0), 
   // .visaRt_lane_out_to_parhlptail_tail_apr({1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,1'b0,
   //         1'b0}), 
   // .visaRt_lane_valid_out_to_parhlptail_tail_apr(2'b0), 
   // .visaRt_cfg_wr_bus_in_to_parhlptail_tail_apr_tail_ngvisa_top_junc(2'b0), 
   // .visaRt_cfg_rd_bus_out_from_parhlptail_tail_apr_tail_ngvisa_top_junc(), 
   // .visaRt_cfg_wr_bus_in_from_parhlptail_tail_apr_tail_ngvisa_top_junc(), 
   // .visaRt_lane_out_from_parhlptail_tail_apr_tail_ngvisa_top_junc(), 
   // .visaRt_lane_valid_out_from_parhlptail_tail_apr_tail_ngvisa_top_junc(), 
    .fary_ijtag_tck(JT_IN_mbist_ijtag_tck), 
    .fary_ijtag_rst_b(JT_IN_mbist_ijtag_reset_b), 
    .fary_ijtag_capture(JT_IN_mbist_ijtag_capture), 
    .fary_ijtag_shift(JT_IN_mbist_ijtag_shift), 
    .fary_ijtag_update(JT_IN_mbist_ijtag_update), 
    .fary_ijtag_select(sib_tail_apr_to_select), 
    .fary_ijtag_si(JT_IN_mbist_ijtag_si), 
    .aary_ijtag_so(tail_apr_so), 
    .bisr_so_pd_vinf(pd_vinf_bisr_so), 
    .bisr_si_pd_vinf(pd_vinf_bisr_si), 
    .bisr_shift_en_pd_vinf(pd_vinf_bisr_shift_en), 
    .bisr_clk_pd_vinf(pd_vinf_bisr_clk), 
    .bisr_reset_pd_vinf(pd_vinf_bisr_reset)
) ; 
// EDIT_INSTANCE END

// EDIT_CONTINUOUS_ASSIGN BEGIN
assign pd_vinf_bisr_shift_en_out = pd_vinf_bisr_shift_en ; 
assign pd_vinf_bisr_reset_out = pd_vinf_bisr_reset ; 
assign pd_vinf_bisr_clk_out = pd_vinf_bisr_clk ; 
// EDIT_CONTINUOUS_ASSIGN END

  /* Added by UltiBuild Instances Start */
  parhlptail_ub parhlptail_ub(
      .secure_group_f(secure_group_f), .sib_scan_so(JT_OUT_scan_ijtag_so), 
                              .sib_tail_apr_so(JT_OUT_mbist_ijtag_so), 
                              .parhlptail_rtl2_tessent_sib_upm_inst_so(JT_OUT_misc_ijtag_so), 
                              .JT_IN_misc_ijtag_si(JT_IN_misc_ijtag_si), 
                              .JT_IN_misc_ijtag_select(JT_IN_misc_ijtag_select), 
                              .JT_IN_mbist_ijtag_si(JT_IN_mbist_ijtag_si), 
                              .tail_apr_so(tail_apr_so), 
                              .JT_IN_mbist_ijtag_select(JT_IN_mbist_ijtag_select), 
                              .JT_IN_scan_ijtag_si(JT_IN_scan_ijtag_si), 
                              .JT_IN_scan_ijtag_select(JT_IN_scan_ijtag_select), 
                              .sib_tail_apr_to_select(sib_tail_apr_to_select), 
                              .JT_IN_scan_ijtag_reset_b(JT_IN_scan_ijtag_reset_b), 
                              .JT_IN_scan_ijtag_capture(JT_IN_scan_ijtag_capture), 
                              .JT_IN_mbist_ijtag_update(JT_IN_mbist_ijtag_update), 
                              .JT_IN_scan_ijtag_shift(JT_IN_scan_ijtag_shift), 
                              .JT_IN_misc_ijtag_tck(JT_IN_misc_ijtag_tck), 
                              .JT_IN_misc_ijtag_update(JT_IN_misc_ijtag_update), 
                              .JT_IN_scan_ijtag_update(JT_IN_scan_ijtag_update), 
                              .JT_IN_misc_ijtag_capture(JT_IN_misc_ijtag_capture), 
                              .JT_IN_misc_ijtag_reset_b(JT_IN_misc_ijtag_reset_b), 
                              .JT_IN_mbist_ijtag_tck(JT_IN_mbist_ijtag_tck), 
                              .JT_IN_misc_ijtag_shift(JT_IN_misc_ijtag_shift), 
                              .JT_IN_mbist_ijtag_capture(JT_IN_mbist_ijtag_capture), 
                              .JT_IN_mbist_ijtag_reset_b(JT_IN_mbist_ijtag_reset_b), 
                              .JT_IN_mbist_ijtag_shift(JT_IN_mbist_ijtag_shift), 
                              .JT_IN_scan_ijtag_tck(JT_IN_scan_ijtag_tck), 
                              .bus_data_out(SSN_END_0_bus_data_out), 
                              .SSN_START_0_bus_data_in(SSN_START_0_bus_data_in), 
                              .SSN_START_0_bus_clock_in(SSN_START_0_bus_clock_in), 
                              .tail_clk_pdop_parhlptail_fdop_scanclk(tail_clk_pdop_parhlptail_fdop_scanclk), 
                              .clkout(tail_clk_pdop_parhlptail_clkout), 
                              .clkfree(clkfree), 
                              .tail_clk_pdop_parhlptail_fdop_clken(tail_clk_pdop_parhlptail_fdop_clken), 
                              .mbist_clk_pdop_parhlptail__clkout_fdop_scanclk(mbist_clk_pdop_parhlptail__clkout_fdop_scanclk), 
                              .clkout_ts1(clkout), .clkfree_ts1(clkfree_ts1), 
                              .mbist_clk_pdop_parhlptail__clkout_fdop_clken(mbist_clk_pdop_parhlptail__clkout_fdop_clken), 
                              .fscan_byprst_b(fscan_byprst_b), 
                              .fscan_clkgenctrl(fscan_clkgenctrl), 
                              .fscan_clkgenctrlen(fscan_clkgenctrlen), 
                              .fscan_clkungate(fscan_clkungate), 
                              .fscan_clkungate_syn_rtl(fscan_clkungate_syn_rtl), 
                              .fscan_latchclosed_b(fscan_latchclosed_b), 
                              .fscan_latchopen(fscan_latchopen), .fscan_mode(fscan_mode), 
                              .fscan_mode_atspeed(fscan_mode_atspeed), 
                              .fscan_ram_init_en(fscan_ram_init_en), 
                              .fscan_ram_init_val(fscan_ram_init_val), 
                              .fscan_ret_ctrl(fscan_ret_ctrl), 
                              .fscan_rstbypen(fscan_rstbypen), .ijtag_tck(ijtag_tck), 
                              .fdfx_powergood(fdfx_powergood)
  );
  /* Added by UltiBuild Instances End */
endmodule
