
/*AUTO_LISP(setq verilog-auto-unused-ignore-regexp
(concat
"^\\("
".*_clk"
"\\|.*aonclk1x"
"\\|.*_rst.*"
"\\|.*_powergood.*"
"\\|.*syscon.*"
"\\|.*hi-f_car_.*_toggle.*"
"\\|.*fuse.*"
"\\|fabric_reset_shield"
"\\|.*_ssn_.*"
"\\|.*_ecc_stop.*"
"\\|.*rxelecidle.*"
"\\|.*pm_linkst.*"
"\\|.*smlh_in_rl0s.*"
"\\|.*syscon.*"
"\\|.*perf_win_sync.*"
"\\)$"
))*/

/*AUTO_LISP(setq verilog-active-low-regexp
(concat
"^\\("
".*pready.*"
"\\)$"
))*/

module parhif_pcie_ss_dwc_ctlx2x2_stub(
/*AUTOINOUTMODULE("parhif_pcie_ss_dwc_ctlx2x2")*/
// Beginning of automatic in/out/inouts (from specific module)
output [1:0]		phy_pcie0_pipe_clk,
output [1:0]		phy_pcie1_pipe_clk,
output [31:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_prdata,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pready,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pslverr,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_abort,
output [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_data,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_dlp_abort,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_dv,
output [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_dwen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_ecrc_err,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_eot,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_fm_format,
output [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_hdr,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_hv,
output [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_hwen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_nullified,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_poisoned,
output [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_porder,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_soh,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_status,
output [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_trailer,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_twen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_abort,
output [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_data,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_dlp_abort,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_dv,
output [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_dwen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_ecrc_err,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_eot,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_fm_format,
output [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_hdr,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_hv,
output [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_hwen,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_in_membar_range,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_io_req_in_range,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_nullified,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_poisoned,
output [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_porder,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_rom_in_range,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_soh,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_status,
output [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_trailer,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_twen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_abort,
output [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_data,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_dlp_abort,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_dv,
output [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_dwen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_ecrc_err,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_eot,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_fm_format,
output [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_hdr,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_hv,
output [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_hwen,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_in_membar_range,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_io_req_in_range,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_nullified,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_pending,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_poisoned,
output [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_porder,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_rom_in_range,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_soh,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_status,
output [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_trailer,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_twen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_halt,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_halt,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_halt,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_aspm_event,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_bme_change,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_cfg_2nd_reset,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_cfg_cii_access,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_hp_pme,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_hp_slot_ctrl_access,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_link_req_rst_not,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_link_up,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_pcie_int,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_phy_sram_ecc_int,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_spare0,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_spare1,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_spare2,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_spare3,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_phy_rxelecidle,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_pm_linkst_in_l0s,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_pm_linkst_in_l1,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_pm_linkst_in_l2,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_smlh_in_rl0s,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_asyncpowerchangeack,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_commonclock_enable,
output [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_messagebus,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_pclk_rate,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_pclkchangeack,
output [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_powerdown,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_rate,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_rxelecidle_disable,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_rxstandby,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_rxwidth,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_serdes_arch,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_sris_enable,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txcommonmode_disable,
output [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txdata,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txdatavalid,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txdetectrx_loopback,
output [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txelecidle,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_width,
output [36:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_ack,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_o_core_rst_n,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_o_muxd_aux_clk,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_perst_pre_ind_nss_hif_n,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_perst_pre_ind_pcie_o_muxd_aux_n,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_reset_n,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_rst_n,
output [11:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_rtlh_fc_allctd_pd,
output [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_rtlh_fc_allctd_ph,
output [11:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_rtlh_fc_rcvd_pd,
output [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_rtlh_fc_rcvd_ph,
output [31:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_prdata,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pready,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pslverr,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_abort,
output [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_data,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_dlp_abort,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_dv,
output [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_dwen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_ecrc_err,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_eot,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_fm_format,
output [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_hdr,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_hv,
output [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_hwen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_nullified,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_poisoned,
output [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_porder,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_soh,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_status,
output [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_trailer,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_twen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_abort,
output [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_data,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_dlp_abort,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_dv,
output [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_dwen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_ecrc_err,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_eot,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_fm_format,
output [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_hdr,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_hv,
output [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_hwen,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_in_membar_range,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_io_req_in_range,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_nullified,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_poisoned,
output [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_porder,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_rom_in_range,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_soh,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_status,
output [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_trailer,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_twen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_abort,
output [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_data,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_dlp_abort,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_dv,
output [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_dwen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_ecrc_err,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_eot,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_fm_format,
output [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_hdr,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_hv,
output [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_hwen,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_in_membar_range,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_io_req_in_range,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_nullified,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_pending,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_poisoned,
output [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_porder,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_rom_in_range,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_soh,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_status,
output [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_trailer,
output [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_twen,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_halt,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_halt,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_halt,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_aspm_event,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_bme_change,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_cfg_2nd_reset,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_cfg_cii_access,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_hp_pme,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_hp_slot_ctrl_access,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_link_req_rst_not,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_link_up,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_pcie_int,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_phy_sram_ecc_int,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_spare0,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_spare1,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_spare2,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_spare3,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_phy_rxelecidle,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_pm_linkst_in_l0s,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_pm_linkst_in_l1,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_pm_linkst_in_l2,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_smlh_in_rl0s,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_asyncpowerchangeack,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_commonclock_enable,
output [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_messagebus,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_pclk_rate,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_pclkchangeack,
output [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_powerdown,
output [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_rate,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_rxelecidle_disable,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_rxstandby,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_rxwidth,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_serdes_arch,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_sris_enable,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txcommonmode_disable,
output [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txdata,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txdatavalid,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txdetectrx_loopback,
output [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txelecidle,
output [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_width,
output [36:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_ack,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_o_core_rst_n,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_o_muxd_aux_clk,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_perst_pre_ind_nss_hif_n,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_perst_pre_ind_pcie_o_muxd_aux_n,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_reset_n,
output			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_rst_n,
output [11:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_rtlh_fc_allctd_pd,
output [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_rtlh_fc_allctd_ph,
output [11:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_rtlh_fc_rcvd_pd,
output [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_rtlh_fc_rcvd_ph,
input			aonclk1x,
input			nss_hif_clk,
input			phy_pcie0_max_pclk,
input [1:0]		phy_pcie0_pipe_rx_clk,
input			phy_pcie1_max_pclk,
input [1:0]		phy_pcie1_pipe_rx_clk,
input			scon_hif_powergood,
input			scon_hifcar_rst_n,
input			soc_per_clk,
input			visa_all_dis,
input			visa_customer_dis,
input			visa_resetb,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_apr_mem_pcie_ss_dwc_ff_memsx2_0_scon_hif_powergood,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_acc_perst_n,
input [31:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_paddr,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_penable,
input [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pprot,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_psel,
input [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pstrb,
input [31:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pwdata,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pwrite,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_halt,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_halt,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_halt,
input [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_data,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_dv,
input [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_dwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_ecrc_err,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_ecrc_gen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_eot,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_fm_format,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_grant,
input [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_hdr,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_hv,
input [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_hwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_nullified,
input [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_order_seqnum,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_poisoned,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_soh,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_t_bit,
input [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_tlp_trailer,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_twen,
input [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_data,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_dv,
input [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_dwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_ecrc_err,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_ecrc_gen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_eot,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_fm_format,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_grant,
input [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_hdr,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_hv,
input [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_hwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_nullified,
input [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_order_seqnum,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_poisoned,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_soh,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_t_bit,
input [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_tlp_trailer,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_twen,
input [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_data,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_dv,
input [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_dwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_ecrc_err,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_ecrc_gen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_eot,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_fm_format,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_grant,
input [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_hdr,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_hv,
input [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_hwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_nullified,
input [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_order_seqnum,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_poisoned,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_soh,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_t_bit,
input [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_tlp_trailer,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_twen,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_ext_phy_rxelecidle,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_ext_pm_linkst_in_l0s,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_ext_pm_linkst_in_l1,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_ext_pm_linkst_in_l2,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_ext_smlh_in_rl0s,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_fuse_ide_disable,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_fuse_pcie_ss_disable,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_fuse_rp_disable,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_car_1us_toggle,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_PERST_n0,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_PERST_n1,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_PERST_n2,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_PERST_n3,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_upp_shim_xfer_pending,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_upp_xfer_pending,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_imc_perst_n,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_nss_hif_div_clk_en,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_nss_hif_div_clk_sel,
input [107:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_perf_win_sync,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_messagebus,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_pclkchangeok,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_phystatus,
input [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_rxdata,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_rxelecidle,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_rxstandbystatus,
input [5:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_rxstatus,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_rxvalid,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_syscon_Int_only_l2_dis,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_syscon_dfd_l0_dis,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_syscon_dfd_l1_dis,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_acc_perst_n,
input [31:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_paddr,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_penable,
input [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pprot,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_psel,
input [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pstrb,
input [31:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pwdata,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pwrite,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_halt,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_halt,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_halt,
input [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_data,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_dv,
input [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_dwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_ecrc_err,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_ecrc_gen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_eot,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_fm_format,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_grant,
input [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_hdr,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_hv,
input [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_hwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_nullified,
input [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_order_seqnum,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_poisoned,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_soh,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_t_bit,
input [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_tlp_trailer,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_twen,
input [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_data,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_dv,
input [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_dwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_ecrc_err,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_ecrc_gen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_eot,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_fm_format,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_grant,
input [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_hdr,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_hv,
input [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_hwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_nullified,
input [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_order_seqnum,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_poisoned,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_soh,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_t_bit,
input [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_tlp_trailer,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_twen,
input [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_data,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_dv,
input [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_dwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_ecrc_err,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_ecrc_gen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_eot,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_fm_format,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_grant,
input [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_hdr,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_hv,
input [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_hwen,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_nullified,
input [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_order_seqnum,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_poisoned,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_soh,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_t_bit,
input [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_tlp_trailer,
input [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_twen,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_ext_phy_rxelecidle,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_ext_pm_linkst_in_l0s,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_ext_pm_linkst_in_l1,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_ext_pm_linkst_in_l2,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_ext_smlh_in_rl0s,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_fuse_ide_disable,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_fuse_pcie_ss_disable,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_fuse_rp_disable,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_car_1us_toggle,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_PERST_n0,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_PERST_n1,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_PERST_n2,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_PERST_n3,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_upp_shim_xfer_pending,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_upp_xfer_pending,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_imc_perst_n,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_nss_hif_div_clk_en,
input			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_nss_hif_div_clk_sel,
input [107:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req,
input [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_messagebus,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_pclkchangeok,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_phystatus,
input [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_rxdata,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_rxelecidle,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_rxstandbystatus,
input [5:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_rxstatus,
input [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_rxvalid
// End of automatics
//ADDON_INCLUDE_STUB_PORTS
);

assign pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_prdata = 'hdeadbeef;
assign pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_prdata = 'hdeadbeef;


wire pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req_valid = pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req[107];
wire [3:0] pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req_opcode = pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req[106:103];

wire pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_ack_read_valid;
wire pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_ack_write_valid;

assign pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_ack_read_valid = (pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req_opcode[0] == 1'b0)&&(|pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req_opcode[3:0]) ? pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req_valid : 1'b0;

assign pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_ack_write_valid = (pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req_opcode[0] == 1'b1)&&(|pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req_opcode[3:0]) ? pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req_valid : 1'b0;

assign pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_ack = {
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_ack_read_valid,
    1'b0,//read_miss
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_ack_write_valid,
    1'b0,//write_miss
    1'b1,//sai_successfull
    32'hdeadbeef
};

wire pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req_valid = pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req[107];
wire [3:0] pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req_opcode = pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req[106:103];

wire pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_ack_read_valid;
wire pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_ack_write_valid;

assign pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_ack_read_valid = (pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req_opcode[0] == 1'b0)&&(|pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req_opcode[3:0]) ? pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req_valid : 1'b0;

assign pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_ack_write_valid = (pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req_opcode[0] == 1'b1)&&(|pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req_opcode[3:0]) ? pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req_valid : 1'b0;

assign pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_ack = {
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_ack_read_valid,
    1'b0,//read_miss
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_ack_write_valid,
    1'b0,//write_miss
    1'b1,//sai_successfull
    32'hdeadbeef
};

/*AUTOTIEOFF*/
// Beginning of automatic tieoffs (for this module's unterminated outputs)
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pready= ~1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pslverr= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_abort= 1'h0;
wire [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_data= 128'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_dlp_abort= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_dv= 1'h0;
wire [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_dwen= 4'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_ecrc_err= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_eot= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_fm_format= 1'h0;
wire [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_hdr= 448'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_hv= 1'h0;
wire [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_hwen= 14'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_nullified= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_poisoned= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_porder= 16'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_soh= 5'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_status= 3'h0;
wire [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_trailer= 160'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_twen= 5'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_abort= 1'h0;
wire [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_data= 128'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_dlp_abort= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_dv= 1'h0;
wire [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_dwen= 4'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_ecrc_err= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_eot= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_fm_format= 1'h0;
wire [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_hdr= 448'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_hv= 1'h0;
wire [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_hwen= 14'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_in_membar_range= 3'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_io_req_in_range= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_nullified= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_poisoned= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_porder= 16'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_rom_in_range= 1'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_soh= 5'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_status= 3'h0;
wire [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_trailer= 160'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_twen= 5'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_abort= 1'h0;
wire [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_data= 128'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_dlp_abort= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_dv= 1'h0;
wire [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_dwen= 4'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_ecrc_err= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_eot= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_fm_format= 1'h0;
wire [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_hdr= 448'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_hv= 1'h0;
wire [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_hwen= 14'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_in_membar_range= 3'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_io_req_in_range= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_nullified= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_pending= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_poisoned= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_porder= 16'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_rom_in_range= 1'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_soh= 5'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_status= 3'h0;
wire [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_trailer= 160'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_twen= 5'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_halt= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_halt= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_halt= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_aspm_event= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_bme_change= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_cfg_2nd_reset= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_cfg_cii_access= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_hp_pme= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_hp_slot_ctrl_access= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_link_req_rst_not= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_link_up= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_pcie_int= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_phy_sram_ecc_int= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_spare0= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_spare1= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_spare2= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_sw_spare3= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_phy_rxelecidle= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_pm_linkst_in_l0s= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_pm_linkst_in_l1= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_pm_linkst_in_l2= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_local_smlh_in_rl0s= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_asyncpowerchangeack= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_commonclock_enable= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_messagebus= 16'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_pclk_rate= 3'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_pclkchangeack= 2'h0;
wire [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_powerdown= 4'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_rate= 3'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_rxelecidle_disable= 1'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_rxstandby= 2'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_rxwidth= 2'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_serdes_arch= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_sris_enable= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txcommonmode_disable= 1'h0;
wire [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txdata= 160'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txdatavalid= 2'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txdetectrx_loopback= 2'h0;
wire [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_txelecidle= 8'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_mac_phy_width= 2'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_o_core_rst_n= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_o_muxd_aux_clk= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_perst_pre_ind_nss_hif_n= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_perst_pre_ind_pcie_o_muxd_aux_n= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_reset_n= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_rst_n= 1'h0;
wire [11:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_rtlh_fc_allctd_pd= 12'h0;
wire [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_rtlh_fc_allctd_ph= 8'h0;
wire [11:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_rtlh_fc_rcvd_pd= 12'h0;
wire [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_rtlh_fc_rcvd_ph= 8'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pready= ~1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pslverr= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_abort= 1'h0;
wire [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_data= 128'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_dlp_abort= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_dv= 1'h0;
wire [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_dwen= 4'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_ecrc_err= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_eot= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_fm_format= 1'h0;
wire [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_hdr= 448'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_hv= 1'h0;
wire [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_hwen= 14'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_nullified= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_poisoned= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_porder= 16'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_soh= 5'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_status= 3'h0;
wire [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_trailer= 160'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_twen= 5'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_abort= 1'h0;
wire [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_data= 128'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_dlp_abort= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_dv= 1'h0;
wire [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_dwen= 4'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_ecrc_err= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_eot= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_fm_format= 1'h0;
wire [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_hdr= 448'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_hv= 1'h0;
wire [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_hwen= 14'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_in_membar_range= 3'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_io_req_in_range= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_nullified= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_poisoned= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_porder= 16'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_rom_in_range= 1'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_soh= 5'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_status= 3'h0;
wire [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_trailer= 160'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_twen= 5'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_abort= 1'h0;
wire [127:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_data= 128'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_dlp_abort= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_dv= 1'h0;
wire [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_dwen= 4'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_ecrc_err= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_eot= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_fm_format= 1'h0;
wire [447:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_hdr= 448'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_hv= 1'h0;
wire [13:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_hwen= 14'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_in_membar_range= 3'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_io_req_in_range= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_nullified= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_pending= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_poisoned= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_porder= 16'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_rom_in_range= 1'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_soh= 5'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_status= 3'h0;
wire [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_trailer= 160'h0;
wire [4:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_twen= 5'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_halt= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_halt= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_halt= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_aspm_event= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_bme_change= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_cfg_2nd_reset= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_cfg_cii_access= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_hp_pme= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_hp_slot_ctrl_access= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_link_req_rst_not= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_link_up= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_pcie_int= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_phy_sram_ecc_int= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_spare0= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_spare1= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_spare2= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_sw_spare3= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_phy_rxelecidle= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_pm_linkst_in_l0s= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_pm_linkst_in_l1= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_pm_linkst_in_l2= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_local_smlh_in_rl0s= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_asyncpowerchangeack= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_commonclock_enable= 1'h0;
wire [15:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_messagebus= 16'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_pclk_rate= 3'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_pclkchangeack= 2'h0;
wire [3:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_powerdown= 4'h0;
wire [2:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_rate= 3'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_rxelecidle_disable= 1'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_rxstandby= 2'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_rxwidth= 2'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_serdes_arch= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_sris_enable= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txcommonmode_disable= 1'h0;
wire [159:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txdata= 160'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txdatavalid= 2'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txdetectrx_loopback= 2'h0;
wire [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_txelecidle= 8'h0;
wire [1:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_mac_phy_width= 2'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_o_core_rst_n= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_o_muxd_aux_clk= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_perst_pre_ind_nss_hif_n= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_perst_pre_ind_pcie_o_muxd_aux_n= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_reset_n= 1'h0;
wire			pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_rst_n= 1'h0;
wire [11:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_rtlh_fc_allctd_pd= 12'h0;
wire [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_rtlh_fc_allctd_ph= 8'h0;
wire [11:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_rtlh_fc_rcvd_pd= 12'h0;
wire [7:0]		pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_rtlh_fc_rcvd_ph= 8'h0;
wire [1:0]		phy_pcie0_pipe_clk	= 2'h0;
wire [1:0]		phy_pcie1_pipe_clk	= 2'h0;
// End of automatics

//ADDON_INCLUDE_STUB_TIEOFF

`ifndef INTEL_SVA_OFF
`ifdef HIF_ASSERT_STUB_INPUTS_NO_TOGGLE

import intel_checkers_pkg::*;
reg unused_xor_d,sva_clk,sva_rst;
wire unused_xor = ^{
    /*AUTOUNUSED*/
    // Beginning of automatic unused inputs
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_acc_perst_n,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_paddr,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_penable,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pprot,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_psel,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pstrb,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pwdata,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_apbslv_pwrite,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_cpl0_halt,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_np0_halt,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_rtrgt1_tlp_p0_halt,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_data,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_dv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_dwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_ecrc_err,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_ecrc_gen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_eot,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_fm_format,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_grant,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_hdr,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_hv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_hwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_nullified,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_order_seqnum,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_poisoned,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_soh,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_t_bit,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_tlp_trailer,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_cpl0_twen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_data,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_dv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_dwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_ecrc_err,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_ecrc_gen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_eot,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_fm_format,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_grant,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_hdr,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_hv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_hwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_nullified,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_order_seqnum,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_poisoned,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_soh,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_t_bit,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_tlp_trailer,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_np0_twen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_data,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_dv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_dwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_ecrc_err,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_ecrc_gen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_eot,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_fm_format,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_grant,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_hdr,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_hv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_hwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_nullified,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_order_seqnum,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_poisoned,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_soh,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_t_bit,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_tlp_trailer,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_dwc_xali_tlp_vc0_p0_twen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_car_1us_toggle,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_PERST_n0,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_PERST_n1,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_PERST_n2,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_pcie_PERST_n3,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_upp_shim_xfer_pending,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_hif_upp_xfer_pending,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_imc_perst_n,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_nss_hif_div_clk_en,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_nss_hif_div_clk_sel,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_pcie_ctl_regs_req,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_messagebus,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_pclkchangeok,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_phystatus,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_rxdata,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_rxstandbystatus,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_rxstatus,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_0_phy_mac_rxvalid,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_acc_perst_n,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_paddr,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_penable,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pprot,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_psel,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pstrb,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pwdata,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_apbslv_pwrite,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_cpl0_halt,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_np0_halt,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_rtrgt1_tlp_p0_halt,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_data,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_dv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_dwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_ecrc_err,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_ecrc_gen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_eot,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_fm_format,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_grant,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_hdr,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_hv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_hwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_nullified,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_order_seqnum,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_poisoned,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_soh,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_t_bit,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_tlp_trailer,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_cpl0_twen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_data,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_dv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_dwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_ecrc_err,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_ecrc_gen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_eot,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_fm_format,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_grant,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_hdr,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_hv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_hwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_nullified,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_order_seqnum,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_poisoned,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_soh,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_t_bit,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_tlp_trailer,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_np0_twen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_data,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_dv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_dwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_ecrc_err,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_ecrc_gen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_eot,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_fm_format,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_grant,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_hdr,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_hv,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_hwen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_nullified,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_order_seqnum,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_poisoned,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_soh,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_t_bit,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_tlp_trailer,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_dwc_xali_tlp_vc0_p0_twen,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_car_1us_toggle,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_PERST_n0,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_PERST_n1,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_PERST_n2,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_pcie_PERST_n3,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_upp_shim_xfer_pending,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_hif_upp_xfer_pending,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_imc_perst_n,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_nss_hif_div_clk_en,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_nss_hif_div_clk_sel,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_pcie_ctl_regs_req,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_messagebus,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_pclkchangeok,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_phystatus,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_rxdata,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_rxstandbystatus,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_rxstatus,
    pcie_ss_dwc_ctlx2x2_apr_pcie_ss_dwc_ctlx2x2_func_logic_pcie_ss_dwc_ctlx2_1_phy_mac_rxvalid,
    phy_pcie0_max_pclk,
    phy_pcie1_max_pclk,
    visa_all_dis,
    visa_customer_dis,
    visa_resetb,
    // End of automatics
    1'b0
};

initial sva_clk = 1'b0;
initial begin
    sva_rst = 1'b0;
    #10ns;
    sva_rst = 1'b1;
end

always #1ns sva_clk = ~sva_clk;

always @(posedge sva_clk) unused_xor_d <= unused_xor;

`ASSERTS_FORBIDDEN(hif_stub_inputs_no_toggle, (unused_xor_d !== unused_xor) , sva_clk, ~sva_rst, `ERR_MSG("Stub input toggle"));

`endif//`ifdef HIF_ASSERT_STUB_INPUTS_NO_TOGGLE
`endif//`ifndef INTEL_SVA_OFF

endmodule

// Local Variables:
// verilog-library-files:("/nfs/site/disks/nhdk.zsc7.mmg800.ipm.211/hif/hif_r15_pre_dft-mmg800-a0-25ww22a/output/hif_core/collage/trial/gen/rtl/parhif_pcie_ss_dwc_ctlx2x2.sv")
// end:

