module physs_hlp_repeater
(
    input         ts_800_rdop_fout0_clkout ,
    input         physs_hlp_repeater_reset ,
	input		  fscan_byprst_b,
	input         fscan_rstbypen,
	input [127:0] hlp_cgmii0_rxd_0 ,
	input [127:0] hlp_cgmii0_txd_nss_0 ,
	input [127:0] hlp_port0_cgmii_tx_data ,
    input [127:0] hlp_cgmii0_rxd_1 ,
    input [127:0] hlp_cgmii0_rxd_2 ,
    input [127:0] hlp_cgmii0_rxd_3 ,
    input [127:0] hlp_cgmii1_rxd_0 ,
    input [127:0] hlp_cgmii1_rxd_1 ,
    input [127:0] hlp_cgmii1_rxd_2 ,
    input [127:0] hlp_cgmii1_rxd_3 ,
    input [127:0] hlp_cgmii1_txd_nss_0 ,
    input [127:0] hlp_cgmii2_rxd_0 ,
    input [127:0] hlp_cgmii2_rxd_1 ,
    input [127:0] hlp_cgmii2_rxd_2 ,
    input [127:0] hlp_cgmii2_rxd_3 ,
    input [127:0] hlp_cgmii2_txd_nss_0 ,
    input [127:0] hlp_cgmii3_rxd_0 ,
    input [127:0] hlp_cgmii3_rxd_1 ,
    input [127:0] hlp_cgmii3_rxd_2 ,
    input [127:0] hlp_cgmii3_rxd_3 ,
    input [127:0] hlp_cgmii3_txd_nss_0 ,
    input [127:0] hlp_port10_cgmii_tx_data ,
    input [127:0] hlp_port11_cgmii_tx_data ,
    input [127:0] hlp_port12_cgmii_tx_data ,
    input [127:0] hlp_port13_cgmii_tx_data ,
    input [127:0] hlp_port14_cgmii_tx_data ,
    input [127:0] hlp_port15_cgmii_tx_data ,
    input [127:0] hlp_port16_cgmii_tx_data ,
    input [127:0] hlp_port17_cgmii_tx_data ,
    input [127:0] hlp_port18_cgmii_tx_data ,
    input [127:0] hlp_port19_cgmii_tx_data ,
    input [127:0] hlp_port1_cgmii_tx_data ,
    input [127:0] hlp_port20_cgmii_tx_data ,
    input [127:0] hlp_port21_cgmii_tx_data ,
    input [127:0] hlp_port22_cgmii_tx_data ,
    input [127:0] hlp_port23_cgmii_tx_data ,
    input [127:0] hlp_port2_cgmii_tx_data ,
    input [127:0] hlp_port3_cgmii_tx_data ,
    input [127:0] hlp_port4_cgmii_tx_data ,
    input [127:0] hlp_port5_cgmii_tx_data ,
    input [127:0] hlp_port6_cgmii_tx_data ,
    input [127:0] hlp_port7_cgmii_tx_data ,
    input [127:0] hlp_port8_cgmii_tx_data ,
    input [127:0] hlp_port9_cgmii_tx_data ,
    input [15:0] hlp_cgmii0_rxc_0 ,
    input [15:0] hlp_cgmii0_rxc_1 ,
    input [15:0] hlp_cgmii0_rxc_2 ,
    input [15:0] hlp_cgmii0_rxc_3 ,
    input [15:0] hlp_cgmii0_txc_nss_0 ,
    input [15:0] hlp_cgmii1_rxc_0 ,
    input [15:0] hlp_cgmii1_rxc_1 ,
    input [15:0] hlp_cgmii1_rxc_2 ,
    input [15:0] hlp_cgmii1_rxc_3 ,
    input [15:0] hlp_cgmii1_txc_nss_0 ,
    input [15:0] hlp_cgmii2_rxc_0 ,
    input [15:0] hlp_cgmii2_rxc_1 ,
    input [15:0] hlp_cgmii2_rxc_2 ,
    input [15:0] hlp_cgmii2_rxc_3 ,
    input [15:0] hlp_cgmii2_txc_nss_0 ,
    input [15:0] hlp_cgmii3_rxc_0 ,
    input [15:0] hlp_cgmii3_rxc_1 ,
    input [15:0] hlp_cgmii3_rxc_2 ,
    input [15:0] hlp_cgmii3_rxc_3 ,
    input [15:0] hlp_cgmii3_txc_nss_0 ,
    input [15:0] hlp_port0_cgmii_tx_c ,
    input [15:0] hlp_port10_cgmii_tx_c ,
    input [15:0] hlp_port11_cgmii_tx_c ,
    input [15:0] hlp_port12_cgmii_tx_c ,
    input [15:0] hlp_port13_cgmii_tx_c ,
    input [15:0] hlp_port14_cgmii_tx_c ,
    input [15:0] hlp_port15_cgmii_tx_c ,
    input [15:0] hlp_port16_cgmii_tx_c ,
    input [15:0] hlp_port17_cgmii_tx_c ,
    input [15:0] hlp_port18_cgmii_tx_c ,
    input [15:0] hlp_port19_cgmii_tx_c ,
    input [15:0] hlp_port1_cgmii_tx_c ,
    input [15:0] hlp_port20_cgmii_tx_c ,
    input [15:0] hlp_port21_cgmii_tx_c ,
    input [15:0] hlp_port22_cgmii_tx_c ,
    input [15:0] hlp_port23_cgmii_tx_c ,
    input [15:0] hlp_port2_cgmii_tx_c ,
    input [15:0] hlp_port3_cgmii_tx_c ,
    input [15:0] hlp_port4_cgmii_tx_c ,
    input [15:0] hlp_port5_cgmii_tx_c ,
    input [15:0] hlp_port6_cgmii_tx_c ,
    input [15:0] hlp_port7_cgmii_tx_c ,
    input [15:0] hlp_port8_cgmii_tx_c ,
    input [15:0] hlp_port9_cgmii_tx_c ,
    input [63:0] hlp_port0_xlgmii_tx_data ,
    input [63:0] hlp_port10_xlgmii_tx_data ,
    input [63:0] hlp_port11_xlgmii_tx_data ,
    input [63:0] hlp_port12_xlgmii_tx_data ,
    input [63:0] hlp_port13_xlgmii_tx_data ,
    input [63:0] hlp_port14_xlgmii_tx_data ,
    input [63:0] hlp_port15_xlgmii_tx_data ,
    input [63:0] hlp_port16_xlgmii_tx_data ,
    input [63:0] hlp_port17_xlgmii_tx_data ,
    input [63:0] hlp_port18_xlgmii_tx_data ,
    input [63:0] hlp_port19_xlgmii_tx_data ,
    input [63:0] hlp_port1_xlgmii_tx_data ,
    input [63:0] hlp_port20_xlgmii_tx_data ,
    input [63:0] hlp_port21_xlgmii_tx_data ,
    input [63:0] hlp_port22_xlgmii_tx_data ,
    input [63:0] hlp_port23_xlgmii_tx_data ,
    input [63:0] hlp_port2_xlgmii_tx_data ,
    input [63:0] hlp_port3_xlgmii_tx_data ,
    input [63:0] hlp_port4_xlgmii_tx_data ,
    input [63:0] hlp_port5_xlgmii_tx_data ,
    input [63:0] hlp_port6_xlgmii_tx_data ,
    input [63:0] hlp_port7_xlgmii_tx_data ,
    input [63:0] hlp_port8_xlgmii_tx_data ,
    input [63:0] hlp_port9_xlgmii_tx_data ,
    input [63:0] hlp_xlgmii0_rxd_0 ,
    input [63:0] hlp_xlgmii0_rxd_1 ,
    input [63:0] hlp_xlgmii0_rxd_2 ,
    input [63:0] hlp_xlgmii0_rxd_3 ,
    input [63:0] hlp_xlgmii0_txd_nss_0 ,
    input [63:0] hlp_xlgmii1_rxd_0 ,
    input [63:0] hlp_xlgmii1_rxd_1 ,
    input [63:0] hlp_xlgmii1_rxd_2 ,
    input [63:0] hlp_xlgmii1_rxd_3 ,
    input [63:0] hlp_xlgmii1_txd_nss_0 ,
    input [63:0] hlp_xlgmii2_rxd_0 ,
    input [63:0] hlp_xlgmii2_rxd_1 ,
    input [63:0] hlp_xlgmii2_rxd_2 ,
    input [63:0] hlp_xlgmii2_rxd_3 ,
    input [63:0] hlp_xlgmii2_txd_nss_0 ,
    input [63:0] hlp_xlgmii3_rxd_0 ,
    input [63:0] hlp_xlgmii3_rxd_1 ,
    input [63:0] hlp_xlgmii3_rxd_2 ,
    input [63:0] hlp_xlgmii3_rxd_3 ,
    input [63:0] hlp_xlgmii3_txd_nss_0 ,
    input [7:0] hlp_port0_xlgmii_tx_c ,
    input [7:0] hlp_port10_xlgmii_tx_c ,
    input [7:0] hlp_port11_xlgmii_tx_c ,
    input [7:0] hlp_port12_xlgmii_tx_c ,
    input [7:0] hlp_port13_xlgmii_tx_c ,
    input [7:0] hlp_port14_xlgmii_tx_c ,
    input [7:0] hlp_port15_xlgmii_tx_c ,
    input [7:0] hlp_port16_xlgmii_tx_c ,
    input [7:0] hlp_port17_xlgmii_tx_c ,
    input [7:0] hlp_port18_xlgmii_tx_c ,
    input [7:0] hlp_port19_xlgmii_tx_c ,
    input [7:0] hlp_port1_xlgmii_tx_c ,
    input [7:0] hlp_port20_xlgmii_tx_c ,
    input [7:0] hlp_port21_xlgmii_tx_c ,
    input [7:0] hlp_port22_xlgmii_tx_c ,
    input [7:0] hlp_port23_xlgmii_tx_c ,
    input [7:0] hlp_port2_xlgmii_tx_c ,
    input [7:0] hlp_port3_xlgmii_tx_c ,
    input [7:0] hlp_port4_xlgmii_tx_c ,
    input [7:0] hlp_port5_xlgmii_tx_c ,
    input [7:0] hlp_port6_xlgmii_tx_c ,
    input [7:0] hlp_port7_xlgmii_tx_c ,
    input [7:0] hlp_port8_xlgmii_tx_c ,
    input [7:0] hlp_port9_xlgmii_tx_c ,
    input [7:0] hlp_xlgmii0_rxc_0 ,
    input [7:0] hlp_xlgmii0_rxc_1 ,
    input [7:0] hlp_xlgmii0_rxc_2 ,
    input [7:0] hlp_xlgmii0_rxc_3 ,
    input [7:0] hlp_xlgmii0_txc_nss_0 ,
    input [7:0] hlp_xlgmii1_rxc_0 ,
    input [7:0] hlp_xlgmii1_rxc_1 ,
    input [7:0] hlp_xlgmii1_rxc_2 ,
    input [7:0] hlp_xlgmii1_rxc_3 ,
    input [7:0] hlp_xlgmii1_txc_nss_0 ,
    input [7:0] hlp_xlgmii2_rxc_0 ,
    input [7:0] hlp_xlgmii2_rxc_1 ,
    input [7:0] hlp_xlgmii2_rxc_2 ,
    input [7:0] hlp_xlgmii2_rxc_3 ,
    input [7:0] hlp_xlgmii2_txc_nss_0 ,
    input [7:0] hlp_xlgmii3_rxc_0 ,
    input [7:0] hlp_xlgmii3_rxc_1 ,
    input [7:0] hlp_xlgmii3_rxc_2 ,
    input [7:0] hlp_xlgmii3_rxc_3 ,
    input [7:0] hlp_xlgmii3_txc_nss_0 ,
    input hlp_cgmii0_rxclk_ena_0 ,
    input hlp_cgmii0_rxclk_ena_1 ,
    input hlp_cgmii0_rxclk_ena_2 ,
    input hlp_cgmii0_rxclk_ena_3 ,
    input hlp_cgmii0_txclk_ena_0 ,
    input hlp_cgmii0_txclk_ena_1 ,
    input hlp_cgmii0_txclk_ena_2 ,
    input hlp_cgmii0_txclk_ena_3 ,
    input hlp_cgmii1_rxclk_ena_0 ,
    input hlp_cgmii1_rxclk_ena_1 ,
    input hlp_cgmii1_rxclk_ena_2 ,
    input hlp_cgmii1_rxclk_ena_3 ,
    input hlp_cgmii1_txclk_ena_0 ,
    input hlp_cgmii1_txclk_ena_1 ,
    input hlp_cgmii1_txclk_ena_2 ,
    input hlp_cgmii1_txclk_ena_3 ,
    input hlp_cgmii2_rxclk_ena_0 ,
    input hlp_cgmii2_rxclk_ena_1 ,
    input hlp_cgmii2_rxclk_ena_2 ,
    input hlp_cgmii2_rxclk_ena_3 ,
    input hlp_cgmii2_txclk_ena_0 ,
    input hlp_cgmii2_txclk_ena_1 ,
    input hlp_cgmii2_txclk_ena_2 ,
    input hlp_cgmii2_txclk_ena_3 ,
    input hlp_cgmii3_rxclk_ena_0 ,
    input hlp_cgmii3_rxclk_ena_1 ,
    input hlp_cgmii3_rxclk_ena_2 ,
    input hlp_cgmii3_rxclk_ena_3 ,
    input hlp_cgmii3_txclk_ena_0 ,
    input hlp_cgmii3_txclk_ena_1 ,
    input hlp_cgmii3_txclk_ena_2 ,
    input hlp_cgmii3_txclk_ena_3 ,
    input hlp_xlgmii0_rxclk_ena_0 ,
    input hlp_xlgmii0_rxclk_ena_1 ,
    input hlp_xlgmii0_rxclk_ena_2 ,
    input hlp_xlgmii0_rxclk_ena_3 ,
    input hlp_xlgmii0_rxt0_next_0 ,
    input hlp_xlgmii0_rxt0_next_1 ,
    input hlp_xlgmii0_rxt0_next_2 ,
    input hlp_xlgmii0_rxt0_next_3 ,
    input hlp_xlgmii0_txclk_ena_0 ,
    input hlp_xlgmii0_txclk_ena_1 ,
    input hlp_xlgmii0_txclk_ena_2 ,
    input hlp_xlgmii0_txclk_ena_3 ,
    input hlp_xlgmii1_rxclk_ena_0 ,
    input hlp_xlgmii1_rxclk_ena_1 ,
    input hlp_xlgmii1_rxclk_ena_2 ,
    input hlp_xlgmii1_rxclk_ena_3 ,
    input hlp_xlgmii1_rxt0_next_0 ,
    input hlp_xlgmii1_rxt0_next_1 ,
    input hlp_xlgmii1_rxt0_next_2 ,
    input hlp_xlgmii1_rxt0_next_3 ,
    input hlp_xlgmii1_txclk_ena_0 ,
    input hlp_xlgmii1_txclk_ena_1 ,
    input hlp_xlgmii1_txclk_ena_2 ,
    input hlp_xlgmii1_txclk_ena_3 ,
    input hlp_xlgmii2_rxclk_ena_0 ,
    input hlp_xlgmii2_rxclk_ena_1 ,
    input hlp_xlgmii2_rxclk_ena_2 ,
    input hlp_xlgmii2_rxclk_ena_3 ,
    input hlp_xlgmii2_rxt0_next_0 ,
    input hlp_xlgmii2_rxt0_next_1 ,
    input hlp_xlgmii2_rxt0_next_2 ,
    input hlp_xlgmii2_rxt0_next_3 ,
    input hlp_xlgmii2_txclk_ena_0 ,
    input hlp_xlgmii2_txclk_ena_1 ,
    input hlp_xlgmii2_txclk_ena_2 ,
    input hlp_xlgmii2_txclk_ena_3 ,
    input hlp_xlgmii3_rxclk_ena_0 ,
    input hlp_xlgmii3_rxclk_ena_1 ,
    input hlp_xlgmii3_rxclk_ena_2 ,
    input hlp_xlgmii3_rxclk_ena_3 ,
    input hlp_xlgmii3_rxt0_next_0 ,
    input hlp_xlgmii3_rxt0_next_1 ,
    input hlp_xlgmii3_rxt0_next_2 ,
    input hlp_xlgmii3_rxt0_next_3 ,
    input hlp_xlgmii3_txclk_ena_0 ,
    input hlp_xlgmii3_txclk_ena_1 ,
    input hlp_xlgmii3_txclk_ena_2 ,
    input hlp_xlgmii3_txclk_ena_3 ,
    input [31:0]  pcs_tsu_rx_sd,
    input [31:0]  mii_rx_tsu_mux,
    input [31:0]  mii_tx_tsu,
    input [127:0] pcs_sd_bit_slip,
    input [111:0] pcs_desk_buf_rlevel,
    input [15:0]  pcs_link_status_tsu,

    output [1:0]    hlp_port9_tsu_rx_sd,
    output [1:0]    hlp_port10_tsu_rx_sd,
    output [1:0]    hlp_port11_tsu_rx_sd,
    output [1:0]    hlp_port12_tsu_rx_sd,
    output [1:0]    hlp_port13_tsu_rx_sd,
    output [1:0]    hlp_port4_tsu_rx_sd,
    output [1:0]    hlp_port14_tsu_rx_sd,
    output [1:0]    hlp_port15_tsu_rx_sd,
    output [1:0]    hlp_port16_tsu_rx_sd,
    output [1:0]    hlp_port17_tsu_rx_sd,
    output [1:0]    hlp_port18_tsu_rx_sd,
    output [1:0]    hlp_port19_tsu_rx_sd,
    output [1:0]    hlp_port5_tsu_rx_sd,
    output [1:0]    hlp_port6_tsu_rx_sd,
    output [1:0]    hlp_port7_tsu_rx_sd,
    output [1:0]    hlp_port8_tsu_rx_sd,

    output [1:0]    hlp_port10_mii_rx_tsu,
    output [1:0]    hlp_port11_mii_rx_tsu,
    output [1:0]    hlp_port12_mii_rx_tsu,
    output [1:0]    hlp_port13_mii_rx_tsu,
    output [1:0]    hlp_port14_mii_rx_tsu,
    output [1:0]    hlp_port15_mii_rx_tsu,
    output [1:0]    hlp_port16_mii_rx_tsu,
    output [1:0]    hlp_port17_mii_rx_tsu,
    output [1:0]    hlp_port18_mii_rx_tsu,
    output [1:0]    hlp_port19_mii_rx_tsu,
    output [1:0]    hlp_port4_mii_rx_tsu,
    output [1:0]    hlp_port5_mii_rx_tsu,
    output [1:0]    hlp_port6_mii_rx_tsu,
    output [1:0]    hlp_port7_mii_rx_tsu,
    output [1:0]    hlp_port8_mii_rx_tsu,
    output [1:0]    hlp_port9_mii_rx_tsu,

    output [1:0]    hlp_port10_mii_tx_tsu,
    output [1:0]    hlp_port11_mii_tx_tsu,
    output [1:0]    hlp_port12_mii_tx_tsu,
    output [1:0]    hlp_port13_mii_tx_tsu,
    output [1:0]    hlp_port14_mii_tx_tsu,
    output [1:0]    hlp_port15_mii_tx_tsu,
    output [1:0]    hlp_port16_mii_tx_tsu,
    output [1:0]    hlp_port17_mii_tx_tsu,
    output [1:0]    hlp_port18_mii_tx_tsu,
    output [1:0]    hlp_port19_mii_tx_tsu,
    output [1:0]    hlp_port4_mii_tx_tsu, 
    output [1:0]    hlp_port5_mii_tx_tsu, 
    output [1:0]    hlp_port6_mii_tx_tsu, 
    output [1:0]    hlp_port7_mii_tx_tsu, 
    output [1:0]    hlp_port8_mii_tx_tsu, 
    output [1:0]    hlp_port9_mii_tx_tsu, 

    output [7:0]    hlp_port16_sd_bit_slip,
    output [7:0]    hlp_port17_sd_bit_slip,
    output [7:0]    hlp_port18_sd_bit_slip,
    output [7:0]    hlp_port19_sd_bit_slip,
    output [7:0]    hlp_port5_sd_bit_slip,
    output [7:0]    hlp_port6_sd_bit_slip,
    output [7:0]    hlp_port7_sd_bit_slip,
    output [7:0]    hlp_port8_sd_bit_slip,
    output [7:0]    hlp_port9_sd_bit_slip,
    output [7:0]    hlp_port10_sd_bit_slip,
    output [7:0]    hlp_port11_sd_bit_slip,
    output [7:0]    hlp_port12_sd_bit_slip,
    output [7:0]    hlp_port13_sd_bit_slip,
    output [7:0]    hlp_port4_sd_bit_slip,
    output [7:0]    hlp_port14_sd_bit_slip,
    output [7:0]    hlp_port15_sd_bit_slip,

    output          hlp_port4_link_status,
    output          hlp_port14_link_status,
    output          hlp_port15_link_status,
    output          hlp_port16_link_status,
    output          hlp_port17_link_status,
    output          hlp_port18_link_status,
    output          hlp_port19_link_status,
    output          hlp_port5_link_status,
    output          hlp_port6_link_status,
    output          hlp_port7_link_status,
    output          hlp_port8_link_status,
    output          hlp_port9_link_status,
    output          hlp_port10_link_status,
    output          hlp_port11_link_status,
    output          hlp_port12_link_status,
    output          hlp_port13_link_status,

    output [6:0]    hlp_port18_desk_rlevel,
    output [6:0]    hlp_port19_desk_rlevel,
    output [6:0]    hlp_port5_desk_rlevel,
    output [6:0]    hlp_port6_desk_rlevel,
    output [6:0]    hlp_port7_desk_rlevel,
    output [6:0]    hlp_port8_desk_rlevel,
    output [6:0]    hlp_port9_desk_rlevel,
    output [6:0]    hlp_port10_desk_rlevel,
    output [6:0]    hlp_port11_desk_rlevel,
    output [6:0]    hlp_port12_desk_rlevel,
    output [6:0]    hlp_port13_desk_rlevel,
    output [6:0]    hlp_port4_desk_rlevel,
    output [6:0]    hlp_port14_desk_rlevel,
    output [6:0]    hlp_port15_desk_rlevel,
    output [6:0]    hlp_port16_desk_rlevel,
    output [6:0]    hlp_port17_desk_rlevel,



    output [127:0] hlp_cgmii0_rxd_nss_0 ,
	output [127:0] hlp_cgmii0_txd_0 ,
    output [127:0] hlp_cgmii0_txd_1 ,
    output [127:0] hlp_cgmii0_txd_2 ,
    output [127:0] hlp_cgmii0_txd_3 ,
    output [127:0] hlp_cgmii1_rxd_nss_0 ,
    output [127:0] hlp_cgmii1_txd_0 ,
    output [127:0] hlp_cgmii1_txd_1 ,
    output [127:0] hlp_cgmii1_txd_2 ,
    output [127:0] hlp_cgmii1_txd_3 ,
    output [127:0] hlp_cgmii2_rxd_nss_0 ,
    output [127:0] hlp_cgmii2_txd_0 ,
    output [127:0] hlp_cgmii2_txd_1 ,
    output [127:0] hlp_cgmii2_txd_2 ,
    output [127:0] hlp_cgmii2_txd_3 ,
    output [127:0] hlp_cgmii3_rxd_nss_0 ,
    output [127:0] hlp_cgmii3_txd_0 ,
    output [127:0] hlp_cgmii3_txd_1 ,
    output [127:0] hlp_cgmii3_txd_2 ,
    output [127:0] hlp_cgmii3_txd_3 ,
    output [127:0] hlp_port0_cgmii_rx_data ,
    output [127:0] hlp_port10_cgmii_rx_data ,
    output [127:0] hlp_port11_cgmii_rx_data ,
    output [127:0] hlp_port12_cgmii_rx_data ,
    output [127:0] hlp_port13_cgmii_rx_data ,
    output [127:0] hlp_port14_cgmii_rx_data ,
    output [127:0] hlp_port15_cgmii_rx_data ,
    output [127:0] hlp_port16_cgmii_rx_data ,
    output [127:0] hlp_port17_cgmii_rx_data ,
    output [127:0] hlp_port18_cgmii_rx_data ,
    output [127:0] hlp_port19_cgmii_rx_data ,
    output [127:0] hlp_port1_cgmii_rx_data ,
    output [127:0] hlp_port20_cgmii_rx_data ,
    output [127:0] hlp_port21_cgmii_rx_data ,
    output [127:0] hlp_port22_cgmii_rx_data ,
    output [127:0] hlp_port23_cgmii_rx_data ,
    output [127:0] hlp_port2_cgmii_rx_data ,
    output [127:0] hlp_port3_cgmii_rx_data ,
    output [127:0] hlp_port4_cgmii_rx_data ,
    output [127:0] hlp_port5_cgmii_rx_data ,
    output [127:0] hlp_port6_cgmii_rx_data ,
    output [127:0] hlp_port7_cgmii_rx_data ,
    output [127:0] hlp_port8_cgmii_rx_data ,
    output [127:0] hlp_port9_cgmii_rx_data ,
    output [15:0] hlp_cgmii0_rxc_nss_0 ,
    output [15:0] hlp_cgmii0_txc_0 ,
    output [15:0] hlp_cgmii0_txc_1 ,
    output [15:0] hlp_cgmii0_txc_2 ,
    output [15:0] hlp_cgmii0_txc_3 ,
    output [15:0] hlp_cgmii1_rxc_nss_0 ,
    output [15:0] hlp_cgmii1_txc_0 ,
    output [15:0] hlp_cgmii1_txc_1 ,
    output [15:0] hlp_cgmii1_txc_2 ,
    output [15:0] hlp_cgmii1_txc_3 ,
    output [15:0] hlp_cgmii2_rxc_nss_0 ,
    output [15:0] hlp_cgmii2_txc_0 ,
    output [15:0] hlp_cgmii2_txc_1 ,
    output [15:0] hlp_cgmii2_txc_2 ,
    output [15:0] hlp_cgmii2_txc_3 ,
    output [15:0] hlp_cgmii3_rxc_nss_0 ,
    output [15:0] hlp_cgmii3_txc_0 ,
    output [15:0] hlp_cgmii3_txc_1 ,
    output [15:0] hlp_cgmii3_txc_2 ,
    output [15:0] hlp_cgmii3_txc_3 ,
    output [15:0] hlp_port0_cgmii_rx_c ,
    output [15:0] hlp_port10_cgmii_rx_c ,
    output [15:0] hlp_port11_cgmii_rx_c ,
    output [15:0] hlp_port12_cgmii_rx_c ,
    output [15:0] hlp_port13_cgmii_rx_c ,
    output [15:0] hlp_port14_cgmii_rx_c ,
    output [15:0] hlp_port15_cgmii_rx_c ,
    output [15:0] hlp_port16_cgmii_rx_c ,
    output [15:0] hlp_port17_cgmii_rx_c ,
    output [15:0] hlp_port18_cgmii_rx_c ,
    output [15:0] hlp_port19_cgmii_rx_c ,
    output [15:0] hlp_port1_cgmii_rx_c ,
    output [15:0] hlp_port20_cgmii_rx_c ,
    output [15:0] hlp_port21_cgmii_rx_c ,
    output [15:0] hlp_port22_cgmii_rx_c ,
    output [15:0] hlp_port23_cgmii_rx_c ,
    output [15:0] hlp_port2_cgmii_rx_c ,
    output [15:0] hlp_port3_cgmii_rx_c ,
    output [15:0] hlp_port4_cgmii_rx_c ,
    output [15:0] hlp_port5_cgmii_rx_c ,
    output [15:0] hlp_port6_cgmii_rx_c ,
    output [15:0] hlp_port7_cgmii_rx_c ,
    output [15:0] hlp_port8_cgmii_rx_c ,
    output [15:0] hlp_port9_cgmii_rx_c ,
    output [63:0] hlp_port0_xlgmii_rx_data ,
    output [63:0] hlp_port10_xlgmii_rx_data ,
    output [63:0] hlp_port11_xlgmii_rx_data ,
    output [63:0] hlp_port12_xlgmii_rx_data ,
    output [63:0] hlp_port13_xlgmii_rx_data ,
    output [63:0] hlp_port14_xlgmii_rx_data ,
    output [63:0] hlp_port15_xlgmii_rx_data ,
    output [63:0] hlp_port16_xlgmii_rx_data ,
    output [63:0] hlp_port17_xlgmii_rx_data ,
    output [63:0] hlp_port18_xlgmii_rx_data ,
    output [63:0] hlp_port19_xlgmii_rx_data ,
    output [63:0] hlp_port1_xlgmii_rx_data ,
    output [63:0] hlp_port20_xlgmii_rx_data ,
    output [63:0] hlp_port21_xlgmii_rx_data ,
    output [63:0] hlp_port22_xlgmii_rx_data ,
    output [63:0] hlp_port23_xlgmii_rx_data ,
    output [63:0] hlp_port2_xlgmii_rx_data ,
    output [63:0] hlp_port3_xlgmii_rx_data ,
    output [63:0] hlp_port4_xlgmii_rx_data ,
    output [63:0] hlp_port5_xlgmii_rx_data ,
    output [63:0] hlp_port6_xlgmii_rx_data ,
    output [63:0] hlp_port7_xlgmii_rx_data ,
    output [63:0] hlp_port8_xlgmii_rx_data ,
    output [63:0] hlp_port9_xlgmii_rx_data ,
    output [63:0] hlp_xlgmii0_rxd_nss_0 ,
    output [63:0] hlp_xlgmii0_txd_0 ,
    output [63:0] hlp_xlgmii0_txd_1 ,
    output [63:0] hlp_xlgmii0_txd_2 ,
    output [63:0] hlp_xlgmii0_txd_3 ,
    output [63:0] hlp_xlgmii1_rxd_nss_0 ,
    output [63:0] hlp_xlgmii1_txd_0 ,
    output [63:0] hlp_xlgmii1_txd_1 ,
    output [63:0] hlp_xlgmii1_txd_2 ,
    output [63:0] hlp_xlgmii1_txd_3 ,
    output [63:0] hlp_xlgmii2_rxd_nss_0 ,
    output [63:0] hlp_xlgmii2_txd_0 ,
    output [63:0] hlp_xlgmii2_txd_1 ,
    output [63:0] hlp_xlgmii2_txd_2 ,
    output [63:0] hlp_xlgmii2_txd_3 ,
    output [63:0] hlp_xlgmii3_rxd_nss_0 ,
    output [63:0] hlp_xlgmii3_txd_0 ,
    output [63:0] hlp_xlgmii3_txd_1 ,
    output [63:0] hlp_xlgmii3_txd_2 ,
    output [63:0] hlp_xlgmii3_txd_3 ,
    output [7:0] hlp_port0_xlgmii_rx_c ,
    output [7:0] hlp_port10_xlgmii_rx_c ,
    output [7:0] hlp_port11_xlgmii_rx_c ,
    output [7:0] hlp_port12_xlgmii_rx_c ,
    output [7:0] hlp_port13_xlgmii_rx_c ,
    output [7:0] hlp_port14_xlgmii_rx_c ,
    output [7:0] hlp_port15_xlgmii_rx_c ,
    output [7:0] hlp_port16_xlgmii_rx_c ,
    output [7:0] hlp_port17_xlgmii_rx_c ,
    output [7:0] hlp_port18_xlgmii_rx_c ,
    output [7:0] hlp_port19_xlgmii_rx_c ,
    output [7:0] hlp_port1_xlgmii_rx_c ,
    output [7:0] hlp_port20_xlgmii_rx_c ,
    output [7:0] hlp_port21_xlgmii_rx_c ,
    output [7:0] hlp_port22_xlgmii_rx_c ,
    output [7:0] hlp_port23_xlgmii_rx_c ,
    output [7:0] hlp_port2_xlgmii_rx_c ,
    output [7:0] hlp_port3_xlgmii_rx_c ,
    output [7:0] hlp_port4_xlgmii_rx_c ,
    output [7:0] hlp_port5_xlgmii_rx_c ,
    output [7:0] hlp_port6_xlgmii_rx_c ,
    output [7:0] hlp_port7_xlgmii_rx_c ,
    output [7:0] hlp_port8_xlgmii_rx_c ,
    output [7:0] hlp_port9_xlgmii_rx_c ,
    output [7:0] hlp_xlgmii0_rxc_nss_0 ,
    output [7:0] hlp_xlgmii0_txc_0 ,
    output [7:0] hlp_xlgmii0_txc_1 ,
    output [7:0] hlp_xlgmii0_txc_2 ,
    output [7:0] hlp_xlgmii0_txc_3 ,
    output [7:0] hlp_xlgmii1_rxc_nss_0 ,
    output [7:0] hlp_xlgmii1_txc_0 ,
    output [7:0] hlp_xlgmii1_txc_1 ,
    output [7:0] hlp_xlgmii1_txc_2 ,
    output [7:0] hlp_xlgmii1_txc_3 ,
    output [7:0] hlp_xlgmii2_rxc_nss_0 ,
    output [7:0] hlp_xlgmii2_txc_0 ,
    output [7:0] hlp_xlgmii2_txc_1 ,
    output [7:0] hlp_xlgmii2_txc_2 ,
    output [7:0] hlp_xlgmii2_txc_3 ,
    output [7:0] hlp_xlgmii3_rxc_nss_0 ,
    output [7:0] hlp_xlgmii3_txc_0 ,
    output [7:0] hlp_xlgmii3_txc_1 ,
    output [7:0] hlp_xlgmii3_txc_2 ,
    output [7:0] hlp_xlgmii3_txc_3 ,
    output hlp_port0_cgmii_rxclk_ena ,
    output hlp_port0_cgmii_rxt0_next ,
    output hlp_port0_cgmii_txclk_ena ,
    output hlp_port0_xlgmii_rxclk_ena ,
    output hlp_port0_xlgmii_rxt0_next ,
    output hlp_port0_xlgmii_txclk_ena ,
    output hlp_port10_cgmii_rxclk_ena ,
    output hlp_port10_cgmii_rxt0_next ,
    output hlp_port10_cgmii_txclk_ena ,
    output hlp_port10_xlgmii_rxclk_ena ,
    output hlp_port10_xlgmii_rxt0_next ,
    output hlp_port10_xlgmii_txclk_ena ,
    output hlp_port11_cgmii_rxclk_ena ,
    output hlp_port11_cgmii_rxt0_next ,
    output hlp_port11_cgmii_txclk_ena ,
    output hlp_port11_xlgmii_rxclk_ena ,
    output hlp_port11_xlgmii_rxt0_next ,
    output hlp_port11_xlgmii_txclk_ena ,
    output hlp_port12_cgmii_rxclk_ena ,
    output hlp_port12_cgmii_rxt0_next ,
    output hlp_port12_cgmii_txclk_ena ,
    output hlp_port12_xlgmii_rxclk_ena ,
    output hlp_port12_xlgmii_rxt0_next ,
    output hlp_port12_xlgmii_txclk_ena ,
    output hlp_port13_cgmii_rxclk_ena ,
    output hlp_port13_cgmii_rxt0_next ,
    output hlp_port13_cgmii_txclk_ena ,
    output hlp_port13_xlgmii_rxclk_ena ,
    output hlp_port13_xlgmii_rxt0_next ,
    output hlp_port13_xlgmii_txclk_ena ,
    output hlp_port14_cgmii_rxclk_ena ,
    output hlp_port14_cgmii_rxt0_next ,
    output hlp_port14_cgmii_txclk_ena ,
    output hlp_port14_xlgmii_rxclk_ena ,
    output hlp_port14_xlgmii_rxt0_next ,
    output hlp_port14_xlgmii_txclk_ena ,
    output hlp_port15_cgmii_rxclk_ena ,
    output hlp_port15_cgmii_rxt0_next ,
    output hlp_port15_cgmii_txclk_ena ,
    output hlp_port15_xlgmii_rxclk_ena ,
    output hlp_port15_xlgmii_rxt0_next ,
    output hlp_port15_xlgmii_txclk_ena ,
    output hlp_port16_cgmii_rxclk_ena ,
    output hlp_port16_cgmii_rxt0_next ,
    output hlp_port16_cgmii_txclk_ena ,
    output hlp_port16_xlgmii_rxclk_ena ,
    output hlp_port16_xlgmii_rxt0_next ,
    output hlp_port16_xlgmii_txclk_ena ,
    output hlp_port17_cgmii_rxclk_ena ,
    output hlp_port17_cgmii_rxt0_next ,
    output hlp_port17_cgmii_txclk_ena ,
    output hlp_port17_xlgmii_rxclk_ena ,
    output hlp_port17_xlgmii_rxt0_next ,
    output hlp_port17_xlgmii_txclk_ena ,
    output hlp_port18_cgmii_rxclk_ena ,
    output hlp_port18_cgmii_rxt0_next ,
    output hlp_port18_cgmii_txclk_ena ,
    output hlp_port18_xlgmii_rxclk_ena ,
    output hlp_port18_xlgmii_rxt0_next ,
    output hlp_port18_xlgmii_txclk_ena ,
    output hlp_port19_cgmii_rxclk_ena ,
    output hlp_port19_cgmii_rxt0_next ,
    output hlp_port19_cgmii_txclk_ena ,
    output hlp_port19_xlgmii_rxclk_ena ,
    output hlp_port19_xlgmii_rxt0_next ,
    output hlp_port19_xlgmii_txclk_ena ,
    output hlp_port1_cgmii_rxclk_ena ,
    output hlp_port1_cgmii_rxt0_next ,
    output hlp_port1_cgmii_txclk_ena ,
    output hlp_port1_xlgmii_rxclk_ena ,
    output hlp_port1_xlgmii_rxt0_next ,
    output hlp_port1_xlgmii_txclk_ena ,
    output hlp_port20_cgmii_rxclk_ena ,
    output hlp_port20_cgmii_rxt0_next ,
    output hlp_port20_cgmii_txclk_ena ,
    output hlp_port20_xlgmii_rxclk_ena ,
    output hlp_port20_xlgmii_rxt0_next ,
    output hlp_port20_xlgmii_txclk_ena ,
    output hlp_port21_cgmii_rxclk_ena ,
    output hlp_port21_cgmii_rxt0_next ,
    output hlp_port21_cgmii_txclk_ena ,
    output hlp_port21_xlgmii_rxclk_ena ,
    output hlp_port21_xlgmii_rxt0_next ,
    output hlp_port21_xlgmii_txclk_ena ,
    output hlp_port22_cgmii_rxclk_ena ,
    output hlp_port22_cgmii_rxt0_next ,
    output hlp_port22_cgmii_txclk_ena ,
    output hlp_port22_xlgmii_rxclk_ena ,
    output hlp_port22_xlgmii_rxt0_next ,
    output hlp_port22_xlgmii_txclk_ena ,
    output hlp_port23_cgmii_rxclk_ena ,
    output hlp_port23_cgmii_rxt0_next ,
    output hlp_port23_cgmii_txclk_ena ,
    output hlp_port23_xlgmii_rxclk_ena ,
    output hlp_port23_xlgmii_rxt0_next ,
    output hlp_port23_xlgmii_txclk_ena ,
    output hlp_port2_cgmii_rxclk_ena ,
    output hlp_port2_cgmii_rxt0_next ,
    output hlp_port2_cgmii_txclk_ena ,
    output hlp_port2_xlgmii_rxclk_ena ,
    output hlp_port2_xlgmii_rxt0_next ,
    output hlp_port2_xlgmii_txclk_ena ,
    output hlp_port3_cgmii_rxclk_ena ,
    output hlp_port3_cgmii_rxt0_next ,
    output hlp_port3_cgmii_txclk_ena ,
    output hlp_port3_xlgmii_rxclk_ena ,
    output hlp_port3_xlgmii_rxt0_next ,
    output hlp_port3_xlgmii_txclk_ena ,
    output hlp_port4_cgmii_rxclk_ena ,
    output hlp_port4_cgmii_rxt0_next ,
    output hlp_port4_cgmii_txclk_ena ,
    output hlp_port4_xlgmii_rxclk_ena ,
    output hlp_port4_xlgmii_rxt0_next ,
    output hlp_port4_xlgmii_txclk_ena ,
    output hlp_port5_cgmii_rxclk_ena ,
    output hlp_port5_cgmii_rxt0_next ,
    output hlp_port5_cgmii_txclk_ena ,
    output hlp_port5_xlgmii_rxclk_ena ,
    output hlp_port5_xlgmii_rxt0_next ,
    output hlp_port5_xlgmii_txclk_ena ,
    output hlp_port6_cgmii_rxclk_ena ,
    output hlp_port6_cgmii_rxt0_next ,
    output hlp_port6_cgmii_txclk_ena ,
    output hlp_port6_xlgmii_rxclk_ena ,
    output hlp_port6_xlgmii_rxt0_next ,
    output hlp_port6_xlgmii_txclk_ena ,
    output hlp_port7_cgmii_rxclk_ena ,
    output hlp_port7_cgmii_rxt0_next ,
    output hlp_port7_cgmii_txclk_ena ,
    output hlp_port7_xlgmii_rxclk_ena ,
    output hlp_port7_xlgmii_rxt0_next ,
    output hlp_port7_xlgmii_txclk_ena ,
    output hlp_port8_cgmii_rxclk_ena ,
    output hlp_port8_cgmii_rxt0_next ,
    output hlp_port8_cgmii_txclk_ena ,
    output hlp_port8_xlgmii_rxclk_ena ,
    output hlp_port8_xlgmii_rxt0_next ,
    output hlp_port8_xlgmii_txclk_ena ,
    output hlp_port9_cgmii_rxclk_ena ,
    output hlp_port9_cgmii_rxt0_next ,
    output hlp_port9_cgmii_txclk_ena ,
    output hlp_port9_xlgmii_rxclk_ena ,
    output hlp_port9_xlgmii_rxt0_next ,
    output hlp_port9_xlgmii_txclk_ena
);


assign  hlp_port4_sd_bit_slip               =   pcs_sd_bit_slip[7:0]	;		
assign  hlp_port5_sd_bit_slip               =   pcs_sd_bit_slip[15:8]	;		
assign  hlp_port6_sd_bit_slip               =   pcs_sd_bit_slip[23:16]	;		
assign  hlp_port7_sd_bit_slip               =   pcs_sd_bit_slip[31:24]	;		
assign  hlp_port8_sd_bit_slip               =   pcs_sd_bit_slip[39:32]	;		
assign  hlp_port9_sd_bit_slip               =   pcs_sd_bit_slip[47:40]	;		
assign  hlp_port10_sd_bit_slip              =   pcs_sd_bit_slip[55:48]	;		
assign  hlp_port11_sd_bit_slip              =   pcs_sd_bit_slip[63:56]	;		
assign  hlp_port12_sd_bit_slip              =   pcs_sd_bit_slip[71:64]	;		
assign  hlp_port13_sd_bit_slip              =   pcs_sd_bit_slip[79:72]	;		
assign  hlp_port14_sd_bit_slip              =   pcs_sd_bit_slip[87:80]	;		
assign  hlp_port15_sd_bit_slip              =   pcs_sd_bit_slip[95:88]	;		
assign  hlp_port16_sd_bit_slip              =   pcs_sd_bit_slip[103:96]	;		
assign  hlp_port17_sd_bit_slip              =   pcs_sd_bit_slip[111:104];		
assign  hlp_port18_sd_bit_slip              =   pcs_sd_bit_slip[119:112];		
assign  hlp_port19_sd_bit_slip              =   pcs_sd_bit_slip[127:120];		
                                                                
assign  hlp_port4_desk_rlevel      =     pcs_desk_buf_rlevel[6:0]		;
assign  hlp_port5_desk_rlevel      =     pcs_desk_buf_rlevel[13:7]		;
assign  hlp_port6_desk_rlevel      =     pcs_desk_buf_rlevel[20:14]		;
assign  hlp_port7_desk_rlevel      =     pcs_desk_buf_rlevel[27:21]		;
assign  hlp_port8_desk_rlevel      =     pcs_desk_buf_rlevel[34:28]		;
assign  hlp_port9_desk_rlevel      =     pcs_desk_buf_rlevel[41:35]		;
assign  hlp_port10_desk_rlevel     =     pcs_desk_buf_rlevel[48:42]		;
assign  hlp_port11_desk_rlevel     =     pcs_desk_buf_rlevel[55:49]		;
assign  hlp_port12_desk_rlevel     =     pcs_desk_buf_rlevel[62:56]		;
assign  hlp_port13_desk_rlevel     =     pcs_desk_buf_rlevel[69:63]		;
assign  hlp_port14_desk_rlevel     =     pcs_desk_buf_rlevel[76:70]		;
assign  hlp_port15_desk_rlevel     =     pcs_desk_buf_rlevel[83:77]		;
assign  hlp_port16_desk_rlevel     =     pcs_desk_buf_rlevel[90:84]		;
assign  hlp_port17_desk_rlevel     =     pcs_desk_buf_rlevel[97:91]		;
assign  hlp_port18_desk_rlevel     =     pcs_desk_buf_rlevel[104:98] 	;
assign  hlp_port19_desk_rlevel     =     pcs_desk_buf_rlevel[111:105]	;


assign 	hlp_port4_link_status       =   pcs_link_status_tsu[0]   ;
assign 	hlp_port5_link_status       =   pcs_link_status_tsu[1]   ;
assign 	hlp_port6_link_status       =   pcs_link_status_tsu[2]   ;
assign 	hlp_port7_link_status       =   pcs_link_status_tsu[3]   ;
assign 	hlp_port8_link_status       =   pcs_link_status_tsu[4]   ;
assign 	hlp_port9_link_status       =   pcs_link_status_tsu[5]   ;
assign 	hlp_port10_link_status      =   pcs_link_status_tsu[6]   ;
assign 	hlp_port11_link_status      =   pcs_link_status_tsu[7]   ;
assign 	hlp_port12_link_status      =   pcs_link_status_tsu[8]   ;
assign 	hlp_port13_link_status      =   pcs_link_status_tsu[9]   ;
assign 	hlp_port14_link_status      =   pcs_link_status_tsu[10]   ;
assign 	hlp_port15_link_status      =   pcs_link_status_tsu[11]   ;
assign 	hlp_port16_link_status      =   pcs_link_status_tsu[12]   ;
assign 	hlp_port17_link_status      =   pcs_link_status_tsu[13]   ;
assign 	hlp_port18_link_status      =   pcs_link_status_tsu[14]   ;
assign 	hlp_port19_link_status      =   pcs_link_status_tsu[15]   ;

assign hlp_port0_cgmii_rxt0_next    =   1'b0 ;
assign hlp_port10_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port11_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port12_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port13_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port14_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port15_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port16_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port17_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port18_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port19_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port1_cgmii_rxt0_next    =   1'b0 ;
assign hlp_port20_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port21_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port22_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port23_cgmii_rxt0_next   =   1'b0 ;
assign hlp_port2_cgmii_rxt0_next    =   1'b0 ;
assign hlp_port3_cgmii_rxt0_next    =   1'b0 ;
assign hlp_port4_cgmii_rxt0_next    =   1'b0 ;
assign hlp_port5_cgmii_rxt0_next    =   1'b0 ;
assign hlp_port6_cgmii_rxt0_next    =   1'b0 ;
assign hlp_port7_cgmii_rxt0_next    =   1'b0 ;
assign hlp_port8_cgmii_rxt0_next    =   1'b0 ;
assign hlp_port9_cgmii_rxt0_next    =   1'b0 ;

assign hlp_port23_cgmii_rx_data      =  128'b0;
assign hlp_port23_cgmii_rx_c         =  16'b0;
assign hlp_port23_xlgmii_rx_data     =  64'b0;
assign hlp_port23_xlgmii_rx_c        =  8'b0;
assign hlp_port23_cgmii_rxclk_ena    =  1'b0;
assign hlp_port23_cgmii_txclk_ena    =  1'b0;
assign hlp_port23_xlgmii_rxclk_ena   =  1'b0;
assign hlp_port23_xlgmii_rxt0_next   =  1'b0;
assign hlp_port23_xlgmii_txclk_ena   =  1'b0;

assign hlp_port22_cgmii_rx_data     =   128'b0;   
assign hlp_port22_cgmii_rx_c        =   16'b0;   
assign hlp_port22_xlgmii_rx_data    =   64'b0;   
assign hlp_port22_xlgmii_rx_c       =   8'b0; 
assign hlp_port22_cgmii_rxclk_ena   =   1'b0;
assign hlp_port22_cgmii_txclk_ena   =   1'b0;
assign hlp_port22_xlgmii_rxclk_ena  =   1'b0;
assign hlp_port22_xlgmii_rxt0_next  =   1'b0;
assign hlp_port22_xlgmii_txclk_ena  =   1'b0;

assign hlp_port21_cgmii_rx_data     =   128'b0;   
assign hlp_port21_cgmii_rx_c        =   16'b0;   
assign hlp_port21_xlgmii_rx_data    =   64'b0;   
assign hlp_port21_xlgmii_rx_c       =   8'b0; 
assign hlp_port21_cgmii_rxclk_ena   =   1'b0;
assign hlp_port21_cgmii_txclk_ena   =   1'b0;
assign hlp_port21_xlgmii_rxclk_ena  =   1'b0;
assign hlp_port21_xlgmii_rxt0_next  =   1'b0;
assign hlp_port21_xlgmii_txclk_ena  =   1'b0;

assign hlp_port20_cgmii_rx_data     =   128'b0;   
assign hlp_port20_cgmii_rx_c        =   16'b0;   
assign hlp_port20_xlgmii_rx_data    =   64'b0;   
assign hlp_port20_xlgmii_rx_c       =   8'b0; 
assign hlp_port20_cgmii_rxclk_ena   =   1'b0;
assign hlp_port20_cgmii_txclk_ena   =   1'b0;
assign hlp_port20_xlgmii_rxclk_ena  =   1'b0;
assign hlp_port20_xlgmii_rxt0_next  =   1'b0;
assign hlp_port20_xlgmii_txclk_ena  =   1'b0;


assign hlp_port3_cgmii_rxclk_ena   =   1'b1;
assign hlp_port3_cgmii_txclk_ena   =   1'b1;
assign hlp_port3_xlgmii_rxclk_ena  =   1'b1;
assign hlp_port3_xlgmii_rxt0_next  =   1'b0;
assign hlp_port3_xlgmii_txclk_ena  =   1'b1;

assign hlp_port2_cgmii_rxclk_ena   =   1'b1;
assign hlp_port2_cgmii_txclk_ena   =   1'b1;
assign hlp_port2_xlgmii_rxclk_ena  =   1'b1;
assign hlp_port2_xlgmii_rxt0_next  =   1'b0;
assign hlp_port2_xlgmii_txclk_ena  =   1'b1;

assign hlp_port1_cgmii_rxclk_ena   =   1'b1;
assign hlp_port1_cgmii_txclk_ena   =   1'b1;
assign hlp_port1_xlgmii_rxclk_ena  =   1'b1;
assign hlp_port1_xlgmii_rxt0_next  =   1'b0;
assign hlp_port1_xlgmii_txclk_ena  =   1'b1;

assign hlp_port0_cgmii_rxclk_ena   =   1'b1;
assign hlp_port0_cgmii_txclk_ena   =   1'b1;
assign hlp_port0_xlgmii_rxclk_ena  =   1'b1;
assign hlp_port0_xlgmii_rxt0_next  =   1'b0;
assign hlp_port0_xlgmii_txclk_ena  =   1'b1;

wire	physs_hlp_repeater_reset_inv;
wire	physs_hlp_repeater_reset_sync;

rstsync 

rst_sync_cdc (

.clk				(ts_800_rdop_fout0_clkout)	,
.rst_n_pre_sync		(physs_hlp_repeater_reset)	,
.scan_byprst_n		(fscan_byprst_b)	,
.scan_rst_bypen		(fscan_rstbypen)	,
.rst_n_post_sync	(physs_hlp_repeater_reset_inv)	

);


ctech_lib_inv reset_inv (

.a	(physs_hlp_repeater_reset_inv),
.o1	(physs_hlp_repeater_reset_sync)

);





pcs_mac_pipeline_top_wrap

#(
.PIPE_NUM (5),
.CGDW     (128),
.CGCW     (16)
)
quad0_port4_0 (

.reset_mac0_ref_clk(1'b0),
.reset_mac1_ref_clk(1'b0),
.reset_mac2_ref_clk(1'b0),
.reset_mac3_ref_clk(1'b0),
.mac0_ref_clk(ts_800_rdop_fout0_clkout),
.mac1_ref_clk(ts_800_rdop_fout0_clkout),
.mac2_ref_clk(ts_800_rdop_fout0_clkout),
.mac3_ref_clk(ts_800_rdop_fout0_clkout),

.pcs0_cgmii_tx_clkena(1'b1),
.pcs0_cgmii_tx_txc(hlp_port0_cgmii_rx_c),
.pcs0_cgmii_tx_txd(hlp_port0_cgmii_rx_data),
.pcs0_cgmii_tx_tsu(),
.pcs0_cgmii_rx_clkena(1'b1),
.pcs0_cgmii_rx_rxc(hlp_port0_cgmii_tx_c),
.pcs0_cgmii_rx_rxd(hlp_port0_cgmii_tx_data),
.pcs0_cgmii_rx_tsu(),
.pcs0_cgmii_tsu_rx_sd(),

.mac0_cgmii_tx_clkena(),
.mac0_cgmii_tx_txc(hlp_cgmii0_txc_nss_0),
.mac0_cgmii_rx_clkena(),
.mac0_cgmii_rx_rxc(hlp_cgmii0_rxc_nss_0),
.mac0_cgmii_tx_txd(hlp_cgmii0_txd_nss_0),
.mac0_cgmii_rx_rxd(hlp_cgmii0_rxd_nss_0),

.tsu0_cgmii_tx_clkena(),
.tsu0_cgmii_tx_tsu(),
.tsu0_cgmii_rx_clkena(),
.tsu0_cgmii_rx_tsu(),
.tsu0_cgmii_rx_sd(),

.pcs0_xlgmii_tx_clkena(1'b1),
.pcs0_xlgmii_tx_txc(hlp_port0_xlgmii_rx_c),
.pcs0_xlgmii_tx_txd(hlp_port0_xlgmii_rx_data),
.pcs0_xlgmii_tx_tsu(),
.pcs0_xlgmii_rx_clkena(1'b1),
.pcs0_xlgmii_rx_rxc(hlp_port0_xlgmii_tx_c),
.pcs0_xlgmii_rx_rxd(hlp_port0_xlgmii_tx_data),
.pcs0_xlgmii_rxt0_next(),
.pcs0_xlgmii_rx_tsu(),
.pcs0_xlgmii_tsu_rx_sd(),

.mac0_xlgmii_tx_clkena(),
.mac0_xlgmii_tx_txc(hlp_xlgmii0_txc_nss_0),
.mac0_xlgmii_tx_txd(hlp_xlgmii0_txd_nss_0),
.mac0_xlgmii_rx_clkena(),
.mac0_xlgmii_rx_rxc(hlp_xlgmii0_rxc_nss_0),
.mac0_xlgmii_rx_rxd(hlp_xlgmii0_rxd_nss_0),
.mac0_xlgmii_rxt0_next(),

.tsu0_xlgmii_tx_clkena(),
.tsu0_xlgmii_tx_tsu(),
.tsu0_xlgmii_rx_clkena(),
.tsu0_xlgmii_rx_tsu(),
.tsu0_xlgmii_rx_sd(),


.pcs1_cgmii_tx_clkena(1'b1),
.pcs1_cgmii_tx_txc(hlp_port1_cgmii_rx_c),
.pcs1_cgmii_tx_txd(hlp_port1_cgmii_rx_data),
.pcs1_cgmii_tx_tsu(),
.pcs1_cgmii_rx_clkena(1'b1),
.pcs1_cgmii_rx_rxc(hlp_port1_cgmii_tx_c),
.pcs1_cgmii_rx_rxd(hlp_port1_cgmii_tx_data),
.pcs1_cgmii_rx_tsu(),
.pcs1_cgmii_tsu_rx_sd(),

.mac1_cgmii_tx_clkena(),
.mac1_cgmii_tx_txc(hlp_cgmii1_txc_nss_0),
.mac1_cgmii_tx_txd(hlp_cgmii1_txd_nss_0),
.mac1_cgmii_rx_clkena(),
.mac1_cgmii_rx_rxc(hlp_cgmii1_rxc_nss_0),
.mac1_cgmii_rx_rxd(hlp_cgmii1_rxd_nss_0),

.tsu1_cgmii_tx_clkena(),
.tsu1_cgmii_tx_tsu(),
.tsu1_cgmii_rx_clkena(),
.tsu1_cgmii_rx_tsu(),
.tsu1_cgmii_rx_sd(),

.pcs1_xlgmii_tx_clkena(1'b1),
.pcs1_xlgmii_tx_txc(hlp_port1_xlgmii_rx_c),
.pcs1_xlgmii_tx_txd(hlp_port1_xlgmii_rx_data),
.pcs1_xlgmii_tx_tsu(),
.pcs1_xlgmii_rx_clkena(1'b1),
.pcs1_xlgmii_rx_rxc(hlp_port1_xlgmii_tx_c),
.pcs1_xlgmii_rx_rxd(hlp_port1_xlgmii_tx_data),
.pcs1_xlgmii_rxt0_next(),
.pcs1_xlgmii_rx_tsu(),
.pcs1_xlgmii_tsu_rx_sd(),

.mac1_xlgmii_tx_clkena(),
.mac1_xlgmii_tx_txc(hlp_xlgmii1_txc_nss_0),
.mac1_xlgmii_tx_txd(hlp_xlgmii1_txd_nss_0),
.mac1_xlgmii_rx_clkena(),
.mac1_xlgmii_rx_rxc(hlp_xlgmii1_rxc_nss_0),
.mac1_xlgmii_rx_rxd(hlp_xlgmii1_rxd_nss_0),
.mac1_xlgmii_rxt0_next(),

.tsu1_xlgmii_tx_clkena(),
.tsu1_xlgmii_tx_tsu(),
.tsu1_xlgmii_rx_clkena(),
.tsu1_xlgmii_rx_tsu(),
.tsu1_xlgmii_rx_sd(),

.pcs2_cgmii_tx_clkena(1'b1),
.pcs2_cgmii_tx_txc(hlp_port2_cgmii_rx_c),
.pcs2_cgmii_tx_txd(hlp_port2_cgmii_rx_data),
.pcs2_cgmii_tx_tsu(),
.pcs2_cgmii_rx_clkena(1'b1),
.pcs2_cgmii_rx_rxc(hlp_port2_cgmii_tx_c),
.pcs2_cgmii_rx_rxd(hlp_port2_cgmii_tx_data),
.pcs2_cgmii_rx_tsu(),
.pcs2_cgmii_tsu_rx_sd(),

.mac2_cgmii_tx_clkena(),
.mac2_cgmii_tx_txc(hlp_cgmii2_txc_nss_0),
.mac2_cgmii_tx_txd(hlp_cgmii2_txd_nss_0),
.mac2_cgmii_rx_clkena(),
.mac2_cgmii_rx_rxc(hlp_cgmii2_rxc_nss_0),
.mac2_cgmii_rx_rxd(hlp_cgmii2_rxd_nss_0),

.tsu2_cgmii_tx_clkena(),
.tsu2_cgmii_tx_tsu(),
.tsu2_cgmii_rx_clkena(),
.tsu2_cgmii_rx_tsu(),
.tsu2_cgmii_rx_sd(),

.pcs2_xlgmii_tx_clkena(1'b1),
.pcs2_xlgmii_tx_txc(hlp_port2_xlgmii_rx_c),
.pcs2_xlgmii_tx_txd(hlp_port2_xlgmii_rx_data),
.pcs2_xlgmii_tx_tsu(),
.pcs2_xlgmii_rx_clkena(1'b1),
.pcs2_xlgmii_rx_rxc(hlp_port2_xlgmii_tx_c),
.pcs2_xlgmii_rx_rxd(hlp_port2_xlgmii_tx_data),
.pcs2_xlgmii_rxt0_next(),
.pcs2_xlgmii_rx_tsu(),
.pcs2_xlgmii_tsu_rx_sd(),

.mac2_xlgmii_tx_clkena(),
.mac2_xlgmii_tx_txc(hlp_xlgmii2_txc_nss_0),
.mac2_xlgmii_tx_txd(hlp_xlgmii2_txd_nss_0),
.mac2_xlgmii_rx_clkena(),
.mac2_xlgmii_rx_rxc(hlp_xlgmii2_rxc_nss_0),
.mac2_xlgmii_rx_rxd(hlp_xlgmii2_rxd_nss_0),
.mac2_xlgmii_rxt0_next(),

.tsu2_xlgmii_tx_clkena(),
.tsu2_xlgmii_tx_tsu(),
.tsu2_xlgmii_rx_clkena(),
.tsu2_xlgmii_rx_tsu(),
.tsu2_xlgmii_rx_sd(),

.pcs3_cgmii_tx_clkena(1'b1),
.pcs3_cgmii_tx_txc(hlp_port3_cgmii_rx_c),
.pcs3_cgmii_tx_txd(hlp_port3_cgmii_rx_data),
.pcs3_cgmii_tx_tsu(),
.pcs3_cgmii_rx_clkena(1'b1),
.pcs3_cgmii_rx_rxc(hlp_port3_cgmii_tx_c),
.pcs3_cgmii_rx_rxd(hlp_port3_cgmii_tx_data),
.pcs3_cgmii_rx_tsu(),
.pcs3_cgmii_tsu_rx_sd(),

.mac3_cgmii_tx_clkena(),
.mac3_cgmii_tx_txc(hlp_cgmii3_txc_nss_0),
.mac3_cgmii_tx_txd(hlp_cgmii3_txd_nss_0),
.mac3_cgmii_rx_clkena(),
.mac3_cgmii_rx_rxc(hlp_cgmii3_rxc_nss_0),
.mac3_cgmii_rx_rxd(hlp_cgmii3_rxd_nss_0),

.tsu3_cgmii_tx_clkena(),
.tsu3_cgmii_tx_tsu(),
.tsu3_cgmii_rx_clkena(),
.tsu3_cgmii_rx_tsu(),
.tsu3_cgmii_rx_sd(),

.pcs3_xlgmii_tx_clkena(1'b1),
.pcs3_xlgmii_tx_txc(hlp_port3_xlgmii_rx_c),
.pcs3_xlgmii_tx_txd(hlp_port3_xlgmii_rx_data),
.pcs3_xlgmii_tx_tsu(),
.pcs3_xlgmii_rx_clkena(1'b1),
.pcs3_xlgmii_rx_rxc(hlp_port3_xlgmii_tx_c),
.pcs3_xlgmii_rx_rxd(hlp_port3_xlgmii_tx_data),
.pcs3_xlgmii_rxt0_next(),
.pcs3_xlgmii_rx_tsu(),
.pcs3_xlgmii_tsu_rx_sd(),

.mac3_xlgmii_tx_clkena(),
.mac3_xlgmii_tx_txc(hlp_xlgmii3_txc_nss_0),
.mac3_xlgmii_tx_txd(hlp_xlgmii3_txd_nss_0),
.mac3_xlgmii_rx_clkena(),
.mac3_xlgmii_rx_rxc(hlp_xlgmii3_rxc_nss_0),
.mac3_xlgmii_rx_rxd(hlp_xlgmii3_rxd_nss_0),
.mac3_xlgmii_rxt0_next(),

.tsu3_xlgmii_tx_clkena(),
.tsu3_xlgmii_tx_tsu(),
.tsu3_xlgmii_rx_clkena(),
.tsu3_xlgmii_rx_tsu(),
.tsu3_xlgmii_rx_sd()

);



pcs_mac_pipeline_top_wrap

#(
.PIPE_NUM (5),
.CGDW     (128),
.CGCW     (16)
)
quad0_port4_1 (

.reset_mac0_ref_clk(1'b0),
.reset_mac1_ref_clk(1'b0),
.reset_mac2_ref_clk(1'b0),
.reset_mac3_ref_clk(1'b0),
.mac0_ref_clk(ts_800_rdop_fout0_clkout),
.mac1_ref_clk(ts_800_rdop_fout0_clkout),
.mac2_ref_clk(ts_800_rdop_fout0_clkout),
.mac3_ref_clk(ts_800_rdop_fout0_clkout),

.pcs0_cgmii_tx_clkena(hlp_cgmii0_txclk_ena_0),
.pcs0_cgmii_tx_txc(hlp_cgmii0_txc_0),
.pcs0_cgmii_tx_txd(hlp_cgmii0_txd_0),
.pcs0_cgmii_tx_tsu(),
.pcs0_cgmii_rx_clkena(hlp_cgmii0_rxclk_ena_0),
.pcs0_cgmii_rx_rxc(hlp_cgmii0_rxc_0),
.pcs0_cgmii_rx_rxd(hlp_cgmii0_rxd_0),
.pcs0_cgmii_rx_tsu(),
.pcs0_cgmii_tsu_rx_sd(),

.mac0_cgmii_tx_clkena(hlp_port4_cgmii_txclk_ena),
.mac0_cgmii_tx_txc(hlp_port4_cgmii_tx_c),
.mac0_cgmii_tx_txd(hlp_port4_cgmii_tx_data),
.mac0_cgmii_rx_clkena(hlp_port4_cgmii_rxclk_ena),
.mac0_cgmii_rx_rxc(hlp_port4_cgmii_rx_c),
.mac0_cgmii_rx_rxd(hlp_port4_cgmii_rx_data),

.tsu0_cgmii_tx_clkena(),
.tsu0_cgmii_tx_tsu(),
.tsu0_cgmii_rx_clkena(),
.tsu0_cgmii_rx_tsu(),
.tsu0_cgmii_rx_sd(),

.pcs0_xlgmii_tx_clkena(hlp_xlgmii0_txclk_ena_0),
.pcs0_xlgmii_tx_txc(hlp_xlgmii0_txc_0),
.pcs0_xlgmii_tx_txd(hlp_xlgmii0_txd_0),
.pcs0_xlgmii_tx_tsu(mii_tx_tsu[1:0]),
.pcs0_xlgmii_rx_clkena(hlp_xlgmii0_rxclk_ena_0),
.pcs0_xlgmii_rx_rxc(hlp_xlgmii0_rxc_0),
.pcs0_xlgmii_rx_rxd(hlp_xlgmii0_rxd_0),
.pcs0_xlgmii_rxt0_next(hlp_xlgmii0_rxt0_next_0),
.pcs0_xlgmii_rx_tsu(mii_rx_tsu_mux[1:0]),
.pcs0_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[1:0]),

.mac0_xlgmii_tx_clkena(hlp_port4_xlgmii_txclk_ena),
.mac0_xlgmii_tx_txc(hlp_port4_xlgmii_tx_c),
.mac0_xlgmii_tx_txd(hlp_port4_xlgmii_tx_data),
.mac0_xlgmii_rx_clkena(hlp_port4_xlgmii_rxclk_ena),
.mac0_xlgmii_rx_rxc(hlp_port4_xlgmii_rx_c),
.mac0_xlgmii_rx_rxd(hlp_port4_xlgmii_rx_data),
.mac0_xlgmii_rxt0_next(hlp_port4_xlgmii_rxt0_next),

.tsu0_xlgmii_tx_clkena(),
.tsu0_xlgmii_tx_tsu(hlp_port4_mii_tx_tsu),
.tsu0_xlgmii_rx_clkena(),
.tsu0_xlgmii_rx_tsu(hlp_port4_mii_rx_tsu),
.tsu0_xlgmii_rx_sd(hlp_port4_tsu_rx_sd),

.pcs1_cgmii_tx_clkena(hlp_cgmii1_txclk_ena_0),
.pcs1_cgmii_tx_txc(hlp_cgmii1_txc_0),
.pcs1_cgmii_tx_txd(hlp_cgmii1_txd_0),
.pcs1_cgmii_tx_tsu(),
.pcs1_cgmii_rx_clkena(hlp_cgmii1_rxclk_ena_0),
.pcs1_cgmii_rx_rxc(hlp_cgmii1_rxc_0),
.pcs1_cgmii_rx_rxd(hlp_cgmii1_rxd_0),
.pcs1_cgmii_rx_tsu(),
.pcs1_cgmii_tsu_rx_sd(),

.mac1_cgmii_tx_clkena(hlp_port5_cgmii_txclk_ena),
.mac1_cgmii_tx_txc(hlp_port5_cgmii_tx_c),
.mac1_cgmii_tx_txd(hlp_port5_cgmii_tx_data),
.mac1_cgmii_rx_clkena(hlp_port5_cgmii_rxclk_ena),
.mac1_cgmii_rx_rxc(hlp_port5_cgmii_rx_c),
.mac1_cgmii_rx_rxd(hlp_port5_cgmii_rx_data),

.tsu1_cgmii_tx_clkena(),
.tsu1_cgmii_tx_tsu(),
.tsu1_cgmii_rx_clkena(),
.tsu1_cgmii_rx_tsu(),
.tsu1_cgmii_rx_sd(),

.pcs1_xlgmii_tx_clkena(hlp_xlgmii1_txclk_ena_0),
.pcs1_xlgmii_tx_txc(hlp_xlgmii1_txc_0),
.pcs1_xlgmii_tx_txd(hlp_xlgmii1_txd_0),
.pcs1_xlgmii_tx_tsu(mii_tx_tsu[3:2]),
.pcs1_xlgmii_rx_clkena(hlp_xlgmii1_rxclk_ena_0),
.pcs1_xlgmii_rx_rxc(hlp_xlgmii1_rxc_0),
.pcs1_xlgmii_rx_rxd(hlp_xlgmii1_rxd_0),
.pcs1_xlgmii_rxt0_next(hlp_xlgmii1_rxt0_next_0),
.pcs1_xlgmii_rx_tsu(mii_rx_tsu_mux[3:2]),
.pcs1_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[3:2]),

.mac1_xlgmii_tx_clkena(hlp_port5_xlgmii_txclk_ena),
.mac1_xlgmii_tx_txc(hlp_port5_xlgmii_tx_c),
.mac1_xlgmii_tx_txd(hlp_port5_xlgmii_tx_data),
.mac1_xlgmii_rx_clkena(hlp_port5_xlgmii_rxclk_ena),
.mac1_xlgmii_rx_rxc(hlp_port5_xlgmii_rx_c),
.mac1_xlgmii_rx_rxd(hlp_port5_xlgmii_rx_data),
.mac1_xlgmii_rxt0_next(hlp_port5_xlgmii_rxt0_next),

.tsu1_xlgmii_tx_clkena(),
.tsu1_xlgmii_tx_tsu(hlp_port5_mii_tx_tsu),
.tsu1_xlgmii_rx_clkena(),
.tsu1_xlgmii_rx_tsu(hlp_port5_mii_rx_tsu),
.tsu1_xlgmii_rx_sd(hlp_port5_tsu_rx_sd),

.pcs2_cgmii_tx_clkena(hlp_cgmii2_txclk_ena_0),
.pcs2_cgmii_tx_txc(hlp_cgmii2_txc_0),
.pcs2_cgmii_tx_txd(hlp_cgmii2_txd_0),
.pcs2_cgmii_tx_tsu(),
.pcs2_cgmii_rx_clkena(hlp_cgmii2_rxclk_ena_0),
.pcs2_cgmii_rx_rxc(hlp_cgmii2_rxc_0),
.pcs2_cgmii_rx_rxd(hlp_cgmii2_rxd_0),
.pcs2_cgmii_rx_tsu(),
.pcs2_cgmii_tsu_rx_sd(),

.mac2_cgmii_tx_clkena(hlp_port6_cgmii_txclk_ena),
.mac2_cgmii_tx_txc(hlp_port6_cgmii_tx_c),
.mac2_cgmii_tx_txd(hlp_port6_cgmii_tx_data),
.mac2_cgmii_rx_clkena(hlp_port6_cgmii_rxclk_ena),
.mac2_cgmii_rx_rxc(hlp_port6_cgmii_rx_c),
.mac2_cgmii_rx_rxd(hlp_port6_cgmii_rx_data),

.tsu2_cgmii_tx_clkena(),
.tsu2_cgmii_tx_tsu(),
.tsu2_cgmii_rx_clkena(),
.tsu2_cgmii_rx_tsu(),
.tsu2_cgmii_rx_sd(),

.pcs2_xlgmii_tx_clkena(hlp_xlgmii2_txclk_ena_0),
.pcs2_xlgmii_tx_txc(hlp_xlgmii2_txc_0),
.pcs2_xlgmii_tx_txd(hlp_xlgmii2_txd_0),
.pcs2_xlgmii_tx_tsu(mii_tx_tsu[5:4]),
.pcs2_xlgmii_rx_clkena(hlp_xlgmii2_rxclk_ena_0),
.pcs2_xlgmii_rx_rxc(hlp_xlgmii2_rxc_0),
.pcs2_xlgmii_rx_rxd(hlp_xlgmii2_rxd_0),
.pcs2_xlgmii_rxt0_next(hlp_xlgmii2_rxt0_next_0),
.pcs2_xlgmii_rx_tsu(mii_rx_tsu_mux[5:4]),
.pcs2_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[5:4]),

.mac2_xlgmii_tx_clkena(hlp_port6_xlgmii_txclk_ena),
.mac2_xlgmii_tx_txc(hlp_port6_xlgmii_tx_c),
.mac2_xlgmii_tx_txd(hlp_port6_xlgmii_tx_data),
.mac2_xlgmii_rx_clkena(hlp_port6_xlgmii_rxclk_ena),
.mac2_xlgmii_rx_rxc(hlp_port6_xlgmii_rx_c),
.mac2_xlgmii_rx_rxd(hlp_port6_xlgmii_rx_data),
.mac2_xlgmii_rxt0_next(hlp_port6_xlgmii_rxt0_next),

.tsu2_xlgmii_tx_clkena(),
.tsu2_xlgmii_tx_tsu(hlp_port6_mii_tx_tsu),
.tsu2_xlgmii_rx_clkena(),
.tsu2_xlgmii_rx_tsu(hlp_port6_mii_rx_tsu),
.tsu2_xlgmii_rx_sd(hlp_port6_tsu_rx_sd),

.pcs3_cgmii_tx_clkena(hlp_cgmii3_txclk_ena_0),
.pcs3_cgmii_tx_txc(hlp_cgmii3_txc_0),
.pcs3_cgmii_tx_txd(hlp_cgmii3_txd_0),
.pcs3_cgmii_tx_tsu(),
.pcs3_cgmii_rx_clkena(hlp_cgmii3_rxclk_ena_0),
.pcs3_cgmii_rx_rxc(hlp_cgmii3_rxc_0),
.pcs3_cgmii_rx_rxd(hlp_cgmii3_rxd_0),
.pcs3_cgmii_rx_tsu(),
.pcs3_cgmii_tsu_rx_sd(),

.mac3_cgmii_tx_clkena(hlp_port7_cgmii_txclk_ena),
.mac3_cgmii_tx_txc(hlp_port7_cgmii_tx_c),
.mac3_cgmii_tx_txd(hlp_port7_cgmii_tx_data),
.mac3_cgmii_rx_clkena(hlp_port7_cgmii_rxclk_ena),
.mac3_cgmii_rx_rxc(hlp_port7_cgmii_rx_c),
.mac3_cgmii_rx_rxd(hlp_port7_cgmii_rx_data),

.tsu3_cgmii_tx_clkena(),
.tsu3_cgmii_tx_tsu(),
.tsu3_cgmii_rx_clkena(),
.tsu3_cgmii_rx_tsu(),
.tsu3_cgmii_rx_sd(),

.pcs3_xlgmii_tx_clkena(hlp_xlgmii3_txclk_ena_0),
.pcs3_xlgmii_tx_txc(hlp_xlgmii3_txc_0),
.pcs3_xlgmii_tx_txd(hlp_xlgmii3_txd_0),
.pcs3_xlgmii_tx_tsu(mii_tx_tsu[7:6]),
.pcs3_xlgmii_rx_clkena(hlp_xlgmii3_rxclk_ena_0),
.pcs3_xlgmii_rx_rxc(hlp_xlgmii3_rxc_0),
.pcs3_xlgmii_rx_rxd(hlp_xlgmii3_rxd_0),
.pcs3_xlgmii_rxt0_next(hlp_xlgmii3_rxt0_next_0),
.pcs3_xlgmii_rx_tsu(mii_rx_tsu_mux[7:6]),
.pcs3_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[7:6]),

.mac3_xlgmii_tx_clkena(hlp_port7_xlgmii_txclk_ena),
.mac3_xlgmii_tx_txc(hlp_port7_xlgmii_tx_c),
.mac3_xlgmii_tx_txd(hlp_port7_xlgmii_tx_data),
.mac3_xlgmii_rx_clkena(hlp_port7_xlgmii_rxclk_ena),
.mac3_xlgmii_rx_rxc(hlp_port7_xlgmii_rx_c),
.mac3_xlgmii_rx_rxd(hlp_port7_xlgmii_rx_data),
.mac3_xlgmii_rxt0_next(hlp_port7_xlgmii_rxt0_next),

.tsu3_xlgmii_tx_clkena(),
.tsu3_xlgmii_tx_tsu(hlp_port7_mii_tx_tsu),
.tsu3_xlgmii_rx_clkena(),
.tsu3_xlgmii_rx_tsu(hlp_port7_mii_rx_tsu),
.tsu3_xlgmii_rx_sd(hlp_port7_tsu_rx_sd)

);



pcs_mac_pipeline_top_wrap

#(
.PIPE_NUM (5),
.CGDW     (128),
.CGCW     (16)
)
quad1_port4_1 (

.reset_mac0_ref_clk(1'b0),
.reset_mac1_ref_clk(1'b0),
.reset_mac2_ref_clk(1'b0),
.reset_mac3_ref_clk(1'b0),
.mac0_ref_clk(ts_800_rdop_fout0_clkout),
.mac1_ref_clk(ts_800_rdop_fout0_clkout),
.mac2_ref_clk(ts_800_rdop_fout0_clkout),
.mac3_ref_clk(ts_800_rdop_fout0_clkout),

.pcs0_cgmii_tx_clkena(hlp_cgmii0_txclk_ena_1),
.pcs0_cgmii_tx_txc(hlp_cgmii0_txc_1),
.pcs0_cgmii_tx_txd(hlp_cgmii0_txd_1),
.pcs0_cgmii_tx_tsu(),
.pcs0_cgmii_rx_clkena(hlp_cgmii0_rxclk_ena_1),
.pcs0_cgmii_rx_rxc(hlp_cgmii0_rxc_1),
.pcs0_cgmii_rx_rxd(hlp_cgmii0_rxd_1),
.pcs0_cgmii_rx_tsu(),
.pcs0_cgmii_tsu_rx_sd(),

.mac0_cgmii_tx_clkena(hlp_port8_cgmii_txclk_ena),
.mac0_cgmii_tx_txc(hlp_port8_cgmii_tx_c),
.mac0_cgmii_tx_txd(hlp_port8_cgmii_tx_data),
.mac0_cgmii_rx_clkena(hlp_port8_cgmii_rxclk_ena),
.mac0_cgmii_rx_rxc(hlp_port8_cgmii_rx_c),
.mac0_cgmii_rx_rxd(hlp_port8_cgmii_rx_data),

.tsu0_cgmii_tx_clkena(),
.tsu0_cgmii_tx_tsu(),
.tsu0_cgmii_rx_clkena(),
.tsu0_cgmii_rx_tsu(),
.tsu0_cgmii_rx_sd(),

.pcs0_xlgmii_tx_clkena(hlp_xlgmii0_txclk_ena_1),
.pcs0_xlgmii_tx_txc(hlp_xlgmii0_txc_1),
.pcs0_xlgmii_tx_txd(hlp_xlgmii0_txd_1),
.pcs0_xlgmii_tx_tsu(mii_tx_tsu[9:8]),
.pcs0_xlgmii_rx_clkena(hlp_xlgmii0_rxclk_ena_1),
.pcs0_xlgmii_rx_rxc(hlp_xlgmii0_rxc_1),
.pcs0_xlgmii_rx_rxd(hlp_xlgmii0_rxd_1),
.pcs0_xlgmii_rxt0_next(hlp_xlgmii0_rxt0_next_1),
.pcs0_xlgmii_rx_tsu(mii_rx_tsu_mux[9:8]),
.pcs0_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[9:8]),

.mac0_xlgmii_tx_clkena(hlp_port8_xlgmii_txclk_ena),
.mac0_xlgmii_tx_txc(hlp_port8_xlgmii_tx_c),
.mac0_xlgmii_tx_txd(hlp_port8_xlgmii_tx_data),
.mac0_xlgmii_rx_clkena(hlp_port8_xlgmii_rxclk_ena),
.mac0_xlgmii_rx_rxc(hlp_port8_xlgmii_rx_c),
.mac0_xlgmii_rx_rxd(hlp_port8_xlgmii_rx_data),
.mac0_xlgmii_rxt0_next(hlp_port8_xlgmii_rxt0_next),

.tsu0_xlgmii_tx_clkena(),
.tsu0_xlgmii_tx_tsu(hlp_port8_mii_tx_tsu),
.tsu0_xlgmii_rx_clkena(),
.tsu0_xlgmii_rx_tsu(hlp_port8_mii_rx_tsu),
.tsu0_xlgmii_rx_sd(hlp_port8_tsu_rx_sd),

.pcs1_cgmii_tx_clkena(hlp_cgmii1_txclk_ena_1),
.pcs1_cgmii_tx_txc(hlp_cgmii1_txc_1),
.pcs1_cgmii_tx_txd(hlp_cgmii1_txd_1),
.pcs1_cgmii_tx_tsu(),
.pcs1_cgmii_rx_clkena(hlp_cgmii1_rxclk_ena_1),
.pcs1_cgmii_rx_rxc(hlp_cgmii1_rxc_1),
.pcs1_cgmii_rx_rxd(hlp_cgmii1_rxd_1),
.pcs1_cgmii_rx_tsu(),
.pcs1_cgmii_tsu_rx_sd(),

.mac1_cgmii_tx_clkena(hlp_port9_cgmii_txclk_ena),
.mac1_cgmii_tx_txc(hlp_port9_cgmii_tx_c),
.mac1_cgmii_tx_txd(hlp_port9_cgmii_tx_data),
.mac1_cgmii_rx_clkena(hlp_port9_cgmii_rxclk_ena),
.mac1_cgmii_rx_rxc(hlp_port9_cgmii_rx_c),
.mac1_cgmii_rx_rxd(hlp_port9_cgmii_rx_data),

.tsu1_cgmii_tx_clkena(),
.tsu1_cgmii_tx_tsu(),
.tsu1_cgmii_rx_clkena(),
.tsu1_cgmii_rx_tsu(),
.tsu1_cgmii_rx_sd(),

.pcs1_xlgmii_tx_clkena(hlp_xlgmii1_txclk_ena_1),
.pcs1_xlgmii_tx_txc(hlp_xlgmii1_txc_1),
.pcs1_xlgmii_tx_txd(hlp_xlgmii1_txd_1),
.pcs1_xlgmii_tx_tsu(mii_tx_tsu[11:10]),
.pcs1_xlgmii_rx_clkena(hlp_xlgmii1_rxclk_ena_1),
.pcs1_xlgmii_rx_rxc(hlp_xlgmii1_rxc_1),
.pcs1_xlgmii_rx_rxd(hlp_xlgmii1_rxd_1),
.pcs1_xlgmii_rxt0_next(hlp_xlgmii1_rxt0_next_1),
.pcs1_xlgmii_rx_tsu(mii_rx_tsu_mux[11:10]),
.pcs1_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[11:10]),

.mac1_xlgmii_tx_clkena(hlp_port9_xlgmii_txclk_ena),
.mac1_xlgmii_tx_txc(hlp_port9_xlgmii_tx_c),
.mac1_xlgmii_tx_txd(hlp_port9_xlgmii_tx_data),
.mac1_xlgmii_rx_clkena(hlp_port9_xlgmii_rxclk_ena),
.mac1_xlgmii_rx_rxc(hlp_port9_xlgmii_rx_c),
.mac1_xlgmii_rx_rxd(hlp_port9_xlgmii_rx_data),
.mac1_xlgmii_rxt0_next(hlp_port9_xlgmii_rxt0_next),

.tsu1_xlgmii_tx_clkena(),
.tsu1_xlgmii_tx_tsu(hlp_port9_mii_tx_tsu),
.tsu1_xlgmii_rx_clkena(),
.tsu1_xlgmii_rx_tsu(hlp_port9_mii_rx_tsu),
.tsu1_xlgmii_rx_sd(hlp_port9_tsu_rx_sd),

.pcs2_cgmii_tx_clkena(hlp_cgmii2_txclk_ena_1),
.pcs2_cgmii_tx_txc(hlp_cgmii2_txc_1),
.pcs2_cgmii_tx_txd(hlp_cgmii2_txd_1),
.pcs2_cgmii_tx_tsu(),
.pcs2_cgmii_rx_clkena(hlp_cgmii2_rxclk_ena_1),
.pcs2_cgmii_rx_rxc(hlp_cgmii2_rxc_1),
.pcs2_cgmii_rx_rxd(hlp_cgmii2_rxd_1),
.pcs2_cgmii_rx_tsu(),
.pcs2_cgmii_tsu_rx_sd(),

.mac2_cgmii_tx_clkena(hlp_port10_cgmii_txclk_ena),
.mac2_cgmii_tx_txc(hlp_port10_cgmii_tx_c),
.mac2_cgmii_tx_txd(hlp_port10_cgmii_tx_data),
.mac2_cgmii_rx_clkena(hlp_port10_cgmii_rxclk_ena),
.mac2_cgmii_rx_rxc(hlp_port10_cgmii_rx_c),
.mac2_cgmii_rx_rxd(hlp_port10_cgmii_rx_data),

.tsu2_cgmii_tx_clkena(),
.tsu2_cgmii_tx_tsu(),
.tsu2_cgmii_rx_clkena(),
.tsu2_cgmii_rx_tsu(),
.tsu2_cgmii_rx_sd(),

.pcs2_xlgmii_tx_clkena(hlp_xlgmii2_txclk_ena_1),
.pcs2_xlgmii_tx_txc(hlp_xlgmii2_txc_1),
.pcs2_xlgmii_tx_txd(hlp_xlgmii2_txd_1),
.pcs2_xlgmii_tx_tsu(mii_tx_tsu[13:12]),
.pcs2_xlgmii_rx_clkena(hlp_xlgmii2_rxclk_ena_1),
.pcs2_xlgmii_rx_rxc(hlp_xlgmii2_rxc_1),
.pcs2_xlgmii_rx_rxd(hlp_xlgmii2_rxd_1),
.pcs2_xlgmii_rxt0_next(hlp_xlgmii2_rxt0_next_1),
.pcs2_xlgmii_rx_tsu(mii_rx_tsu_mux[13:12]),
.pcs2_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[13:12]),

.mac2_xlgmii_tx_clkena(hlp_port10_xlgmii_txclk_ena),
.mac2_xlgmii_tx_txc(hlp_port10_xlgmii_tx_c),
.mac2_xlgmii_tx_txd(hlp_port10_xlgmii_tx_data),
.mac2_xlgmii_rx_clkena(hlp_port10_xlgmii_rxclk_ena),
.mac2_xlgmii_rx_rxc(hlp_port10_xlgmii_rx_c),
.mac2_xlgmii_rx_rxd(hlp_port10_xlgmii_rx_data),
.mac2_xlgmii_rxt0_next(hlp_port10_xlgmii_rxt0_next),

.tsu2_xlgmii_tx_clkena(),
.tsu2_xlgmii_tx_tsu(hlp_port10_mii_tx_tsu),
.tsu2_xlgmii_rx_clkena(),
.tsu2_xlgmii_rx_tsu(hlp_port10_mii_rx_tsu),
.tsu2_xlgmii_rx_sd(hlp_port10_tsu_rx_sd),

.pcs3_cgmii_tx_clkena(hlp_cgmii3_txclk_ena_1),
.pcs3_cgmii_tx_txc(hlp_cgmii3_txc_1),
.pcs3_cgmii_tx_txd(hlp_cgmii3_txd_1),
.pcs3_cgmii_tx_tsu(),
.pcs3_cgmii_rx_clkena(hlp_cgmii3_rxclk_ena_1),
.pcs3_cgmii_rx_rxc(hlp_cgmii3_rxc_1),
.pcs3_cgmii_rx_rxd(hlp_cgmii3_rxd_1),
.pcs3_cgmii_rx_tsu(),
.pcs3_cgmii_tsu_rx_sd(),

.mac3_cgmii_tx_clkena(hlp_port11_cgmii_txclk_ena),
.mac3_cgmii_tx_txc(hlp_port11_cgmii_tx_c),
.mac3_cgmii_tx_txd(hlp_port11_cgmii_tx_data),
.mac3_cgmii_rx_clkena(hlp_port11_cgmii_rxclk_ena),
.mac3_cgmii_rx_rxc(hlp_port11_cgmii_rx_c),
.mac3_cgmii_rx_rxd(hlp_port11_cgmii_rx_data),

.tsu3_cgmii_tx_clkena(),
.tsu3_cgmii_tx_tsu(),
.tsu3_cgmii_rx_clkena(),
.tsu3_cgmii_rx_tsu(),
.tsu3_cgmii_rx_sd(),

.pcs3_xlgmii_tx_clkena(hlp_xlgmii3_txclk_ena_1),
.pcs3_xlgmii_tx_txc(hlp_xlgmii3_txc_1),
.pcs3_xlgmii_tx_txd(hlp_xlgmii3_txd_1),
.pcs3_xlgmii_tx_tsu(mii_tx_tsu[15:14]),
.pcs3_xlgmii_rx_clkena(hlp_xlgmii3_rxclk_ena_1),
.pcs3_xlgmii_rx_rxc(hlp_xlgmii3_rxc_1),
.pcs3_xlgmii_rx_rxd(hlp_xlgmii3_rxd_1),
.pcs3_xlgmii_rxt0_next(hlp_xlgmii3_rxt0_next_1),
.pcs3_xlgmii_rx_tsu(mii_rx_tsu_mux[15:14]),
.pcs3_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[15:14]),

.mac3_xlgmii_tx_clkena(hlp_port11_xlgmii_txclk_ena),
.mac3_xlgmii_tx_txc(hlp_port11_xlgmii_tx_c),
.mac3_xlgmii_tx_txd(hlp_port11_xlgmii_tx_data),
.mac3_xlgmii_rx_clkena(hlp_port11_xlgmii_rxclk_ena),
.mac3_xlgmii_rx_rxc(hlp_port11_xlgmii_rx_c),
.mac3_xlgmii_rx_rxd(hlp_port11_xlgmii_rx_data),
.mac3_xlgmii_rxt0_next(hlp_port11_xlgmii_rxt0_next),

.tsu3_xlgmii_tx_clkena(),
.tsu3_xlgmii_tx_tsu(hlp_port11_mii_tx_tsu),
.tsu3_xlgmii_rx_clkena(),
.tsu3_xlgmii_rx_tsu(hlp_port11_mii_rx_tsu),
.tsu3_xlgmii_rx_sd(hlp_port11_tsu_rx_sd)

);



pcs_mac_pipeline_top_wrap

#(
.PIPE_NUM (2),
.CGDW     (128),
.CGCW     (16)
)
quad2_port4_3 (

.reset_mac0_ref_clk(1'b0),
.reset_mac1_ref_clk(1'b0),
.reset_mac2_ref_clk(1'b0),
.reset_mac3_ref_clk(1'b0),
.mac0_ref_clk(ts_800_rdop_fout0_clkout),
.mac1_ref_clk(ts_800_rdop_fout0_clkout),
.mac2_ref_clk(ts_800_rdop_fout0_clkout),
.mac3_ref_clk(ts_800_rdop_fout0_clkout),

.pcs0_cgmii_tx_clkena(hlp_cgmii0_txclk_ena_2),
.pcs0_cgmii_tx_txc(hlp_cgmii0_txc_2),
.pcs0_cgmii_tx_txd(hlp_cgmii0_txd_2),
.pcs0_cgmii_tx_tsu(),
.pcs0_cgmii_rx_clkena(hlp_cgmii0_rxclk_ena_2),
.pcs0_cgmii_rx_rxc(hlp_cgmii0_rxc_2),
.pcs0_cgmii_rx_rxd(hlp_cgmii0_rxd_2),
.pcs0_cgmii_rx_tsu(),
.pcs0_cgmii_tsu_rx_sd(),

.mac0_cgmii_tx_clkena(hlp_port12_cgmii_txclk_ena),
.mac0_cgmii_tx_txc(hlp_port12_cgmii_tx_c),
.mac0_cgmii_tx_txd(hlp_port12_cgmii_tx_data),
.mac0_cgmii_rx_clkena(hlp_port12_cgmii_rxclk_ena),
.mac0_cgmii_rx_rxc(hlp_port12_cgmii_rx_c),
.mac0_cgmii_rx_rxd(hlp_port12_cgmii_rx_data),

.tsu0_cgmii_tx_clkena(),
.tsu0_cgmii_tx_tsu(),
.tsu0_cgmii_rx_clkena(),
.tsu0_cgmii_rx_tsu(),
.tsu0_cgmii_rx_sd(),

.pcs0_xlgmii_tx_clkena(hlp_xlgmii0_txclk_ena_2),
.pcs0_xlgmii_tx_txc(hlp_xlgmii0_txc_2),
.pcs0_xlgmii_tx_txd(hlp_xlgmii0_txd_2),
.pcs0_xlgmii_tx_tsu(mii_tx_tsu[17:16]),
.pcs0_xlgmii_rx_clkena(hlp_xlgmii0_rxclk_ena_2),
.pcs0_xlgmii_rx_rxc(hlp_xlgmii0_rxc_2),
.pcs0_xlgmii_rx_rxd(hlp_xlgmii0_rxd_2),
.pcs0_xlgmii_rxt0_next(hlp_xlgmii0_rxt0_next_2),
.pcs0_xlgmii_rx_tsu(mii_rx_tsu_mux[17:16]),
.pcs0_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[17:16]),

.mac0_xlgmii_tx_clkena(hlp_port12_xlgmii_txclk_ena),
.mac0_xlgmii_tx_txc(hlp_port12_xlgmii_tx_c),
.mac0_xlgmii_tx_txd(hlp_port12_xlgmii_tx_data),
.mac0_xlgmii_rx_clkena(hlp_port12_xlgmii_rxclk_ena),
.mac0_xlgmii_rx_rxc(hlp_port12_xlgmii_rx_c),
.mac0_xlgmii_rx_rxd(hlp_port12_xlgmii_rx_data),
.mac0_xlgmii_rxt0_next(hlp_port12_xlgmii_rxt0_next),

.tsu0_xlgmii_tx_clkena(),
.tsu0_xlgmii_tx_tsu(hlp_port12_mii_tx_tsu),
.tsu0_xlgmii_rx_clkena(),
.tsu0_xlgmii_rx_tsu(hlp_port12_mii_rx_tsu),
.tsu0_xlgmii_rx_sd(hlp_port12_tsu_rx_sd),

.pcs1_cgmii_tx_clkena(hlp_cgmii1_txclk_ena_2),
.pcs1_cgmii_tx_txc(hlp_cgmii1_txc_2),
.pcs1_cgmii_tx_txd(hlp_cgmii1_txd_2),
.pcs1_cgmii_tx_tsu(),
.pcs1_cgmii_rx_clkena(hlp_cgmii1_rxclk_ena_2),
.pcs1_cgmii_rx_rxc(hlp_cgmii1_rxc_2),
.pcs1_cgmii_rx_rxd(hlp_cgmii1_rxd_2),
.pcs1_cgmii_rx_tsu(),
.pcs1_cgmii_tsu_rx_sd(),

.mac1_cgmii_tx_clkena(hlp_port13_cgmii_txclk_ena),
.mac1_cgmii_tx_txc(hlp_port13_cgmii_tx_c),
.mac1_cgmii_tx_txd(hlp_port13_cgmii_tx_data),
.mac1_cgmii_rx_clkena(hlp_port13_cgmii_rxclk_ena),
.mac1_cgmii_rx_rxc(hlp_port13_cgmii_rx_c),
.mac1_cgmii_rx_rxd(hlp_port13_cgmii_rx_data),

.tsu1_cgmii_tx_clkena(),
.tsu1_cgmii_tx_tsu(),
.tsu1_cgmii_rx_clkena(),
.tsu1_cgmii_rx_tsu(),
.tsu1_cgmii_rx_sd(),

.pcs1_xlgmii_tx_clkena(hlp_xlgmii1_txclk_ena_2),
.pcs1_xlgmii_tx_txc(hlp_xlgmii1_txc_2),
.pcs1_xlgmii_tx_txd(hlp_xlgmii1_txd_2),
.pcs1_xlgmii_tx_tsu(mii_tx_tsu[19:18]),
.pcs1_xlgmii_rx_clkena(hlp_xlgmii1_rxclk_ena_2),
.pcs1_xlgmii_rx_rxc(hlp_xlgmii1_rxc_2),
.pcs1_xlgmii_rx_rxd(hlp_xlgmii1_rxd_2),
.pcs1_xlgmii_rxt0_next(hlp_xlgmii1_rxt0_next_2),
.pcs1_xlgmii_rx_tsu(mii_rx_tsu_mux[19:18]),
.pcs1_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[19:18]),

.mac1_xlgmii_tx_clkena(hlp_port13_xlgmii_txclk_ena),
.mac1_xlgmii_tx_txc(hlp_port13_xlgmii_tx_c),
.mac1_xlgmii_tx_txd(hlp_port13_xlgmii_tx_data),
.mac1_xlgmii_rx_clkena(hlp_port13_xlgmii_rxclk_ena),
.mac1_xlgmii_rx_rxc(hlp_port13_xlgmii_rx_c),
.mac1_xlgmii_rx_rxd(hlp_port13_xlgmii_rx_data),
.mac1_xlgmii_rxt0_next(hlp_port13_xlgmii_rxt0_next),

.tsu1_xlgmii_tx_clkena(),
.tsu1_xlgmii_tx_tsu(hlp_port13_mii_tx_tsu),
.tsu1_xlgmii_rx_clkena(),
.tsu1_xlgmii_rx_tsu(hlp_port13_mii_rx_tsu),
.tsu1_xlgmii_rx_sd(hlp_port13_tsu_rx_sd),

.pcs2_cgmii_tx_clkena(hlp_cgmii2_txclk_ena_2),
.pcs2_cgmii_tx_txc(hlp_cgmii2_txc_2),
.pcs2_cgmii_tx_txd(hlp_cgmii2_txd_2),
.pcs2_cgmii_tx_tsu(),
.pcs2_cgmii_rx_clkena(hlp_cgmii2_rxclk_ena_2),
.pcs2_cgmii_rx_rxc(hlp_cgmii2_rxc_2),
.pcs2_cgmii_rx_rxd(hlp_cgmii2_rxd_2),
.pcs2_cgmii_rx_tsu(),
.pcs2_cgmii_tsu_rx_sd(),

.mac2_cgmii_tx_clkena(hlp_port14_cgmii_txclk_ena),
.mac2_cgmii_tx_txc(hlp_port14_cgmii_tx_c),
.mac2_cgmii_tx_txd(hlp_port14_cgmii_tx_data),
.mac2_cgmii_rx_clkena(hlp_port14_cgmii_rxclk_ena),
.mac2_cgmii_rx_rxc(hlp_port14_cgmii_rx_c),
.mac2_cgmii_rx_rxd(hlp_port14_cgmii_rx_data),

.tsu2_cgmii_tx_clkena(),
.tsu2_cgmii_tx_tsu(),
.tsu2_cgmii_rx_clkena(),
.tsu2_cgmii_rx_tsu(),
.tsu2_cgmii_rx_sd(),

.pcs2_xlgmii_tx_clkena(hlp_xlgmii2_txclk_ena_2),
.pcs2_xlgmii_tx_txc(hlp_xlgmii2_txc_2),
.pcs2_xlgmii_tx_txd(hlp_xlgmii2_txd_2),
.pcs2_xlgmii_tx_tsu(mii_tx_tsu[21:20]),
.pcs2_xlgmii_rx_clkena(hlp_xlgmii2_rxclk_ena_2),
.pcs2_xlgmii_rx_rxc(hlp_xlgmii2_rxc_2),
.pcs2_xlgmii_rx_rxd(hlp_xlgmii2_rxd_2),
.pcs2_xlgmii_rxt0_next(hlp_xlgmii2_rxt0_next_2),
.pcs2_xlgmii_rx_tsu(mii_rx_tsu_mux[21:20]),
.pcs2_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[21:20]),

.mac2_xlgmii_tx_clkena(hlp_port14_xlgmii_txclk_ena),
.mac2_xlgmii_tx_txc(hlp_port14_xlgmii_tx_c),
.mac2_xlgmii_tx_txd(hlp_port14_xlgmii_tx_data),
.mac2_xlgmii_rx_clkena(hlp_port14_xlgmii_rxclk_ena),
.mac2_xlgmii_rx_rxc(hlp_port14_xlgmii_rx_c),
.mac2_xlgmii_rx_rxd(hlp_port14_xlgmii_rx_data),
.mac2_xlgmii_rxt0_next(hlp_port14_xlgmii_rxt0_next),

.tsu2_xlgmii_tx_clkena(),
.tsu2_xlgmii_tx_tsu(hlp_port14_mii_tx_tsu),
.tsu2_xlgmii_rx_clkena(),
.tsu2_xlgmii_rx_tsu(hlp_port14_mii_rx_tsu),
.tsu2_xlgmii_rx_sd(hlp_port14_tsu_rx_sd),

.pcs3_cgmii_tx_clkena(hlp_cgmii3_txclk_ena_2),
.pcs3_cgmii_tx_txc(hlp_cgmii3_txc_2),
.pcs3_cgmii_tx_txd(hlp_cgmii3_txd_2),
.pcs3_cgmii_tx_tsu(),
.pcs3_cgmii_rx_clkena(hlp_cgmii3_rxclk_ena_2),
.pcs3_cgmii_rx_rxc(hlp_cgmii3_rxc_2),
.pcs3_cgmii_rx_rxd(hlp_cgmii3_rxd_2),
.pcs3_cgmii_rx_tsu(),
.pcs3_cgmii_tsu_rx_sd(),

.mac3_cgmii_tx_clkena(hlp_port15_cgmii_txclk_ena),
.mac3_cgmii_tx_txc(hlp_port15_cgmii_tx_c),
.mac3_cgmii_tx_txd(hlp_port15_cgmii_tx_data),
.mac3_cgmii_rx_clkena(hlp_port15_cgmii_rxclk_ena),
.mac3_cgmii_rx_rxc(hlp_port15_cgmii_rx_c),
.mac3_cgmii_rx_rxd(hlp_port15_cgmii_rx_data),

.tsu3_cgmii_tx_clkena(),
.tsu3_cgmii_tx_tsu(),
.tsu3_cgmii_rx_clkena(),
.tsu3_cgmii_rx_tsu(),
.tsu3_cgmii_rx_sd(),

.pcs3_xlgmii_tx_clkena(hlp_xlgmii3_txclk_ena_2),
.pcs3_xlgmii_tx_txc(hlp_xlgmii3_txc_2),
.pcs3_xlgmii_tx_txd(hlp_xlgmii3_txd_2),
.pcs3_xlgmii_tx_tsu(mii_tx_tsu[23:22]),
.pcs3_xlgmii_rx_clkena(hlp_xlgmii3_rxclk_ena_2),
.pcs3_xlgmii_rx_rxc(hlp_xlgmii3_rxc_2),
.pcs3_xlgmii_rx_rxd(hlp_xlgmii3_rxd_2),
.pcs3_xlgmii_rxt0_next(hlp_xlgmii3_rxt0_next_2),
.pcs3_xlgmii_rx_tsu(mii_rx_tsu_mux[23:22]),
.pcs3_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[23:22]),

.mac3_xlgmii_tx_clkena(hlp_port15_xlgmii_txclk_ena),
.mac3_xlgmii_tx_txc(hlp_port15_xlgmii_tx_c),
.mac3_xlgmii_tx_txd(hlp_port15_xlgmii_tx_data),
.mac3_xlgmii_rx_clkena(hlp_port15_xlgmii_rxclk_ena),
.mac3_xlgmii_rx_rxc(hlp_port15_xlgmii_rx_c),
.mac3_xlgmii_rx_rxd(hlp_port15_xlgmii_rx_data),
.mac3_xlgmii_rxt0_next(hlp_port15_xlgmii_rxt0_next),

.tsu3_xlgmii_tx_clkena(),
.tsu3_xlgmii_tx_tsu(hlp_port15_mii_tx_tsu),
.tsu3_xlgmii_rx_clkena(),
.tsu3_xlgmii_rx_tsu(hlp_port15_mii_rx_tsu),
.tsu3_xlgmii_rx_sd(hlp_port15_tsu_rx_sd)

);

pcs_mac_pipeline_top_wrap

#(
.PIPE_NUM (2),
.CGDW     (128),
.CGCW     (16)
)
quad3_port4_4 (

.reset_mac0_ref_clk(1'b0),
.reset_mac1_ref_clk(1'b0),
.reset_mac2_ref_clk(1'b0),
.reset_mac3_ref_clk(1'b0),
.mac0_ref_clk(ts_800_rdop_fout0_clkout),
.mac1_ref_clk(ts_800_rdop_fout0_clkout),
.mac2_ref_clk(ts_800_rdop_fout0_clkout),
.mac3_ref_clk(ts_800_rdop_fout0_clkout),

.pcs0_cgmii_tx_clkena(hlp_cgmii0_txclk_ena_3),
.pcs0_cgmii_tx_txc(hlp_cgmii0_txc_3),
.pcs0_cgmii_tx_txd(hlp_cgmii0_txd_3),
.pcs0_cgmii_tx_tsu(),
.pcs0_cgmii_rx_clkena(hlp_cgmii0_rxclk_ena_3),
.pcs0_cgmii_rx_rxc(hlp_cgmii0_rxc_3),
.pcs0_cgmii_rx_rxd(hlp_cgmii0_rxd_3),
.pcs0_cgmii_rx_tsu(),
.pcs0_cgmii_tsu_rx_sd(),

.mac0_cgmii_tx_clkena(hlp_port16_cgmii_txclk_ena),
.mac0_cgmii_tx_txc(hlp_port16_cgmii_tx_c),
.mac0_cgmii_tx_txd(hlp_port16_cgmii_tx_data),
.mac0_cgmii_rx_clkena(hlp_port16_cgmii_rxclk_ena),
.mac0_cgmii_rx_rxc(hlp_port16_cgmii_rx_c),
.mac0_cgmii_rx_rxd(hlp_port16_cgmii_rx_data),

.tsu0_cgmii_tx_clkena(),
.tsu0_cgmii_tx_tsu(),
.tsu0_cgmii_rx_clkena(),
.tsu0_cgmii_rx_tsu(),
.tsu0_cgmii_rx_sd(),

.pcs0_xlgmii_tx_clkena(hlp_xlgmii0_txclk_ena_3),
.pcs0_xlgmii_tx_txc(hlp_xlgmii0_txc_3),
.pcs0_xlgmii_tx_txd(hlp_xlgmii0_txd_3),
.pcs0_xlgmii_tx_tsu(mii_tx_tsu[25:24]),
.pcs0_xlgmii_rx_clkena(hlp_xlgmii0_rxclk_ena_3),
.pcs0_xlgmii_rx_rxc(hlp_xlgmii0_rxc_3),
.pcs0_xlgmii_rx_rxd(hlp_xlgmii0_rxd_3),
.pcs0_xlgmii_rxt0_next(hlp_xlgmii0_rxt0_next_3),
.pcs0_xlgmii_rx_tsu(mii_rx_tsu_mux[25:24]),
.pcs0_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[25:24]),

.mac0_xlgmii_tx_clkena(hlp_port16_xlgmii_txclk_ena),
.mac0_xlgmii_tx_txc(hlp_port16_xlgmii_tx_c),
.mac0_xlgmii_tx_txd(hlp_port16_xlgmii_tx_data),
.mac0_xlgmii_rx_clkena(hlp_port16_xlgmii_rxclk_ena),
.mac0_xlgmii_rx_rxc(hlp_port16_xlgmii_rx_c),
.mac0_xlgmii_rx_rxd(hlp_port16_xlgmii_rx_data),
.mac0_xlgmii_rxt0_next(hlp_port16_xlgmii_rxt0_next),

.tsu0_xlgmii_tx_clkena(),
.tsu0_xlgmii_tx_tsu(hlp_port16_mii_tx_tsu),
.tsu0_xlgmii_rx_clkena(),
.tsu0_xlgmii_rx_tsu(hlp_port16_mii_rx_tsu),
.tsu0_xlgmii_rx_sd(hlp_port16_tsu_rx_sd),

.pcs1_cgmii_tx_clkena(hlp_cgmii1_txclk_ena_3),
.pcs1_cgmii_tx_txc(hlp_cgmii1_txc_3),
.pcs1_cgmii_tx_txd(hlp_cgmii1_txd_3),
.pcs1_cgmii_tx_tsu(),
.pcs1_cgmii_rx_clkena(hlp_cgmii1_rxclk_ena_3),
.pcs1_cgmii_rx_rxc(hlp_cgmii1_rxc_3),
.pcs1_cgmii_rx_rxd(hlp_cgmii1_rxd_3),
.pcs1_cgmii_rx_tsu(),
.pcs1_cgmii_tsu_rx_sd(),

.mac1_cgmii_tx_clkena(hlp_port17_cgmii_txclk_ena),
.mac1_cgmii_tx_txc(hlp_port17_cgmii_tx_c),
.mac1_cgmii_tx_txd(hlp_port17_cgmii_tx_data),
.mac1_cgmii_rx_clkena(hlp_port17_cgmii_rxclk_ena),
.mac1_cgmii_rx_rxc(hlp_port17_cgmii_rx_c),
.mac1_cgmii_rx_rxd(hlp_port17_cgmii_rx_data),

.tsu1_cgmii_tx_clkena(),
.tsu1_cgmii_tx_tsu(),
.tsu1_cgmii_rx_clkena(),
.tsu1_cgmii_rx_tsu(),
.tsu1_cgmii_rx_sd(),

.pcs1_xlgmii_tx_clkena(hlp_xlgmii1_txclk_ena_3),
.pcs1_xlgmii_tx_txc(hlp_xlgmii1_txc_3),
.pcs1_xlgmii_tx_txd(hlp_xlgmii1_txd_3),
.pcs1_xlgmii_tx_tsu(mii_tx_tsu[27:26]),
.pcs1_xlgmii_rx_clkena(hlp_xlgmii1_rxclk_ena_3),
.pcs1_xlgmii_rx_rxc(hlp_xlgmii1_rxc_3),
.pcs1_xlgmii_rx_rxd(hlp_xlgmii1_rxd_3),
.pcs1_xlgmii_rxt0_next(hlp_xlgmii1_rxt0_next_3),
.pcs1_xlgmii_rx_tsu(mii_rx_tsu_mux[27:26]),
.pcs1_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[27:26]),

.mac1_xlgmii_tx_clkena(hlp_port17_xlgmii_txclk_ena),
.mac1_xlgmii_tx_txc(hlp_port17_xlgmii_tx_c),
.mac1_xlgmii_tx_txd(hlp_port17_xlgmii_tx_data),
.mac1_xlgmii_rx_clkena(hlp_port17_xlgmii_rxclk_ena),
.mac1_xlgmii_rx_rxc(hlp_port17_xlgmii_rx_c),
.mac1_xlgmii_rx_rxd(hlp_port17_xlgmii_rx_data),
.mac1_xlgmii_rxt0_next(hlp_port17_xlgmii_rxt0_next),

.tsu1_xlgmii_tx_clkena(),
.tsu1_xlgmii_tx_tsu(hlp_port17_mii_tx_tsu),
.tsu1_xlgmii_rx_clkena(),
.tsu1_xlgmii_rx_tsu(hlp_port17_mii_rx_tsu),
.tsu1_xlgmii_rx_sd(hlp_port17_tsu_rx_sd),

.pcs2_cgmii_tx_clkena(hlp_cgmii2_txclk_ena_3),
.pcs2_cgmii_tx_txc(hlp_cgmii2_txc_3),
.pcs2_cgmii_tx_txd(hlp_cgmii2_txd_3),
.pcs2_cgmii_tx_tsu(),
.pcs2_cgmii_rx_clkena(hlp_cgmii2_rxclk_ena_3),
.pcs2_cgmii_rx_rxc(hlp_cgmii2_rxc_3),
.pcs2_cgmii_rx_rxd(hlp_cgmii2_rxd_3),
.pcs2_cgmii_rx_tsu(),
.pcs2_cgmii_tsu_rx_sd(),

.mac2_cgmii_tx_clkena(hlp_port18_cgmii_txclk_ena),
.mac2_cgmii_tx_txc(hlp_port18_cgmii_tx_c),
.mac2_cgmii_tx_txd(hlp_port18_cgmii_tx_data),
.mac2_cgmii_rx_clkena(hlp_port18_cgmii_rxclk_ena),
.mac2_cgmii_rx_rxc(hlp_port18_cgmii_rx_c),
.mac2_cgmii_rx_rxd(hlp_port18_cgmii_rx_data),

.tsu2_cgmii_tx_clkena(),
.tsu2_cgmii_tx_tsu(),
.tsu2_cgmii_rx_clkena(),
.tsu2_cgmii_rx_tsu(),
.tsu2_cgmii_rx_sd(),

.pcs2_xlgmii_tx_clkena(hlp_xlgmii2_txclk_ena_3),
.pcs2_xlgmii_tx_txc(hlp_xlgmii2_txc_3),
.pcs2_xlgmii_tx_txd(hlp_xlgmii2_txd_3),
.pcs2_xlgmii_tx_tsu(mii_tx_tsu[29:28]),
.pcs2_xlgmii_rx_clkena(hlp_xlgmii2_rxclk_ena_3),
.pcs2_xlgmii_rx_rxc(hlp_xlgmii2_rxc_3),
.pcs2_xlgmii_rx_rxd(hlp_xlgmii2_rxd_3),
.pcs2_xlgmii_rxt0_next(hlp_xlgmii2_rxt0_next_3),
.pcs2_xlgmii_rx_tsu( mii_rx_tsu_mux[29:28]),
.pcs2_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[29:28]),

.mac2_xlgmii_tx_clkena(hlp_port18_xlgmii_txclk_ena),
.mac2_xlgmii_tx_txc(hlp_port18_xlgmii_tx_c),
.mac2_xlgmii_tx_txd(hlp_port18_xlgmii_tx_data),
.mac2_xlgmii_rx_clkena(hlp_port18_xlgmii_rxclk_ena),
.mac2_xlgmii_rx_rxc(hlp_port18_xlgmii_rx_c),
.mac2_xlgmii_rx_rxd(hlp_port18_xlgmii_rx_data),
.mac2_xlgmii_rxt0_next(hlp_port18_xlgmii_rxt0_next),

.tsu2_xlgmii_tx_clkena(),
.tsu2_xlgmii_tx_tsu(hlp_port18_mii_tx_tsu),
.tsu2_xlgmii_rx_clkena(),
.tsu2_xlgmii_rx_tsu(hlp_port18_mii_rx_tsu),
.tsu2_xlgmii_rx_sd(hlp_port18_tsu_rx_sd),

.pcs3_cgmii_tx_clkena(hlp_cgmii3_txclk_ena_3),
.pcs3_cgmii_tx_txc(hlp_cgmii3_txc_3),
.pcs3_cgmii_tx_txd(hlp_cgmii3_txd_3),
.pcs3_cgmii_tx_tsu(),
.pcs3_cgmii_rx_clkena(hlp_cgmii3_rxclk_ena_3),
.pcs3_cgmii_rx_rxc(hlp_cgmii3_rxc_3),
.pcs3_cgmii_rx_rxd(hlp_cgmii3_rxd_3),
.pcs3_cgmii_rx_tsu(),
.pcs3_cgmii_tsu_rx_sd(),

.mac3_cgmii_tx_clkena(hlp_port19_cgmii_txclk_ena),
.mac3_cgmii_tx_txc(hlp_port19_cgmii_tx_c),
.mac3_cgmii_tx_txd(hlp_port19_cgmii_tx_data),
.mac3_cgmii_rx_clkena(hlp_port19_cgmii_rxclk_ena),
.mac3_cgmii_rx_rxc(hlp_port19_cgmii_rx_c),
.mac3_cgmii_rx_rxd(hlp_port19_cgmii_rx_data),

.tsu3_cgmii_tx_clkena(),
.tsu3_cgmii_tx_tsu(),
.tsu3_cgmii_rx_clkena(),
.tsu3_cgmii_rx_tsu(),
.tsu3_cgmii_rx_sd(),

.pcs3_xlgmii_tx_clkena(hlp_xlgmii3_txclk_ena_3),
.pcs3_xlgmii_tx_txc(hlp_xlgmii3_txc_3),
.pcs3_xlgmii_tx_txd(hlp_xlgmii3_txd_3),
.pcs3_xlgmii_tx_tsu(mii_tx_tsu[31:30]),
.pcs3_xlgmii_rx_clkena(hlp_xlgmii3_rxclk_ena_3),
.pcs3_xlgmii_rx_rxc(hlp_xlgmii3_rxc_3),
.pcs3_xlgmii_rx_rxd(hlp_xlgmii3_rxd_3),
.pcs3_xlgmii_rxt0_next(hlp_xlgmii3_rxt0_next_3),
.pcs3_xlgmii_rx_tsu(mii_rx_tsu_mux[31:30]),
.pcs3_xlgmii_tsu_rx_sd(pcs_tsu_rx_sd[31:30]),

.mac3_xlgmii_tx_clkena(hlp_port19_xlgmii_txclk_ena),
.mac3_xlgmii_tx_txc(hlp_port19_xlgmii_tx_c),
.mac3_xlgmii_tx_txd(hlp_port19_xlgmii_tx_data),
.mac3_xlgmii_rx_clkena(hlp_port19_xlgmii_rxclk_ena),
.mac3_xlgmii_rx_rxc(hlp_port19_xlgmii_rx_c),
.mac3_xlgmii_rx_rxd(hlp_port19_xlgmii_rx_data),
.mac3_xlgmii_rxt0_next(hlp_port19_xlgmii_rxt0_next),

.tsu3_xlgmii_tx_clkena(),
.tsu3_xlgmii_tx_tsu(hlp_port19_mii_tx_tsu),
.tsu3_xlgmii_rx_clkena(),
.tsu3_xlgmii_rx_tsu(hlp_port19_mii_rx_tsu),
.tsu3_xlgmii_rx_sd(hlp_port19_tsu_rx_sd)

);



endmodule
