#########################################################################
#    Early probe file generated by Redview.
#    Please provide this file to debug_file command.
#########################################################################

# Infrastructure settings 

add_station -name "STN_0" -clock {"reference_clk"} -width 4096 -depth 4096

#add_station -name "STN_0" -clock {"spi_debug_clk"}


add_probe {physs_eth.physs_func_rst_raw_n} -clock reference_clk -station STN_0
add_probe {physs_eth.i_reset}  -clock reference_clk -station STN_0
# Probes
#add_probe {physs_eth..physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.tx_clk} 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.tx_clk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.pattern_gen.reset_n}  -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.pattern_gen.rx_tbi} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.pattern_gen.transition_detected} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.pattern_gen.prev_rx_tbi} -clock reference_clk -station STN_0
#######add_probe {physs_eth..physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.rx_clk}
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_RXBUF.dout} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.rx_clk_ena} -clock reference_clk -station STN_0 
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.tbi_tx} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.tbi_rx} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.gmii_rxd} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.gmii_rxdv} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.gmii_rxer} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.gmii_txd} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.gmii_txen} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.gmii_txer} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.gmii0_txd_mux} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.gmii0_txen_mux} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.gmii0_txer_mux} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.pcs_loopback_en} -clock reference_clk -station STN_0 
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.tbi_rx_phy} -clock reference_clk -station STN_0 
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.tbi_tx_phy} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sync_i_reset} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.tbi_rx} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.sdbf_data} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_RXBUF.sdbf_dval} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_RXBUF.rx_clk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_RXBUF.U_RXBUF.U_RAM.dout} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sdbf_data} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.tbi_rx} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.tbi_rx} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.tbi_rx_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.din} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.data_align} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.dout} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.gmii_rxd} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.tx_d} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.gmii_txd} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sgpcs_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_TXBUF.tx_d} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_TXBUF.sd_tx} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.reset} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.frame} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.nextstate} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.tbi_tx} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_ENCOD.din} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_ENCOD.rst} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.rx_clk_ena} -clock reference_clk -station STN_0 
#######
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.rx_clk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.rx_clk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sg_rxclk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sgpcs_ena_r} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sgpcs_ena_st} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.sgpcs_ena_s} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.sgpcs_ena_r} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.sgpcs_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sgpcs_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.sgpcs_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parquad0.physs_registers_wrapper_0.physs_common_registers_0.pcs100_sgmii0_reg_sg0_sgpcs_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.din} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.align_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.rst_align} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.data_align} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.sync} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.ce} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.din_reg} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sg_rxclk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.data} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.clk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.frame} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.frame_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_data} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.clk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.signal_det} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.gmii_rxd} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.gmii_rxd} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.kchar} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.nextstate} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.din} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.ce} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.dout} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.kout} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.kout} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.kchar} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.sw_reset} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.reset} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.state} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_even} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.xmit_data} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.stm_lpi_k} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.stm_lpi_d} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.k285_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.frame_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.seq_w_reg1} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_err_reg1} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_dv_reg1} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_data_reg1} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_data_reg2} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.din} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.dout} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.rst} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.kout_5b_pos} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.kout_5b_neg} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.kout_3b_pos} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.kout_3b_neg} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.sync} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.char_err} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.ce} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_DEC.dout} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.rx_sync_eee} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.state} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.code_sync} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_sync} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.sync_acqurd_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.sync_acqurd} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.nextstate} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.sync_lost} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.state} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.stm_sub_lpi} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.nextstate} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.char_err} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.kchar} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.rx_even_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.data} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.comma_detect} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.signal_detect} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.good_cg_cnt} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.sw_reset} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.reset} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.clk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.align_det} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.rst_align} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.bit_slip} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.par} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_link_status_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.reset_reg_clk} -clock reference_clk -station STN_0 
#######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.reg_clk} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_link_status_dff} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.reset_ref_clk} -clock reference_clk -station STN_0 
#######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.ref_clk} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_link_status} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.ena_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_an_enable_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_an_done_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_rx_sync_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.ena_r} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_rx_sync_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_an_done_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sgpcs_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.sg_rx_sync} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.sd_sig_det} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.sg_speed} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.xmit_data} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.kchar_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.carr_detect_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.char_err_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.gmii_txd} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.gmii_txd} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.gmii_data} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.frame} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.state} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.nextstate} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.reset} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.clk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.tx_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.tx_idle} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.an_ability} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.an_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.gmii_dv} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.gmii_ctl} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.gmii_data} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.gmii_tx_even} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.disparity} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.transmit} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.kchar} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.tx_ena_reg2} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.sw_reset_reg2} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.tx_idle_reg2} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.an_ena_reg2} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_FRM.an_ability_reg2} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.frame} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.tbi_tx_int} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.kchar} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.gmii_txclk_ena} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.sw_reset_s} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_ENCOD.kin} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_ENCOD.ce} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_ENCOD.rd_in} -clock reference_clk -station STN_0 
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_TX.U_ENCOD.disp} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_enable} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_restart} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.rx_invalid} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.rx_sync} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.idle_ena} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.max_link_timer} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_restart_rst} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.lp_ability} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.lp_ability_ena} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_ability_in} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_np} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_np_loaded} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_np_loaded_rst} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_ability_out} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_page_rx} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_is_basepage} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_page} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_restart_state} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_done} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_ack} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_txidle} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_txena} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.state} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.nextstate} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.link_timer} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.link_timer_dec} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_restart_rst_i} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_sync_status} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_sync_cnt} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.link_status} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.sgmii_speed} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.sgmii_duplex} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.sgmii_enap} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.if_mode} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.reg_addr} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.reg_din} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.reg_write} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.mdio_control} -clock reference_clk -station STN_0
#######add_probe {physs_eth.dbg_rx_serial_data} -clock reference_clk -station STN_0
#######add_probe {physs_eth.dbg_tx_serial_data} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_RXBUF.U_RXBUF.din} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_RXBUF.sd_rx} -clock reference_clk -station STN_0
######add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_RXBUF.U_RXBUF.dout} -clock reference_clk -station STN_0
#physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_PCSREG.sgpcs_ena
#add_probe {cnic_wrapper.sys_rst_n} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.par_gpio_north.pti_repeater_visa_resetb} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.par_gpio_north.gpio_north_1p8_XX_AUX_PWRGOOD} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.XX_GLOBAL_RESET_N} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.XX_PWRGOOD} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.XX_RESET_N} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.XX_S0_PWRGOOD} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parrst.hwrs_top_hwrs_rst_b} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parfuse.parparfuse_dvp_dtf_rst_b} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parfuse.parfuse2rb_side_rst_b} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parfuse.parfuse_top_drng_pgcb_rst_b} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parunit.rc_cfc_dvp_rst_b} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parunit.rc_cfc_pwr_rst_b} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parunit.punit_vnn_array_wrapper_ip_rst_b} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parunit.rc_cfc_rst_b pmusvid_dtf_rst_b} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.cmd_idx[8:0]} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk 
#add_probe {cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.seq_fsm_ns[4:0]} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper.cnic.parrst.hwrs_top.hvm_imh_disable_programming_done} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper.cnic.parrst.hwrs_top.hvm_start_feature_ip_bringup} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper.cnic.parrst.hwrs_top_xxresetb_rx} -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.rst_zero_dly_cmd            } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.cmd_idx[8:0]                } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.rst_cmd_dly_wait_done       } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.hwrs_brkpoint_index[15:0]   } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.hwrs_brkpoint_valid         } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.rst_dly_cnt[63:0]           } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.seq_fsm_cs[4:0]             } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.hwrs_delay_mul[5:0]         } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.rst_dly_cnt_param[4:0]      } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.time_unit_shift_amount[5:0] } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.cold_rst_flow               } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.bmbs_boot_seq               } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.BMBS_BOOT_SEQ[0:29]         } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.S0_BOOT_RST_SEQ[0:302]      } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.COLD_RST_EXIT_SEQ[0:220]    } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk
#add_probe {cnic_wrapper_tb.cnic_wrapper.cnic.parrst.hwrs_top.hwrs_seq_fsm_inst.cold_rst_entry              } -clock reference_clk -station STN_0 -clock reference_clk prim_clk -station reference_clk prim_clk

#Added by Lokesh
#I2C APB Master
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_enable} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_restart} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.rx_invalid} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.rx_sync} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.idle_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.max_link_timer} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_restart_rst} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.lp_ability} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.lp_ability_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_ability_in} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_np} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_np_loaded} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_np_loaded_rst} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_ability_out} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_page_rx} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_is_basepage} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.mr_page} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_restart_state} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_done} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_ack} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_txidle} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_txena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.state} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.nextstate} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.link_timer} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.link_timer_dec} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_restart_rst_i} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_sync_status} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_AUTONEG.an_sync_cnt} -clock reference_clk -station STN_0

add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.rst_align} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.align_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.din} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.dout} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.sync} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.ce} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.reset} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.din_reg} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.par} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.align_det} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.dout_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.U_ALIGN.bit_slip} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.align_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.rst_align} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.din} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.dout} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.ce} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.kout} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.nd} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.sync} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.error} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.comma} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.ce} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.sw_reset} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.rst} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.carrier} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.data_align} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.sync_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.sync_int_del} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.rd_in} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.rd_out} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.char_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.disp_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.ce_del} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.carrier_reg} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.sw_reset_reg2} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.bit_slip} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.comma} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.clk_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.signal_detect} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.data} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.comma_detect} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.kchar} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.char_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.sync_lost} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.sync_acqurd} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.rx_even} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.state} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.nextstate} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.good_cg_cnt} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.rx_even_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.good_cg_cnt} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.rx_clk_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.tbi_rx} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.sdbf_data} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.sdbf_dval} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.gmii_txd} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.gmii_txerr} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.gmii_txen} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.rx_detect} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.an_enable} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.an_done} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.an_ack} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.tbi_rx} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.xmit_data} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.rx_invalid} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.rx_clk_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.rx_clk_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.rx_detect} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.comma} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.receive} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.dec_sync} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.dec_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.sync_acqurd} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.align_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.tbi_rx_gbe} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.din} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.dout} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.kout} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_DECOD.carrier} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.state} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.nextstate} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.data} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.kchar} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.rx_even_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.char_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.good_cg_cnt} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.sync_acqurd} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_SYNC.sync_lost} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.signal_det} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_sync} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_even} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.receive} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.idle_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_invalid} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.frame} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.kchar} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.char_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.xmit_data} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.carrier_detect} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_dv} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_data} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.state} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.nextstate} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.k285_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.d_cfg_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.d_idle_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.carr_detect_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.char_err_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.frame} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.k285_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.kchar} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_even} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.d_cfg_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.d_lpi_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.frame_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.kchar_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.frame_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.carr_detect_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_even} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_even} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_invalid} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.lp_ability} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.lp_ability_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.idle_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_dv_reg1} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_data_reg1} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_dv_reg2} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_dv} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.seq_w_reg2} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_err_reg2} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_dv_reg2} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.state} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.seq_w_reg1} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_err_reg1} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_dv_reg1} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_data_reg2} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_data_reg1} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_data} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gseq.seq_w_reg1_r} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gseq.seq_w_reg2_r} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.clk_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.kchar_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.frame_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.receive} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.page_receive} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.stm_sub_lpi} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.stm_lpi_d} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.stm_lpi_k} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.stm_lpi_lfail} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.stm_sub_lpi} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.rx_sync_eee} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.code_sync} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.rx_mode_quiet} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.rx_lpi_active} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.rx_wake_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.state} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.U_STM367c.nextstate} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.gmii_txclk_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.gmii_tx_even} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.gmii_rxclk_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_an_enable_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_rx_sync_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_an_done_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_page_rx} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.sg_speed} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.clk_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.signal_det} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.signal_det} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_sync} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_even} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.receive} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.idle_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_invalid} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.page_receive} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.reset} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.lp_ability_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.clk} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.kchar} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.frame} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.char_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.xmit_data} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.carrier_detect} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_dv} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_err} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.gmii_data} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.state} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.nextstate} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.carrier_detect} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.clk_ena} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.sg_speed} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.sg_hd} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sgmii_speed} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sgmii_speed_r} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.sgmii_speed_t} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.an_enable} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.tx_lane_thresh} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.sw_reset} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.rx_sync_eee_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.k285_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.char_err_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.carr_detect_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.signal_det} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.d_cfg_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.d_idle_int} -clock reference_clk -station STN_0
add_probe {physs_eth.physs0.parmquad0.pcs100_wrap_0.quadpcs100_0.U_PCS_TOP.U_SGMII4x_USXGMII4x_INST.U_SGMII_10B_0.U_PCS.U_PCSMMD.U_GPCS.U_RX.U_FRM.kchar_int} -clock reference_clk -station STN_0
