#!make
RED_HOME         := /nfs/site/disks/xne_tip_0001/bindhus/vps_2024.2_install
#RED_HOME         := /p/hdk/rtl/cad/x86-64_linux26/mentor/VPS/2023.06
#QUARTUS_HOME         := /nfs/site/cproj/gnrd/zsc14.xne_00263/users/tools/altera/pro.23.3/quartus
QUARTUS_HOME         := /p/hdk/rtl/cad/x86-64_linux26/altera/quartus_prime_pro/24.1/quartus
CTECH_EXP      := /p/hdk/cad/ctech/ctech_exp_c4v20ww35_hdk162_xpg
CTECH_SOURCE   := /p/hdk/cad/ctech/c4v20ww43c_hdk162/source/v
CTECH_EXP_PATH := /p/hdk/cad/ctech/ctech_exp_c4v20ww35_hdk162_xpg/source/v
CTECH_PATH     := /p/hdk/cad/ctech/c4v20ww16d_hdk161_p1276_19ww35.5_g1m_f.0/source/v

#=========== Vendor Tool Setting ============
#PHD_FILE          :=
#RDC_FILE          :=
WRAP_SETTING_FILE :=  build_input_dir/wrap_settings.tcl

# If provided, flow will add these files in top-level veloce.map file
#==============================================================================
ADDITIONAL_LIBMAP_FILES :=

# TARGET_DIR will be created inside WORKDIR
#==========================================
WORKDIR := build

# Additional command-line switch for redcomp
#===========================================
REDCOMP_ARGS :=

# VPS custom mode
#=================================
REDCOMP_CUSTOM_MODE :=


# Num analyze jobs to be launched in parallel
#=================================
NUM_ANALYZE_PARALLEL_JOBS := 20

# vendor-tb compilation options
#=================================
# - To enable vendor-tb compilation, add "redcomp -enable_tbx" in red.config file
# - Space-separated list of C files to compile with redhvl
# - REDHVL_CFILES is used with redhvl when NO_SPARK set 1
REDHVL_CFILES           :=
REDHVL_OPTIONS          :=

# Spark and Simics related options
# - Putting these options here in build specific Makefile.cfg
#   because it can vary from one build configuration to another.
#   But if user finds that it is common across all build configs and
#   flows, then move these variables from here to top-level Makefile,
#   which is "verif/emu/Makefile."
# - To checkout spark-transactors in TARGET_DIR, instead of at
#   common location, set COMMON_SPARK_MODULE_DIR to 0
#====================================================================
MODEL_CFG := $(WORKAREA)/verif/fpga/vps_dvb/build_input_dir/cbb_hardware_files/301.cfg
REPOSITORY_JSON               := $(WORKAREA)/filelists/val/transactors.json
NO_SPARK                      := 1
COMMON_SPARK_MODULE_DIR       := 1
NUM_SPARK_BUILD_PARALLEL_JOBS := 12
SPARK_PROJECT                 :=
SIMICS_RUNTIME_INPUT_DIR      :=
SIMICS_USE_REALPATH           := 0
SIMICS_PKGS                   :=
CREATE_EMPTY_SIMICS_PKGS_LIST := 0
ROM_IMAGES                    :=

#***************************************************************
# Netbatch & Vendor Job Distriution
#---------------------------------------------------------------
# NB settings:
# - Set NB to 1 to launch main task (stage) on netbatch.
# - Makefile NB<Variable> is mapped as <Variable> in lite-infra:
#       NBNAME   => NAME
#       NBFEEDER => FEEDER
# - To extract info from lite-infra:
#     NBNAME: Tool will try to find compute section, having NAME as <NBNAME>.
#             And then, will read this compute section for different varaibles.
#             If compute section with same NAME is used more than once,
#             later will take precedence. Order in which default is searched:
#             Default: $(FLOW)@$(EC_ZONE), _DEFAULT@$(EC_ZONE), $(FLOW)@$(EC_SITE),
#                      _DEFAULT@$(EC_SITE), _DEFAULT
#
#     [Compute]
#         NAME           = vps@sc
#         FEEDER         = abc_pqr
#         FEEDER_MAX_MEM = 4G
#         TARGET         = sc_normal
#         QSLOT          = /pesg/fast
#         CLASS_ANA      = SLES11&&4G
#         CLASS_FE       = SLES11&&16G
#         CLASS_BE       = SLES11&&32G
#         CLASS_TB       = SLES11&&4G&&6C
#   lite-infra will read "verif/fpga/vps/tool.cth" file.
#
# - Default values exist for following variables:
#      NBNAME           = $(FLOW)@$(EC_ZONE)
#      NBFEEDER         = $(USER)_$(FLOW)_<date_time>_<mac>_<pid>
#   Other variables are mandatory to be provided, using 'Compute' section of 'tool.cth' file.
# - Target mapping with NB-Classes:
#       CLASS_ANA: analyze
#       CLASS_FE : fe, vps_tb
#       CLASS_BE : fe_be, custom
#       CLASS_TB : spark_tb
#==============================================
NB               := 1
NBNAME           :=
NBFEEDER         :=

# CDE configurations: To launch distributed tasks of a stage on netbatch
# - Set ENABLE_CDE to 1
# - The order in which the COMPUTE sections will be read from $WORKAREA/verif/fpga/vps/tool.cth, for
#   determining resource info for standard queues are:
#   1. zone-specific and stage-specific COMPUTE section, for eg: VpsFrontend@<EC_ZONE>
#   2. zone-specific default COMPUTE section,            for eg: VpsDefault@<EC_ZONE>
#   3. site-specific and stage-specific COMPUTE section, for eg: VpsFrontend@<EC_SITE>
#   4. site-specific default COMPUTE section,            for eg: VpsDefault@<EC_SITE>
#   5. stage-specific COMPUTE section without site info, for eg: VpsFrontend
#   6. default COMPUTE section without site info,        for eg: VpsDefault
#       [ COMPUTE ]
#           Name = VpsFrontend@pdx
#           qslot = /pesg/fast
#           target = pdx_normal
#           RAM = 8
#           CPU = 1
#           OS = SLES11
#
# - "gen_vendor_distrib_files" target will generate vps_custom_dist_VpsFrontend.bash,
#   vps_custom_dist_VpsBackend.bash and netbatch.config in $(TARGET_DIR)/vendor_distrib_src dir
#==============================================
# While running with ENABLE_CDE, distributed tasks are not being reaped,
# even after completion. Thus, we are seeing hung scenario with it. So,
# if you are facing same issue, it is advised to disable CDE and increase
# Memory-Requirement in CLASS_FE & CLASS_BE of NB compute section.
ENABLE_CDE := 1
# Optional variables
VELCOMP_CUSTOM_TASK_DISTRIB_SUBMIT_THROTTLE :=
VELCOMP_CDE_USE_MEM_REQ_FOR_CLASS           := 1
VELCOMP_CDE_CLASS_APPEND                    := SLES12SP5

#***************************************************************
# Other options
#---------------------------------------------------------------
PREPEND_PATH            :=
PREPEND_LD_LIBRARY_PATH :=

# List the names of variables that should not be captured in source_env_var*, separated by whitespaces
DVB_CUSTOM_VARS_TO_IGNORE ?=

export
