// sys_pll.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module sys_pll (
		input  wire       rst,              //            reset.reset
		input  wire       refclk,           //           refclk.clk
		output wire       locked,           //           locked.export
		input  wire       scanclk,          //          scanclk.clk
		input  wire       phase_en,         //         phase_en.phase_en
		input  wire       updn,             //             updn.updn
		input  wire [4:0] cntsel,           //           cntsel.cntsel
		output wire       phase_done,       //       phase_done.phase_done
		input  wire [2:0] num_phase_shifts, // num_phase_shifts.num_phase_shifts
		output wire       outclk_0,         //          outclk0.clk
		output wire       outclk_1,         //          outclk1.clk
		output wire       outclk_2,         //          outclk2.clk
		output wire       outclk_3,         //          outclk3.clk
		output wire       outclk_4,         //          outclk4.clk
		output wire       outclk_5,         //          outclk5.clk
		output wire       outclk_6,         //          outclk6.clk
		output wire       outclk_7          //          outclk7.clk
	);

	sys_pll_altera_iopll_1931_bh7nqvi iopll_0 (
		.rst              (rst),              //   input,  width = 1,            reset.reset
		.refclk           (refclk),           //   input,  width = 1,           refclk.clk
		.locked           (locked),           //  output,  width = 1,           locked.export
		.scanclk          (scanclk),          //   input,  width = 1,          scanclk.clk
		.phase_en         (phase_en),         //   input,  width = 1,         phase_en.phase_en
		.updn             (updn),             //   input,  width = 1,             updn.updn
		.cntsel           (cntsel),           //   input,  width = 5,           cntsel.cntsel
		.phase_done       (phase_done),       //  output,  width = 1,       phase_done.phase_done
		.num_phase_shifts (num_phase_shifts), //   input,  width = 3, num_phase_shifts.num_phase_shifts
		.outclk_0         (outclk_0),         //  output,  width = 1,          outclk0.clk
		.outclk_1         (outclk_1),         //  output,  width = 1,          outclk1.clk
		.outclk_2         (outclk_2),         //  output,  width = 1,          outclk2.clk
		.outclk_3         (outclk_3),         //  output,  width = 1,          outclk3.clk
		.outclk_4         (outclk_4),         //  output,  width = 1,          outclk4.clk
		.outclk_5         (outclk_5),         //  output,  width = 1,          outclk5.clk
		.outclk_6         (outclk_6),         //  output,  width = 1,          outclk6.clk
		.outclk_7         (outclk_7)          //  output,  width = 1,          outclk7.clk
	);

endmodule
