// ddr_emif_reset_in_1.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module ddr_emif_reset_in_1 (
		input  wire  clk,         //       clk.clk
		input  wire  in_reset_n,  //  in_reset.reset_n
		output wire  out_reset_n  // out_reset.reset_n
	);

	assign out_reset_n = in_reset_n;

endmodule
