// fpt_ddr4_nw.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module fpt_ddr4_nw (
		input  wire         clk_misc_sa_clk,          // clk_misc_sa.clk
		input  wire         clk_mm_0_clk,             //    clk_mm_0.clk
		input  wire         clk_mm_1_clk,             //    clk_mm_1.clk
		input  wire         clk_mm_2_clk,             //    clk_mm_2.clk
		input  wire         clk_mm_3_clk,             //    clk_mm_3.clk
		output wire [25:0]  ddr4_amm_address,         //    ddr4_amm.address
		output wire [6:0]   ddr4_amm_burstcount,      //            .burstcount
		output wire [63:0]  ddr4_amm_byteenable,      //            .byteenable
		output wire         ddr4_amm_debugaccess,     //            .debugaccess
		output wire         ddr4_amm_read,            //            .read
		input  wire [511:0] ddr4_amm_readdata,        //            .readdata
		input  wire         ddr4_amm_readdatavalid,   //            .readdatavalid
		input  wire         ddr4_amm_waitrequest,     //            .waitrequest
		output wire         ddr4_amm_write,           //            .write
		output wire [511:0] ddr4_amm_writedata,       //            .writedata
		input  wire         reset_emif_reset_n,       //  reset_emif.reset_n
		input  wire         clk_emif_clk,             //    clk_emif.clk
		input  wire [31:0]  mm_0_address,             //        mm_0.address
		input  wire [3:0]   mm_0_burstcount,          //            .burstcount
		input  wire [31:0]  mm_0_byteenable,          //            .byteenable
		input  wire         mm_0_debugaccess,         //            .debugaccess
		input  wire         mm_0_read,                //            .read
		output wire [255:0] mm_0_readdata,            //            .readdata
		output wire         mm_0_readdatavalid,       //            .readdatavalid
		output wire         mm_0_waitrequest,         //            .waitrequest
		input  wire         mm_0_write,               //            .write
		input  wire [255:0] mm_0_writedata,           //            .writedata
		input  wire [31:0]  mm_1_address,             //        mm_1.address
		input  wire [3:0]   mm_1_burstcount,          //            .burstcount
		input  wire [31:0]  mm_1_byteenable,          //            .byteenable
		input  wire         mm_1_debugaccess,         //            .debugaccess
		input  wire         mm_1_read,                //            .read
		output wire [255:0] mm_1_readdata,            //            .readdata
		output wire         mm_1_readdatavalid,       //            .readdatavalid
		output wire         mm_1_waitrequest,         //            .waitrequest
		input  wire         mm_1_write,               //            .write
		input  wire [255:0] mm_1_writedata,           //            .writedata
		input  wire [31:0]  mm_2_address,             //        mm_2.address
		input  wire [3:0]   mm_2_burstcount,          //            .burstcount
		input  wire [31:0]  mm_2_byteenable,          //            .byteenable
		input  wire         mm_2_debugaccess,         //            .debugaccess
		input  wire         mm_2_read,                //            .read
		output wire [255:0] mm_2_readdata,            //            .readdata
		output wire         mm_2_readdatavalid,       //            .readdatavalid
		output wire         mm_2_waitrequest,         //            .waitrequest
		input  wire         mm_2_write,               //            .write
		input  wire [255:0] mm_2_writedata,           //            .writedata
		input  wire [31:0]  mm_3_address,             //        mm_3.address
		input  wire [3:0]   mm_3_burstcount,          //            .burstcount
		input  wire [31:0]  mm_3_byteenable,          //            .byteenable
		input  wire         mm_3_debugaccess,         //            .debugaccess
		input  wire         mm_3_read,                //            .read
		output wire [255:0] mm_3_readdata,            //            .readdata
		output wire         mm_3_readdatavalid,       //            .readdatavalid
		output wire         mm_3_waitrequest,         //            .waitrequest
		input  wire         mm_3_write,               //            .write
		input  wire [255:0] mm_3_writedata,           //            .writedata
		output wire [10:0]  mm_csr_address,           //      mm_csr.address
		output wire [3:0]   mm_csr_burstcount,        //            .burstcount
		output wire [3:0]   mm_csr_byteenable,        //            .byteenable
		output wire         mm_csr_debugaccess,       //            .debugaccess
		output wire         mm_csr_read,              //            .read
		input  wire [31:0]  mm_csr_readdata,          //            .readdata
		input  wire         mm_csr_readdatavalid,     //            .readdatavalid
		input  wire         mm_csr_waitrequest,       //            .waitrequest
		output wire         mm_csr_write,             //            .write
		output wire [31:0]  mm_csr_writedata,         //            .writedata
		input  wire [33:0]  mm_misc_sa_address,       //  mm_misc_sa.address
		input  wire [3:0]   mm_misc_sa_burstcount,    //            .burstcount
		input  wire [31:0]  mm_misc_sa_byteenable,    //            .byteenable
		input  wire         mm_misc_sa_debugaccess,   //            .debugaccess
		input  wire         mm_misc_sa_read,          //            .read
		output wire [255:0] mm_misc_sa_readdata,      //            .readdata
		output wire         mm_misc_sa_readdatavalid, //            .readdatavalid
		output wire         mm_misc_sa_waitrequest,   //            .waitrequest
		input  wire         mm_misc_sa_write,         //            .write
		input  wire [255:0] mm_misc_sa_writedata,     //            .writedata
		output wire [9:0]   emif_mmr_address,         //    emif_mmr.address
		output wire [0:0]   emif_mmr_burstcount,      //            .burstcount
		output wire [3:0]   emif_mmr_byteenable,      //            .byteenable
		output wire         emif_mmr_debugaccess,     //            .debugaccess
		output wire         emif_mmr_read,            //            .read
		input  wire [31:0]  emif_mmr_readdata,        //            .readdata
		input  wire         emif_mmr_readdatavalid,   //            .readdatavalid
		input  wire         emif_mmr_waitrequest,     //            .waitrequest
		output wire         emif_mmr_write,           //            .write
		output wire [31:0]  emif_mmr_writedata,       //            .writedata
		input  wire         rst_misc_sa_reset_n,      // rst_misc_sa.reset_n
		input  wire         rst_mm_0_reset_n,         //    rst_mm_0.reset_n
		input  wire         rst_mm_1_reset_n,         //    rst_mm_1.reset_n
		input  wire         rst_mm_2_reset_n,         //    rst_mm_2.reset_n
		input  wire         rst_mm_3_reset_n          //    rst_mm_3.reset_n
	);

	wire  [255:0] mm_0_m0_readdata;                            // clkx_0:s0_readdata -> mm_0:m0_readdata
	wire          mm_0_m0_waitrequest;                         // clkx_0:s0_waitrequest -> mm_0:m0_waitrequest
	wire          mm_0_m0_debugaccess;                         // mm_0:m0_debugaccess -> clkx_0:s0_debugaccess
	wire   [31:0] mm_0_m0_address;                             // mm_0:m0_address -> clkx_0:s0_address
	wire   [31:0] mm_0_m0_byteenable;                          // mm_0:m0_byteenable -> clkx_0:s0_byteenable
	wire          mm_0_m0_read;                                // mm_0:m0_read -> clkx_0:s0_read
	wire          mm_0_m0_readdatavalid;                       // clkx_0:s0_readdatavalid -> mm_0:m0_readdatavalid
	wire          mm_0_m0_write;                               // mm_0:m0_write -> clkx_0:s0_write
	wire  [255:0] mm_0_m0_writedata;                           // mm_0:m0_writedata -> clkx_0:s0_writedata
	wire    [3:0] mm_0_m0_burstcount;                          // mm_0:m0_burstcount -> clkx_0:s0_burstcount
	wire  [255:0] mm_1_m0_readdata;                            // clkx_1:s0_readdata -> mm_1:m0_readdata
	wire          mm_1_m0_waitrequest;                         // clkx_1:s0_waitrequest -> mm_1:m0_waitrequest
	wire          mm_1_m0_debugaccess;                         // mm_1:m0_debugaccess -> clkx_1:s0_debugaccess
	wire   [31:0] mm_1_m0_address;                             // mm_1:m0_address -> clkx_1:s0_address
	wire   [31:0] mm_1_m0_byteenable;                          // mm_1:m0_byteenable -> clkx_1:s0_byteenable
	wire          mm_1_m0_read;                                // mm_1:m0_read -> clkx_1:s0_read
	wire          mm_1_m0_readdatavalid;                       // clkx_1:s0_readdatavalid -> mm_1:m0_readdatavalid
	wire          mm_1_m0_write;                               // mm_1:m0_write -> clkx_1:s0_write
	wire  [255:0] mm_1_m0_writedata;                           // mm_1:m0_writedata -> clkx_1:s0_writedata
	wire    [3:0] mm_1_m0_burstcount;                          // mm_1:m0_burstcount -> clkx_1:s0_burstcount
	wire  [255:0] mm_2_m0_readdata;                            // clkx_2:s0_readdata -> mm_2:m0_readdata
	wire          mm_2_m0_waitrequest;                         // clkx_2:s0_waitrequest -> mm_2:m0_waitrequest
	wire          mm_2_m0_debugaccess;                         // mm_2:m0_debugaccess -> clkx_2:s0_debugaccess
	wire   [31:0] mm_2_m0_address;                             // mm_2:m0_address -> clkx_2:s0_address
	wire   [31:0] mm_2_m0_byteenable;                          // mm_2:m0_byteenable -> clkx_2:s0_byteenable
	wire          mm_2_m0_read;                                // mm_2:m0_read -> clkx_2:s0_read
	wire          mm_2_m0_readdatavalid;                       // clkx_2:s0_readdatavalid -> mm_2:m0_readdatavalid
	wire          mm_2_m0_write;                               // mm_2:m0_write -> clkx_2:s0_write
	wire  [255:0] mm_2_m0_writedata;                           // mm_2:m0_writedata -> clkx_2:s0_writedata
	wire    [3:0] mm_2_m0_burstcount;                          // mm_2:m0_burstcount -> clkx_2:s0_burstcount
	wire  [255:0] mm_3_m0_readdata;                            // clkx_3:s0_readdata -> mm_3:m0_readdata
	wire          mm_3_m0_waitrequest;                         // clkx_3:s0_waitrequest -> mm_3:m0_waitrequest
	wire          mm_3_m0_debugaccess;                         // mm_3:m0_debugaccess -> clkx_3:s0_debugaccess
	wire   [31:0] mm_3_m0_address;                             // mm_3:m0_address -> clkx_3:s0_address
	wire   [31:0] mm_3_m0_byteenable;                          // mm_3:m0_byteenable -> clkx_3:s0_byteenable
	wire          mm_3_m0_read;                                // mm_3:m0_read -> clkx_3:s0_read
	wire          mm_3_m0_readdatavalid;                       // clkx_3:s0_readdatavalid -> mm_3:m0_readdatavalid
	wire          mm_3_m0_write;                               // mm_3:m0_write -> clkx_3:s0_write
	wire  [255:0] mm_3_m0_writedata;                           // mm_3:m0_writedata -> clkx_3:s0_writedata
	wire    [3:0] mm_3_m0_burstcount;                          // mm_3:m0_burstcount -> clkx_3:s0_burstcount
	wire          clk_misc_sa_out_clk_clk;                     // clk_misc_sa:out_clk -> [clkx_4:s0_clk, mm_csr:clk, mm_interconnect_5:clk_misc_sa_out_clk_clk, mm_misc_sa:clk, rst_misc_sa:clk]
	wire          clk_mm_0_out_clk_clk;                        // clk_mm_0:out_clk -> [clkx_0:s0_clk, mm_0:clk, rst_mm_0:clk]
	wire          clk_mm_1_out_clk_clk;                        // clk_mm_1:out_clk -> [clkx_1:s0_clk, mm_1:clk, rst_mm_1:clk]
	wire          clk_mm_2_out_clk_clk;                        // clk_mm_2:out_clk -> [clkx_2:s0_clk, mm_2:clk, rst_mm_2:clk]
	wire          clk_mm_3_out_clk_clk;                        // clk_mm_3:out_clk -> [clkx_3:s0_clk, mm_3:clk, rst_mm_3:clk]
	wire          ddr_emif_usr_clk_out_clk_clk;                // ddr_emif_usr_clk:out_clk -> [clkx_0:m0_clk, clkx_1:m0_clk, clkx_2:m0_clk, clkx_3:m0_clk, clkx_4:m0_clk, ddr4_amm:clk, ddr_emif_reset_in:clk, mm_interconnect_0:ddr_emif_usr_clk_out_clk_clk, mm_mmr:clk]
	wire          ddr_emif_reset_in_out_reset_reset;           // ddr_emif_reset_in:out_reset_n -> [clkx_0:m0_reset, clkx_1:m0_reset, clkx_2:m0_reset, clkx_3:m0_reset, clkx_4:m0_reset, ddr4_amm:reset, mm_interconnect_0:clkx_0_m0_reset_reset_bridge_in_reset_reset, mm_mmr:reset]
	wire          rst_misc_sa_out_reset_reset;                 // rst_misc_sa:out_reset_n -> [clkx_4:s0_reset, mm_csr:reset, mm_interconnect_5:mm_misc_sa_reset_reset_bridge_in_reset_reset, mm_misc_sa:reset]
	wire          rst_mm_0_out_reset_reset;                    // rst_mm_0:out_reset_n -> [clkx_0:s0_reset, mm_0:reset]
	wire          rst_mm_1_out_reset_reset;                    // rst_mm_1:out_reset_n -> [clkx_1:s0_reset, mm_1:reset]
	wire          rst_mm_2_out_reset_reset;                    // rst_mm_2:out_reset_n -> [clkx_2:s0_reset, mm_2:reset]
	wire          rst_mm_3_out_reset_reset;                    // rst_mm_3:out_reset_n -> [clkx_3:s0_reset, mm_3:reset]
	wire  [255:0] clkx_0_m0_readdata;                          // mm_interconnect_0:clkx_0_m0_readdata -> clkx_0:m0_readdata
	wire          clkx_0_m0_waitrequest;                       // mm_interconnect_0:clkx_0_m0_waitrequest -> clkx_0:m0_waitrequest
	wire          clkx_0_m0_debugaccess;                       // clkx_0:m0_debugaccess -> mm_interconnect_0:clkx_0_m0_debugaccess
	wire   [31:0] clkx_0_m0_address;                           // clkx_0:m0_address -> mm_interconnect_0:clkx_0_m0_address
	wire   [31:0] clkx_0_m0_byteenable;                        // clkx_0:m0_byteenable -> mm_interconnect_0:clkx_0_m0_byteenable
	wire          clkx_0_m0_read;                              // clkx_0:m0_read -> mm_interconnect_0:clkx_0_m0_read
	wire          clkx_0_m0_readdatavalid;                     // mm_interconnect_0:clkx_0_m0_readdatavalid -> clkx_0:m0_readdatavalid
	wire          clkx_0_m0_write;                             // clkx_0:m0_write -> mm_interconnect_0:clkx_0_m0_write
	wire  [255:0] clkx_0_m0_writedata;                         // clkx_0:m0_writedata -> mm_interconnect_0:clkx_0_m0_writedata
	wire    [3:0] clkx_0_m0_burstcount;                        // clkx_0:m0_burstcount -> mm_interconnect_0:clkx_0_m0_burstcount
	wire  [255:0] clkx_1_m0_readdata;                          // mm_interconnect_0:clkx_1_m0_readdata -> clkx_1:m0_readdata
	wire          clkx_1_m0_waitrequest;                       // mm_interconnect_0:clkx_1_m0_waitrequest -> clkx_1:m0_waitrequest
	wire          clkx_1_m0_debugaccess;                       // clkx_1:m0_debugaccess -> mm_interconnect_0:clkx_1_m0_debugaccess
	wire   [31:0] clkx_1_m0_address;                           // clkx_1:m0_address -> mm_interconnect_0:clkx_1_m0_address
	wire   [31:0] clkx_1_m0_byteenable;                        // clkx_1:m0_byteenable -> mm_interconnect_0:clkx_1_m0_byteenable
	wire          clkx_1_m0_read;                              // clkx_1:m0_read -> mm_interconnect_0:clkx_1_m0_read
	wire          clkx_1_m0_readdatavalid;                     // mm_interconnect_0:clkx_1_m0_readdatavalid -> clkx_1:m0_readdatavalid
	wire          clkx_1_m0_write;                             // clkx_1:m0_write -> mm_interconnect_0:clkx_1_m0_write
	wire  [255:0] clkx_1_m0_writedata;                         // clkx_1:m0_writedata -> mm_interconnect_0:clkx_1_m0_writedata
	wire    [3:0] clkx_1_m0_burstcount;                        // clkx_1:m0_burstcount -> mm_interconnect_0:clkx_1_m0_burstcount
	wire  [255:0] clkx_2_m0_readdata;                          // mm_interconnect_0:clkx_2_m0_readdata -> clkx_2:m0_readdata
	wire          clkx_2_m0_waitrequest;                       // mm_interconnect_0:clkx_2_m0_waitrequest -> clkx_2:m0_waitrequest
	wire          clkx_2_m0_debugaccess;                       // clkx_2:m0_debugaccess -> mm_interconnect_0:clkx_2_m0_debugaccess
	wire   [31:0] clkx_2_m0_address;                           // clkx_2:m0_address -> mm_interconnect_0:clkx_2_m0_address
	wire   [31:0] clkx_2_m0_byteenable;                        // clkx_2:m0_byteenable -> mm_interconnect_0:clkx_2_m0_byteenable
	wire          clkx_2_m0_read;                              // clkx_2:m0_read -> mm_interconnect_0:clkx_2_m0_read
	wire          clkx_2_m0_readdatavalid;                     // mm_interconnect_0:clkx_2_m0_readdatavalid -> clkx_2:m0_readdatavalid
	wire          clkx_2_m0_write;                             // clkx_2:m0_write -> mm_interconnect_0:clkx_2_m0_write
	wire  [255:0] clkx_2_m0_writedata;                         // clkx_2:m0_writedata -> mm_interconnect_0:clkx_2_m0_writedata
	wire    [3:0] clkx_2_m0_burstcount;                        // clkx_2:m0_burstcount -> mm_interconnect_0:clkx_2_m0_burstcount
	wire  [255:0] clkx_3_m0_readdata;                          // mm_interconnect_0:clkx_3_m0_readdata -> clkx_3:m0_readdata
	wire          clkx_3_m0_waitrequest;                       // mm_interconnect_0:clkx_3_m0_waitrequest -> clkx_3:m0_waitrequest
	wire          clkx_3_m0_debugaccess;                       // clkx_3:m0_debugaccess -> mm_interconnect_0:clkx_3_m0_debugaccess
	wire   [31:0] clkx_3_m0_address;                           // clkx_3:m0_address -> mm_interconnect_0:clkx_3_m0_address
	wire   [31:0] clkx_3_m0_byteenable;                        // clkx_3:m0_byteenable -> mm_interconnect_0:clkx_3_m0_byteenable
	wire          clkx_3_m0_read;                              // clkx_3:m0_read -> mm_interconnect_0:clkx_3_m0_read
	wire          clkx_3_m0_readdatavalid;                     // mm_interconnect_0:clkx_3_m0_readdatavalid -> clkx_3:m0_readdatavalid
	wire          clkx_3_m0_write;                             // clkx_3:m0_write -> mm_interconnect_0:clkx_3_m0_write
	wire  [255:0] clkx_3_m0_writedata;                         // clkx_3:m0_writedata -> mm_interconnect_0:clkx_3_m0_writedata
	wire    [3:0] clkx_3_m0_burstcount;                        // clkx_3:m0_burstcount -> mm_interconnect_0:clkx_3_m0_burstcount
	wire   [31:0] clkx_4_m0_readdata;                          // mm_interconnect_0:clkx_4_m0_readdata -> clkx_4:m0_readdata
	wire          clkx_4_m0_waitrequest;                       // mm_interconnect_0:clkx_4_m0_waitrequest -> clkx_4:m0_waitrequest
	wire          clkx_4_m0_debugaccess;                       // clkx_4:m0_debugaccess -> mm_interconnect_0:clkx_4_m0_debugaccess
	wire   [32:0] clkx_4_m0_address;                           // clkx_4:m0_address -> mm_interconnect_0:clkx_4_m0_address
	wire    [3:0] clkx_4_m0_byteenable;                        // clkx_4:m0_byteenable -> mm_interconnect_0:clkx_4_m0_byteenable
	wire          clkx_4_m0_read;                              // clkx_4:m0_read -> mm_interconnect_0:clkx_4_m0_read
	wire          clkx_4_m0_readdatavalid;                     // mm_interconnect_0:clkx_4_m0_readdatavalid -> clkx_4:m0_readdatavalid
	wire          clkx_4_m0_write;                             // clkx_4:m0_write -> mm_interconnect_0:clkx_4_m0_write
	wire   [31:0] clkx_4_m0_writedata;                         // clkx_4:m0_writedata -> mm_interconnect_0:clkx_4_m0_writedata
	wire    [0:0] clkx_4_m0_burstcount;                        // clkx_4:m0_burstcount -> mm_interconnect_0:clkx_4_m0_burstcount
	wire  [511:0] mm_interconnect_0_ddr4_amm_s0_readdata;      // ddr4_amm:s0_readdata -> mm_interconnect_0:ddr4_amm_s0_readdata
	wire          mm_interconnect_0_ddr4_amm_s0_waitrequest;   // ddr4_amm:s0_waitrequest -> mm_interconnect_0:ddr4_amm_s0_waitrequest
	wire          mm_interconnect_0_ddr4_amm_s0_debugaccess;   // mm_interconnect_0:ddr4_amm_s0_debugaccess -> ddr4_amm:s0_debugaccess
	wire   [25:0] mm_interconnect_0_ddr4_amm_s0_address;       // mm_interconnect_0:ddr4_amm_s0_address -> ddr4_amm:s0_address
	wire          mm_interconnect_0_ddr4_amm_s0_read;          // mm_interconnect_0:ddr4_amm_s0_read -> ddr4_amm:s0_read
	wire   [63:0] mm_interconnect_0_ddr4_amm_s0_byteenable;    // mm_interconnect_0:ddr4_amm_s0_byteenable -> ddr4_amm:s0_byteenable
	wire          mm_interconnect_0_ddr4_amm_s0_readdatavalid; // ddr4_amm:s0_readdatavalid -> mm_interconnect_0:ddr4_amm_s0_readdatavalid
	wire          mm_interconnect_0_ddr4_amm_s0_write;         // mm_interconnect_0:ddr4_amm_s0_write -> ddr4_amm:s0_write
	wire  [511:0] mm_interconnect_0_ddr4_amm_s0_writedata;     // mm_interconnect_0:ddr4_amm_s0_writedata -> ddr4_amm:s0_writedata
	wire    [6:0] mm_interconnect_0_ddr4_amm_s0_burstcount;    // mm_interconnect_0:ddr4_amm_s0_burstcount -> ddr4_amm:s0_burstcount
	wire   [31:0] mm_interconnect_0_mm_mmr_s0_readdata;        // mm_mmr:s0_readdata -> mm_interconnect_0:mm_mmr_s0_readdata
	wire          mm_interconnect_0_mm_mmr_s0_waitrequest;     // mm_mmr:s0_waitrequest -> mm_interconnect_0:mm_mmr_s0_waitrequest
	wire          mm_interconnect_0_mm_mmr_s0_debugaccess;     // mm_interconnect_0:mm_mmr_s0_debugaccess -> mm_mmr:s0_debugaccess
	wire    [9:0] mm_interconnect_0_mm_mmr_s0_address;         // mm_interconnect_0:mm_mmr_s0_address -> mm_mmr:s0_address
	wire          mm_interconnect_0_mm_mmr_s0_read;            // mm_interconnect_0:mm_mmr_s0_read -> mm_mmr:s0_read
	wire    [3:0] mm_interconnect_0_mm_mmr_s0_byteenable;      // mm_interconnect_0:mm_mmr_s0_byteenable -> mm_mmr:s0_byteenable
	wire          mm_interconnect_0_mm_mmr_s0_readdatavalid;   // mm_mmr:s0_readdatavalid -> mm_interconnect_0:mm_mmr_s0_readdatavalid
	wire          mm_interconnect_0_mm_mmr_s0_write;           // mm_interconnect_0:mm_mmr_s0_write -> mm_mmr:s0_write
	wire   [31:0] mm_interconnect_0_mm_mmr_s0_writedata;       // mm_interconnect_0:mm_mmr_s0_writedata -> mm_mmr:s0_writedata
	wire    [0:0] mm_interconnect_0_mm_mmr_s0_burstcount;      // mm_interconnect_0:mm_mmr_s0_burstcount -> mm_mmr:s0_burstcount
	wire  [255:0] mm_misc_sa_m0_readdata;                      // mm_interconnect_5:mm_misc_sa_m0_readdata -> mm_misc_sa:m0_readdata
	wire          mm_misc_sa_m0_waitrequest;                   // mm_interconnect_5:mm_misc_sa_m0_waitrequest -> mm_misc_sa:m0_waitrequest
	wire          mm_misc_sa_m0_debugaccess;                   // mm_misc_sa:m0_debugaccess -> mm_interconnect_5:mm_misc_sa_m0_debugaccess
	wire   [33:0] mm_misc_sa_m0_address;                       // mm_misc_sa:m0_address -> mm_interconnect_5:mm_misc_sa_m0_address
	wire   [31:0] mm_misc_sa_m0_byteenable;                    // mm_misc_sa:m0_byteenable -> mm_interconnect_5:mm_misc_sa_m0_byteenable
	wire          mm_misc_sa_m0_read;                          // mm_misc_sa:m0_read -> mm_interconnect_5:mm_misc_sa_m0_read
	wire          mm_misc_sa_m0_readdatavalid;                 // mm_interconnect_5:mm_misc_sa_m0_readdatavalid -> mm_misc_sa:m0_readdatavalid
	wire          mm_misc_sa_m0_write;                         // mm_misc_sa:m0_write -> mm_interconnect_5:mm_misc_sa_m0_write
	wire  [255:0] mm_misc_sa_m0_writedata;                     // mm_misc_sa:m0_writedata -> mm_interconnect_5:mm_misc_sa_m0_writedata
	wire    [3:0] mm_misc_sa_m0_burstcount;                    // mm_misc_sa:m0_burstcount -> mm_interconnect_5:mm_misc_sa_m0_burstcount
	wire   [31:0] mm_interconnect_5_clkx_4_s0_readdata;        // clkx_4:s0_readdata -> mm_interconnect_5:clkx_4_s0_readdata
	wire          mm_interconnect_5_clkx_4_s0_waitrequest;     // clkx_4:s0_waitrequest -> mm_interconnect_5:clkx_4_s0_waitrequest
	wire          mm_interconnect_5_clkx_4_s0_debugaccess;     // mm_interconnect_5:clkx_4_s0_debugaccess -> clkx_4:s0_debugaccess
	wire   [32:0] mm_interconnect_5_clkx_4_s0_address;         // mm_interconnect_5:clkx_4_s0_address -> clkx_4:s0_address
	wire          mm_interconnect_5_clkx_4_s0_read;            // mm_interconnect_5:clkx_4_s0_read -> clkx_4:s0_read
	wire    [3:0] mm_interconnect_5_clkx_4_s0_byteenable;      // mm_interconnect_5:clkx_4_s0_byteenable -> clkx_4:s0_byteenable
	wire          mm_interconnect_5_clkx_4_s0_readdatavalid;   // clkx_4:s0_readdatavalid -> mm_interconnect_5:clkx_4_s0_readdatavalid
	wire          mm_interconnect_5_clkx_4_s0_write;           // mm_interconnect_5:clkx_4_s0_write -> clkx_4:s0_write
	wire   [31:0] mm_interconnect_5_clkx_4_s0_writedata;       // mm_interconnect_5:clkx_4_s0_writedata -> clkx_4:s0_writedata
	wire    [0:0] mm_interconnect_5_clkx_4_s0_burstcount;      // mm_interconnect_5:clkx_4_s0_burstcount -> clkx_4:s0_burstcount
	wire   [31:0] mm_interconnect_5_mm_csr_s0_readdata;        // mm_csr:s0_readdata -> mm_interconnect_5:mm_csr_s0_readdata
	wire          mm_interconnect_5_mm_csr_s0_waitrequest;     // mm_csr:s0_waitrequest -> mm_interconnect_5:mm_csr_s0_waitrequest
	wire          mm_interconnect_5_mm_csr_s0_debugaccess;     // mm_interconnect_5:mm_csr_s0_debugaccess -> mm_csr:s0_debugaccess
	wire   [10:0] mm_interconnect_5_mm_csr_s0_address;         // mm_interconnect_5:mm_csr_s0_address -> mm_csr:s0_address
	wire          mm_interconnect_5_mm_csr_s0_read;            // mm_interconnect_5:mm_csr_s0_read -> mm_csr:s0_read
	wire    [3:0] mm_interconnect_5_mm_csr_s0_byteenable;      // mm_interconnect_5:mm_csr_s0_byteenable -> mm_csr:s0_byteenable
	wire          mm_interconnect_5_mm_csr_s0_readdatavalid;   // mm_csr:s0_readdatavalid -> mm_interconnect_5:mm_csr_s0_readdatavalid
	wire          mm_interconnect_5_mm_csr_s0_write;           // mm_interconnect_5:mm_csr_s0_write -> mm_csr:s0_write
	wire   [31:0] mm_interconnect_5_mm_csr_s0_writedata;       // mm_interconnect_5:mm_csr_s0_writedata -> mm_csr:s0_writedata
	wire    [3:0] mm_interconnect_5_mm_csr_s0_burstcount;      // mm_interconnect_5:mm_csr_s0_burstcount -> mm_csr:s0_burstcount

	clk_mm_4 clk_misc_sa (
		.in_clk  (clk_misc_sa_clk),         //   input,  width = 1,  in_clk.clk
		.out_clk (clk_misc_sa_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	ddr_emif_usr_clk_0 clk_mm_0 (
		.in_clk  (clk_mm_0_clk),         //   input,  width = 1,  in_clk.clk
		.out_clk (clk_mm_0_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	clk_mm_1 clk_mm_1 (
		.in_clk  (clk_mm_1_clk),         //   input,  width = 1,  in_clk.clk
		.out_clk (clk_mm_1_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	clk_mm_2 clk_mm_2 (
		.in_clk  (clk_mm_2_clk),         //   input,  width = 1,  in_clk.clk
		.out_clk (clk_mm_2_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	clk_mm_3 clk_mm_3 (
		.in_clk  (clk_mm_3_clk),         //   input,  width = 1,  in_clk.clk
		.out_clk (clk_mm_3_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	fpt_ddr4_nw_mm_clock_crossing_bridge_0 clkx_0 (
		.m0_address       (clkx_0_m0_address),                  //  output,   width = 32,       m0.address
		.m0_burstcount    (clkx_0_m0_burstcount),               //  output,    width = 4,         .burstcount
		.m0_byteenable    (clkx_0_m0_byteenable),               //  output,   width = 32,         .byteenable
		.m0_debugaccess   (clkx_0_m0_debugaccess),              //  output,    width = 1,         .debugaccess
		.m0_read          (clkx_0_m0_read),                     //  output,    width = 1,         .read
		.m0_readdata      (clkx_0_m0_readdata),                 //   input,  width = 256,         .readdata
		.m0_readdatavalid (clkx_0_m0_readdatavalid),            //   input,    width = 1,         .readdatavalid
		.m0_waitrequest   (clkx_0_m0_waitrequest),              //   input,    width = 1,         .waitrequest
		.m0_write         (clkx_0_m0_write),                    //  output,    width = 1,         .write
		.m0_writedata     (clkx_0_m0_writedata),                //  output,  width = 256,         .writedata
		.m0_clk           (ddr_emif_usr_clk_out_clk_clk),       //   input,    width = 1,   m0_clk.clk
		.m0_reset         (~ddr_emif_reset_in_out_reset_reset), //   input,    width = 1, m0_reset.reset
		.s0_address       (mm_0_m0_address),                    //   input,   width = 32,       s0.address
		.s0_burstcount    (mm_0_m0_burstcount),                 //   input,    width = 4,         .burstcount
		.s0_byteenable    (mm_0_m0_byteenable),                 //   input,   width = 32,         .byteenable
		.s0_debugaccess   (mm_0_m0_debugaccess),                //   input,    width = 1,         .debugaccess
		.s0_read          (mm_0_m0_read),                       //   input,    width = 1,         .read
		.s0_readdata      (mm_0_m0_readdata),                   //  output,  width = 256,         .readdata
		.s0_readdatavalid (mm_0_m0_readdatavalid),              //  output,    width = 1,         .readdatavalid
		.s0_waitrequest   (mm_0_m0_waitrequest),                //  output,    width = 1,         .waitrequest
		.s0_write         (mm_0_m0_write),                      //   input,    width = 1,         .write
		.s0_writedata     (mm_0_m0_writedata),                  //   input,  width = 256,         .writedata
		.s0_clk           (clk_mm_0_out_clk_clk),               //   input,    width = 1,   s0_clk.clk
		.s0_reset         (~rst_mm_0_out_reset_reset)           //   input,    width = 1, s0_reset.reset
	);

	clkx_1 clkx_1 (
		.m0_address       (clkx_1_m0_address),                  //  output,   width = 32,       m0.address
		.m0_burstcount    (clkx_1_m0_burstcount),               //  output,    width = 4,         .burstcount
		.m0_byteenable    (clkx_1_m0_byteenable),               //  output,   width = 32,         .byteenable
		.m0_debugaccess   (clkx_1_m0_debugaccess),              //  output,    width = 1,         .debugaccess
		.m0_read          (clkx_1_m0_read),                     //  output,    width = 1,         .read
		.m0_readdata      (clkx_1_m0_readdata),                 //   input,  width = 256,         .readdata
		.m0_readdatavalid (clkx_1_m0_readdatavalid),            //   input,    width = 1,         .readdatavalid
		.m0_waitrequest   (clkx_1_m0_waitrequest),              //   input,    width = 1,         .waitrequest
		.m0_write         (clkx_1_m0_write),                    //  output,    width = 1,         .write
		.m0_writedata     (clkx_1_m0_writedata),                //  output,  width = 256,         .writedata
		.m0_clk           (ddr_emif_usr_clk_out_clk_clk),       //   input,    width = 1,   m0_clk.clk
		.m0_reset         (~ddr_emif_reset_in_out_reset_reset), //   input,    width = 1, m0_reset.reset
		.s0_address       (mm_1_m0_address),                    //   input,   width = 32,       s0.address
		.s0_burstcount    (mm_1_m0_burstcount),                 //   input,    width = 4,         .burstcount
		.s0_byteenable    (mm_1_m0_byteenable),                 //   input,   width = 32,         .byteenable
		.s0_debugaccess   (mm_1_m0_debugaccess),                //   input,    width = 1,         .debugaccess
		.s0_read          (mm_1_m0_read),                       //   input,    width = 1,         .read
		.s0_readdata      (mm_1_m0_readdata),                   //  output,  width = 256,         .readdata
		.s0_readdatavalid (mm_1_m0_readdatavalid),              //  output,    width = 1,         .readdatavalid
		.s0_waitrequest   (mm_1_m0_waitrequest),                //  output,    width = 1,         .waitrequest
		.s0_write         (mm_1_m0_write),                      //   input,    width = 1,         .write
		.s0_writedata     (mm_1_m0_writedata),                  //   input,  width = 256,         .writedata
		.s0_clk           (clk_mm_1_out_clk_clk),               //   input,    width = 1,   s0_clk.clk
		.s0_reset         (~rst_mm_1_out_reset_reset)           //   input,    width = 1, s0_reset.reset
	);

	clkx_2 clkx_2 (
		.m0_address       (clkx_2_m0_address),                  //  output,   width = 32,       m0.address
		.m0_burstcount    (clkx_2_m0_burstcount),               //  output,    width = 4,         .burstcount
		.m0_byteenable    (clkx_2_m0_byteenable),               //  output,   width = 32,         .byteenable
		.m0_debugaccess   (clkx_2_m0_debugaccess),              //  output,    width = 1,         .debugaccess
		.m0_read          (clkx_2_m0_read),                     //  output,    width = 1,         .read
		.m0_readdata      (clkx_2_m0_readdata),                 //   input,  width = 256,         .readdata
		.m0_readdatavalid (clkx_2_m0_readdatavalid),            //   input,    width = 1,         .readdatavalid
		.m0_waitrequest   (clkx_2_m0_waitrequest),              //   input,    width = 1,         .waitrequest
		.m0_write         (clkx_2_m0_write),                    //  output,    width = 1,         .write
		.m0_writedata     (clkx_2_m0_writedata),                //  output,  width = 256,         .writedata
		.m0_clk           (ddr_emif_usr_clk_out_clk_clk),       //   input,    width = 1,   m0_clk.clk
		.m0_reset         (~ddr_emif_reset_in_out_reset_reset), //   input,    width = 1, m0_reset.reset
		.s0_address       (mm_2_m0_address),                    //   input,   width = 32,       s0.address
		.s0_burstcount    (mm_2_m0_burstcount),                 //   input,    width = 4,         .burstcount
		.s0_byteenable    (mm_2_m0_byteenable),                 //   input,   width = 32,         .byteenable
		.s0_debugaccess   (mm_2_m0_debugaccess),                //   input,    width = 1,         .debugaccess
		.s0_read          (mm_2_m0_read),                       //   input,    width = 1,         .read
		.s0_readdata      (mm_2_m0_readdata),                   //  output,  width = 256,         .readdata
		.s0_readdatavalid (mm_2_m0_readdatavalid),              //  output,    width = 1,         .readdatavalid
		.s0_waitrequest   (mm_2_m0_waitrequest),                //  output,    width = 1,         .waitrequest
		.s0_write         (mm_2_m0_write),                      //   input,    width = 1,         .write
		.s0_writedata     (mm_2_m0_writedata),                  //   input,  width = 256,         .writedata
		.s0_clk           (clk_mm_2_out_clk_clk),               //   input,    width = 1,   s0_clk.clk
		.s0_reset         (~rst_mm_2_out_reset_reset)           //   input,    width = 1, s0_reset.reset
	);

	clkx_3 clkx_3 (
		.m0_address       (clkx_3_m0_address),                  //  output,   width = 32,       m0.address
		.m0_burstcount    (clkx_3_m0_burstcount),               //  output,    width = 4,         .burstcount
		.m0_byteenable    (clkx_3_m0_byteenable),               //  output,   width = 32,         .byteenable
		.m0_debugaccess   (clkx_3_m0_debugaccess),              //  output,    width = 1,         .debugaccess
		.m0_read          (clkx_3_m0_read),                     //  output,    width = 1,         .read
		.m0_readdata      (clkx_3_m0_readdata),                 //   input,  width = 256,         .readdata
		.m0_readdatavalid (clkx_3_m0_readdatavalid),            //   input,    width = 1,         .readdatavalid
		.m0_waitrequest   (clkx_3_m0_waitrequest),              //   input,    width = 1,         .waitrequest
		.m0_write         (clkx_3_m0_write),                    //  output,    width = 1,         .write
		.m0_writedata     (clkx_3_m0_writedata),                //  output,  width = 256,         .writedata
		.m0_clk           (ddr_emif_usr_clk_out_clk_clk),       //   input,    width = 1,   m0_clk.clk
		.m0_reset         (~ddr_emif_reset_in_out_reset_reset), //   input,    width = 1, m0_reset.reset
		.s0_address       (mm_3_m0_address),                    //   input,   width = 32,       s0.address
		.s0_burstcount    (mm_3_m0_burstcount),                 //   input,    width = 4,         .burstcount
		.s0_byteenable    (mm_3_m0_byteenable),                 //   input,   width = 32,         .byteenable
		.s0_debugaccess   (mm_3_m0_debugaccess),                //   input,    width = 1,         .debugaccess
		.s0_read          (mm_3_m0_read),                       //   input,    width = 1,         .read
		.s0_readdata      (mm_3_m0_readdata),                   //  output,  width = 256,         .readdata
		.s0_readdatavalid (mm_3_m0_readdatavalid),              //  output,    width = 1,         .readdatavalid
		.s0_waitrequest   (mm_3_m0_waitrequest),                //  output,    width = 1,         .waitrequest
		.s0_write         (mm_3_m0_write),                      //   input,    width = 1,         .write
		.s0_writedata     (mm_3_m0_writedata),                  //   input,  width = 256,         .writedata
		.s0_clk           (clk_mm_3_out_clk_clk),               //   input,    width = 1,   s0_clk.clk
		.s0_reset         (~rst_mm_3_out_reset_reset)           //   input,    width = 1, s0_reset.reset
	);

	fpt_ddr4_nw_mm_clock_crossing_bridge_1 clkx_4 (
		.m0_address       (clkx_4_m0_address),                         //  output,  width = 33,       m0.address
		.m0_burstcount    (clkx_4_m0_burstcount),                      //  output,   width = 1,         .burstcount
		.m0_byteenable    (clkx_4_m0_byteenable),                      //  output,   width = 4,         .byteenable
		.m0_debugaccess   (clkx_4_m0_debugaccess),                     //  output,   width = 1,         .debugaccess
		.m0_read          (clkx_4_m0_read),                            //  output,   width = 1,         .read
		.m0_readdata      (clkx_4_m0_readdata),                        //   input,  width = 32,         .readdata
		.m0_readdatavalid (clkx_4_m0_readdatavalid),                   //   input,   width = 1,         .readdatavalid
		.m0_waitrequest   (clkx_4_m0_waitrequest),                     //   input,   width = 1,         .waitrequest
		.m0_write         (clkx_4_m0_write),                           //  output,   width = 1,         .write
		.m0_writedata     (clkx_4_m0_writedata),                       //  output,  width = 32,         .writedata
		.m0_clk           (ddr_emif_usr_clk_out_clk_clk),              //   input,   width = 1,   m0_clk.clk
		.m0_reset         (~ddr_emif_reset_in_out_reset_reset),        //   input,   width = 1, m0_reset.reset
		.s0_address       (mm_interconnect_5_clkx_4_s0_address),       //   input,  width = 33,       s0.address
		.s0_burstcount    (mm_interconnect_5_clkx_4_s0_burstcount),    //   input,   width = 1,         .burstcount
		.s0_byteenable    (mm_interconnect_5_clkx_4_s0_byteenable),    //   input,   width = 4,         .byteenable
		.s0_debugaccess   (mm_interconnect_5_clkx_4_s0_debugaccess),   //   input,   width = 1,         .debugaccess
		.s0_read          (mm_interconnect_5_clkx_4_s0_read),          //   input,   width = 1,         .read
		.s0_readdata      (mm_interconnect_5_clkx_4_s0_readdata),      //  output,  width = 32,         .readdata
		.s0_readdatavalid (mm_interconnect_5_clkx_4_s0_readdatavalid), //  output,   width = 1,         .readdatavalid
		.s0_waitrequest   (mm_interconnect_5_clkx_4_s0_waitrequest),   //  output,   width = 1,         .waitrequest
		.s0_write         (mm_interconnect_5_clkx_4_s0_write),         //   input,   width = 1,         .write
		.s0_writedata     (mm_interconnect_5_clkx_4_s0_writedata),     //   input,  width = 32,         .writedata
		.s0_clk           (clk_misc_sa_out_clk_clk),                   //   input,   width = 1,   s0_clk.clk
		.s0_reset         (~rst_misc_sa_out_reset_reset)               //   input,   width = 1, s0_reset.reset
	);

	fpt_ddr4_nw_mm_bridge_0 ddr4_amm (
		.clk              (ddr_emif_usr_clk_out_clk_clk),                //   input,    width = 1,   clk.clk
		.m0_address       (ddr4_amm_address),                            //  output,   width = 26,    m0.address
		.m0_burstcount    (ddr4_amm_burstcount),                         //  output,    width = 7,      .burstcount
		.m0_byteenable    (ddr4_amm_byteenable),                         //  output,   width = 64,      .byteenable
		.m0_debugaccess   (ddr4_amm_debugaccess),                        //  output,    width = 1,      .debugaccess
		.m0_read          (ddr4_amm_read),                               //  output,    width = 1,      .read
		.m0_readdata      (ddr4_amm_readdata),                           //   input,  width = 512,      .readdata
		.m0_readdatavalid (ddr4_amm_readdatavalid),                      //   input,    width = 1,      .readdatavalid
		.m0_waitrequest   (ddr4_amm_waitrequest),                        //   input,    width = 1,      .waitrequest
		.m0_write         (ddr4_amm_write),                              //  output,    width = 1,      .write
		.m0_writedata     (ddr4_amm_writedata),                          //  output,  width = 512,      .writedata
		.reset            (~ddr_emif_reset_in_out_reset_reset),          //   input,    width = 1, reset.reset
		.s0_address       (mm_interconnect_0_ddr4_amm_s0_address),       //   input,   width = 26,    s0.address
		.s0_burstcount    (mm_interconnect_0_ddr4_amm_s0_burstcount),    //   input,    width = 7,      .burstcount
		.s0_byteenable    (mm_interconnect_0_ddr4_amm_s0_byteenable),    //   input,   width = 64,      .byteenable
		.s0_debugaccess   (mm_interconnect_0_ddr4_amm_s0_debugaccess),   //   input,    width = 1,      .debugaccess
		.s0_read          (mm_interconnect_0_ddr4_amm_s0_read),          //   input,    width = 1,      .read
		.s0_readdata      (mm_interconnect_0_ddr4_amm_s0_readdata),      //  output,  width = 512,      .readdata
		.s0_readdatavalid (mm_interconnect_0_ddr4_amm_s0_readdatavalid), //  output,    width = 1,      .readdatavalid
		.s0_waitrequest   (mm_interconnect_0_ddr4_amm_s0_waitrequest),   //  output,    width = 1,      .waitrequest
		.s0_write         (mm_interconnect_0_ddr4_amm_s0_write),         //   input,    width = 1,      .write
		.s0_writedata     (mm_interconnect_0_ddr4_amm_s0_writedata)      //   input,  width = 512,      .writedata
	);

	fpt_ddr4_nw_reset_in ddr_emif_reset_in (
		.clk         (ddr_emif_usr_clk_out_clk_clk),      //   input,  width = 1,       clk.clk
		.in_reset_n  (reset_emif_reset_n),                //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (ddr_emif_reset_in_out_reset_reset)  //  output,  width = 1, out_reset.reset_n
	);

	fpt_ddr4_nw_clock_in ddr_emif_usr_clk (
		.in_clk  (clk_emif_clk),                 //   input,  width = 1,  in_clk.clk
		.out_clk (ddr_emif_usr_clk_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	ddr4_amm_0 mm_0 (
		.clk              (clk_mm_0_out_clk_clk),      //   input,    width = 1,   clk.clk
		.m0_address       (mm_0_m0_address),           //  output,   width = 32,    m0.address
		.m0_burstcount    (mm_0_m0_burstcount),        //  output,    width = 4,      .burstcount
		.m0_byteenable    (mm_0_m0_byteenable),        //  output,   width = 32,      .byteenable
		.m0_debugaccess   (mm_0_m0_debugaccess),       //  output,    width = 1,      .debugaccess
		.m0_read          (mm_0_m0_read),              //  output,    width = 1,      .read
		.m0_readdata      (mm_0_m0_readdata),          //   input,  width = 256,      .readdata
		.m0_readdatavalid (mm_0_m0_readdatavalid),     //   input,    width = 1,      .readdatavalid
		.m0_waitrequest   (mm_0_m0_waitrequest),       //   input,    width = 1,      .waitrequest
		.m0_write         (mm_0_m0_write),             //  output,    width = 1,      .write
		.m0_writedata     (mm_0_m0_writedata),         //  output,  width = 256,      .writedata
		.reset            (~rst_mm_0_out_reset_reset), //   input,    width = 1, reset.reset
		.s0_address       (mm_0_address),              //   input,   width = 32,    s0.address
		.s0_burstcount    (mm_0_burstcount),           //   input,    width = 4,      .burstcount
		.s0_byteenable    (mm_0_byteenable),           //   input,   width = 32,      .byteenable
		.s0_debugaccess   (mm_0_debugaccess),          //   input,    width = 1,      .debugaccess
		.s0_read          (mm_0_read),                 //   input,    width = 1,      .read
		.s0_readdata      (mm_0_readdata),             //  output,  width = 256,      .readdata
		.s0_readdatavalid (mm_0_readdatavalid),        //  output,    width = 1,      .readdatavalid
		.s0_waitrequest   (mm_0_waitrequest),          //  output,    width = 1,      .waitrequest
		.s0_write         (mm_0_write),                //   input,    width = 1,      .write
		.s0_writedata     (mm_0_writedata)             //   input,  width = 256,      .writedata
	);

	mm_1 mm_1 (
		.clk              (clk_mm_1_out_clk_clk),      //   input,    width = 1,   clk.clk
		.m0_address       (mm_1_m0_address),           //  output,   width = 32,    m0.address
		.m0_burstcount    (mm_1_m0_burstcount),        //  output,    width = 4,      .burstcount
		.m0_byteenable    (mm_1_m0_byteenable),        //  output,   width = 32,      .byteenable
		.m0_debugaccess   (mm_1_m0_debugaccess),       //  output,    width = 1,      .debugaccess
		.m0_read          (mm_1_m0_read),              //  output,    width = 1,      .read
		.m0_readdata      (mm_1_m0_readdata),          //   input,  width = 256,      .readdata
		.m0_readdatavalid (mm_1_m0_readdatavalid),     //   input,    width = 1,      .readdatavalid
		.m0_waitrequest   (mm_1_m0_waitrequest),       //   input,    width = 1,      .waitrequest
		.m0_write         (mm_1_m0_write),             //  output,    width = 1,      .write
		.m0_writedata     (mm_1_m0_writedata),         //  output,  width = 256,      .writedata
		.reset            (~rst_mm_1_out_reset_reset), //   input,    width = 1, reset.reset
		.s0_address       (mm_1_address),              //   input,   width = 32,    s0.address
		.s0_burstcount    (mm_1_burstcount),           //   input,    width = 4,      .burstcount
		.s0_byteenable    (mm_1_byteenable),           //   input,   width = 32,      .byteenable
		.s0_debugaccess   (mm_1_debugaccess),          //   input,    width = 1,      .debugaccess
		.s0_read          (mm_1_read),                 //   input,    width = 1,      .read
		.s0_readdata      (mm_1_readdata),             //  output,  width = 256,      .readdata
		.s0_readdatavalid (mm_1_readdatavalid),        //  output,    width = 1,      .readdatavalid
		.s0_waitrequest   (mm_1_waitrequest),          //  output,    width = 1,      .waitrequest
		.s0_write         (mm_1_write),                //   input,    width = 1,      .write
		.s0_writedata     (mm_1_writedata)             //   input,  width = 256,      .writedata
	);

	mm_2 mm_2 (
		.clk              (clk_mm_2_out_clk_clk),      //   input,    width = 1,   clk.clk
		.m0_address       (mm_2_m0_address),           //  output,   width = 32,    m0.address
		.m0_burstcount    (mm_2_m0_burstcount),        //  output,    width = 4,      .burstcount
		.m0_byteenable    (mm_2_m0_byteenable),        //  output,   width = 32,      .byteenable
		.m0_debugaccess   (mm_2_m0_debugaccess),       //  output,    width = 1,      .debugaccess
		.m0_read          (mm_2_m0_read),              //  output,    width = 1,      .read
		.m0_readdata      (mm_2_m0_readdata),          //   input,  width = 256,      .readdata
		.m0_readdatavalid (mm_2_m0_readdatavalid),     //   input,    width = 1,      .readdatavalid
		.m0_waitrequest   (mm_2_m0_waitrequest),       //   input,    width = 1,      .waitrequest
		.m0_write         (mm_2_m0_write),             //  output,    width = 1,      .write
		.m0_writedata     (mm_2_m0_writedata),         //  output,  width = 256,      .writedata
		.reset            (~rst_mm_2_out_reset_reset), //   input,    width = 1, reset.reset
		.s0_address       (mm_2_address),              //   input,   width = 32,    s0.address
		.s0_burstcount    (mm_2_burstcount),           //   input,    width = 4,      .burstcount
		.s0_byteenable    (mm_2_byteenable),           //   input,   width = 32,      .byteenable
		.s0_debugaccess   (mm_2_debugaccess),          //   input,    width = 1,      .debugaccess
		.s0_read          (mm_2_read),                 //   input,    width = 1,      .read
		.s0_readdata      (mm_2_readdata),             //  output,  width = 256,      .readdata
		.s0_readdatavalid (mm_2_readdatavalid),        //  output,    width = 1,      .readdatavalid
		.s0_waitrequest   (mm_2_waitrequest),          //  output,    width = 1,      .waitrequest
		.s0_write         (mm_2_write),                //   input,    width = 1,      .write
		.s0_writedata     (mm_2_writedata)             //   input,  width = 256,      .writedata
	);

	mm_3 mm_3 (
		.clk              (clk_mm_3_out_clk_clk),      //   input,    width = 1,   clk.clk
		.m0_address       (mm_3_m0_address),           //  output,   width = 32,    m0.address
		.m0_burstcount    (mm_3_m0_burstcount),        //  output,    width = 4,      .burstcount
		.m0_byteenable    (mm_3_m0_byteenable),        //  output,   width = 32,      .byteenable
		.m0_debugaccess   (mm_3_m0_debugaccess),       //  output,    width = 1,      .debugaccess
		.m0_read          (mm_3_m0_read),              //  output,    width = 1,      .read
		.m0_readdata      (mm_3_m0_readdata),          //   input,  width = 256,      .readdata
		.m0_readdatavalid (mm_3_m0_readdatavalid),     //   input,    width = 1,      .readdatavalid
		.m0_waitrequest   (mm_3_m0_waitrequest),       //   input,    width = 1,      .waitrequest
		.m0_write         (mm_3_m0_write),             //  output,    width = 1,      .write
		.m0_writedata     (mm_3_m0_writedata),         //  output,  width = 256,      .writedata
		.reset            (~rst_mm_3_out_reset_reset), //   input,    width = 1, reset.reset
		.s0_address       (mm_3_address),              //   input,   width = 32,    s0.address
		.s0_burstcount    (mm_3_burstcount),           //   input,    width = 4,      .burstcount
		.s0_byteenable    (mm_3_byteenable),           //   input,   width = 32,      .byteenable
		.s0_debugaccess   (mm_3_debugaccess),          //   input,    width = 1,      .debugaccess
		.s0_read          (mm_3_read),                 //   input,    width = 1,      .read
		.s0_readdata      (mm_3_readdata),             //  output,  width = 256,      .readdata
		.s0_readdatavalid (mm_3_readdatavalid),        //  output,    width = 1,      .readdatavalid
		.s0_waitrequest   (mm_3_waitrequest),          //  output,    width = 1,      .waitrequest
		.s0_write         (mm_3_write),                //   input,    width = 1,      .write
		.s0_writedata     (mm_3_writedata)             //   input,  width = 256,      .writedata
	);

	mm_5 mm_csr (
		.clk              (clk_misc_sa_out_clk_clk),                   //   input,   width = 1,   clk.clk
		.m0_address       (mm_csr_address),                            //  output,  width = 11,    m0.address
		.m0_burstcount    (mm_csr_burstcount),                         //  output,   width = 4,      .burstcount
		.m0_byteenable    (mm_csr_byteenable),                         //  output,   width = 4,      .byteenable
		.m0_debugaccess   (mm_csr_debugaccess),                        //  output,   width = 1,      .debugaccess
		.m0_read          (mm_csr_read),                               //  output,   width = 1,      .read
		.m0_readdata      (mm_csr_readdata),                           //   input,  width = 32,      .readdata
		.m0_readdatavalid (mm_csr_readdatavalid),                      //   input,   width = 1,      .readdatavalid
		.m0_waitrequest   (mm_csr_waitrequest),                        //   input,   width = 1,      .waitrequest
		.m0_write         (mm_csr_write),                              //  output,   width = 1,      .write
		.m0_writedata     (mm_csr_writedata),                          //  output,  width = 32,      .writedata
		.reset            (~rst_misc_sa_out_reset_reset),              //   input,   width = 1, reset.reset
		.s0_address       (mm_interconnect_5_mm_csr_s0_address),       //   input,  width = 11,    s0.address
		.s0_burstcount    (mm_interconnect_5_mm_csr_s0_burstcount),    //   input,   width = 4,      .burstcount
		.s0_byteenable    (mm_interconnect_5_mm_csr_s0_byteenable),    //   input,   width = 4,      .byteenable
		.s0_debugaccess   (mm_interconnect_5_mm_csr_s0_debugaccess),   //   input,   width = 1,      .debugaccess
		.s0_read          (mm_interconnect_5_mm_csr_s0_read),          //   input,   width = 1,      .read
		.s0_readdata      (mm_interconnect_5_mm_csr_s0_readdata),      //  output,  width = 32,      .readdata
		.s0_readdatavalid (mm_interconnect_5_mm_csr_s0_readdatavalid), //  output,   width = 1,      .readdatavalid
		.s0_waitrequest   (mm_interconnect_5_mm_csr_s0_waitrequest),   //  output,   width = 1,      .waitrequest
		.s0_write         (mm_interconnect_5_mm_csr_s0_write),         //   input,   width = 1,      .write
		.s0_writedata     (mm_interconnect_5_mm_csr_s0_writedata)      //   input,  width = 32,      .writedata
	);

	mm_4 mm_misc_sa (
		.clk              (clk_misc_sa_out_clk_clk),      //   input,    width = 1,   clk.clk
		.m0_address       (mm_misc_sa_m0_address),        //  output,   width = 34,    m0.address
		.m0_burstcount    (mm_misc_sa_m0_burstcount),     //  output,    width = 4,      .burstcount
		.m0_byteenable    (mm_misc_sa_m0_byteenable),     //  output,   width = 32,      .byteenable
		.m0_debugaccess   (mm_misc_sa_m0_debugaccess),    //  output,    width = 1,      .debugaccess
		.m0_read          (mm_misc_sa_m0_read),           //  output,    width = 1,      .read
		.m0_readdata      (mm_misc_sa_m0_readdata),       //   input,  width = 256,      .readdata
		.m0_readdatavalid (mm_misc_sa_m0_readdatavalid),  //   input,    width = 1,      .readdatavalid
		.m0_waitrequest   (mm_misc_sa_m0_waitrequest),    //   input,    width = 1,      .waitrequest
		.m0_write         (mm_misc_sa_m0_write),          //  output,    width = 1,      .write
		.m0_writedata     (mm_misc_sa_m0_writedata),      //  output,  width = 256,      .writedata
		.reset            (~rst_misc_sa_out_reset_reset), //   input,    width = 1, reset.reset
		.s0_address       (mm_misc_sa_address),           //   input,   width = 34,    s0.address
		.s0_burstcount    (mm_misc_sa_burstcount),        //   input,    width = 4,      .burstcount
		.s0_byteenable    (mm_misc_sa_byteenable),        //   input,   width = 32,      .byteenable
		.s0_debugaccess   (mm_misc_sa_debugaccess),       //   input,    width = 1,      .debugaccess
		.s0_read          (mm_misc_sa_read),              //   input,    width = 1,      .read
		.s0_readdata      (mm_misc_sa_readdata),          //  output,  width = 256,      .readdata
		.s0_readdatavalid (mm_misc_sa_readdatavalid),     //  output,    width = 1,      .readdatavalid
		.s0_waitrequest   (mm_misc_sa_waitrequest),       //  output,    width = 1,      .waitrequest
		.s0_write         (mm_misc_sa_write),             //   input,    width = 1,      .write
		.s0_writedata     (mm_misc_sa_writedata)          //   input,  width = 256,      .writedata
	);

	mm_csr_0 mm_mmr (
		.clk              (ddr_emif_usr_clk_out_clk_clk),              //   input,   width = 1,   clk.clk
		.m0_address       (emif_mmr_address),                          //  output,  width = 10,    m0.address
		.m0_burstcount    (emif_mmr_burstcount),                       //  output,   width = 1,      .burstcount
		.m0_byteenable    (emif_mmr_byteenable),                       //  output,   width = 4,      .byteenable
		.m0_debugaccess   (emif_mmr_debugaccess),                      //  output,   width = 1,      .debugaccess
		.m0_read          (emif_mmr_read),                             //  output,   width = 1,      .read
		.m0_readdata      (emif_mmr_readdata),                         //   input,  width = 32,      .readdata
		.m0_readdatavalid (emif_mmr_readdatavalid),                    //   input,   width = 1,      .readdatavalid
		.m0_waitrequest   (emif_mmr_waitrequest),                      //   input,   width = 1,      .waitrequest
		.m0_write         (emif_mmr_write),                            //  output,   width = 1,      .write
		.m0_writedata     (emif_mmr_writedata),                        //  output,  width = 32,      .writedata
		.reset            (~ddr_emif_reset_in_out_reset_reset),        //   input,   width = 1, reset.reset
		.s0_address       (mm_interconnect_0_mm_mmr_s0_address),       //   input,  width = 10,    s0.address
		.s0_burstcount    (mm_interconnect_0_mm_mmr_s0_burstcount),    //   input,   width = 1,      .burstcount
		.s0_byteenable    (mm_interconnect_0_mm_mmr_s0_byteenable),    //   input,   width = 4,      .byteenable
		.s0_debugaccess   (mm_interconnect_0_mm_mmr_s0_debugaccess),   //   input,   width = 1,      .debugaccess
		.s0_read          (mm_interconnect_0_mm_mmr_s0_read),          //   input,   width = 1,      .read
		.s0_readdata      (mm_interconnect_0_mm_mmr_s0_readdata),      //  output,  width = 32,      .readdata
		.s0_readdatavalid (mm_interconnect_0_mm_mmr_s0_readdatavalid), //  output,   width = 1,      .readdatavalid
		.s0_waitrequest   (mm_interconnect_0_mm_mmr_s0_waitrequest),   //  output,   width = 1,      .waitrequest
		.s0_write         (mm_interconnect_0_mm_mmr_s0_write),         //   input,   width = 1,      .write
		.s0_writedata     (mm_interconnect_0_mm_mmr_s0_writedata)      //   input,  width = 32,      .writedata
	);

	rst_mm_4 rst_misc_sa (
		.clk         (clk_misc_sa_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset_n  (rst_misc_sa_reset_n),         //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (rst_misc_sa_out_reset_reset)  //  output,  width = 1, out_reset.reset_n
	);

	ddr_emif_reset_in_1 rst_mm_0 (
		.clk         (clk_mm_0_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset_n  (rst_mm_0_reset_n),         //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (rst_mm_0_out_reset_reset)  //  output,  width = 1, out_reset.reset_n
	);

	rst_mm_1 rst_mm_1 (
		.clk         (clk_mm_1_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset_n  (rst_mm_1_reset_n),         //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (rst_mm_1_out_reset_reset)  //  output,  width = 1, out_reset.reset_n
	);

	rst_mm_2 rst_mm_2 (
		.clk         (clk_mm_2_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset_n  (rst_mm_2_reset_n),         //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (rst_mm_2_out_reset_reset)  //  output,  width = 1, out_reset.reset_n
	);

	rst_mm_3 rst_mm_3 (
		.clk         (clk_mm_3_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset_n  (rst_mm_3_reset_n),         //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (rst_mm_3_out_reset_reset)  //  output,  width = 1, out_reset.reset_n
	);

	fpt_ddr4_nw_altera_mm_interconnect_1920_updnsey mm_interconnect_0 (
		.clkx_0_m0_address                           (clkx_0_m0_address),                           //   input,   width = 32,                             clkx_0_m0.address
		.clkx_0_m0_waitrequest                       (clkx_0_m0_waitrequest),                       //  output,    width = 1,                                      .waitrequest
		.clkx_0_m0_burstcount                        (clkx_0_m0_burstcount),                        //   input,    width = 4,                                      .burstcount
		.clkx_0_m0_byteenable                        (clkx_0_m0_byteenable),                        //   input,   width = 32,                                      .byteenable
		.clkx_0_m0_read                              (clkx_0_m0_read),                              //   input,    width = 1,                                      .read
		.clkx_0_m0_readdata                          (clkx_0_m0_readdata),                          //  output,  width = 256,                                      .readdata
		.clkx_0_m0_readdatavalid                     (clkx_0_m0_readdatavalid),                     //  output,    width = 1,                                      .readdatavalid
		.clkx_0_m0_write                             (clkx_0_m0_write),                             //   input,    width = 1,                                      .write
		.clkx_0_m0_writedata                         (clkx_0_m0_writedata),                         //   input,  width = 256,                                      .writedata
		.clkx_0_m0_debugaccess                       (clkx_0_m0_debugaccess),                       //   input,    width = 1,                                      .debugaccess
		.clkx_1_m0_address                           (clkx_1_m0_address),                           //   input,   width = 32,                             clkx_1_m0.address
		.clkx_1_m0_waitrequest                       (clkx_1_m0_waitrequest),                       //  output,    width = 1,                                      .waitrequest
		.clkx_1_m0_burstcount                        (clkx_1_m0_burstcount),                        //   input,    width = 4,                                      .burstcount
		.clkx_1_m0_byteenable                        (clkx_1_m0_byteenable),                        //   input,   width = 32,                                      .byteenable
		.clkx_1_m0_read                              (clkx_1_m0_read),                              //   input,    width = 1,                                      .read
		.clkx_1_m0_readdata                          (clkx_1_m0_readdata),                          //  output,  width = 256,                                      .readdata
		.clkx_1_m0_readdatavalid                     (clkx_1_m0_readdatavalid),                     //  output,    width = 1,                                      .readdatavalid
		.clkx_1_m0_write                             (clkx_1_m0_write),                             //   input,    width = 1,                                      .write
		.clkx_1_m0_writedata                         (clkx_1_m0_writedata),                         //   input,  width = 256,                                      .writedata
		.clkx_1_m0_debugaccess                       (clkx_1_m0_debugaccess),                       //   input,    width = 1,                                      .debugaccess
		.clkx_2_m0_address                           (clkx_2_m0_address),                           //   input,   width = 32,                             clkx_2_m0.address
		.clkx_2_m0_waitrequest                       (clkx_2_m0_waitrequest),                       //  output,    width = 1,                                      .waitrequest
		.clkx_2_m0_burstcount                        (clkx_2_m0_burstcount),                        //   input,    width = 4,                                      .burstcount
		.clkx_2_m0_byteenable                        (clkx_2_m0_byteenable),                        //   input,   width = 32,                                      .byteenable
		.clkx_2_m0_read                              (clkx_2_m0_read),                              //   input,    width = 1,                                      .read
		.clkx_2_m0_readdata                          (clkx_2_m0_readdata),                          //  output,  width = 256,                                      .readdata
		.clkx_2_m0_readdatavalid                     (clkx_2_m0_readdatavalid),                     //  output,    width = 1,                                      .readdatavalid
		.clkx_2_m0_write                             (clkx_2_m0_write),                             //   input,    width = 1,                                      .write
		.clkx_2_m0_writedata                         (clkx_2_m0_writedata),                         //   input,  width = 256,                                      .writedata
		.clkx_2_m0_debugaccess                       (clkx_2_m0_debugaccess),                       //   input,    width = 1,                                      .debugaccess
		.clkx_3_m0_address                           (clkx_3_m0_address),                           //   input,   width = 32,                             clkx_3_m0.address
		.clkx_3_m0_waitrequest                       (clkx_3_m0_waitrequest),                       //  output,    width = 1,                                      .waitrequest
		.clkx_3_m0_burstcount                        (clkx_3_m0_burstcount),                        //   input,    width = 4,                                      .burstcount
		.clkx_3_m0_byteenable                        (clkx_3_m0_byteenable),                        //   input,   width = 32,                                      .byteenable
		.clkx_3_m0_read                              (clkx_3_m0_read),                              //   input,    width = 1,                                      .read
		.clkx_3_m0_readdata                          (clkx_3_m0_readdata),                          //  output,  width = 256,                                      .readdata
		.clkx_3_m0_readdatavalid                     (clkx_3_m0_readdatavalid),                     //  output,    width = 1,                                      .readdatavalid
		.clkx_3_m0_write                             (clkx_3_m0_write),                             //   input,    width = 1,                                      .write
		.clkx_3_m0_writedata                         (clkx_3_m0_writedata),                         //   input,  width = 256,                                      .writedata
		.clkx_3_m0_debugaccess                       (clkx_3_m0_debugaccess),                       //   input,    width = 1,                                      .debugaccess
		.clkx_4_m0_address                           (clkx_4_m0_address),                           //   input,   width = 33,                             clkx_4_m0.address
		.clkx_4_m0_waitrequest                       (clkx_4_m0_waitrequest),                       //  output,    width = 1,                                      .waitrequest
		.clkx_4_m0_burstcount                        (clkx_4_m0_burstcount),                        //   input,    width = 1,                                      .burstcount
		.clkx_4_m0_byteenable                        (clkx_4_m0_byteenable),                        //   input,    width = 4,                                      .byteenable
		.clkx_4_m0_read                              (clkx_4_m0_read),                              //   input,    width = 1,                                      .read
		.clkx_4_m0_readdata                          (clkx_4_m0_readdata),                          //  output,   width = 32,                                      .readdata
		.clkx_4_m0_readdatavalid                     (clkx_4_m0_readdatavalid),                     //  output,    width = 1,                                      .readdatavalid
		.clkx_4_m0_write                             (clkx_4_m0_write),                             //   input,    width = 1,                                      .write
		.clkx_4_m0_writedata                         (clkx_4_m0_writedata),                         //   input,   width = 32,                                      .writedata
		.clkx_4_m0_debugaccess                       (clkx_4_m0_debugaccess),                       //   input,    width = 1,                                      .debugaccess
		.ddr4_amm_s0_address                         (mm_interconnect_0_ddr4_amm_s0_address),       //  output,   width = 26,                           ddr4_amm_s0.address
		.ddr4_amm_s0_write                           (mm_interconnect_0_ddr4_amm_s0_write),         //  output,    width = 1,                                      .write
		.ddr4_amm_s0_read                            (mm_interconnect_0_ddr4_amm_s0_read),          //  output,    width = 1,                                      .read
		.ddr4_amm_s0_readdata                        (mm_interconnect_0_ddr4_amm_s0_readdata),      //   input,  width = 512,                                      .readdata
		.ddr4_amm_s0_writedata                       (mm_interconnect_0_ddr4_amm_s0_writedata),     //  output,  width = 512,                                      .writedata
		.ddr4_amm_s0_burstcount                      (mm_interconnect_0_ddr4_amm_s0_burstcount),    //  output,    width = 7,                                      .burstcount
		.ddr4_amm_s0_byteenable                      (mm_interconnect_0_ddr4_amm_s0_byteenable),    //  output,   width = 64,                                      .byteenable
		.ddr4_amm_s0_readdatavalid                   (mm_interconnect_0_ddr4_amm_s0_readdatavalid), //   input,    width = 1,                                      .readdatavalid
		.ddr4_amm_s0_waitrequest                     (mm_interconnect_0_ddr4_amm_s0_waitrequest),   //   input,    width = 1,                                      .waitrequest
		.ddr4_amm_s0_debugaccess                     (mm_interconnect_0_ddr4_amm_s0_debugaccess),   //  output,    width = 1,                                      .debugaccess
		.mm_mmr_s0_address                           (mm_interconnect_0_mm_mmr_s0_address),         //  output,   width = 10,                             mm_mmr_s0.address
		.mm_mmr_s0_write                             (mm_interconnect_0_mm_mmr_s0_write),           //  output,    width = 1,                                      .write
		.mm_mmr_s0_read                              (mm_interconnect_0_mm_mmr_s0_read),            //  output,    width = 1,                                      .read
		.mm_mmr_s0_readdata                          (mm_interconnect_0_mm_mmr_s0_readdata),        //   input,   width = 32,                                      .readdata
		.mm_mmr_s0_writedata                         (mm_interconnect_0_mm_mmr_s0_writedata),       //  output,   width = 32,                                      .writedata
		.mm_mmr_s0_burstcount                        (mm_interconnect_0_mm_mmr_s0_burstcount),      //  output,    width = 1,                                      .burstcount
		.mm_mmr_s0_byteenable                        (mm_interconnect_0_mm_mmr_s0_byteenable),      //  output,    width = 4,                                      .byteenable
		.mm_mmr_s0_readdatavalid                     (mm_interconnect_0_mm_mmr_s0_readdatavalid),   //   input,    width = 1,                                      .readdatavalid
		.mm_mmr_s0_waitrequest                       (mm_interconnect_0_mm_mmr_s0_waitrequest),     //   input,    width = 1,                                      .waitrequest
		.mm_mmr_s0_debugaccess                       (mm_interconnect_0_mm_mmr_s0_debugaccess),     //  output,    width = 1,                                      .debugaccess
		.clkx_0_m0_reset_reset_bridge_in_reset_reset (~ddr_emif_reset_in_out_reset_reset),          //   input,    width = 1, clkx_0_m0_reset_reset_bridge_in_reset.reset
		.ddr_emif_usr_clk_out_clk_clk                (ddr_emif_usr_clk_out_clk_clk)                 //   input,    width = 1,              ddr_emif_usr_clk_out_clk.clk
	);

	fpt_ddr4_nw_altera_mm_interconnect_1920_sxos7si mm_interconnect_5 (
		.mm_misc_sa_m0_address                        (mm_misc_sa_m0_address),                     //   input,   width = 34,                          mm_misc_sa_m0.address
		.mm_misc_sa_m0_waitrequest                    (mm_misc_sa_m0_waitrequest),                 //  output,    width = 1,                                       .waitrequest
		.mm_misc_sa_m0_burstcount                     (mm_misc_sa_m0_burstcount),                  //   input,    width = 4,                                       .burstcount
		.mm_misc_sa_m0_byteenable                     (mm_misc_sa_m0_byteenable),                  //   input,   width = 32,                                       .byteenable
		.mm_misc_sa_m0_read                           (mm_misc_sa_m0_read),                        //   input,    width = 1,                                       .read
		.mm_misc_sa_m0_readdata                       (mm_misc_sa_m0_readdata),                    //  output,  width = 256,                                       .readdata
		.mm_misc_sa_m0_readdatavalid                  (mm_misc_sa_m0_readdatavalid),               //  output,    width = 1,                                       .readdatavalid
		.mm_misc_sa_m0_write                          (mm_misc_sa_m0_write),                       //   input,    width = 1,                                       .write
		.mm_misc_sa_m0_writedata                      (mm_misc_sa_m0_writedata),                   //   input,  width = 256,                                       .writedata
		.mm_misc_sa_m0_debugaccess                    (mm_misc_sa_m0_debugaccess),                 //   input,    width = 1,                                       .debugaccess
		.clkx_4_s0_address                            (mm_interconnect_5_clkx_4_s0_address),       //  output,   width = 33,                              clkx_4_s0.address
		.clkx_4_s0_write                              (mm_interconnect_5_clkx_4_s0_write),         //  output,    width = 1,                                       .write
		.clkx_4_s0_read                               (mm_interconnect_5_clkx_4_s0_read),          //  output,    width = 1,                                       .read
		.clkx_4_s0_readdata                           (mm_interconnect_5_clkx_4_s0_readdata),      //   input,   width = 32,                                       .readdata
		.clkx_4_s0_writedata                          (mm_interconnect_5_clkx_4_s0_writedata),     //  output,   width = 32,                                       .writedata
		.clkx_4_s0_burstcount                         (mm_interconnect_5_clkx_4_s0_burstcount),    //  output,    width = 1,                                       .burstcount
		.clkx_4_s0_byteenable                         (mm_interconnect_5_clkx_4_s0_byteenable),    //  output,    width = 4,                                       .byteenable
		.clkx_4_s0_readdatavalid                      (mm_interconnect_5_clkx_4_s0_readdatavalid), //   input,    width = 1,                                       .readdatavalid
		.clkx_4_s0_waitrequest                        (mm_interconnect_5_clkx_4_s0_waitrequest),   //   input,    width = 1,                                       .waitrequest
		.clkx_4_s0_debugaccess                        (mm_interconnect_5_clkx_4_s0_debugaccess),   //  output,    width = 1,                                       .debugaccess
		.mm_csr_s0_address                            (mm_interconnect_5_mm_csr_s0_address),       //  output,   width = 11,                              mm_csr_s0.address
		.mm_csr_s0_write                              (mm_interconnect_5_mm_csr_s0_write),         //  output,    width = 1,                                       .write
		.mm_csr_s0_read                               (mm_interconnect_5_mm_csr_s0_read),          //  output,    width = 1,                                       .read
		.mm_csr_s0_readdata                           (mm_interconnect_5_mm_csr_s0_readdata),      //   input,   width = 32,                                       .readdata
		.mm_csr_s0_writedata                          (mm_interconnect_5_mm_csr_s0_writedata),     //  output,   width = 32,                                       .writedata
		.mm_csr_s0_burstcount                         (mm_interconnect_5_mm_csr_s0_burstcount),    //  output,    width = 4,                                       .burstcount
		.mm_csr_s0_byteenable                         (mm_interconnect_5_mm_csr_s0_byteenable),    //  output,    width = 4,                                       .byteenable
		.mm_csr_s0_readdatavalid                      (mm_interconnect_5_mm_csr_s0_readdatavalid), //   input,    width = 1,                                       .readdatavalid
		.mm_csr_s0_waitrequest                        (mm_interconnect_5_mm_csr_s0_waitrequest),   //   input,    width = 1,                                       .waitrequest
		.mm_csr_s0_debugaccess                        (mm_interconnect_5_mm_csr_s0_debugaccess),   //  output,    width = 1,                                       .debugaccess
		.mm_misc_sa_reset_reset_bridge_in_reset_reset (~rst_misc_sa_out_reset_reset),              //   input,    width = 1, mm_misc_sa_reset_reset_bridge_in_reset.reset
		.clk_misc_sa_out_clk_clk                      (clk_misc_sa_out_clk_clk)                    //   input,    width = 1,                    clk_misc_sa_out_clk.clk
	);

endmodule
