// fpt_ddr4_nw_clock_in.v

// Generated using ACDS version 20.3 158

`timescale 1 ps / 1 ps
module fpt_ddr4_nw_clock_in (
		input  wire  in_clk,  //  in_clk.clk
		output wire  out_clk  // out_clk.clk
	);

	assign out_clk = in_clk;

endmodule
