//////////////////////////////////////////////////////////////////////
//
//                      Automated Memory Wrappers Creator
//
//                                      & 
//
//////////////////////////////////////////////////////////////////////
`include        "hlp_fwd_mem.def"
module hlp_fwd_tcam_mems 
// Interface
(

// Module inputs

   input                                          DFTMASK                                 ,   
   input                                          DFTSHIFTEN                              ,   
   input                                          DFT_AFD_RESET_B                         ,   
   input                                          DFT_ARRAY_FREEZE                        ,   
   input                                          clk                                     ,   
   input                                          fary_ffuse_tcam_sleep                   ,   
   input                                   [15:0] fary_ffuse_tune_tcam                    ,   
   input                                          fary_isolation_control_in               ,   
   input                                          fary_output_reset                       ,   
   input                                          fary_pwren_b_tcam                       ,   
`ifdef HLP_FPGA_TCAM_MEMS
   input                                          fpga_fast_clk                           ,   
`endif
   input                                          fscan_clkungate                         ,   
   input                                          fscan_mode                              ,   
   input                                          fscan_ram_bypsel_tcam                   ,   
   input                                          fscan_ram_init_en                       ,   
   input                                          fscan_ram_init_val                      ,   
   input                                          fscan_ram_rdis_b                        ,   
   input                                          fscan_ram_wdis_b                        ,   
   input                                          fscan_shiften                           ,   
   input                                          fsta_dfxact_afd                         ,   
   input [`HLP_FWD_MA_TABLE_TCAM_TO_TCAM_WIDTH-1:0] fwd_ma_table_tcam_0_to_tcam             ,   
   input [`HLP_FWD_MA_TABLE_TCAM_TO_TCAM_WIDTH-1:0] fwd_ma_table_tcam_1_to_tcam             ,   
   input [`HLP_FWD_MA_TABLE_TCAM_TO_TCAM_WIDTH-1:0] fwd_ma_table_tcam_2_to_tcam             ,   
   input [`HLP_FWD_MA_TABLE_TCAM_TO_TCAM_WIDTH-1:0] fwd_ma_table_tcam_3_to_tcam             ,   
   input                                          ip_reset_b                              ,

// Module outputs

  output                                          aary_pwren_b_tcam                       ,   
  output [`HLP_FWD_MA_TABLE_TCAM_FROM_TCAM_WIDTH-1:0] fwd_ma_table_tcam_0_from_tcam           ,   
  output [`HLP_FWD_MA_TABLE_TCAM_FROM_TCAM_WIDTH-1:0] fwd_ma_table_tcam_1_from_tcam           ,   
  output [`HLP_FWD_MA_TABLE_TCAM_FROM_TCAM_WIDTH-1:0] fwd_ma_table_tcam_2_from_tcam           ,   
  output [`HLP_FWD_MA_TABLE_TCAM_FROM_TCAM_WIDTH-1:0] fwd_ma_table_tcam_3_from_tcam             
   , input wire BIST_SETUP, input wire BIST_SETUP_ts1, 
   input wire BIST_SETUP_ts2, input wire to_interfaces_tck, 
   input wire mcp_bounding_to_en, input wire scan_to_en, 
   input wire memory_bypass_to_en, input wire GO_ID_REG_SEL, 
   input wire BIST_CLEAR_BIRA, input wire BIST_COLLAR_DIAG_EN, 
   input wire BIST_COLLAR_BIRA_EN, input wire BIST_SHIFT_BIRA_COLLAR, 
   input wire CHECK_REPAIR_NEEDED, input wire MEM0_BIST_COLLAR_SI, 
   input wire MEM1_BIST_COLLAR_SI, input wire MEM2_BIST_COLLAR_SI, 
   input wire MEM3_BIST_COLLAR_SI, input wire MEM4_BIST_COLLAR_SI, 
   input wire MEM5_BIST_COLLAR_SI, input wire MEM6_BIST_COLLAR_SI, 
   input wire MEM7_BIST_COLLAR_SI, output wire BIST_SO, 
   output wire BIST_SO_ts1, output wire BIST_SO_ts2, output wire BIST_SO_ts3, 
   output wire BIST_SO_ts4, output wire BIST_SO_ts5, output wire BIST_SO_ts6, 
   output wire BIST_SO_ts7, output wire BIST_GO, output wire BIST_GO_ts1, 
   output wire BIST_GO_ts2, output wire BIST_GO_ts3, output wire BIST_GO_ts4, 
   output wire BIST_GO_ts5, output wire BIST_GO_ts6, output wire BIST_GO_ts7, 
   input wire ltest_to_en, input wire BIST_USER9, input wire BIST_USER10, 
   input wire BIST_USER11, input wire BIST_USER0, input wire BIST_USER1, 
   input wire BIST_USER2, input wire BIST_USER3, input wire BIST_USER4, 
   input wire BIST_USER5, input wire BIST_USER6, input wire BIST_USER7, 
   input wire BIST_USER8, input wire BIST_EVEN_GROUPWRITEENABLE, 
   input wire BIST_ODD_GROUPWRITEENABLE, input wire BIST_WRITEENABLE, 
   input wire BIST_READENABLE, input wire BIST_SELECT, input wire BIST_CMP, 
   input wire INCLUDE_MEM_RESULTS_REG, input wire BIST_COL_ADD, 
   input wire BIST_ROW_ADD, input wire BIST_ROW_ADD_ts1, 
   input wire BIST_ROW_ADD_ts2, input wire BIST_ROW_ADD_ts3, 
   input wire BIST_ROW_ADD_ts4, input wire BIST_ROW_ADD_ts5, 
   input wire BIST_BANK_ADD, input wire BIST_BANK_ADD_ts1, 
   input wire BIST_BANK_ADD_ts2, input wire BIST_COLLAR_EN0, 
   input wire BIST_COLLAR_EN1, input wire BIST_COLLAR_EN2, 
   input wire BIST_COLLAR_EN3, input wire BIST_COLLAR_EN4, 
   input wire BIST_COLLAR_EN5, input wire BIST_COLLAR_EN6, 
   input wire BIST_COLLAR_EN7, input wire BIST_RUN_TO_COLLAR0, 
   input wire BIST_RUN_TO_COLLAR1, input wire BIST_RUN_TO_COLLAR2, 
   input wire BIST_RUN_TO_COLLAR3, input wire BIST_RUN_TO_COLLAR4, 
   input wire BIST_RUN_TO_COLLAR5, input wire BIST_RUN_TO_COLLAR6, 
   input wire BIST_RUN_TO_COLLAR7, input wire BIST_ASYNC_RESET, 
   input wire BIST_TESTDATA_SELECT_TO_COLLAR, input wire BIST_ON_TO_COLLAR, 
   input wire BIST_WRITE_DATA, input wire BIST_WRITE_DATA_ts1, 
   input wire BIST_WRITE_DATA_ts2, input wire BIST_WRITE_DATA_ts3, 
   input wire BIST_WRITE_DATA_ts4, input wire BIST_WRITE_DATA_ts5, 
   input wire BIST_WRITE_DATA_ts6, input wire BIST_WRITE_DATA_ts7, 
   input wire BIST_WRITE_DATA_ts8, input wire BIST_WRITE_DATA_ts9, 
   input wire BIST_WRITE_DATA_ts10, input wire BIST_WRITE_DATA_ts11, 
   input wire BIST_WRITE_DATA_ts12, input wire BIST_WRITE_DATA_ts13, 
   input wire BIST_WRITE_DATA_ts14, input wire BIST_WRITE_DATA_ts15, 
   input wire BIST_WRITE_DATA_ts16, input wire BIST_WRITE_DATA_ts17, 
   input wire BIST_WRITE_DATA_ts18, input wire BIST_WRITE_DATA_ts19, 
   input wire BIST_WRITE_DATA_ts20, input wire BIST_WRITE_DATA_ts21, 
   input wire BIST_WRITE_DATA_ts22, input wire BIST_WRITE_DATA_ts23, 
   input wire BIST_WRITE_DATA_ts24, input wire BIST_WRITE_DATA_ts25, 
   input wire BIST_WRITE_DATA_ts26, input wire BIST_WRITE_DATA_ts27, 
   input wire BIST_WRITE_DATA_ts28, input wire BIST_WRITE_DATA_ts29, 
   input wire BIST_WRITE_DATA_ts30, input wire BIST_WRITE_DATA_ts31, 
   input wire BIST_EXPECT_DATA, input wire BIST_EXPECT_DATA_ts1, 
   input wire BIST_EXPECT_DATA_ts2, input wire BIST_EXPECT_DATA_ts3, 
   input wire BIST_EXPECT_DATA_ts4, input wire BIST_EXPECT_DATA_ts5, 
   input wire BIST_EXPECT_DATA_ts6, input wire BIST_EXPECT_DATA_ts7, 
   input wire BIST_EXPECT_DATA_ts8, input wire BIST_EXPECT_DATA_ts9, 
   input wire BIST_EXPECT_DATA_ts10, input wire BIST_EXPECT_DATA_ts11, 
   input wire BIST_EXPECT_DATA_ts12, input wire BIST_EXPECT_DATA_ts13, 
   input wire BIST_EXPECT_DATA_ts14, input wire BIST_EXPECT_DATA_ts15, 
   input wire BIST_EXPECT_DATA_ts16, input wire BIST_EXPECT_DATA_ts17, 
   input wire BIST_EXPECT_DATA_ts18, input wire BIST_EXPECT_DATA_ts19, 
   input wire BIST_EXPECT_DATA_ts20, input wire BIST_EXPECT_DATA_ts21, 
   input wire BIST_EXPECT_DATA_ts22, input wire BIST_EXPECT_DATA_ts23, 
   input wire BIST_EXPECT_DATA_ts24, input wire BIST_EXPECT_DATA_ts25, 
   input wire BIST_EXPECT_DATA_ts26, input wire BIST_EXPECT_DATA_ts27, 
   input wire BIST_EXPECT_DATA_ts28, input wire BIST_EXPECT_DATA_ts29, 
   input wire BIST_EXPECT_DATA_ts30, input wire BIST_EXPECT_DATA_ts31, 
   input wire BIST_SHIFT_COLLAR, input wire BIST_COLLAR_SETUP, 
   input wire BIST_CLEAR_DEFAULT, input wire BIST_CLEAR, 
   input wire BIST_COLLAR_OPSET_SELECT, 
   input wire BIST_COLLAR_OPSET_SELECT_ts1, input wire BIST_COLLAR_HOLD, 
   input wire FREEZE_STOP_ERROR, input wire ERROR_CNT_ZERO, 
   input wire MBISTPG_RESET_REG_SETUP2, input wire bisr_shift_en_pd_vinf, 
   input wire bisr_clk_pd_vinf, input wire bisr_reset_pd_vinf, 
   input wire ram_row_0_col_0_bisr_inst_SO, 
   output wire tcam_row_1_col_0_bisr_inst_SO_ts3);

genvar iter;


// Instances


  wire tcam_row_1_col_0_bisr_inst_SO, tcam_row_1_col_0_bisr_inst_SO_ts1, 
       tcam_row_1_col_0_bisr_inst_SO_ts2;
hlp_fwd_wrap_tcam_ma_table_tcam_shell_1024x35  #( // Parameters
    .TCAM_PATRN1_EXP_RESET_VALUE( ),
    .FROM_TCAM_WIDTH(`HLP_FWD_MA_TABLE_TCAM_FROM_TCAM_WIDTH),
    .TCAM_INIT_TYPE(1),
    .TCAM_E0_INIT_VALUE(35'h0),
    .NFUSERED_TCAM(7),
    .TO_TCAM_WIDTH(`HLP_FWD_MA_TABLE_TCAM_TO_TCAM_WIDTH),
    .WRAPPER_COL_REPAIR(1),
    .TCAM_WIDTH(35),
    .TCAM_PROTECTION_TYPE(0),
    .TCAM_E1_INIT_VALUE(35'h0),
    .TCAM_SLICE_SIZE(64),
    .FPGA_MARGIN(0),
    .TCAM_PATRN0_EXP_RESET_VALUE( ),
    .FPGA_CLOCKS_RATIO(100),
    .TOTAL_MEMORY_INSTANCE(2),
    .TCAM_RULES_NUM(1024),
    .BCAM_RELIEF(0)
) fwd_wrap_tcam_ma_table_tcam_shell_1024x35_0(
        .clk(clk),
`ifdef HLP_FPGA_TCAM_MEMS
        .fpga_fast_clk(fpga_fast_clk),
`endif
        .wrap_shell_to_tcam(fwd_ma_table_tcam_0_to_tcam),
        .wrap_shell_from_tcam(fwd_ma_table_tcam_0_from_tcam),
        .fscan_mode(fscan_mode),
        .fscan_clkungate(fscan_clkungate),
        .fscan_shiften(fscan_shiften),
        .fary_ffuse_tune_tcam(fary_ffuse_tune_tcam),
        .fary_output_reset(fary_output_reset),
        .fary_isolation_control_in(fary_isolation_control_in),
        .fary_ffuse_tcam_sleep(fary_ffuse_tcam_sleep),
        .fsta_dfxact_afd(fsta_dfxact_afd),
        .ip_reset_b(ip_reset_b),
        .fscan_ram_bypsel_tcam(fscan_ram_bypsel_tcam),
        .fscan_ram_init_en(fscan_ram_init_en),
        .fscan_ram_init_val(fscan_ram_init_val),
        .fscan_ram_rdis_b(fscan_ram_rdis_b),
        .fscan_ram_wdis_b(fscan_ram_wdis_b),
        .DFTSHIFTEN(DFTSHIFTEN),
        .DFTMASK(DFTMASK),
        .DFT_ARRAY_FREEZE(DFT_ARRAY_FREEZE),
        .DFT_AFD_RESET_B(DFT_AFD_RESET_B),
        .fary_pwren_b_tcam(fary_pwren_b_tcam),
        .aary_pwren_b_tcam(aary_pwren_b_tcam), .BIST_SETUP(BIST_SETUP), 
                        .BIST_SETUP_ts1(BIST_SETUP_ts1), .BIST_SETUP_ts2(BIST_SETUP_ts2), 
                        .to_interfaces_tck(to_interfaces_tck), 
                        .mcp_bounding_to_en(mcp_bounding_to_en), .scan_to_en(scan_to_en), 
                        .memory_bypass_to_en(memory_bypass_to_en), 
                        .GO_ID_REG_SEL(GO_ID_REG_SEL), .BIST_CLEAR_BIRA(BIST_CLEAR_BIRA), 
                        .BIST_COLLAR_DIAG_EN(BIST_COLLAR_DIAG_EN), 
                        .BIST_COLLAR_BIRA_EN(BIST_COLLAR_BIRA_EN), 
                        .BIST_SHIFT_BIRA_COLLAR(BIST_SHIFT_BIRA_COLLAR), 
                        .CHECK_REPAIR_NEEDED(CHECK_REPAIR_NEEDED), 
                        .MEM0_BIST_COLLAR_SI(MEM0_BIST_COLLAR_SI), 
                        .MEM4_BIST_COLLAR_SI(MEM4_BIST_COLLAR_SI), .BIST_SO(BIST_SO), 
                        .BIST_SO_ts1(BIST_SO_ts4), .BIST_GO(BIST_GO), 
                        .BIST_GO_ts1(BIST_GO_ts4), .ltest_to_en(ltest_to_en), 
                        .BIST_USER9(BIST_USER9), .BIST_USER10(BIST_USER10), 
                        .BIST_USER11(BIST_USER11), .BIST_USER0(BIST_USER0), 
                        .BIST_USER1(BIST_USER1), .BIST_USER2(BIST_USER2), 
                        .BIST_USER3(BIST_USER3), .BIST_USER4(BIST_USER4), 
                        .BIST_USER5(BIST_USER5), .BIST_USER6(BIST_USER6), 
                        .BIST_USER7(BIST_USER7), .BIST_USER8(BIST_USER8), 
                        .BIST_EVEN_GROUPWRITEENABLE(BIST_EVEN_GROUPWRITEENABLE), 
                        .BIST_ODD_GROUPWRITEENABLE(BIST_ODD_GROUPWRITEENABLE), 
                        .BIST_WRITEENABLE(BIST_WRITEENABLE), .BIST_READENABLE(BIST_READENABLE), 
                        .BIST_SELECT(BIST_SELECT), .BIST_CMP(BIST_CMP), 
                        .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), 
                        .BIST_COL_ADD(BIST_COL_ADD), .BIST_ROW_ADD(BIST_ROW_ADD), 
                        .BIST_ROW_ADD_ts1(BIST_ROW_ADD_ts1), 
                        .BIST_ROW_ADD_ts2(BIST_ROW_ADD_ts2), 
                        .BIST_ROW_ADD_ts3(BIST_ROW_ADD_ts3), 
                        .BIST_ROW_ADD_ts4(BIST_ROW_ADD_ts4), 
                        .BIST_ROW_ADD_ts5(BIST_ROW_ADD_ts5), .BIST_BANK_ADD(BIST_BANK_ADD), 
                        .BIST_BANK_ADD_ts1(BIST_BANK_ADD_ts1), 
                        .BIST_BANK_ADD_ts2(BIST_BANK_ADD_ts2), 
                        .BIST_COLLAR_EN0(BIST_COLLAR_EN0), .BIST_COLLAR_EN4(BIST_COLLAR_EN4), 
                        .BIST_RUN_TO_COLLAR0(BIST_RUN_TO_COLLAR0), 
                        .BIST_RUN_TO_COLLAR4(BIST_RUN_TO_COLLAR4), 
                        .BIST_ASYNC_RESET(BIST_ASYNC_RESET), 
                        .BIST_TESTDATA_SELECT_TO_COLLAR(BIST_TESTDATA_SELECT_TO_COLLAR), 
                        .BIST_ON_TO_COLLAR(BIST_ON_TO_COLLAR), 
                        .BIST_WRITE_DATA(BIST_WRITE_DATA), 
                        .BIST_WRITE_DATA_ts1(BIST_WRITE_DATA_ts1), 
                        .BIST_WRITE_DATA_ts2(BIST_WRITE_DATA_ts2), 
                        .BIST_WRITE_DATA_ts3(BIST_WRITE_DATA_ts3), 
                        .BIST_WRITE_DATA_ts4(BIST_WRITE_DATA_ts4), 
                        .BIST_WRITE_DATA_ts5(BIST_WRITE_DATA_ts5), 
                        .BIST_WRITE_DATA_ts6(BIST_WRITE_DATA_ts6), 
                        .BIST_WRITE_DATA_ts7(BIST_WRITE_DATA_ts7), 
                        .BIST_WRITE_DATA_ts8(BIST_WRITE_DATA_ts8), 
                        .BIST_WRITE_DATA_ts9(BIST_WRITE_DATA_ts9), 
                        .BIST_WRITE_DATA_ts10(BIST_WRITE_DATA_ts10), 
                        .BIST_WRITE_DATA_ts11(BIST_WRITE_DATA_ts11), 
                        .BIST_WRITE_DATA_ts12(BIST_WRITE_DATA_ts12), 
                        .BIST_WRITE_DATA_ts13(BIST_WRITE_DATA_ts13), 
                        .BIST_WRITE_DATA_ts14(BIST_WRITE_DATA_ts14), 
                        .BIST_WRITE_DATA_ts15(BIST_WRITE_DATA_ts15), 
                        .BIST_WRITE_DATA_ts16(BIST_WRITE_DATA_ts16), 
                        .BIST_WRITE_DATA_ts17(BIST_WRITE_DATA_ts17), 
                        .BIST_WRITE_DATA_ts18(BIST_WRITE_DATA_ts18), 
                        .BIST_WRITE_DATA_ts19(BIST_WRITE_DATA_ts19), 
                        .BIST_WRITE_DATA_ts20(BIST_WRITE_DATA_ts20), 
                        .BIST_WRITE_DATA_ts21(BIST_WRITE_DATA_ts21), 
                        .BIST_WRITE_DATA_ts22(BIST_WRITE_DATA_ts22), 
                        .BIST_WRITE_DATA_ts23(BIST_WRITE_DATA_ts23), 
                        .BIST_WRITE_DATA_ts24(BIST_WRITE_DATA_ts24), 
                        .BIST_WRITE_DATA_ts25(BIST_WRITE_DATA_ts25), 
                        .BIST_WRITE_DATA_ts26(BIST_WRITE_DATA_ts26), 
                        .BIST_WRITE_DATA_ts27(BIST_WRITE_DATA_ts27), 
                        .BIST_WRITE_DATA_ts28(BIST_WRITE_DATA_ts28), 
                        .BIST_WRITE_DATA_ts29(BIST_WRITE_DATA_ts29), 
                        .BIST_WRITE_DATA_ts30(BIST_WRITE_DATA_ts30), 
                        .BIST_WRITE_DATA_ts31(BIST_WRITE_DATA_ts31), 
                        .BIST_EXPECT_DATA(BIST_EXPECT_DATA), 
                        .BIST_EXPECT_DATA_ts1(BIST_EXPECT_DATA_ts1), 
                        .BIST_EXPECT_DATA_ts2(BIST_EXPECT_DATA_ts2), 
                        .BIST_EXPECT_DATA_ts3(BIST_EXPECT_DATA_ts3), 
                        .BIST_EXPECT_DATA_ts4(BIST_EXPECT_DATA_ts4), 
                        .BIST_EXPECT_DATA_ts5(BIST_EXPECT_DATA_ts5), 
                        .BIST_EXPECT_DATA_ts6(BIST_EXPECT_DATA_ts6), 
                        .BIST_EXPECT_DATA_ts7(BIST_EXPECT_DATA_ts7), 
                        .BIST_EXPECT_DATA_ts8(BIST_EXPECT_DATA_ts8), 
                        .BIST_EXPECT_DATA_ts9(BIST_EXPECT_DATA_ts9), 
                        .BIST_EXPECT_DATA_ts10(BIST_EXPECT_DATA_ts10), 
                        .BIST_EXPECT_DATA_ts11(BIST_EXPECT_DATA_ts11), 
                        .BIST_EXPECT_DATA_ts12(BIST_EXPECT_DATA_ts12), 
                        .BIST_EXPECT_DATA_ts13(BIST_EXPECT_DATA_ts13), 
                        .BIST_EXPECT_DATA_ts14(BIST_EXPECT_DATA_ts14), 
                        .BIST_EXPECT_DATA_ts15(BIST_EXPECT_DATA_ts15), 
                        .BIST_EXPECT_DATA_ts16(BIST_EXPECT_DATA_ts16), 
                        .BIST_EXPECT_DATA_ts17(BIST_EXPECT_DATA_ts17), 
                        .BIST_EXPECT_DATA_ts18(BIST_EXPECT_DATA_ts18), 
                        .BIST_EXPECT_DATA_ts19(BIST_EXPECT_DATA_ts19), 
                        .BIST_EXPECT_DATA_ts20(BIST_EXPECT_DATA_ts20), 
                        .BIST_EXPECT_DATA_ts21(BIST_EXPECT_DATA_ts21), 
                        .BIST_EXPECT_DATA_ts22(BIST_EXPECT_DATA_ts22), 
                        .BIST_EXPECT_DATA_ts23(BIST_EXPECT_DATA_ts23), 
                        .BIST_EXPECT_DATA_ts24(BIST_EXPECT_DATA_ts24), 
                        .BIST_EXPECT_DATA_ts25(BIST_EXPECT_DATA_ts25), 
                        .BIST_EXPECT_DATA_ts26(BIST_EXPECT_DATA_ts26), 
                        .BIST_EXPECT_DATA_ts27(BIST_EXPECT_DATA_ts27), 
                        .BIST_EXPECT_DATA_ts28(BIST_EXPECT_DATA_ts28), 
                        .BIST_EXPECT_DATA_ts29(BIST_EXPECT_DATA_ts29), 
                        .BIST_EXPECT_DATA_ts30(BIST_EXPECT_DATA_ts30), 
                        .BIST_EXPECT_DATA_ts31(BIST_EXPECT_DATA_ts31), 
                        .BIST_SHIFT_COLLAR(BIST_SHIFT_COLLAR), 
                        .BIST_COLLAR_SETUP(BIST_COLLAR_SETUP), 
                        .BIST_CLEAR_DEFAULT(BIST_CLEAR_DEFAULT), .BIST_CLEAR(BIST_CLEAR), 
                        .BIST_COLLAR_OPSET_SELECT(BIST_COLLAR_OPSET_SELECT), 
                        .BIST_COLLAR_OPSET_SELECT_ts1(BIST_COLLAR_OPSET_SELECT_ts1), 
                        .BIST_COLLAR_HOLD(BIST_COLLAR_HOLD), 
                        .FREEZE_STOP_ERROR(FREEZE_STOP_ERROR), 
                        .ERROR_CNT_ZERO(ERROR_CNT_ZERO), 
                        .MBISTPG_RESET_REG_SETUP2(MBISTPG_RESET_REG_SETUP2), 
                        .bisr_shift_en_pd_vinf(bisr_shift_en_pd_vinf), 
                        .bisr_clk_pd_vinf(bisr_clk_pd_vinf), 
                        .bisr_reset_pd_vinf(bisr_reset_pd_vinf), 
                        .ram_row_0_col_0_bisr_inst_SO(ram_row_0_col_0_bisr_inst_SO), 
                        .tcam_row_1_col_0_bisr_inst_SO(tcam_row_1_col_0_bisr_inst_SO), 
                        .fscan_mode_ts1(fscan_mode), .fscan_mode_ts2(fscan_mode)
);

hlp_fwd_wrap_tcam_ma_table_tcam_shell_1024x35  #( // Parameters
    .TCAM_PATRN0_EXP_RESET_VALUE( ),
    .FPGA_CLOCKS_RATIO(100),
    .FPGA_MARGIN(0),
    .TCAM_RULES_NUM(1024),
    .TOTAL_MEMORY_INSTANCE(2),
    .BCAM_RELIEF(0),
    .TO_TCAM_WIDTH(`HLP_FWD_MA_TABLE_TCAM_TO_TCAM_WIDTH),
    .NFUSERED_TCAM(7),
    .TCAM_PATRN1_EXP_RESET_VALUE( ),
    .FROM_TCAM_WIDTH(`HLP_FWD_MA_TABLE_TCAM_FROM_TCAM_WIDTH),
    .TCAM_E0_INIT_VALUE(35'h0),
    .TCAM_INIT_TYPE(1),
    .WRAPPER_COL_REPAIR(1),
    .TCAM_WIDTH(35),
    .TCAM_PROTECTION_TYPE(0),
    .TCAM_SLICE_SIZE(64),
    .TCAM_E1_INIT_VALUE(35'h0)
) fwd_wrap_tcam_ma_table_tcam_shell_1024x35_1(
        .clk(clk),
`ifdef HLP_FPGA_TCAM_MEMS
        .fpga_fast_clk(fpga_fast_clk),
`endif
        .wrap_shell_to_tcam(fwd_ma_table_tcam_1_to_tcam),
        .wrap_shell_from_tcam(fwd_ma_table_tcam_1_from_tcam),
        .fscan_mode(fscan_mode),
        .fscan_clkungate(fscan_clkungate),
        .fscan_shiften(fscan_shiften),
        .fary_ffuse_tune_tcam(fary_ffuse_tune_tcam),
        .fary_output_reset(fary_output_reset),
        .fary_isolation_control_in(fary_isolation_control_in),
        .fary_ffuse_tcam_sleep(fary_ffuse_tcam_sleep),
        .fsta_dfxact_afd(fsta_dfxact_afd),
        .ip_reset_b(ip_reset_b),
        .fscan_ram_bypsel_tcam(fscan_ram_bypsel_tcam),
        .fscan_ram_init_en(fscan_ram_init_en),
        .fscan_ram_init_val(fscan_ram_init_val),
        .fscan_ram_rdis_b(fscan_ram_rdis_b),
        .fscan_ram_wdis_b(fscan_ram_wdis_b),
        .DFTSHIFTEN(DFTSHIFTEN),
        .DFTMASK(DFTMASK),
        .DFT_ARRAY_FREEZE(DFT_ARRAY_FREEZE),
        .DFT_AFD_RESET_B(DFT_AFD_RESET_B),
        .fary_pwren_b_tcam(fary_pwren_b_tcam),
        .aary_pwren_b_tcam(aary_pwren_b_tcam), .BIST_SETUP(BIST_SETUP), 
                        .BIST_SETUP_ts1(BIST_SETUP_ts1), .BIST_SETUP_ts2(BIST_SETUP_ts2), 
                        .to_interfaces_tck(to_interfaces_tck), 
                        .mcp_bounding_to_en(mcp_bounding_to_en), .scan_to_en(scan_to_en), 
                        .memory_bypass_to_en(memory_bypass_to_en), 
                        .GO_ID_REG_SEL(GO_ID_REG_SEL), .BIST_CLEAR_BIRA(BIST_CLEAR_BIRA), 
                        .BIST_COLLAR_DIAG_EN(BIST_COLLAR_DIAG_EN), 
                        .BIST_COLLAR_BIRA_EN(BIST_COLLAR_BIRA_EN), 
                        .BIST_SHIFT_BIRA_COLLAR(BIST_SHIFT_BIRA_COLLAR), 
                        .CHECK_REPAIR_NEEDED(CHECK_REPAIR_NEEDED), 
                        .MEM0_BIST_COLLAR_SI(MEM1_BIST_COLLAR_SI), 
                        .MEM4_BIST_COLLAR_SI(MEM5_BIST_COLLAR_SI), .BIST_SO(BIST_SO_ts1), 
                        .BIST_SO_ts1(BIST_SO_ts5), .BIST_GO(BIST_GO_ts1), 
                        .BIST_GO_ts1(BIST_GO_ts5), .ltest_to_en(ltest_to_en), 
                        .BIST_USER9(BIST_USER9), .BIST_USER10(BIST_USER10), 
                        .BIST_USER11(BIST_USER11), .BIST_USER0(BIST_USER0), 
                        .BIST_USER1(BIST_USER1), .BIST_USER2(BIST_USER2), 
                        .BIST_USER3(BIST_USER3), .BIST_USER4(BIST_USER4), 
                        .BIST_USER5(BIST_USER5), .BIST_USER6(BIST_USER6), 
                        .BIST_USER7(BIST_USER7), .BIST_USER8(BIST_USER8), 
                        .BIST_EVEN_GROUPWRITEENABLE(BIST_EVEN_GROUPWRITEENABLE), 
                        .BIST_ODD_GROUPWRITEENABLE(BIST_ODD_GROUPWRITEENABLE), 
                        .BIST_WRITEENABLE(BIST_WRITEENABLE), .BIST_READENABLE(BIST_READENABLE), 
                        .BIST_SELECT(BIST_SELECT), .BIST_CMP(BIST_CMP), 
                        .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), 
                        .BIST_COL_ADD(BIST_COL_ADD), .BIST_ROW_ADD(BIST_ROW_ADD), 
                        .BIST_ROW_ADD_ts1(BIST_ROW_ADD_ts1), 
                        .BIST_ROW_ADD_ts2(BIST_ROW_ADD_ts2), 
                        .BIST_ROW_ADD_ts3(BIST_ROW_ADD_ts3), 
                        .BIST_ROW_ADD_ts4(BIST_ROW_ADD_ts4), 
                        .BIST_ROW_ADD_ts5(BIST_ROW_ADD_ts5), .BIST_BANK_ADD(BIST_BANK_ADD), 
                        .BIST_BANK_ADD_ts1(BIST_BANK_ADD_ts1), 
                        .BIST_BANK_ADD_ts2(BIST_BANK_ADD_ts2), 
                        .BIST_COLLAR_EN0(BIST_COLLAR_EN1), .BIST_COLLAR_EN4(BIST_COLLAR_EN5), 
                        .BIST_RUN_TO_COLLAR0(BIST_RUN_TO_COLLAR1), 
                        .BIST_RUN_TO_COLLAR4(BIST_RUN_TO_COLLAR5), 
                        .BIST_ASYNC_RESET(BIST_ASYNC_RESET), 
                        .BIST_TESTDATA_SELECT_TO_COLLAR(BIST_TESTDATA_SELECT_TO_COLLAR), 
                        .BIST_ON_TO_COLLAR(BIST_ON_TO_COLLAR), 
                        .BIST_WRITE_DATA(BIST_WRITE_DATA), 
                        .BIST_WRITE_DATA_ts1(BIST_WRITE_DATA_ts1), 
                        .BIST_WRITE_DATA_ts2(BIST_WRITE_DATA_ts2), 
                        .BIST_WRITE_DATA_ts3(BIST_WRITE_DATA_ts3), 
                        .BIST_WRITE_DATA_ts4(BIST_WRITE_DATA_ts4), 
                        .BIST_WRITE_DATA_ts5(BIST_WRITE_DATA_ts5), 
                        .BIST_WRITE_DATA_ts6(BIST_WRITE_DATA_ts6), 
                        .BIST_WRITE_DATA_ts7(BIST_WRITE_DATA_ts7), 
                        .BIST_WRITE_DATA_ts8(BIST_WRITE_DATA_ts8), 
                        .BIST_WRITE_DATA_ts9(BIST_WRITE_DATA_ts9), 
                        .BIST_WRITE_DATA_ts10(BIST_WRITE_DATA_ts10), 
                        .BIST_WRITE_DATA_ts11(BIST_WRITE_DATA_ts11), 
                        .BIST_WRITE_DATA_ts12(BIST_WRITE_DATA_ts12), 
                        .BIST_WRITE_DATA_ts13(BIST_WRITE_DATA_ts13), 
                        .BIST_WRITE_DATA_ts14(BIST_WRITE_DATA_ts14), 
                        .BIST_WRITE_DATA_ts15(BIST_WRITE_DATA_ts15), 
                        .BIST_WRITE_DATA_ts16(BIST_WRITE_DATA_ts16), 
                        .BIST_WRITE_DATA_ts17(BIST_WRITE_DATA_ts17), 
                        .BIST_WRITE_DATA_ts18(BIST_WRITE_DATA_ts18), 
                        .BIST_WRITE_DATA_ts19(BIST_WRITE_DATA_ts19), 
                        .BIST_WRITE_DATA_ts20(BIST_WRITE_DATA_ts20), 
                        .BIST_WRITE_DATA_ts21(BIST_WRITE_DATA_ts21), 
                        .BIST_WRITE_DATA_ts22(BIST_WRITE_DATA_ts22), 
                        .BIST_WRITE_DATA_ts23(BIST_WRITE_DATA_ts23), 
                        .BIST_WRITE_DATA_ts24(BIST_WRITE_DATA_ts24), 
                        .BIST_WRITE_DATA_ts25(BIST_WRITE_DATA_ts25), 
                        .BIST_WRITE_DATA_ts26(BIST_WRITE_DATA_ts26), 
                        .BIST_WRITE_DATA_ts27(BIST_WRITE_DATA_ts27), 
                        .BIST_WRITE_DATA_ts28(BIST_WRITE_DATA_ts28), 
                        .BIST_WRITE_DATA_ts29(BIST_WRITE_DATA_ts29), 
                        .BIST_WRITE_DATA_ts30(BIST_WRITE_DATA_ts30), 
                        .BIST_WRITE_DATA_ts31(BIST_WRITE_DATA_ts31), 
                        .BIST_EXPECT_DATA(BIST_EXPECT_DATA), 
                        .BIST_EXPECT_DATA_ts1(BIST_EXPECT_DATA_ts1), 
                        .BIST_EXPECT_DATA_ts2(BIST_EXPECT_DATA_ts2), 
                        .BIST_EXPECT_DATA_ts3(BIST_EXPECT_DATA_ts3), 
                        .BIST_EXPECT_DATA_ts4(BIST_EXPECT_DATA_ts4), 
                        .BIST_EXPECT_DATA_ts5(BIST_EXPECT_DATA_ts5), 
                        .BIST_EXPECT_DATA_ts6(BIST_EXPECT_DATA_ts6), 
                        .BIST_EXPECT_DATA_ts7(BIST_EXPECT_DATA_ts7), 
                        .BIST_EXPECT_DATA_ts8(BIST_EXPECT_DATA_ts8), 
                        .BIST_EXPECT_DATA_ts9(BIST_EXPECT_DATA_ts9), 
                        .BIST_EXPECT_DATA_ts10(BIST_EXPECT_DATA_ts10), 
                        .BIST_EXPECT_DATA_ts11(BIST_EXPECT_DATA_ts11), 
                        .BIST_EXPECT_DATA_ts12(BIST_EXPECT_DATA_ts12), 
                        .BIST_EXPECT_DATA_ts13(BIST_EXPECT_DATA_ts13), 
                        .BIST_EXPECT_DATA_ts14(BIST_EXPECT_DATA_ts14), 
                        .BIST_EXPECT_DATA_ts15(BIST_EXPECT_DATA_ts15), 
                        .BIST_EXPECT_DATA_ts16(BIST_EXPECT_DATA_ts16), 
                        .BIST_EXPECT_DATA_ts17(BIST_EXPECT_DATA_ts17), 
                        .BIST_EXPECT_DATA_ts18(BIST_EXPECT_DATA_ts18), 
                        .BIST_EXPECT_DATA_ts19(BIST_EXPECT_DATA_ts19), 
                        .BIST_EXPECT_DATA_ts20(BIST_EXPECT_DATA_ts20), 
                        .BIST_EXPECT_DATA_ts21(BIST_EXPECT_DATA_ts21), 
                        .BIST_EXPECT_DATA_ts22(BIST_EXPECT_DATA_ts22), 
                        .BIST_EXPECT_DATA_ts23(BIST_EXPECT_DATA_ts23), 
                        .BIST_EXPECT_DATA_ts24(BIST_EXPECT_DATA_ts24), 
                        .BIST_EXPECT_DATA_ts25(BIST_EXPECT_DATA_ts25), 
                        .BIST_EXPECT_DATA_ts26(BIST_EXPECT_DATA_ts26), 
                        .BIST_EXPECT_DATA_ts27(BIST_EXPECT_DATA_ts27), 
                        .BIST_EXPECT_DATA_ts28(BIST_EXPECT_DATA_ts28), 
                        .BIST_EXPECT_DATA_ts29(BIST_EXPECT_DATA_ts29), 
                        .BIST_EXPECT_DATA_ts30(BIST_EXPECT_DATA_ts30), 
                        .BIST_EXPECT_DATA_ts31(BIST_EXPECT_DATA_ts31), 
                        .BIST_SHIFT_COLLAR(BIST_SHIFT_COLLAR), 
                        .BIST_COLLAR_SETUP(BIST_COLLAR_SETUP), 
                        .BIST_CLEAR_DEFAULT(BIST_CLEAR_DEFAULT), .BIST_CLEAR(BIST_CLEAR), 
                        .BIST_COLLAR_OPSET_SELECT(BIST_COLLAR_OPSET_SELECT), 
                        .BIST_COLLAR_OPSET_SELECT_ts1(BIST_COLLAR_OPSET_SELECT_ts1), 
                        .BIST_COLLAR_HOLD(BIST_COLLAR_HOLD), 
                        .FREEZE_STOP_ERROR(FREEZE_STOP_ERROR), 
                        .ERROR_CNT_ZERO(ERROR_CNT_ZERO), 
                        .MBISTPG_RESET_REG_SETUP2(MBISTPG_RESET_REG_SETUP2), 
                        .bisr_shift_en_pd_vinf(bisr_shift_en_pd_vinf), 
                        .bisr_clk_pd_vinf(bisr_clk_pd_vinf), 
                        .bisr_reset_pd_vinf(bisr_reset_pd_vinf), 
                        .ram_row_0_col_0_bisr_inst_SO(tcam_row_1_col_0_bisr_inst_SO), 
                        .tcam_row_1_col_0_bisr_inst_SO(tcam_row_1_col_0_bisr_inst_SO_ts1), 
                        .fscan_mode_ts1(fscan_mode), .fscan_mode_ts2(fscan_mode)
);

hlp_fwd_wrap_tcam_ma_table_tcam_shell_1024x35  #( // Parameters
    .BCAM_RELIEF(0),
    .TCAM_PATRN0_EXP_RESET_VALUE( ),
    .FPGA_CLOCKS_RATIO(100),
    .FPGA_MARGIN(0),
    .TCAM_RULES_NUM(1024),
    .TOTAL_MEMORY_INSTANCE(2),
    .TCAM_PROTECTION_TYPE(0),
    .TCAM_SLICE_SIZE(64),
    .TCAM_E1_INIT_VALUE(35'h0),
    .NFUSERED_TCAM(7),
    .TO_TCAM_WIDTH(`HLP_FWD_MA_TABLE_TCAM_TO_TCAM_WIDTH),
    .TCAM_PATRN1_EXP_RESET_VALUE( ),
    .TCAM_E0_INIT_VALUE(35'h0),
    .FROM_TCAM_WIDTH(`HLP_FWD_MA_TABLE_TCAM_FROM_TCAM_WIDTH),
    .TCAM_INIT_TYPE(1),
    .WRAPPER_COL_REPAIR(1),
    .TCAM_WIDTH(35)
) fwd_wrap_tcam_ma_table_tcam_shell_1024x35_2(
        .clk(clk),
`ifdef HLP_FPGA_TCAM_MEMS
        .fpga_fast_clk(fpga_fast_clk),
`endif
        .wrap_shell_to_tcam(fwd_ma_table_tcam_2_to_tcam),
        .wrap_shell_from_tcam(fwd_ma_table_tcam_2_from_tcam),
        .fscan_mode(fscan_mode),
        .fscan_clkungate(fscan_clkungate),
        .fscan_shiften(fscan_shiften),
        .fary_ffuse_tune_tcam(fary_ffuse_tune_tcam),
        .fary_output_reset(fary_output_reset),
        .fary_isolation_control_in(fary_isolation_control_in),
        .fary_ffuse_tcam_sleep(fary_ffuse_tcam_sleep),
        .fsta_dfxact_afd(fsta_dfxact_afd),
        .ip_reset_b(ip_reset_b),
        .fscan_ram_bypsel_tcam(fscan_ram_bypsel_tcam),
        .fscan_ram_init_en(fscan_ram_init_en),
        .fscan_ram_init_val(fscan_ram_init_val),
        .fscan_ram_rdis_b(fscan_ram_rdis_b),
        .fscan_ram_wdis_b(fscan_ram_wdis_b),
        .DFTSHIFTEN(DFTSHIFTEN),
        .DFTMASK(DFTMASK),
        .DFT_ARRAY_FREEZE(DFT_ARRAY_FREEZE),
        .DFT_AFD_RESET_B(DFT_AFD_RESET_B),
        .fary_pwren_b_tcam(fary_pwren_b_tcam),
        .aary_pwren_b_tcam(aary_pwren_b_tcam), .BIST_SETUP(BIST_SETUP), 
                        .BIST_SETUP_ts1(BIST_SETUP_ts1), .BIST_SETUP_ts2(BIST_SETUP_ts2), 
                        .to_interfaces_tck(to_interfaces_tck), 
                        .mcp_bounding_to_en(mcp_bounding_to_en), .scan_to_en(scan_to_en), 
                        .memory_bypass_to_en(memory_bypass_to_en), 
                        .GO_ID_REG_SEL(GO_ID_REG_SEL), .BIST_CLEAR_BIRA(BIST_CLEAR_BIRA), 
                        .BIST_COLLAR_DIAG_EN(BIST_COLLAR_DIAG_EN), 
                        .BIST_COLLAR_BIRA_EN(BIST_COLLAR_BIRA_EN), 
                        .BIST_SHIFT_BIRA_COLLAR(BIST_SHIFT_BIRA_COLLAR), 
                        .CHECK_REPAIR_NEEDED(CHECK_REPAIR_NEEDED), 
                        .MEM0_BIST_COLLAR_SI(MEM2_BIST_COLLAR_SI), 
                        .MEM4_BIST_COLLAR_SI(MEM6_BIST_COLLAR_SI), .BIST_SO(BIST_SO_ts2), 
                        .BIST_SO_ts1(BIST_SO_ts6), .BIST_GO(BIST_GO_ts2), 
                        .BIST_GO_ts1(BIST_GO_ts6), .ltest_to_en(ltest_to_en), 
                        .BIST_USER9(BIST_USER9), .BIST_USER10(BIST_USER10), 
                        .BIST_USER11(BIST_USER11), .BIST_USER0(BIST_USER0), 
                        .BIST_USER1(BIST_USER1), .BIST_USER2(BIST_USER2), 
                        .BIST_USER3(BIST_USER3), .BIST_USER4(BIST_USER4), 
                        .BIST_USER5(BIST_USER5), .BIST_USER6(BIST_USER6), 
                        .BIST_USER7(BIST_USER7), .BIST_USER8(BIST_USER8), 
                        .BIST_EVEN_GROUPWRITEENABLE(BIST_EVEN_GROUPWRITEENABLE), 
                        .BIST_ODD_GROUPWRITEENABLE(BIST_ODD_GROUPWRITEENABLE), 
                        .BIST_WRITEENABLE(BIST_WRITEENABLE), .BIST_READENABLE(BIST_READENABLE), 
                        .BIST_SELECT(BIST_SELECT), .BIST_CMP(BIST_CMP), 
                        .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), 
                        .BIST_COL_ADD(BIST_COL_ADD), .BIST_ROW_ADD(BIST_ROW_ADD), 
                        .BIST_ROW_ADD_ts1(BIST_ROW_ADD_ts1), 
                        .BIST_ROW_ADD_ts2(BIST_ROW_ADD_ts2), 
                        .BIST_ROW_ADD_ts3(BIST_ROW_ADD_ts3), 
                        .BIST_ROW_ADD_ts4(BIST_ROW_ADD_ts4), 
                        .BIST_ROW_ADD_ts5(BIST_ROW_ADD_ts5), .BIST_BANK_ADD(BIST_BANK_ADD), 
                        .BIST_BANK_ADD_ts1(BIST_BANK_ADD_ts1), 
                        .BIST_BANK_ADD_ts2(BIST_BANK_ADD_ts2), 
                        .BIST_COLLAR_EN0(BIST_COLLAR_EN2), .BIST_COLLAR_EN4(BIST_COLLAR_EN6), 
                        .BIST_RUN_TO_COLLAR0(BIST_RUN_TO_COLLAR2), 
                        .BIST_RUN_TO_COLLAR4(BIST_RUN_TO_COLLAR6), 
                        .BIST_ASYNC_RESET(BIST_ASYNC_RESET), 
                        .BIST_TESTDATA_SELECT_TO_COLLAR(BIST_TESTDATA_SELECT_TO_COLLAR), 
                        .BIST_ON_TO_COLLAR(BIST_ON_TO_COLLAR), 
                        .BIST_WRITE_DATA(BIST_WRITE_DATA), 
                        .BIST_WRITE_DATA_ts1(BIST_WRITE_DATA_ts1), 
                        .BIST_WRITE_DATA_ts2(BIST_WRITE_DATA_ts2), 
                        .BIST_WRITE_DATA_ts3(BIST_WRITE_DATA_ts3), 
                        .BIST_WRITE_DATA_ts4(BIST_WRITE_DATA_ts4), 
                        .BIST_WRITE_DATA_ts5(BIST_WRITE_DATA_ts5), 
                        .BIST_WRITE_DATA_ts6(BIST_WRITE_DATA_ts6), 
                        .BIST_WRITE_DATA_ts7(BIST_WRITE_DATA_ts7), 
                        .BIST_WRITE_DATA_ts8(BIST_WRITE_DATA_ts8), 
                        .BIST_WRITE_DATA_ts9(BIST_WRITE_DATA_ts9), 
                        .BIST_WRITE_DATA_ts10(BIST_WRITE_DATA_ts10), 
                        .BIST_WRITE_DATA_ts11(BIST_WRITE_DATA_ts11), 
                        .BIST_WRITE_DATA_ts12(BIST_WRITE_DATA_ts12), 
                        .BIST_WRITE_DATA_ts13(BIST_WRITE_DATA_ts13), 
                        .BIST_WRITE_DATA_ts14(BIST_WRITE_DATA_ts14), 
                        .BIST_WRITE_DATA_ts15(BIST_WRITE_DATA_ts15), 
                        .BIST_WRITE_DATA_ts16(BIST_WRITE_DATA_ts16), 
                        .BIST_WRITE_DATA_ts17(BIST_WRITE_DATA_ts17), 
                        .BIST_WRITE_DATA_ts18(BIST_WRITE_DATA_ts18), 
                        .BIST_WRITE_DATA_ts19(BIST_WRITE_DATA_ts19), 
                        .BIST_WRITE_DATA_ts20(BIST_WRITE_DATA_ts20), 
                        .BIST_WRITE_DATA_ts21(BIST_WRITE_DATA_ts21), 
                        .BIST_WRITE_DATA_ts22(BIST_WRITE_DATA_ts22), 
                        .BIST_WRITE_DATA_ts23(BIST_WRITE_DATA_ts23), 
                        .BIST_WRITE_DATA_ts24(BIST_WRITE_DATA_ts24), 
                        .BIST_WRITE_DATA_ts25(BIST_WRITE_DATA_ts25), 
                        .BIST_WRITE_DATA_ts26(BIST_WRITE_DATA_ts26), 
                        .BIST_WRITE_DATA_ts27(BIST_WRITE_DATA_ts27), 
                        .BIST_WRITE_DATA_ts28(BIST_WRITE_DATA_ts28), 
                        .BIST_WRITE_DATA_ts29(BIST_WRITE_DATA_ts29), 
                        .BIST_WRITE_DATA_ts30(BIST_WRITE_DATA_ts30), 
                        .BIST_WRITE_DATA_ts31(BIST_WRITE_DATA_ts31), 
                        .BIST_EXPECT_DATA(BIST_EXPECT_DATA), 
                        .BIST_EXPECT_DATA_ts1(BIST_EXPECT_DATA_ts1), 
                        .BIST_EXPECT_DATA_ts2(BIST_EXPECT_DATA_ts2), 
                        .BIST_EXPECT_DATA_ts3(BIST_EXPECT_DATA_ts3), 
                        .BIST_EXPECT_DATA_ts4(BIST_EXPECT_DATA_ts4), 
                        .BIST_EXPECT_DATA_ts5(BIST_EXPECT_DATA_ts5), 
                        .BIST_EXPECT_DATA_ts6(BIST_EXPECT_DATA_ts6), 
                        .BIST_EXPECT_DATA_ts7(BIST_EXPECT_DATA_ts7), 
                        .BIST_EXPECT_DATA_ts8(BIST_EXPECT_DATA_ts8), 
                        .BIST_EXPECT_DATA_ts9(BIST_EXPECT_DATA_ts9), 
                        .BIST_EXPECT_DATA_ts10(BIST_EXPECT_DATA_ts10), 
                        .BIST_EXPECT_DATA_ts11(BIST_EXPECT_DATA_ts11), 
                        .BIST_EXPECT_DATA_ts12(BIST_EXPECT_DATA_ts12), 
                        .BIST_EXPECT_DATA_ts13(BIST_EXPECT_DATA_ts13), 
                        .BIST_EXPECT_DATA_ts14(BIST_EXPECT_DATA_ts14), 
                        .BIST_EXPECT_DATA_ts15(BIST_EXPECT_DATA_ts15), 
                        .BIST_EXPECT_DATA_ts16(BIST_EXPECT_DATA_ts16), 
                        .BIST_EXPECT_DATA_ts17(BIST_EXPECT_DATA_ts17), 
                        .BIST_EXPECT_DATA_ts18(BIST_EXPECT_DATA_ts18), 
                        .BIST_EXPECT_DATA_ts19(BIST_EXPECT_DATA_ts19), 
                        .BIST_EXPECT_DATA_ts20(BIST_EXPECT_DATA_ts20), 
                        .BIST_EXPECT_DATA_ts21(BIST_EXPECT_DATA_ts21), 
                        .BIST_EXPECT_DATA_ts22(BIST_EXPECT_DATA_ts22), 
                        .BIST_EXPECT_DATA_ts23(BIST_EXPECT_DATA_ts23), 
                        .BIST_EXPECT_DATA_ts24(BIST_EXPECT_DATA_ts24), 
                        .BIST_EXPECT_DATA_ts25(BIST_EXPECT_DATA_ts25), 
                        .BIST_EXPECT_DATA_ts26(BIST_EXPECT_DATA_ts26), 
                        .BIST_EXPECT_DATA_ts27(BIST_EXPECT_DATA_ts27), 
                        .BIST_EXPECT_DATA_ts28(BIST_EXPECT_DATA_ts28), 
                        .BIST_EXPECT_DATA_ts29(BIST_EXPECT_DATA_ts29), 
                        .BIST_EXPECT_DATA_ts30(BIST_EXPECT_DATA_ts30), 
                        .BIST_EXPECT_DATA_ts31(BIST_EXPECT_DATA_ts31), 
                        .BIST_SHIFT_COLLAR(BIST_SHIFT_COLLAR), 
                        .BIST_COLLAR_SETUP(BIST_COLLAR_SETUP), 
                        .BIST_CLEAR_DEFAULT(BIST_CLEAR_DEFAULT), .BIST_CLEAR(BIST_CLEAR), 
                        .BIST_COLLAR_OPSET_SELECT(BIST_COLLAR_OPSET_SELECT), 
                        .BIST_COLLAR_OPSET_SELECT_ts1(BIST_COLLAR_OPSET_SELECT_ts1), 
                        .BIST_COLLAR_HOLD(BIST_COLLAR_HOLD), 
                        .FREEZE_STOP_ERROR(FREEZE_STOP_ERROR), 
                        .ERROR_CNT_ZERO(ERROR_CNT_ZERO), 
                        .MBISTPG_RESET_REG_SETUP2(MBISTPG_RESET_REG_SETUP2), 
                        .bisr_shift_en_pd_vinf(bisr_shift_en_pd_vinf), 
                        .bisr_clk_pd_vinf(bisr_clk_pd_vinf), 
                        .bisr_reset_pd_vinf(bisr_reset_pd_vinf), 
                        .ram_row_0_col_0_bisr_inst_SO(tcam_row_1_col_0_bisr_inst_SO_ts1), 
                        .tcam_row_1_col_0_bisr_inst_SO(tcam_row_1_col_0_bisr_inst_SO_ts2), 
                        .fscan_mode_ts1(fscan_mode), .fscan_mode_ts2(fscan_mode)
);

hlp_fwd_wrap_tcam_ma_table_tcam_shell_1024x35  #( // Parameters
    .BCAM_RELIEF(0),
    .TCAM_PATRN0_EXP_RESET_VALUE( ),
    .FPGA_CLOCKS_RATIO(100),
    .FPGA_MARGIN(0),
    .TCAM_RULES_NUM(1024),
    .TOTAL_MEMORY_INSTANCE(2),
    .TCAM_PROTECTION_TYPE(0),
    .TCAM_SLICE_SIZE(64),
    .TCAM_E1_INIT_VALUE(35'h0),
    .NFUSERED_TCAM(7),
    .TO_TCAM_WIDTH(`HLP_FWD_MA_TABLE_TCAM_TO_TCAM_WIDTH),
    .TCAM_PATRN1_EXP_RESET_VALUE( ),
    .FROM_TCAM_WIDTH(`HLP_FWD_MA_TABLE_TCAM_FROM_TCAM_WIDTH),
    .TCAM_E0_INIT_VALUE(35'h0),
    .TCAM_INIT_TYPE(1),
    .WRAPPER_COL_REPAIR(1),
    .TCAM_WIDTH(35)
) fwd_wrap_tcam_ma_table_tcam_shell_1024x35_3(
        .clk(clk),
`ifdef HLP_FPGA_TCAM_MEMS
        .fpga_fast_clk(fpga_fast_clk),
`endif
        .wrap_shell_to_tcam(fwd_ma_table_tcam_3_to_tcam),
        .wrap_shell_from_tcam(fwd_ma_table_tcam_3_from_tcam),
        .fscan_mode(fscan_mode),
        .fscan_clkungate(fscan_clkungate),
        .fscan_shiften(fscan_shiften),
        .fary_ffuse_tune_tcam(fary_ffuse_tune_tcam),
        .fary_output_reset(fary_output_reset),
        .fary_isolation_control_in(fary_isolation_control_in),
        .fary_ffuse_tcam_sleep(fary_ffuse_tcam_sleep),
        .fsta_dfxact_afd(fsta_dfxact_afd),
        .ip_reset_b(ip_reset_b),
        .fscan_ram_bypsel_tcam(fscan_ram_bypsel_tcam),
        .fscan_ram_init_en(fscan_ram_init_en),
        .fscan_ram_init_val(fscan_ram_init_val),
        .fscan_ram_rdis_b(fscan_ram_rdis_b),
        .fscan_ram_wdis_b(fscan_ram_wdis_b),
        .DFTSHIFTEN(DFTSHIFTEN),
        .DFTMASK(DFTMASK),
        .DFT_ARRAY_FREEZE(DFT_ARRAY_FREEZE),
        .DFT_AFD_RESET_B(DFT_AFD_RESET_B),
        .fary_pwren_b_tcam(fary_pwren_b_tcam),
        .aary_pwren_b_tcam(aary_pwren_b_tcam), .BIST_SETUP(BIST_SETUP), 
                        .BIST_SETUP_ts1(BIST_SETUP_ts1), .BIST_SETUP_ts2(BIST_SETUP_ts2), 
                        .to_interfaces_tck(to_interfaces_tck), 
                        .mcp_bounding_to_en(mcp_bounding_to_en), .scan_to_en(scan_to_en), 
                        .memory_bypass_to_en(memory_bypass_to_en), 
                        .GO_ID_REG_SEL(GO_ID_REG_SEL), .BIST_CLEAR_BIRA(BIST_CLEAR_BIRA), 
                        .BIST_COLLAR_DIAG_EN(BIST_COLLAR_DIAG_EN), 
                        .BIST_COLLAR_BIRA_EN(BIST_COLLAR_BIRA_EN), 
                        .BIST_SHIFT_BIRA_COLLAR(BIST_SHIFT_BIRA_COLLAR), 
                        .CHECK_REPAIR_NEEDED(CHECK_REPAIR_NEEDED), 
                        .MEM0_BIST_COLLAR_SI(MEM3_BIST_COLLAR_SI), 
                        .MEM4_BIST_COLLAR_SI(MEM7_BIST_COLLAR_SI), .BIST_SO(BIST_SO_ts3), 
                        .BIST_SO_ts1(BIST_SO_ts7), .BIST_GO(BIST_GO_ts3), 
                        .BIST_GO_ts1(BIST_GO_ts7), .ltest_to_en(ltest_to_en), 
                        .BIST_USER9(BIST_USER9), .BIST_USER10(BIST_USER10), 
                        .BIST_USER11(BIST_USER11), .BIST_USER0(BIST_USER0), 
                        .BIST_USER1(BIST_USER1), .BIST_USER2(BIST_USER2), 
                        .BIST_USER3(BIST_USER3), .BIST_USER4(BIST_USER4), 
                        .BIST_USER5(BIST_USER5), .BIST_USER6(BIST_USER6), 
                        .BIST_USER7(BIST_USER7), .BIST_USER8(BIST_USER8), 
                        .BIST_EVEN_GROUPWRITEENABLE(BIST_EVEN_GROUPWRITEENABLE), 
                        .BIST_ODD_GROUPWRITEENABLE(BIST_ODD_GROUPWRITEENABLE), 
                        .BIST_WRITEENABLE(BIST_WRITEENABLE), .BIST_READENABLE(BIST_READENABLE), 
                        .BIST_SELECT(BIST_SELECT), .BIST_CMP(BIST_CMP), 
                        .INCLUDE_MEM_RESULTS_REG(INCLUDE_MEM_RESULTS_REG), 
                        .BIST_COL_ADD(BIST_COL_ADD), .BIST_ROW_ADD(BIST_ROW_ADD), 
                        .BIST_ROW_ADD_ts1(BIST_ROW_ADD_ts1), 
                        .BIST_ROW_ADD_ts2(BIST_ROW_ADD_ts2), 
                        .BIST_ROW_ADD_ts3(BIST_ROW_ADD_ts3), 
                        .BIST_ROW_ADD_ts4(BIST_ROW_ADD_ts4), 
                        .BIST_ROW_ADD_ts5(BIST_ROW_ADD_ts5), .BIST_BANK_ADD(BIST_BANK_ADD), 
                        .BIST_BANK_ADD_ts1(BIST_BANK_ADD_ts1), 
                        .BIST_BANK_ADD_ts2(BIST_BANK_ADD_ts2), 
                        .BIST_COLLAR_EN0(BIST_COLLAR_EN3), .BIST_COLLAR_EN4(BIST_COLLAR_EN7), 
                        .BIST_RUN_TO_COLLAR0(BIST_RUN_TO_COLLAR3), 
                        .BIST_RUN_TO_COLLAR4(BIST_RUN_TO_COLLAR7), 
                        .BIST_ASYNC_RESET(BIST_ASYNC_RESET), 
                        .BIST_TESTDATA_SELECT_TO_COLLAR(BIST_TESTDATA_SELECT_TO_COLLAR), 
                        .BIST_ON_TO_COLLAR(BIST_ON_TO_COLLAR), 
                        .BIST_WRITE_DATA(BIST_WRITE_DATA), 
                        .BIST_WRITE_DATA_ts1(BIST_WRITE_DATA_ts1), 
                        .BIST_WRITE_DATA_ts2(BIST_WRITE_DATA_ts2), 
                        .BIST_WRITE_DATA_ts3(BIST_WRITE_DATA_ts3), 
                        .BIST_WRITE_DATA_ts4(BIST_WRITE_DATA_ts4), 
                        .BIST_WRITE_DATA_ts5(BIST_WRITE_DATA_ts5), 
                        .BIST_WRITE_DATA_ts6(BIST_WRITE_DATA_ts6), 
                        .BIST_WRITE_DATA_ts7(BIST_WRITE_DATA_ts7), 
                        .BIST_WRITE_DATA_ts8(BIST_WRITE_DATA_ts8), 
                        .BIST_WRITE_DATA_ts9(BIST_WRITE_DATA_ts9), 
                        .BIST_WRITE_DATA_ts10(BIST_WRITE_DATA_ts10), 
                        .BIST_WRITE_DATA_ts11(BIST_WRITE_DATA_ts11), 
                        .BIST_WRITE_DATA_ts12(BIST_WRITE_DATA_ts12), 
                        .BIST_WRITE_DATA_ts13(BIST_WRITE_DATA_ts13), 
                        .BIST_WRITE_DATA_ts14(BIST_WRITE_DATA_ts14), 
                        .BIST_WRITE_DATA_ts15(BIST_WRITE_DATA_ts15), 
                        .BIST_WRITE_DATA_ts16(BIST_WRITE_DATA_ts16), 
                        .BIST_WRITE_DATA_ts17(BIST_WRITE_DATA_ts17), 
                        .BIST_WRITE_DATA_ts18(BIST_WRITE_DATA_ts18), 
                        .BIST_WRITE_DATA_ts19(BIST_WRITE_DATA_ts19), 
                        .BIST_WRITE_DATA_ts20(BIST_WRITE_DATA_ts20), 
                        .BIST_WRITE_DATA_ts21(BIST_WRITE_DATA_ts21), 
                        .BIST_WRITE_DATA_ts22(BIST_WRITE_DATA_ts22), 
                        .BIST_WRITE_DATA_ts23(BIST_WRITE_DATA_ts23), 
                        .BIST_WRITE_DATA_ts24(BIST_WRITE_DATA_ts24), 
                        .BIST_WRITE_DATA_ts25(BIST_WRITE_DATA_ts25), 
                        .BIST_WRITE_DATA_ts26(BIST_WRITE_DATA_ts26), 
                        .BIST_WRITE_DATA_ts27(BIST_WRITE_DATA_ts27), 
                        .BIST_WRITE_DATA_ts28(BIST_WRITE_DATA_ts28), 
                        .BIST_WRITE_DATA_ts29(BIST_WRITE_DATA_ts29), 
                        .BIST_WRITE_DATA_ts30(BIST_WRITE_DATA_ts30), 
                        .BIST_WRITE_DATA_ts31(BIST_WRITE_DATA_ts31), 
                        .BIST_EXPECT_DATA(BIST_EXPECT_DATA), 
                        .BIST_EXPECT_DATA_ts1(BIST_EXPECT_DATA_ts1), 
                        .BIST_EXPECT_DATA_ts2(BIST_EXPECT_DATA_ts2), 
                        .BIST_EXPECT_DATA_ts3(BIST_EXPECT_DATA_ts3), 
                        .BIST_EXPECT_DATA_ts4(BIST_EXPECT_DATA_ts4), 
                        .BIST_EXPECT_DATA_ts5(BIST_EXPECT_DATA_ts5), 
                        .BIST_EXPECT_DATA_ts6(BIST_EXPECT_DATA_ts6), 
                        .BIST_EXPECT_DATA_ts7(BIST_EXPECT_DATA_ts7), 
                        .BIST_EXPECT_DATA_ts8(BIST_EXPECT_DATA_ts8), 
                        .BIST_EXPECT_DATA_ts9(BIST_EXPECT_DATA_ts9), 
                        .BIST_EXPECT_DATA_ts10(BIST_EXPECT_DATA_ts10), 
                        .BIST_EXPECT_DATA_ts11(BIST_EXPECT_DATA_ts11), 
                        .BIST_EXPECT_DATA_ts12(BIST_EXPECT_DATA_ts12), 
                        .BIST_EXPECT_DATA_ts13(BIST_EXPECT_DATA_ts13), 
                        .BIST_EXPECT_DATA_ts14(BIST_EXPECT_DATA_ts14), 
                        .BIST_EXPECT_DATA_ts15(BIST_EXPECT_DATA_ts15), 
                        .BIST_EXPECT_DATA_ts16(BIST_EXPECT_DATA_ts16), 
                        .BIST_EXPECT_DATA_ts17(BIST_EXPECT_DATA_ts17), 
                        .BIST_EXPECT_DATA_ts18(BIST_EXPECT_DATA_ts18), 
                        .BIST_EXPECT_DATA_ts19(BIST_EXPECT_DATA_ts19), 
                        .BIST_EXPECT_DATA_ts20(BIST_EXPECT_DATA_ts20), 
                        .BIST_EXPECT_DATA_ts21(BIST_EXPECT_DATA_ts21), 
                        .BIST_EXPECT_DATA_ts22(BIST_EXPECT_DATA_ts22), 
                        .BIST_EXPECT_DATA_ts23(BIST_EXPECT_DATA_ts23), 
                        .BIST_EXPECT_DATA_ts24(BIST_EXPECT_DATA_ts24), 
                        .BIST_EXPECT_DATA_ts25(BIST_EXPECT_DATA_ts25), 
                        .BIST_EXPECT_DATA_ts26(BIST_EXPECT_DATA_ts26), 
                        .BIST_EXPECT_DATA_ts27(BIST_EXPECT_DATA_ts27), 
                        .BIST_EXPECT_DATA_ts28(BIST_EXPECT_DATA_ts28), 
                        .BIST_EXPECT_DATA_ts29(BIST_EXPECT_DATA_ts29), 
                        .BIST_EXPECT_DATA_ts30(BIST_EXPECT_DATA_ts30), 
                        .BIST_EXPECT_DATA_ts31(BIST_EXPECT_DATA_ts31), 
                        .BIST_SHIFT_COLLAR(BIST_SHIFT_COLLAR), 
                        .BIST_COLLAR_SETUP(BIST_COLLAR_SETUP), 
                        .BIST_CLEAR_DEFAULT(BIST_CLEAR_DEFAULT), .BIST_CLEAR(BIST_CLEAR), 
                        .BIST_COLLAR_OPSET_SELECT(BIST_COLLAR_OPSET_SELECT), 
                        .BIST_COLLAR_OPSET_SELECT_ts1(BIST_COLLAR_OPSET_SELECT_ts1), 
                        .BIST_COLLAR_HOLD(BIST_COLLAR_HOLD), 
                        .FREEZE_STOP_ERROR(FREEZE_STOP_ERROR), 
                        .ERROR_CNT_ZERO(ERROR_CNT_ZERO), 
                        .MBISTPG_RESET_REG_SETUP2(MBISTPG_RESET_REG_SETUP2), 
                        .bisr_shift_en_pd_vinf(bisr_shift_en_pd_vinf), 
                        .bisr_clk_pd_vinf(bisr_clk_pd_vinf), 
                        .bisr_reset_pd_vinf(bisr_reset_pd_vinf), 
                        .ram_row_0_col_0_bisr_inst_SO(tcam_row_1_col_0_bisr_inst_SO_ts2), 
                        .tcam_row_1_col_0_bisr_inst_SO(tcam_row_1_col_0_bisr_inst_SO_ts3), 
                        .fscan_mode_ts1(fscan_mode), .fscan_mode_ts2(fscan_mode)
);


// BEGIN_BOTTOM_LOGIC


// END_BOTTOM_LOGIC


endmodule

